// content for the "Bento Features" section — extracted by extract-site.
// Edit values here to re-skin the "Bento Features" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "Not just vibes, a full platform",
  webVitals: "Core Web Vitals",
  webVitals_2: "GOOD",
  webVitals_3: "LCP",
  webVitals_4: "1.1s",
  webVitals_5: "INP",
  webVitals_6: "95ms",
  webVitals_7: "CLS",
  webVitals_8: "0.01",
  l: "/performance",
  l_2: "Performance",
  tabs: "Collections",
  tabs_2: "Fields",
  sidebar: "Blog",
  sidebar_2: "Careers",
  sidebar_3: "Events",
  sidebar_4: "Categories",
  sidebar_5: "13",
  sidebar_6: "Speakers",
  sidebar_7: "18",
  sidebar_8: "Talks",
  sidebar_9: "89",
  sidebar_10: "Startups",
  sidebar_11: "Help",
  sidebar_12: "Add...",
  darkFp: "Title",
  darkFp_2: "Status",
  darkFp_3: "Image",
  darkFp_4: "Category",
  title: "Generative design rooted in natural forms",
  live: "Live",
  image: { src: "/images/f57a8251-jsKLc6lXoHjCysrAHeG3ghcriI14a7.jpg?width=450&height=450", alt: "CMS Item image" },
  dark: "Design",
  dark_2: "Blog",
  title_2: "Designing AI tools that feel organic",
  live_2: "Live",
  image_2: { src: "/images/4debb902-uDdBqfuYdrKTwMfwVUNHXY3FtJk14a7.jpg?width=450&height=450", alt: "CMS Item image" },
  dark_3: "AI",
  dark_4: "Blog",
  title_3: "Living systems: data visualization from nature",
  live_3: "Live",
  image_3: { src: "/images/031b66cb-noTZrAnaWnle2PIeZvXS66nzXG414a7.jpg?width=450&height=450", alt: "CMS Item image" },
  dark_5: "Data",
  dark_6: "Blog",
  title_4: "Sustainable interfaces for a greener web",
  live_4: "Live",
  image_4: { src: "/images/ba7271a9-9fmhLlnuVij5WJGb7AKAPHd8K414a7.jpg?width=450&height=450", alt: "CMS Item image" },
  dark_7: "Engineering",
  dark_8: "Blog",
  title_5: "Learning from nature to design better products",
  live_5: "Live",
  image_5: { src: "/images/5079b999-FnIAILjnZeFuwBoETfTs4DaTubU14a7.jpg?width=450&height=450", alt: "CMS Item image" },
  dark_9: "AI",
  dark_10: "Blog",
  l_3: "/cms",
  l_4: "CMS",
  title_6: "Site Settings",
  title_7: "Title",
  value: "Comet Browser: a Personal…",
  title_8: "URL",
  value_2: "/comet/",
  title_9: "Page Description",
  description: "Comet browser by Perplexity is the AI browser that acts as a personal assistant. Automate tasks, research the web, organize your email, and more with Comet.",
  title_10: "Social Preview",
  size: "1200 x 630 pixels",
  label: "Upload",
  image2: { src: "../framerusercontent.com/images/FXS1HldC2ITgGNLZTGbBDGA7h06875.png?width=1200&height=630", alt: "Social preview example" },
  l_5: "/seo",
  l_6: "SEO",
  branches: "Branches",
  branches_2: "Main",
  branches_3: "1m",
  branches_4: { src: "/images/96913bcf-OmKDjH7juzfJ8ETRwLy9hglwa0f73b.png?width=192&height=192", alt: "Framer user avatar" },
  branches_5: "use-cases",
  branches_6: "1m",
  branches_7: { src: "/images/8d225e32-PNKbO6dGnRRwEvctPlhddS3H2s20cf.png?width=512&height=512", alt: "Framer user avatar" },
  branches_8: "publishing",
  branches_9: "8m",
  branches_10: { src: "/images/1ea3b48d-kFiEvDg0LczTmqWVkfNUFTc5020cf.png?width=512&height=512", alt: "Framer user avatar" },
  branches_11: "content",
  branches_12: "10m",
  l_7: "/collaborate",
  l_8: "Collaboration",
  locales: "Locales",
  cmsCollectionItem: "NL",
  layerTitle: "Dutch",
  cmsCollectionItem_2: "35%",
  cmsCollectionItemCopy: "IT",
  layerTitle_2: "Italian",
  cmsCollectionItemCopy_2: "100%",
  cmsCollectionItemCopy_3: "CN",
  layerTitle_3: "Chinese",
  cmsCollectionItemCopy_4: "90%",
  l_9: "https://framer-ai.com/academy/lessons/localization",
  l_10: "Localization",
  gradient: { src: "../framerusercontent.com/images/CQsZ1v3Cg7a8s5gQ8zH4usL7HU2cf8.png?width=774&height=480", alt: "Hosting Background" },
  text: "99.99%",
  text_2: "uptime",
  l_11: "/hosting",
  l_12: "Hosting",
  urlBar: "https://www.framer.com/",
  l_13: "https://framer-ai.com/legal/security",
  l_14: "Security",
  card: "Analytics",
  deviceTitle: "Live Visitors",
  card_2: "400",
  deviceTitle_2: "Unique Visitors",
  card_3: "1.7M",
  deviceTitle_3: "Total Pageviews",
  card_4: "2.2M",
  deviceTitle_4: "Bounce Rate",
  card_5: "40.9%",
  analyticsModal: "330k",
  content: "Sep 5, 2026",
  content_2: "Pageviews",
  content_3: "135,535",
  content_4: "Visitors",
  content_5: "54,817",
  l_15: "https://framer-ai.com/analytics",
  l_16: "Analytics",
  deviceTitle_5: "View Home",
  abTest: "400",
  header_2: "Variant",
  header_3: "Views",
  header_4: "Events",
  header_5: "Conversion",
  header_6: "Lift",
  header_7: "Best",
  row: "Home Page 2026",
  result: "WINNER",
  row_2: "4,916",
  row_3: "837",
  row_4: "17.1%",
  row_5: "14.1%",
  row_6: "91%",
  row_7: "Home Page",
  row_8: "4,799",
  row_9: "719",
  row_10: "15%",
  row_11: "—",
  row_12: "9%",
  l_17: "https://framer-ai.com/analytics",
  l_18: "A/B Testing",
};
