// content for the "Agents" section — extracted by extract-site.
// Edit values here to re-skin the "Agents" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "Agents that work alongside you, not instead of you",
  regular: "/agents",
  label: "Start with agents",
  default: "Exploration",
  haus: { src: "../framerusercontent.com/images/EX9NZExSFA4eodl7ZJOzgSOmf07ab5.jpg?lossless=1&width=1200&height=1549", alt: "Desktop website preview for the Haus design example" },
  bigIntro: "Exploration — Big Intro",
  site: { src: "../framerusercontent.com/images/4dSrVgS0I0XvJg2hlhEERFeaI43f93.jpg?lossless=1&width=1200&height=1454", alt: "Website preview in the explorations section" },
  sideNav: "Exploration — Side Nav",
  site_2: { src: "../framerusercontent.com/images/MY18WE0x641B3s93Ntxb9EyNDgae43.jpg?lossless=1&width=1200&height=1632", alt: "Website sidebar preview in the explorations section" },
  text: "Design with an agent",
  text_2: "A professional",
  text_3: "design agent",
  text_4: ", native to the canvas. It works directly on your site to generate and refine in place, with every change visible, editable, and under your control.",
  m: "https://framer-ai.com/signup",
  m_2: "Start with Agents",
  topbar2: "CMS",
  default_2: "Site",
  default_3: "·",
  off: "main",
  topbar2_2: { src: "/images/1534cc3a-LPkXlDTlZn3Gg3nOt0vzCxLJXU20cf.png?width=512&height=512", alt: "CMS table view interface preview" },
  topbar2_3: "Invite",
  topbar2_4: "Publish",
  collectionsPanel: "Collections",
  collectionsPanel_2: "Fields",
  collectionsPanel_3: "Plugins",
  collectionsPanel_4: "Academy",
  collectionsPanel_5: "Blog",
  collectionsPanel_6: "Articles",
  collectionsPanel_7: "320",
  collectionsPanel_8: "Creators",
  collectionsPanel_9: "256",
  collectionsPanel_10: "Categories",
  collectionsPanel_11: "18",
  collectionsPanel_12: "Styles",
  collectionsPanel_13: "7",
  collectionsPanel_14: "Developers",
  collectionsPanel_15: "Startups",
  collectionsPanel_16: "Help",
  collectionsPanel_17: "Add...",
  darkFp: "Title",
  darkFp_2: "Status",
  darkFp_3: "Image",
  darkFp_4: "Category",
  title: "T",
  title_2: "h",
  title_3: "e",
  title_4: "a",
  title_5: "r",
  title_6: "t",
  title_7: "o",
  title_8: "f",
  title_9: "c",
  title_10: "r",
  title_11: "e",
  title_12: "a",
  title_13: "t",
  title_14: "i",
  title_15: "v",
  title_16: "e",
  title_17: "d",
  title_18: "i",
  title_19: "r",
  title_20: "e",
  title_21: "c",
  title_22: "t",
  title_23: "i",
  title_24: "o",
  title_25: "n",
  image: { src: "/images/24e60a8b-4lqMHnXQfYqTAzY33snof8y0Es.avif?width=764&height=480", alt: "CMS feature image preview" },
  dark: "Product",
  draft: "Draft",
  title_26: "Designing calmer interfaces inspired by nature",
  live: "Live",
  image_2: { src: "/images/a414220f-MpLFDC67YQNhZn2xoUIeyQAZK07ff5.jpg?width=120&height=120", alt: "CMS image example" },
  dark_2: "Inspiration",
  title_27: "Organic shapes and natural motion in modern UI",
  live_2: "Live",
  image_3: { src: "/images/7f7e93ec-Yrl5iQeyEEzLD8pNITy1dJET2RM7ff5.jpg?width=120&height=120", alt: "CMS image example" },
  dark_3: "Product",
  title_28: "Earthy color palettes inspired by the natural world",
  live_3: "Live",
  image_4: { src: "/images/fdf165c6-vXcO4WGVMInagNXNjSGxl3jl0U7ff5.jpg?width=120&height=120", alt: "CMS image example" },
  dark_4: "Inspiration",
  title_29: "Designing with growth: how nature shapes UX patterns",
  live_4: "Live",
  image_5: { src: "/images/cb738255-YY5IEBQkB2R1f6V5zwAeWX6sl2M7ff5.jpg?width=120&height=120", alt: "CMS image example" },
  dark_5: "Guide",
  title_30: "From forests to pixels: textures rooted in nature",
  live_5: "Live",
  image_6: { src: "/images/e2732f48-Hmpf3NeQjpUx0q8s2c8riF2jpQ7ff5.jpg?width=120&height=120", alt: "CMS image example" },
  dark_6: "Design",
  copy: "Run your CMS with an agent",
  copy_2: "Manage more. Publish faster.",
  copy_3: "The CMS agent sets up, organizes, and updates your entire CMS, connecting it directly to the canvas so content and design stay in sync.",
  m_3: "https://framer-ai.com/signup",
  m_4: "Start with Agents",
  visualDesktop: "ImageWheel",
  visualDesktop_2: { src: "/images/b3906416-GjvoTAZBS3bbZCkT9BvgvSP3Tio14a7.jpg?width=450&height=450", alt: "Code Component Image" },
  visualDesktop_3: { src: "/images/f57a8251-jsKLc6lXoHjCysrAHeG3ghcriI14a7.jpg?width=450&height=450", alt: "Code Component Image" },
  visualDesktop_4: { src: "/images/ba7271a9-9fmhLlnuVij5WJGb7AKAPHd8K414a7.jpg?width=450&height=450", alt: "Code Component Image" },
  visualDesktop_5: { src: "/images/031b66cb-noTZrAnaWnle2PIeZvXS66nzXG414a7.jpg?width=450&height=450", alt: "Code Component Image" },
  visualDesktop_6: { src: "/images/462ef51d-7hSz2Jc01Ilj9LZpJlZ7RcYh0Q14a7.jpg?width=450&height=450", alt: "Code Component Image" },
  visualDesktop_7: { src: "/images/4debb902-uDdBqfuYdrKTwMfwVUNHXY3FtJk14a7.jpg?width=450&height=450", alt: "Code Component Image" },
  visualDesktop_8: { src: "/images/b7648699-hlpxQq1a2zZi2B0UH9nlvggCYZY14a7.jpg?width=450&height=450", alt: "Code Component Image" },
  visualDesktop_9: { src: "/images/5079b999-FnIAILjnZeFuwBoETfTs4DaTubU14a7.jpg?width=450&height=450", alt: "Code Component Image" },
  copy_4: "Code with an agent",
  copy_5: "Agents turn your wildest ideas into code and put them on your site. From simple custom effects to complex interactions.",
  m_5: "https://framer-ai.com/signup",
  m_6: "Start with Agents",
  breakpoint: "Desktop",
  top: "Create a few layout",
  chatBox: "variations of my site. Keep the content but try some different compositions.",
  thinking: "Thinking...",
  thinking_2: "Thinking...",
  designPlan: "Created a design plan",
  designPlan_2: "2s",
  text_5: "Placing layout variations side by side.",
  promptInput: "._R2plmatkn6l5dp_::placeholder { color: var(--token-f5637926-8ee6-41cb-a320-ec3462d62cd5, rgba(255, 255, 255, 0.4)); opacity: 1; }",
  aiModel: "GPT 5.6",
  aiModel_2: "Terra",
  off_2: "Desktop",
  off_3: "1200",
  topBar: { src: "../framerusercontent.com/images/izmhOCZ9AE4RHH29q34wCc5W3Mo2cd5.jpg?width=2240&height=140", alt: "Interface preview in 2026 Frontpage/Home External CMS." },
  header_2: { src: "../framerusercontent.com/images/RUCQXTdC1P3kOSgwlXiUYL7zXc51a1.jpg?width=2240&height=880", alt: "Interface preview in 2026 Frontpage/Home External CMS." },
  update1: { src: "../framerusercontent.com/images/FZ7lxiXg058Q5WkLuIXqolcRD84214.jpg?width=750&height=1080", alt: "Interface preview in 2026 Frontpage/Home External CMS." },
  update2: { src: "../framerusercontent.com/images/usaoXNWRLeM7U9Xt0Tx5xMMbc4214.jpg?width=750&height=1080", alt: "Interface preview in 2026 Frontpage/Home External CMS." },
  update3: { src: "../framerusercontent.com/images/CRKaWbZDqmciaZB3o8TLxfNfg4214.jpg?width=750&height=1080", alt: "Interface preview in 2026 Frontpage/Home External CMS." },
  update4: { src: "../framerusercontent.com/images/ImSxIBL5r0HQ0A9eAfv3URGZ6s4214.jpg?width=750&height=1080", alt: "Interface preview in 2026 Frontpage/Home External CMS." },
  update5: { src: "../framerusercontent.com/images/kNTFdAbq8KepLO0ZTbRn615fg44214.jpg?width=750&height=1080", alt: "Interface preview in 2026 Frontpage/Home External CMS." },
  update6: { src: "../framerusercontent.com/images/l43trLLXSdDM5JxPLAjSBS0yFZQ4214.jpg?width=750&height=1080", alt: "Interface preview in 2026 Frontpage/Home External CMS." },
  update7: { src: "../framerusercontent.com/images/7mIYCJjy7b59G8bbbUNvCTZ5tg4214.jpg?width=750&height=1080", alt: "Interface preview in 2026 Frontpage/Home External CMS." },
  update8: { src: "../framerusercontent.com/images/QTBWCthlYtWCw8cIvFl8tkXTZx44214.jpg?width=750&height=1080", alt: "Interface preview in 2026 Frontpage/Home External CMS." },
  update9: { src: "../framerusercontent.com/images/f4S0gAvTsWVVdZcuwBqWpJJJx4Q4214.jpg?width=750&height=1080", alt: "Interface preview in 2026 Frontpage/Home External CMS." },
  footer: { src: "../framerusercontent.com/images/NSyL5fO3XPhUYlHmNfv0May8LM2cd5.jpg?width=2240&height=140", alt: "Interface preview in 2026 Frontpage/Home External CMS." },
  text_6: "Connect to any AI",
  text_7: "Take action on your site from anywhere. Update copy from Slack. Trigger CMS changes from the terminal. Ship from a GitHub PR. Drive it all from your Terminal, Codex in ChatGPT, Claude Code, Cursor, or any external AI.",
  topBar_2: "framer-agent",
  segmentItem: "claude",
  segmentItem_2: "cursor",
  segmentItem_3: "codex",
  claude: "╭─── Claude Code",
  claude_2: "v2.1.170",
  claude_3: "─────────────────────────╮",
  claude_4: "│ │",
  model: "│ │",
  model_2: "Sonnet 4.6 · Claude Team · Framer",
  claude_5: "│ │",
  claude_6: "╰──────────────────────────────────────────────────╯",
  response1: "Initializing",
  response1_2: "WordPress importer",
  response1_3: "…",
  response1_4: "└",
  response1_5: "WP REST API",
  response1_6: "detected.",
  response1_7: "└",
  response1_8: "Framer CMS",
  response1_9: "connected.",
  response2: "Skill",
  response2_2: "(check-wordpress-auth)",
  response2_3: "└",
  response2_4: "WordPress credentials verified.",
  response2_5: "└",
  response2_6: "Connected to Framer CMS collection.",
  response3: "Bash",
  response3_2: "(GET /wp-json/wp/v2/posts?per_page)",
  response3_3: "└",
  response3_4: "47 posts returned · 47 mapped to Blog schema.",
  response4: "Bash",
  response4_2: "(GET /wp-json/wp/v2/media × 47)",
  response4_3: "└",
  response4_4: "titles, slugs, authors, dates, and cover images resolved.",
  response5: "Import complete · 47 blog entries published to Framer CMS.",
  copy_6: "Copy",
  copy_7: "Copy",
  variant1: "Copy install prompt",
  regular_2: "https://framer-ai.com/agents/external/index.html#connect",
  label_2: "Install",
};
