// content for the "Community" section — extracted by extract-site.
// Edit values here to re-skin the "Community" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "Built on a community that isn’t going anywhere",
  cta: "12,447 Resources",
  regular: "https://framer-ai.com/community/feed",
  label: "Browse the community",
  trafficLights: { src: "/images/3732051e-rRuvXeJC8VZ7naTn6TEU38KyMk0d5c.png?width=156&height=64", alt: "App window controls in the community interface preview" },
  fallback: { src: "../framerusercontent.com/images/HpuIynUBjhAJSaXjaIesR9XZ7fMacf0.png?width=2160&height=2160", alt: "User avatar." },
  user: "Jurre",
  search: "Search…",
  explore: "Explore",
  feed: "Feed",
  hype: "Hype",
  activity: "Activity",
  community: "Community",
  marketplace: "Marketplace",
  gallery: "Gallery",
  members: "Members",
  contents: "Contests",
  tab: "For You",
  tab_2: "Following",
  button: "Post",
  avatar: { src: "/images/6d214e4f-vT8YWu2HpMqiF96ExFdnTUwjuk12f3.png?width=400&height=400", alt: "Community member avatar" },
  user_2: "Lee Black",
  badge: "Pro",
  header_2: "in Marketplace · 3s",
  post: "The only",
  post_2: "@Framer",
  post_3: "Liquid Glass component that is cross browser and mobile friendly. Sound on 🤖",
  visual: "/videos/82f9b791-IxrpbsCJLku5W91FcYn0gQuQY.mp4",
  like: "30",
  comment: "5",
  avatar_2: { src: "../framerusercontent.com/images/p84L3wZzLg8rmtYvL85BAH0STM6177.png?width=640&height=640", alt: "Community member avatar" },
  user_3: "Gustave Flowbert",
  badge_2: "Pro",
  header_3: "in Marketplace · 12m",
  carouselImage: { src: "../framerusercontent.com/images/6Mk8jyDEgOtr9zqsKnmAgsWAob351.png?width=1600&height=1200", alt: "Community carousel image preview" },
  footer: "Billiie",
  footer_2: "· Template",
  button_2: "Copy",
  like_2: "23",
  comment_2: "6",
  avatar_3: { src: "../framerusercontent.com/images/MBxTAYW1PmysHhfbcP7XfQPdoyI12f3.png?width=400&height=400", alt: "Community member avatar" },
  user_4: "Ben Fryc",
  header_4: "1d",
  post_4: "in my fisheye era",
  visual_2: "https://framerusercontent.com/assets/d5okMiktMgbhCcGtgbr8gGqqHU.mp4",
  like_3: "85",
  comment_3: "12",
  avatar_4: { src: "../framerusercontent.com/images/u3JjDt32OwSOygGRRZ6rQTgZURo12f3.png?width=400&height=400", alt: "Community member avatar" },
  user_5: "Adriano Reis",
  badge_3: "Pro",
  header_5: "2d",
  post_5: "I’m beyond excited to have collaborated with",
  post_6: "@Smith_Diction",
  post_7: "to bring the",
  post_8: "@CowboySpaceCorp",
  post_9: "website to life 🔥",
  post_10: "Designed by S&D, developed by me in",
  post_11: "@Framer",
  post_12: "yeehaww 🤠 🚀",
  visual_3: "https://framerusercontent.com/assets/CgG06QT8BUlSAEO3d4bWJgF0YgI.mp4",
  like_4: "22",
  comment_4: "7",
  avatar_5: { src: "../framerusercontent.com/images/t0AxBQTyoDw9K4AFQrXmuKebU5ad8.png?width=80&height=80", alt: "Community member avatar" },
  user_6: "Renny Mathew",
  badge_4: "Pro",
  header_6: "in Marketplace · 1w",
  marketplaceItem: "https://framerusercontent.com/assets/EGqLxawrgBiyYfcyRAdEFPRAMWo.mp4",
  footer_3: "Carousel 3D",
  footer_4: "· Component",
  button_3: "Copy",
  like_5: "16",
  comment_5: "6",
  avatar_6: { src: "/images/23dc354d-vT8YWu2HpMqiF96ExFdnTUwjuk.avif?width=400&height=400", alt: "Community member avatar" },
  user_7: "Lee Black",
  badge_5: "Pro",
  header_7: "in Marketplace · 3s",
  post_13: "The only",
  post_14: "@Framer",
  post_15: "Liquid Glass component that is cross browser and mobile friendly. Sound on 🤖",
  visual_4: "/videos/82f9b791-IxrpbsCJLku5W91FcYn0gQuQY.mp4",
  like_6: "30",
  comment_6: "5",
  avatar_7: { src: "/images/cd12a973-p84L3wZzLg8rmtYvL85BAH0STM.avif?width=640&height=640", alt: "Community member avatar" },
  user_8: "Gustave Flowbert",
  badge_6: "Pro",
  header_8: "in Marketplace · 12m",
  carouselImage_2: { src: "/images/ce08fedc-6Mk8jyDEgOtr9zqsKnmAgsWAo.avif?width=1600&height=1200", alt: "Community carousel image preview" },
  footer_5: "Billiie",
  footer_6: "· Template",
  button_4: "Copy",
  like_7: "23",
  comment_7: "6",
  avatar_8: { src: "https://framerusercontent.com/images/MBxTAYW1PmysHhfbcP7XfQPdoyI.png?width=400&height=400", alt: "Community member avatar" },
  user_9: "Ben Fryc",
  header_9: "1d",
  post_16: "in my fisheye era",
  visual_5: "https://framerusercontent.com/assets/d5okMiktMgbhCcGtgbr8gGqqHU.mp4",
  like_8: "85",
  comment_8: "12",
  avatar_9: { src: "https://framerusercontent.com/images/u3JjDt32OwSOygGRRZ6rQTgZURo.png?width=400&height=400", alt: "Community member avatar" },
  user_10: "Adriano Reis",
  badge_7: "Pro",
  header_10: "2d",
  post_17: "I’m beyond excited to have collaborated with",
  post_18: "@Smith_Diction",
  post_19: "to bring the",
  post_20: "@CowboySpaceCorp",
  post_21: "website to life 🔥",
  post_22: "Designed by S&D, developed by me in",
  post_23: "@Framer",
  post_24: "yeehaww 🤠 🚀",
  visual_6: "https://framerusercontent.com/assets/CgG06QT8BUlSAEO3d4bWJgF0YgI.mp4",
  like_9: "22",
  comment_9: "7",
  avatar_10: { src: "https://framerusercontent.com/images/t0AxBQTyoDw9K4AFQrXmuKebU.png?width=80&height=80", alt: "Community member avatar" },
  user_11: "Renny Mathew",
  badge_8: "Pro",
  header_11: "in Marketplace · 1w",
  marketplaceItem_2: "https://framerusercontent.com/assets/EGqLxawrgBiyYfcyRAdEFPRAMWo.mp4",
  footer_7: "Carousel 3D",
  footer_8: "· Component",
  button_5: "Copy",
  like_10: "16",
  comment_10: "6",
  header_12: "Marketplace",
  cover: { src: "../framerusercontent.com/images/1a8BOgJ1jcruChleGrSASckBIRkda50.png?width=828&height=621", alt: "Community post cover image" },
  text: "Claude + Framer",
  text_2: "Tutorial · 1.3K likes",
  cover_2: { src: "../framerusercontent.com/images/QchK2Mvzs4ZwqHCLITcEsyXfJQb351.png?width=1600&height=1200", alt: "Community post cover image" },
  text_3: "Recraft",
  text_4: "Plugin · 32 likes",
  cover_3: { src: "../framerusercontent.com/images/CijpUPlN5zOHYpIxnwrXuL3SJAAb351.png?width=1600&height=1200", alt: "Community post cover image" },
  text_5: "Kinetic Type",
  text_6: "Plugin · 862 likes",
  cover_4: { src: "../framerusercontent.com/images/l7c3NmDQLA0tJaEOrCfPslyQ8da50.png?width=828&height=621", alt: "Community post cover image" },
  text_7: "Digital Rotary Radio",
  text_8: "Component · 76 likes",
  cover_5: { src: "../framerusercontent.com/images/3LFHK78Tyjrkd29aNyaCt4kswb351.png?width=1600&height=1200", alt: "Community post cover image" },
  text_9: "Fuel X",
  text_10: "Template · 1.3K likes",
  header_13: "Members",
  creator: { src: "/images/1ea5e92f-T2YwdLK1HMT7WuGimy8fHgXO012f3.png?width=400&height=400", alt: "Community member avatar" },
  text_11: "Asia Gawron",
  text_12: "@asia_gawron",
  button_6: "Follow",
  creator_2: { src: "/images/937158ac-Bp2MR74pImwyNdPUKsjjHl1ORCw7654.png?width=320&height=320", alt: "Community member avatar" },
  text_13: "27b",
  text_14: "@27b.ureau",
  button_7: "Follow",
  creator_3: { src: "/images/19fc8412-Gy0sO0Azs6C5MstLQyaS45HuA12f3.png?width=400&height=400", alt: "Community member avatar" },
  text_15: "Benjamin",
  text_16: "@benjaminnathan",
  button_8: "Following",
  avatar_11: { src: "/images/fd8a6b4f-jXiW6TqMFnx6tg1hfTRJqWhBtk12f3.png?width=400&height=400", alt: "Community member avatar" },
  text_17: "Ryan Hayward",
  text_18: "@theryanhayward",
  button_9: "Follow",
  creator_4: { src: "/images/7df12f25-YamtXHt4RrF5czl9OsBVudYFxg12f3.png?width=400&height=400", alt: "Community member avatar" },
  text_19: "Victoria",
  text_20: "@victoria_framer",
  button_10: "Follow",
};
