// content for the "Agent" section — extracted by extract-site.
// Edit values here to re-skin the "Agent" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "Faster ideas. Better designs. Still yours.",
  regular: "https://framer-ai.com/ai",
  label: "Design with AI",
  hero2: { src: "../../../framerusercontent.com/images/NGJAnJajvBrK1SEEjxh78Qdgee45.jpg?width=2400&height=1600", alt: "Hero design preview" },
  hero1: { src: "../../../framerusercontent.com/images/cfgKNHtptOS5ZoQgFRDgaMANZjY7c17.jpg?width=1314&height=876", alt: "Hero design preview" },
  hero3: { src: "../../../framerusercontent.com/images/guwqpIEPe9mN4oB7W9fnkOtof6k7c17.jpg?width=1314&height=876", alt: "Hero design preview" },
  text: "The agent iterates & ideates with you",
  text_2: "Refine a section, explore layout directions, or ask for ideas you haven’t thought of yet. The agent responds to feedback in real time, generating new variations until the design feels right.",
  agent: "@keyframes ghostFlow { 0%, 18% { opacity: 1; } 35% { opacity: 0.6; } 50%, 100% { opacity: 0.3; } } @keyframes doubleSlow { 0%, 100% { opacity: 0.3; } 8% { opacity: 0.72; } 16%, 24% { opacity: 1; } 34%, 50% { opacity: 0.3; } 58% { opacity: 0.58; } 66%, 74% { opacity: 0.96; } 84% { opacity: 0.48; } } @keyframes danceSpark { 0%, 6% { opacity: 1; } 18% { opacity: 0.45; } 24%, 100% { opacity: 0.3; } }",
  agent_2: "Tablet",
  agent_3: "810",
  hero2x: { src: "../../../framerusercontent.com/images/B4VMaVxB1JPQso8jLQz1cNveGM69a6.jpg?width=840&height=740", alt: "Hero design preview made in Framer" },
  agent_4: "@keyframes ghostFlow { 0%, 18% { opacity: 1; } 35% { opacity: 0.6; } 50%, 100% { opacity: 0.3; } } @keyframes doubleSlow { 0%, 100% { opacity: 0.3; } 8% { opacity: 0.72; } 16%, 24% { opacity: 1; } 34%, 50% { opacity: 0.3; } 58% { opacity: 0.58; } 66%, 74% { opacity: 0.96; } 84% { opacity: 0.48; } } @keyframes danceSpark { 0%, 6% { opacity: 1; } 18% { opacity: 0.45; } 24%, 100% { opacity: 0.3; } }",
  agent_5: "Phone",
  agent_6: "390",
  paralelPhone1: { src: "../../../framerusercontent.com/images/g4ErSWqFZvLB29rfknyH1Xg064a3.jpg?width=480&height=740", alt: "Mobile design preview made in Framer" },
  text_3: "Make any design responsive",
  text_4: "Ask the agent to “Make this responsive for tablet and phone.” It adapts your layouts across breakpoints, adjusting stacks, type sizes, spacing, and image crops until everything works.",
  links: "Company",
  links_2: "About",
  links_3: "News",
  links_4: "Culture",
  links_5: "Careers",
  links_6: "Security",
  links_7: "Legal",
  links_8: "Accessibility",
  links_9: "Privacy policy",
  links_10: "Terms of use",
  links_11: "Product",
  links_12: "Invest",
  links_13: "Portfolios",
  links_14: "Early access",
  links_15: "Advisor",
  links_16: "Learn",
  links_17: "Resources",
  links_18: "Market insights",
  links_19: "Investment guides",
  links_20: "Planning tools",
  links_21: "Social",
  links_22: "Instagram",
  links_23: "LinkedIn",
  links_24: "X",
  links_25: "Support",
  links_26: "Contact",
  links_27: "Transfer account",
  links_28: "Help centre",
  links_29: "Compare plans",
  logo: { src: "../../../framerusercontent.com/images/c1Bn3kHyoBzB7TfAgrqwOnYgfc3dfd.png?width=3504&height=709", alt: "Framer logo mark" },
  copyright: "©2026 Parallel Investing. All rights reserved.",
  links_30: "Legal disclosures",
  text_5: "Turn references into editable web designs",
  text_6: "Drop in images or share a URL and the agent uses it as a starting point. The layout, style, and feel of your reference, brought directly onto the canvas.",
  logo_2: "Parallel®",
  dropdown: "Product",
  topBar: "Support",
  list: "About",
  list_2: "News",
  list_3: "Blog",
  list_4: "Careers",
  list_5: "Invest",
  list_6: "Portfolios",
  list_7: "Early access",
  list_8: "Advisor",
  list_9: "Learn",
  list_10: "Contact",
  list_11: "Transfers",
  list_12: "Help centre",
  list_13: "Compare",
  image: { src: "../../../framerusercontent.com/images/UBF85ytILrra5y9lutZNqB9ZveQ90ee.png?width=1024&height=1024", alt: "Interaction menu preview image" },
  button: "How it works",
  text_7: "Complex interactions, done in seconds",
  text_8: "Sticky navbars, animated menus, interactive carousels, just describe what you want. The agent handles the wiring so you can focus on the design, not the how-to.",
  paragraph1: "Social Asset 1",
  image1: { src: "../../../framerusercontent.com/images/OqeBYmv5CfLeKUcIyR5AfOkJtso0d99.jpg?width=430&height=600", alt: "Design exploration in Framer" },
  paragraph2: "Social Asset 2",
  image2: { src: "../../../framerusercontent.com/images/9e6mQgfVJqEUmm9HZdfFpQiNFw0d99.jpg?width=430&height=600", alt: "Design exploration in Framer" },
  paragraph3: "Social Asset 3",
  image3: { src: "../../../framerusercontent.com/images/WcJqN5pRdus9rQEBbbjOjpBUNIs0d99.jpg?width=430&height=600", alt: "Design exploration in Framer" },
  dock: "100%",
  text_9: "Sites, icons, social assets. All on freeform canvas.",
  text_10: "From websites to icons, every change the agent makes is fully editable. Move it, restyle it, tweak it by hand. You’re never stuck in a prompt loop.",
  top: "Hero Section",
  top_2: "Give me a couple",
  fpAgentsChatBox: "layout variations of the hero section of my front page.",
  thinking: "Thinking...",
  thinking_2: "Thinking...",
  fpAgentsChatResponse: "I created three hero variations for Parallel: a split dark panel, a full-bleed image, and a centered scenic layout. Want me to apply one?",
  promptInput: "._R5jbelrael5dp_::placeholder { color: var(--token-f5637926-8ee6-41cb-a320-ec3462d62cd5, rgba(255, 255, 255, 0.4)); opacity: 1; }",
  aiModel: "GPT 5.6",
  aiModel_2: "Terra",
};
