// Stories.tsx — section converted to a real JSX component by extract-site.
// Editable React: entrance animations are inline framer-motion props with the
// MEASURED timing from the original site; hover effects live in hover.css.
// Copy, photos, and links live in the sibling content module — edit there to
// re-skin this section without touching layout/motion.
import type { CSSProperties } from "react";
import { motion } from "framer-motion";
import content from "../content/06-Stories";

export function Stories() {
  return (
    <section className="framer-1468qj4" data-framer-name="Stories" style={{ width: "1440px", height: "818.797px", padding: "120px 20px 102px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "40px" } as CSSProperties}>
      <header className="framer-2slawz" data-framer-name="Header" style={{ width: "1200px", height: "96.7969px", maxWidth: "1200px", position: "relative", zIndex: "1", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end", alignContent: "flex-end" } as CSSProperties}>
        <div className="framer-cuuzt3 hv-1693" data-framer-component-type="RichTextContainer" style={{ width: "330px", height: "96.7969px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", transform: "none" } as CSSProperties}>
          <h2 className="framer-text framer-styles-preset-fbtpvo" data-styles-preset="qRN7MgZKk" dir="auto" style={{ width: "330px", height: "96.7969px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"GT Walsheim Medium\", \"GT Walsheim Medium Placeholder\", sans-serif", fontSize: "44px", fontWeight: "500", lineHeight: "48.4px", letterSpacing: "-1.76px", color: "rgb(255, 255, 255)" } as CSSProperties}>
            {content.header}
          </h2>
        </div>
        <div className="framer-if9n81" data-framer-name="CTA" style={{ width: "107.344px", height: "42px", padding: "0px 0px 8px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "10px" } as CSSProperties}>
          <div className="ssr-variant hidden-apjvv1" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
            <div className="framer-rr6zvs-container" style={{ width: "107.344px", height: "34px", position: "relative", display: "block", flexDirection: "row" } as CSSProperties}>
              <a className="framer-k8Dz4 framer-qkzqfa framer-v-qkzqfa framer-lt5xhr" data-framer-name="Regular" data-highlight="true" data-reset="button" tabIndex={0} style={{ width: "107.344px", height: "34px", maxHeight: "35px", padding: "10px 14px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "7px", backgroundColor: "var(--token-70c17056-82cb-4934-97c9-7213cf77c853, rgba(255, 255, 255, 0.1))", borderRadius: "8px", color: "rgb(0, 0, 238)", borderBottomLeftRadius: "8px", borderBottomRightRadius: "8px", borderTopLeftRadius: "8px", borderTopRightRadius: "8px", boxShadow: "var(--9xgf7k)", opacity: "1" } as CSSProperties} href={content.regular}>
                <div className="framer-o5mers" data-framer-name="Label" data-framer-component-type="RichTextContainer" style={{ width: "79.3438px", height: "14px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 18, \"wght\" 540", "--extracted-r6o4lv": "var(--variable-reference-xdxfhd9wh-KsxdqjKwX)", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", "--variable-reference-rm8thjdvn-ksxdqjkwx": "14", "--variable-reference-xdxfhd9wh-ksxdqjkwx": "rgb(255, 255, 255)", opacity: "1", transform: "none" } as CSSProperties}>
                  <p dir="auto" className="framer-text" style={{ width: "79.3438px", height: "14px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "14px", lineHeight: "14px", letterSpacing: "-0.28px", textAlign: "center", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTRMQ0FpZDJkb2RDSWdOVFF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on", "--framer-font-size": "calc(var(--variable-reference-rm8ThjdVN-KsxdqjKwX) * 1px)", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 18, \"wght\" 540)", "--framer-letter-spacing": "-0.02em", "--framer-line-height": "1em", "--framer-text-alignment": "center", "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-xdxfhd9wh-KsxdqjKwX))" } as CSSProperties}>
                    {content.label}
                  </p>
                </div>
              </a>
            </div>
          </div>
        </div>
      </header>
      <div className="ssr-variant hidden-apjvv1" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
        <div className="framer-1fghgqd-container" style={{ width: "1400px", height: "460px", position: "relative", display: "block", flexDirection: "row" } as CSSProperties}>
          <div className="framer-smq7L framer-psyzf0 framer-v-psyzf0" data-framer-name="Desktop" style={{ width: "100%", height: "100%", position: "absolute", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "20px", opacity: "1" } as CSSProperties}>
            <motion.ul style={{ width: "100%", height: "100%", maxWidth: "100%", maxHeight: "100%", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", gap: "10px", transform: "translateX(-107.71px)", transformOrigin: "700px 230px", listStyleType: "none", padding: "0px", margin: "0px", opacity: "1" } as CSSProperties} className="hvt-1704" initial={{ opacity: 0, x: -10 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}>
              <li className="ticker-item" aria-hidden="false" aria-posinset={1} aria-setsize={8} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                <div className="framer-1nz8zzz-container" style={{ width: "360px", height: "460px", position: "relative", display: "block", flexDirection: "row", aspectRatio: "0.782609 / 1", opacity: "1" } as CSSProperties}>
                  <a className="framer-Vm6Ys framer-0k2u9 framer-naRDe framer-13l9zkl framer-v-13l9zkl framer-1n8nkmz" data-border="true" data-framer-name="Desktop" style={{ width: "100%", height: "100%", padding: "40px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", backgroundColor: "var(--token-958e2cd1-b113-4aa3-9235-7a2b959c8feb, rgb(0, 0, 0))", borderRadius: "18px", color: "rgb(0, 0, 238)", overflow: "clip", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.desktop}>
                    <div className="framer-1ywsa29" data-framer-name="Brand" style={{ width: "280px", height: "40px", position: "relative", zIndex: "2", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                      <div className="framer-1h8gyr8 hv-1709" data-framer-name="Logo 40px" style={{ width: "280px", height: "40px", position: "relative", display: "block", flexDirection: "row", overflow: "clip", opacity: "1" } as CSSProperties}>
                        <div style={{ width: "280px", height: "40px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                          <img decoding="auto" loading="lazy" width="57" height="21" style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "contain", aspectRatio: "auto 57 / 21", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.logo40px.src} alt={content.logo40px.alt} />
                        </div>
                      </div>
                    </div>
                    <motion.div className="framer-z4oca6" data-framer-name="CTA" style={{ width: "110.953px", height: "24.2969px", position: "absolute", top: "405.703px", right: "69.0469px", bottom: "30px", left: "180px", zIndex: "2", inset: "405.703px 69.0469px 30px 180px", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "6px", transform: "translateX(-50%)", transformOrigin: "55.4766px 12.1484px", overflow: "hidden", opacity: "1" } as CSSProperties} initial={{ opacity: 1, x: "-50%" }} whileInView={{ opacity: 1, x: "-50%" }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}>
                      <div className="framer-qrad30" data-framer-name="CTA Label" data-framer-component-type="RichTextContainer" style={{ width: "88.9531px", height: "24.2969px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", transform: "none", opacity: "1" } as CSSProperties}>
                        <p className="framer-text framer-styles-preset-vn6u90" data-styles-preset="kuibWYBoM" dir="auto" style={{ width: "88.9531px", height: "24.2969px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "24.3px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.ctaLabel}
                        </p>
                      </div>
                      <div className="framer-1tmvhth" data-framer-name="Icon" style={{ width: "16px", height: "24.2969px", padding: "1px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                        <svg className="framer-ooj1j framer-1xhp9uz" role="presentation" viewBox="0 0 20 20" style={{ width: "16px", height: "16px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)", "--17kkcf8": "rgba(136, 136, 136, 0.2)", opacity: "1" } as CSSProperties}>
                          <use href="#1825208344" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                        </svg>
                      </div>
                    </motion.div>
                    <div className="framer-1qgdug0" data-framer-name="BG Image" draggable="false" style={{ width: "360px", height: "460px", position: "absolute", zIndex: "0", display: "block", flexDirection: "row", opacity: "0", filter: "contrast(1) saturate(1)", mask: "linear-gradient(180deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 100%) add", WebkitFilter: "contrast(1) saturate(1)", WebkitMask: "linear-gradient(180deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 100%) add" } as CSSProperties}>
                      <div style={{ width: "360px", height: "460px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="auto" loading="lazy" width="2048" height="1070" sizes="(min-width: 1200px) 360px, (max-width: 809.98px) 250px, (min-width: 810px) and (max-width: 1199.98px) 360px" srcSet={"/images/241bdb5f-DL8hej2J0ENXehCcjm05h3CmA.avif?scale-down-to=512&width=2048&height=1070 512w,/images/241bdb5f-DL8hej2J0ENXehCcjm05h3CmA.avif?scale-down-to=1024&width=2048&height=1070 1024w,/images/241bdb5f-DL8hej2J0ENXehCcjm05h3CmA.avif?width=2048&height=1070 2048w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", objectPosition: "53.8% 48%", aspectRatio: "auto 2048 / 1070", borderRadius: "inherit", cornerShape: "inherit" } as CSSProperties} draggable="false" className="hvt-1720" src={content.bgImage.src} alt={content.bgImage.alt} />
                      </div>
                    </div>
                  </a>
                </div>
              </li>
              <li className="ticker-item" aria-hidden="false" aria-posinset={2} aria-setsize={8} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                <div className="framer-98pumj-container" style={{ width: "360px", height: "460px", position: "relative", display: "block", flexDirection: "row", aspectRatio: "0.782609 / 1", opacity: "1" } as CSSProperties}>
                  <a className="framer-Vm6Ys framer-0k2u9 framer-naRDe framer-13l9zkl framer-v-13l9zkl framer-1n8nkmz" data-border="true" data-framer-name="Desktop" style={{ width: "100%", height: "100%", padding: "40px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", backgroundColor: "var(--token-958e2cd1-b113-4aa3-9235-7a2b959c8feb, rgb(0, 0, 0))", borderRadius: "18px", color: "rgb(0, 0, 238)", overflow: "clip", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.desktop_2}>
                    <div className="framer-1ywsa29" data-framer-name="Brand" style={{ width: "280px", height: "40px", position: "relative", zIndex: "2", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                      <div className="framer-1h8gyr8 hv-1725" data-framer-name="Logo 40px" style={{ width: "280px", height: "40px", position: "relative", display: "block", flexDirection: "row", overflow: "clip", opacity: "1" } as CSSProperties}>
                        <div style={{ width: "280px", height: "40px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                          <img decoding="auto" loading="lazy" width="710" height="160" sizes="(min-width: 1200px) calc(360px - 80px), (max-width: 809.98px) calc(250px - 80px), (min-width: 810px) and (max-width: 1199.98px) calc(360px - 80px)" srcSet={"/images/39d77aa5-Xflqz4b166Nn6flLSNwZ3YHpnA.avif?scale-down-to=512&width=710&height=160 512w,/images/39d77aa5-Xflqz4b166Nn6flLSNwZ3YHpnA.avif?width=710&height=160 710w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "contain", aspectRatio: "auto 710 / 160", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.logo40px_2.src} alt={content.logo40px_2.alt} />
                        </div>
                      </div>
                    </div>
                    <motion.div className="framer-z4oca6" data-framer-name="CTA" style={{ width: "110.953px", height: "24.2969px", position: "absolute", top: "405.703px", right: "69.0469px", bottom: "30px", left: "180px", zIndex: "2", inset: "405.703px 69.0469px 30px 180px", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "6px", transform: "translateX(-50%)", transformOrigin: "55.4766px 12.1484px", overflow: "hidden", opacity: "1" } as CSSProperties} initial={{ opacity: 1, x: "-50%" }} whileInView={{ opacity: 1, x: "-50%" }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}>
                      <div className="framer-qrad30" data-framer-name="CTA Label" data-framer-component-type="RichTextContainer" style={{ width: "88.9531px", height: "24.2969px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", transform: "none", opacity: "1" } as CSSProperties}>
                        <p className="framer-text framer-styles-preset-vn6u90" data-styles-preset="kuibWYBoM" dir="auto" style={{ width: "88.9531px", height: "24.2969px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "24.3px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.ctaLabel_2}
                        </p>
                      </div>
                      <div className="framer-1tmvhth" data-framer-name="Icon" style={{ width: "16px", height: "24.2969px", padding: "1px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                        <svg className="framer-ooj1j framer-1xhp9uz" role="presentation" viewBox="0 0 20 20" style={{ width: "16px", height: "16px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)", "--17kkcf8": "rgba(136, 136, 136, 0.2)", opacity: "1" } as CSSProperties}>
                          <use href="#1825208344" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                        </svg>
                      </div>
                    </motion.div>
                    <div className="framer-1qgdug0" data-framer-name="BG Image" draggable="false" style={{ width: "360px", height: "460px", position: "absolute", zIndex: "0", display: "block", flexDirection: "row", opacity: "0", filter: "contrast(1) saturate(1)", mask: "linear-gradient(180deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 100%) add", WebkitFilter: "contrast(1) saturate(1)", WebkitMask: "linear-gradient(180deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 100%) add" } as CSSProperties}>
                      <div style={{ width: "360px", height: "460px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="auto" loading="lazy" width="2048" height="1152" sizes="(min-width: 1200px) 360px, (max-width: 809.98px) 250px, (min-width: 810px) and (max-width: 1199.98px) 360px" srcSet={"/images/d039be29-eGoO50sQnLTjwFBzhi9LqDdU3vQ.avif?scale-down-to=512&width=2048&height=1152 512w,/images/d039be29-eGoO50sQnLTjwFBzhi9LqDdU3vQ.avif?scale-down-to=1024&width=2048&height=1152 1024w,/images/d039be29-eGoO50sQnLTjwFBzhi9LqDdU3vQ.avif?width=2048&height=1152 2048w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2048 / 1152", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} draggable="false" className="hvt-1736" src={content.bgImage_2.src} alt={content.bgImage_2.alt} />
                      </div>
                    </div>
                  </a>
                </div>
              </li>
              <li className="ticker-item" aria-hidden="false" aria-posinset={3} aria-setsize={8} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                <div className="framer-vs2r7a-container" style={{ width: "360px", height: "460px", position: "relative", display: "block", flexDirection: "row", aspectRatio: "0.782609 / 1", opacity: "1" } as CSSProperties}>
                  <a className="framer-Vm6Ys framer-0k2u9 framer-naRDe framer-13l9zkl framer-v-13l9zkl framer-1n8nkmz" data-border="true" data-framer-name="Desktop" style={{ width: "100%", height: "100%", padding: "40px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", backgroundColor: "var(--token-958e2cd1-b113-4aa3-9235-7a2b959c8feb, rgb(0, 0, 0))", borderRadius: "18px", color: "rgb(0, 0, 238)", overflow: "clip", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.desktop_3}>
                    <div className="framer-1ywsa29" data-framer-name="Brand" style={{ width: "280px", height: "30px", position: "relative", zIndex: "2", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                      <div className="framer-1yurazf hv-1741" data-framer-name="Logo 30px" style={{ width: "280px", height: "30px", position: "relative", display: "block", flexDirection: "row", overflow: "clip", opacity: "1" } as CSSProperties}>
                        <div style={{ width: "280px", height: "30px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                          <img decoding="auto" loading="lazy" width="88" height="17" style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "contain", aspectRatio: "auto 88 / 17", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.logo30px.src} alt={content.logo30px.alt} />
                        </div>
                      </div>
                    </div>
                    <motion.div className="framer-z4oca6" data-framer-name="CTA" style={{ width: "110.953px", height: "24.2969px", position: "absolute", top: "405.703px", right: "69.0469px", bottom: "30px", left: "180px", zIndex: "2", inset: "405.703px 69.0469px 30px 180px", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "6px", transform: "translateX(-50%)", transformOrigin: "55.4766px 12.1484px", overflow: "hidden", opacity: "1" } as CSSProperties} initial={{ opacity: 1, x: "-50%" }} whileInView={{ opacity: 1, x: "-50%" }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}>
                      <div className="framer-qrad30" data-framer-name="CTA Label" data-framer-component-type="RichTextContainer" style={{ width: "88.9531px", height: "24.2969px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", transform: "none", opacity: "1" } as CSSProperties}>
                        <p className="framer-text framer-styles-preset-vn6u90" data-styles-preset="kuibWYBoM" dir="auto" style={{ width: "88.9531px", height: "24.2969px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "24.3px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.ctaLabel_3}
                        </p>
                      </div>
                      <div className="framer-1tmvhth" data-framer-name="Icon" style={{ width: "16px", height: "24.2969px", padding: "1px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                        <svg className="framer-ooj1j framer-1xhp9uz" role="presentation" viewBox="0 0 20 20" style={{ width: "16px", height: "16px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)", "--17kkcf8": "rgba(136, 136, 136, 0.2)", opacity: "1" } as CSSProperties}>
                          <use href="#1825208344" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                        </svg>
                      </div>
                    </motion.div>
                    <div className="framer-1qgdug0" data-framer-name="BG Image" draggable="false" style={{ width: "360px", height: "460px", position: "absolute", zIndex: "0", display: "block", flexDirection: "row", opacity: "0", filter: "contrast(1) saturate(1)", mask: "linear-gradient(180deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 100%) add", WebkitFilter: "contrast(1) saturate(1)", WebkitMask: "linear-gradient(180deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 100%) add" } as CSSProperties}>
                      <div style={{ width: "360px", height: "460px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="auto" loading="lazy" width="1000" height="1250" sizes="(min-width: 1200px) 360px, (max-width: 809.98px) 250px, (min-width: 810px) and (max-width: 1199.98px) 360px" srcSet={"/images/f03c695a-jTtsVVBhSR0HphLKfSJpeVnmPos.avif?scale-down-to=1024&width=1000&height=1250 819w,/images/f03c695a-jTtsVVBhSR0HphLKfSJpeVnmPos.avif?width=1000&height=1250 1000w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 1000 / 1250", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} draggable="false" className="hvt-1752" src={content.bgImage_3.src} alt={content.bgImage_3.alt} />
                      </div>
                    </div>
                  </a>
                </div>
              </li>
              <li className="ticker-item" aria-hidden="false" aria-posinset={4} aria-setsize={8} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                <div className="framer-6qveii-container" style={{ width: "360px", height: "460px", position: "relative", display: "block", flexDirection: "row", aspectRatio: "0.782609 / 1", opacity: "1" } as CSSProperties}>
                  <a className="framer-Vm6Ys framer-0k2u9 framer-naRDe framer-13l9zkl framer-v-13l9zkl framer-1n8nkmz" data-border="true" data-framer-name="Desktop" style={{ width: "100%", height: "100%", padding: "40px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", backgroundColor: "var(--token-958e2cd1-b113-4aa3-9235-7a2b959c8feb, rgb(0, 0, 0))", borderRadius: "18px", color: "rgb(0, 0, 238)", overflow: "clip", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.desktop_4}>
                    <div className="framer-1ywsa29" data-framer-name="Brand" style={{ width: "280px", height: "40px", position: "relative", zIndex: "2", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                      <div className="framer-1h8gyr8 hv-1757" data-framer-name="Logo 40px" style={{ width: "280px", height: "40px", position: "relative", display: "block", flexDirection: "row", overflow: "clip", opacity: "1" } as CSSProperties}>
                        <div style={{ width: "280px", height: "40px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                          <img decoding="auto" loading="lazy" width="556" height="132" sizes="(min-width: 1200px) calc(360px - 80px), (max-width: 809.98px) calc(250px - 80px), (min-width: 810px) and (max-width: 1199.98px) calc(360px - 80px)" srcSet={"/images/ce7faf39-438CGnEJ8fW9oxKnD8cAdepnjS0.avif?scale-down-to=512&width=556&height=132 512w,/images/ce7faf39-438CGnEJ8fW9oxKnD8cAdepnjS0.avif?width=556&height=132 556w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "contain", aspectRatio: "auto 556 / 132", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.logo40px_3.src} alt={content.logo40px_3.alt} />
                        </div>
                      </div>
                    </div>
                    <motion.div className="framer-z4oca6" data-framer-name="CTA" style={{ width: "110.953px", height: "24.2969px", position: "absolute", top: "405.703px", right: "69.0469px", bottom: "30px", left: "180px", zIndex: "2", inset: "405.703px 69.0469px 30px 180px", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "6px", transform: "translateX(-50%)", transformOrigin: "55.4766px 12.1484px", overflow: "hidden", opacity: "1" } as CSSProperties} initial={{ opacity: 1, x: "-50%" }} whileInView={{ opacity: 1, x: "-50%" }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}>
                      <div className="framer-qrad30" data-framer-name="CTA Label" data-framer-component-type="RichTextContainer" style={{ width: "88.9531px", height: "24.2969px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", transform: "none", opacity: "1" } as CSSProperties}>
                        <p className="framer-text framer-styles-preset-vn6u90" data-styles-preset="kuibWYBoM" dir="auto" style={{ width: "88.9531px", height: "24.2969px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "24.3px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.ctaLabel_4}
                        </p>
                      </div>
                      <div className="framer-1tmvhth" data-framer-name="Icon" style={{ width: "16px", height: "24.2969px", padding: "1px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                        <svg className="framer-ooj1j framer-1xhp9uz" role="presentation" viewBox="0 0 20 20" style={{ width: "16px", height: "16px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)", "--17kkcf8": "rgba(136, 136, 136, 0.2)", opacity: "1" } as CSSProperties}>
                          <use href="#1825208344" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                        </svg>
                      </div>
                    </motion.div>
                    <div className="framer-1qgdug0" data-framer-name="BG Image" draggable="false" style={{ width: "360px", height: "460px", position: "absolute", zIndex: "0", display: "block", flexDirection: "row", opacity: "0", filter: "contrast(1) saturate(1)", mask: "linear-gradient(rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 100%)", willChange: "transform" } as CSSProperties}>
                      <div style={{ width: "360px", height: "460px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="auto" loading="lazy" width="2680" height="1320" sizes="(min-width: 1200px) 360px, (max-width: 809.98px) 250px, (min-width: 810px) and (max-width: 1199.98px) 360px" srcSet={"/images/1f1b5c3f-sxoUHMyDJmczUkVs28JyYftbQGM.avif?scale-down-to=512&width=2680&height=1320 512w,/images/1f1b5c3f-sxoUHMyDJmczUkVs28JyYftbQGM.avif?scale-down-to=1024&width=2680&height=1320 1024w,/images/1f1b5c3f-sxoUHMyDJmczUkVs28JyYftbQGM.avif?scale-down-to=2048&width=2680&height=1320 2048w,/images/1f1b5c3f-sxoUHMyDJmczUkVs28JyYftbQGM.avif?width=2680&height=1320 2680w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2680 / 1320", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} draggable="false" className="hvt-1768" src={content.bgImage_4.src} alt={content.bgImage_4.alt} />
                      </div>
                    </div>
                  </a>
                </div>
              </li>
              <li className="ticker-item" aria-hidden="false" aria-posinset={5} aria-setsize={8} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                <div className="framer-1cjm5zc-container" style={{ width: "360px", height: "460px", position: "relative", display: "block", flexDirection: "row", aspectRatio: "0.782609 / 1", opacity: "1" } as CSSProperties}>
                  <a className="framer-Vm6Ys framer-0k2u9 framer-naRDe framer-13l9zkl framer-v-13l9zkl framer-1n8nkmz" data-border="true" data-framer-name="Desktop" style={{ width: "100%", height: "100%", padding: "40px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", backgroundColor: "var(--token-958e2cd1-b113-4aa3-9235-7a2b959c8feb, rgb(0, 0, 0))", borderRadius: "18px", color: "rgb(0, 0, 238)", overflow: "clip", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.desktop_5}>
                    <div className="framer-1ywsa29" data-framer-name="Brand" style={{ width: "280px", height: "40px", position: "relative", zIndex: "2", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                      <div className="framer-1h8gyr8" data-framer-name="Logo 40px" style={{ width: "280px", height: "40px", position: "relative", display: "block", flexDirection: "row", overflow: "clip", opacity: "1" } as CSSProperties}>
                        <div style={{ width: "280px", height: "40px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                          <img decoding="auto" loading="lazy" width="110" height="30" style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "contain", aspectRatio: "auto 110 / 30", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.logo40px_4.src} alt={content.logo40px_4.alt} />
                        </div>
                      </div>
                    </div>
                    <motion.div className="framer-z4oca6" data-framer-name="CTA" style={{ width: "110.953px", height: "24.2969px", position: "absolute", top: "405.703px", right: "69.0469px", bottom: "30px", left: "180px", zIndex: "2", inset: "405.703px 69.0469px 30px 180px", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "6px", transform: "translateX(-50%)", transformOrigin: "55.4766px 12.1484px", overflow: "hidden", opacity: "1" } as CSSProperties} initial={{ opacity: 1, x: "-50%" }} whileInView={{ opacity: 1, x: "-50%" }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}>
                      <div className="framer-qrad30" data-framer-name="CTA Label" data-framer-component-type="RichTextContainer" style={{ width: "88.9531px", height: "24.2969px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", transform: "none", opacity: "1" } as CSSProperties}>
                        <p className="framer-text framer-styles-preset-vn6u90" data-styles-preset="kuibWYBoM" dir="auto" style={{ width: "88.9531px", height: "24.2969px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "24.3px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.ctaLabel_5}
                        </p>
                      </div>
                      <div className="framer-1tmvhth" data-framer-name="Icon" style={{ width: "16px", height: "24.2969px", padding: "1px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                        <svg className="framer-ooj1j framer-1xhp9uz" role="presentation" viewBox="0 0 20 20" style={{ width: "16px", height: "16px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)", "--17kkcf8": "rgba(136, 136, 136, 0.2)", opacity: "1" } as CSSProperties}>
                          <use href="#1825208344" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                        </svg>
                      </div>
                    </motion.div>
                    <div className="framer-1qgdug0" data-framer-name="BG Image" draggable="false" style={{ width: "360px", height: "460px", position: "absolute", zIndex: "0", display: "block", flexDirection: "row", opacity: "0", filter: "contrast(1) saturate(1)", mask: "linear-gradient(180deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 100%) add", WebkitFilter: "contrast(1) saturate(1)", WebkitMask: "linear-gradient(180deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 100%) add" } as CSSProperties}>
                      <div style={{ width: "360px", height: "460px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="auto" loading="lazy" width="2374" height="1746" sizes="(min-width: 1200px) 360px, (max-width: 809.98px) 250px, (min-width: 810px) and (max-width: 1199.98px) 360px" srcSet={"/images/276b19af-2HcMn3WE6ABg2DKf1egvCVZpn6s.avif?scale-down-to=512&width=2374&height=1746 512w,/images/276b19af-2HcMn3WE6ABg2DKf1egvCVZpn6s.avif?scale-down-to=1024&width=2374&height=1746 1024w,/images/276b19af-2HcMn3WE6ABg2DKf1egvCVZpn6s.avif?scale-down-to=2048&width=2374&height=1746 2048w,/images/276b19af-2HcMn3WE6ABg2DKf1egvCVZpn6s.avif?width=2374&height=1746 2374w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2374 / 1746", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} draggable="false" src={content.bgImage_5.src} alt={content.bgImage_5.alt} />
                      </div>
                    </div>
                  </a>
                </div>
              </li>
              <li className="ticker-item" aria-hidden="false" aria-posinset={6} aria-setsize={8} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                <div className="framer-1bcqbub-container" style={{ width: "360px", height: "460px", position: "relative", display: "block", flexDirection: "row", aspectRatio: "0.782609 / 1", opacity: "1" } as CSSProperties}>
                  <a className="framer-Vm6Ys framer-0k2u9 framer-naRDe framer-13l9zkl framer-v-13l9zkl framer-1n8nkmz" data-border="true" data-framer-name="Desktop" style={{ width: "100%", height: "100%", padding: "40px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", backgroundColor: "var(--token-958e2cd1-b113-4aa3-9235-7a2b959c8feb, rgb(0, 0, 0))", borderRadius: "18px", color: "rgb(0, 0, 238)", overflow: "clip", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.desktop_6}>
                    <div className="framer-1ywsa29" data-framer-name="Brand" style={{ width: "280px", height: "30px", position: "relative", zIndex: "2", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                      <div className="framer-1yurazf" data-framer-name="Logo 30px" style={{ width: "280px", height: "30px", position: "relative", display: "block", flexDirection: "row", overflow: "clip", opacity: "1" } as CSSProperties}>
                        <div style={{ width: "280px", height: "30px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                          <img decoding="async" loading="lazy" width="600" height="96" sizes="(min-width: 1200px) calc(360px - 80px), (max-width: 809.98px) calc(250px - 80px), (min-width: 810px) and (max-width: 1199.98px) calc(360px - 80px)" srcSet={"/images/ed142ecf-IHDPUOs7g9U4PEQJmkEUXMpbsMI.avif?scale-down-to=512&width=600&height=96 512w,/images/ed142ecf-IHDPUOs7g9U4PEQJmkEUXMpbsMI.avif?width=600&height=96 600w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "contain", aspectRatio: "auto 600 / 96", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.logo30px_2.src} alt={content.logo30px_2.alt} />
                        </div>
                      </div>
                    </div>
                    <motion.div className="framer-z4oca6" data-framer-name="CTA" style={{ width: "110.953px", height: "24.2969px", position: "absolute", top: "405.703px", right: "69.0469px", bottom: "30px", left: "180px", zIndex: "2", inset: "405.703px 69.0469px 30px 180px", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "6px", transform: "translateX(-50%)", transformOrigin: "55.4766px 12.1484px", overflow: "hidden", opacity: "1" } as CSSProperties} initial={{ opacity: 1, x: "-50%" }} whileInView={{ opacity: 1, x: "-50%" }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}>
                      <div className="framer-qrad30" data-framer-name="CTA Label" data-framer-component-type="RichTextContainer" style={{ width: "88.9531px", height: "24.2969px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", transform: "none", opacity: "1" } as CSSProperties}>
                        <p className="framer-text framer-styles-preset-vn6u90" data-styles-preset="kuibWYBoM" dir="auto" style={{ width: "88.9531px", height: "24.2969px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "24.3px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.ctaLabel_6}
                        </p>
                      </div>
                      <div className="framer-1tmvhth" data-framer-name="Icon" style={{ width: "16px", height: "24.2969px", padding: "1px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                        <svg className="framer-ooj1j framer-1xhp9uz" role="presentation" viewBox="0 0 20 20" style={{ width: "16px", height: "16px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)", "--17kkcf8": "rgba(136, 136, 136, 0.2)", opacity: "1" } as CSSProperties}>
                          <use href="#1825208344" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                        </svg>
                      </div>
                    </motion.div>
                    <div className="framer-1qgdug0" data-framer-name="BG Image" draggable="false" style={{ width: "360px", height: "460px", position: "absolute", zIndex: "0", display: "block", flexDirection: "row", opacity: "0", filter: "contrast(1) saturate(1)", mask: "linear-gradient(180deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 100%) add", WebkitFilter: "contrast(1) saturate(1)", WebkitMask: "linear-gradient(180deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 100%) add" } as CSSProperties}>
                      <div style={{ width: "360px", height: "460px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="async" loading="lazy" width="900" height="980" sizes="(min-width: 1200px) 360px, (max-width: 809.98px) 250px, (min-width: 810px) and (max-width: 1199.98px) 360px" srcSet={"/images/7e080c5c-jmDZzRZa7eG7o6UwM4myFdsE.avif?width=900&height=980 900w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 900 / 980", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} draggable="false" src={content.bgImage_6.src} alt={content.bgImage_6.alt} />
                      </div>
                    </div>
                  </a>
                </div>
              </li>
              <li className="ticker-item" aria-hidden="false" aria-posinset={7} aria-setsize={8} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                <div className="framer-uwygfm-container" style={{ width: "360px", height: "460px", position: "relative", display: "block", flexDirection: "row", aspectRatio: "0.782609 / 1", opacity: "1" } as CSSProperties}>
                  <a className="framer-Vm6Ys framer-0k2u9 framer-naRDe framer-13l9zkl framer-v-13l9zkl framer-1n8nkmz" data-border="true" data-framer-name="Desktop" style={{ width: "100%", height: "100%", padding: "40px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", backgroundColor: "var(--token-958e2cd1-b113-4aa3-9235-7a2b959c8feb, rgb(0, 0, 0))", borderRadius: "18px", color: "rgb(0, 0, 238)", overflow: "clip", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.desktop_7}>
                    <div className="framer-1ywsa29" data-framer-name="Brand" style={{ width: "280px", height: "50px", position: "relative", zIndex: "2", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                      <div className="framer-1jg6g2" data-framer-name="Logo 50px" style={{ width: "280px", height: "50px", position: "relative", display: "block", flexDirection: "row", overflow: "clip", opacity: "1" } as CSSProperties}>
                        <div style={{ width: "280px", height: "50px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                          <img decoding="async" loading="lazy" width="1000" height="481" sizes="(min-width: 1200px) calc(360px - 80px), (max-width: 809.98px) calc(250px - 80px), (min-width: 810px) and (max-width: 1199.98px) calc(360px - 80px)" srcSet={"https://framerusercontent.com/images/NzfMBw82styKJA2j3DPEV081U.svg?scale-down-to=512&width=1000&height=481 512w,https://framerusercontent.com/images/NzfMBw82styKJA2j3DPEV081U.svg?width=1000&height=481 1000w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "contain", aspectRatio: "auto 1000 / 481", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.logo50px.src} alt={content.logo50px.alt} />
                        </div>
                      </div>
                    </div>
                    <motion.div className="framer-z4oca6" data-framer-name="CTA" style={{ width: "110.953px", height: "24.2969px", position: "absolute", top: "405.703px", right: "69.0469px", bottom: "30px", left: "180px", zIndex: "2", inset: "405.703px 69.0469px 30px 180px", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "6px", transform: "translateX(-50%)", transformOrigin: "55.4766px 12.1484px", overflow: "hidden", opacity: "1" } as CSSProperties} initial={{ opacity: 1, x: "-50%" }} whileInView={{ opacity: 1, x: "-50%" }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}>
                      <div className="framer-qrad30" data-framer-name="CTA Label" data-framer-component-type="RichTextContainer" style={{ width: "88.9531px", height: "24.2969px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", transform: "none", opacity: "1" } as CSSProperties}>
                        <p className="framer-text framer-styles-preset-vn6u90" data-styles-preset="kuibWYBoM" dir="auto" style={{ width: "88.9531px", height: "24.2969px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "24.3px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.ctaLabel_7}
                        </p>
                      </div>
                      <div className="framer-1tmvhth" data-framer-name="Icon" style={{ width: "16px", height: "24.2969px", padding: "1px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                        <svg className="framer-ooj1j framer-1xhp9uz" role="presentation" viewBox="0 0 20 20" style={{ width: "16px", height: "16px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)", "--17kkcf8": "rgba(136, 136, 136, 0.2)", opacity: "1" } as CSSProperties}>
                          <use href="#1825208344" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                        </svg>
                      </div>
                    </motion.div>
                    <div className="framer-1qgdug0" data-framer-name="BG Image" draggable="false" style={{ width: "360px", height: "460px", position: "absolute", zIndex: "0", display: "block", flexDirection: "row", opacity: "0", filter: "contrast(1) saturate(1)", mask: "linear-gradient(180deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 100%) add", WebkitFilter: "contrast(1) saturate(1)", WebkitMask: "linear-gradient(180deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 100%) add" } as CSSProperties}>
                      <div style={{ width: "360px", height: "460px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="async" loading="lazy" width="648" height="752" sizes="(min-width: 1200px) 360px, (max-width: 809.98px) 250px, (min-width: 810px) and (max-width: 1199.98px) 360px" srcSet={"https://framerusercontent.com/images/RFqRfs88P7646TFOvUgWoxE0.png?width=648&height=752 648w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 648 / 752", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} draggable="false" src={content.bgImage_7.src} alt={content.bgImage_7.alt} />
                      </div>
                    </div>
                  </a>
                </div>
              </li>
              <li className="ticker-item" aria-hidden="false" aria-posinset={8} aria-setsize={8} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                <div className="framer-v8zp0y-container" style={{ width: "360px", height: "460px", position: "relative", display: "block", flexDirection: "row", aspectRatio: "0.782609 / 1", opacity: "1" } as CSSProperties}>
                  <a className="framer-Vm6Ys framer-0k2u9 framer-naRDe framer-13l9zkl framer-v-13l9zkl framer-1n8nkmz" data-border="true" data-framer-name="Desktop" style={{ width: "100%", height: "100%", padding: "40px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", backgroundColor: "var(--token-958e2cd1-b113-4aa3-9235-7a2b959c8feb, rgb(0, 0, 0))", borderRadius: "18px", color: "rgb(0, 0, 238)", overflow: "clip", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.desktop_8}>
                    <div className="framer-1ywsa29" data-framer-name="Brand" style={{ width: "280px", height: "40px", position: "relative", zIndex: "2", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                      <div className="framer-1h8gyr8" data-framer-name="Logo 40px" style={{ width: "280px", height: "40px", position: "relative", display: "block", flexDirection: "row", overflow: "clip", opacity: "1" } as CSSProperties}>
                        <div style={{ width: "280px", height: "40px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                          <img decoding="async" loading="lazy" width="1052" height="245" sizes="(min-width: 1200px) calc(360px - 80px), (max-width: 809.98px) calc(250px - 80px), (min-width: 810px) and (max-width: 1199.98px) calc(360px - 80px)" srcSet={"/images/93832c8a-lUZ3uzIob6NgeCKawVZCpNKJjE.avif?scale-down-to=512&width=1052&height=245 512w,/images/93832c8a-lUZ3uzIob6NgeCKawVZCpNKJjE.avif?scale-down-to=1024&width=1052&height=245 1024w,/images/93832c8a-lUZ3uzIob6NgeCKawVZCpNKJjE.avif?width=1052&height=245 1052w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "contain", aspectRatio: "auto 1052 / 245", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.logo40px_5.src} alt={content.logo40px_5.alt} />
                        </div>
                      </div>
                    </div>
                    <motion.div className="framer-z4oca6" data-framer-name="CTA" style={{ width: "110.953px", height: "24.2969px", position: "absolute", top: "405.703px", right: "69.0469px", bottom: "30px", left: "180px", zIndex: "2", inset: "405.703px 69.0469px 30px 180px", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "6px", transform: "translateX(-50%)", transformOrigin: "55.4766px 12.1484px", overflow: "hidden", opacity: "1" } as CSSProperties} initial={{ opacity: 1, x: "-50%" }} whileInView={{ opacity: 1, x: "-50%" }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}>
                      <div className="framer-qrad30" data-framer-name="CTA Label" data-framer-component-type="RichTextContainer" style={{ width: "88.9531px", height: "24.2969px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", transform: "none", opacity: "1" } as CSSProperties}>
                        <p className="framer-text framer-styles-preset-vn6u90" data-styles-preset="kuibWYBoM" dir="auto" style={{ width: "88.9531px", height: "24.2969px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "24.3px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.ctaLabel_8}
                        </p>
                      </div>
                      <div className="framer-1tmvhth" data-framer-name="Icon" style={{ width: "16px", height: "24.2969px", padding: "1px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                        <svg className="framer-ooj1j framer-1xhp9uz hv-1828" role="presentation" viewBox="0 0 20 20" style={{ width: "16px", height: "16px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)", "--17kkcf8": "rgba(136, 136, 136, 0.2)", opacity: "1" } as CSSProperties}>
                          <use href="#1825208344" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                        </svg>
                      </div>
                    </motion.div>
                    <div className="framer-1qgdug0" data-framer-name="BG Image" draggable="false" style={{ width: "360px", height: "460px", position: "absolute", zIndex: "0", display: "block", flexDirection: "row", opacity: "0", filter: "contrast(1) saturate(1)", mask: "linear-gradient(180deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 100%) add", WebkitFilter: "contrast(1) saturate(1)", WebkitMask: "linear-gradient(180deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 100%) add" } as CSSProperties}>
                      <div style={{ width: "360px", height: "460px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="auto" loading="lazy" width="2460" height="1296" sizes="(min-width: 1200px) 360px, (max-width: 809.98px) 250px, (min-width: 810px) and (max-width: 1199.98px) 360px" srcSet={"/images/83a4459c-u0RvuERtz1FFu2w5kUQAVWmyU.avif?scale-down-to=512&width=2460&height=1296 512w,/images/83a4459c-u0RvuERtz1FFu2w5kUQAVWmyU.avif?scale-down-to=1024&width=2460&height=1296 1024w,/images/83a4459c-u0RvuERtz1FFu2w5kUQAVWmyU.avif?scale-down-to=2048&width=2460&height=1296 2048w,/images/83a4459c-u0RvuERtz1FFu2w5kUQAVWmyU.avif?width=2460&height=1296 2460w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2460 / 1296", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} draggable="false" src={content.bgImage_8.src} alt={content.bgImage_8.alt} />
                      </div>
                    </div>
                  </a>
                </div>
              </li>
            </motion.ul>
          </div>
          {" "}
        </div>
      </div>
    </section>
  );
}
