// Gallery_11.tsx — section converted to a real JSX component by extract-site.
// Editable React: entrance animations are inline framer-motion props with the
// MEASURED timing from the original site; hover effects live in hover.css.
// Copy, photos, and links live in the sibling content module — edit there to
// re-skin this section without touching layout/motion.
import type { CSSProperties } from "react";
import { motion } from "framer-motion";
import content from "../content/11-Gallery_11";

export function Gallery_11() {
  return (
    <section className="framer-1fjbrlw" data-framer-name="Gallery" style={{ width: "1440px", height: "1238.4px", padding: "120px 20px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "40px" } as CSSProperties}>
      <header className="framer-2or15l" data-framer-name="Header" style={{ width: "1200px", height: "48.3984px", maxWidth: "1200px", position: "relative", zIndex: "1", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end", alignContent: "flex-end" } as CSSProperties}>
        <div className="framer-1052w6g" data-framer-component-type="RichTextContainer" style={{ width: "400px", height: "48.3984px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre-wrap", transform: "none" } as CSSProperties}>
          <h2 className="framer-text framer-styles-preset-fbtpvo" data-styles-preset="qRN7MgZKk" dir="auto" style={{ width: "400px", height: "48.3984px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"GT Walsheim Medium\", \"GT Walsheim Medium Placeholder\", sans-serif", fontSize: "44px", fontWeight: "500", lineHeight: "48.4px", letterSpacing: "-1.76px", color: "rgb(255, 255, 255)" } as CSSProperties}>
            {content.header}
          </h2>
        </div>
        <div className="framer-nawnmg" data-framer-name="CTA" style={{ width: "134.484px", height: "42px", padding: "0px 0px 8px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "flex-end", alignContent: "flex-end", gap: "10px" } as CSSProperties}>
          <div className="ssr-variant hidden-apjvv1" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
            <div className="framer-pk7nvr-container" style={{ width: "134.484px", height: "34px", position: "relative", display: "block", flexDirection: "row" } as CSSProperties}>
              <a className="framer-k8Dz4 framer-qkzqfa framer-v-qkzqfa framer-lt5xhr" data-framer-name="Regular" data-highlight="true" data-reset="button" tabIndex={0} style={{ width: "134.484px", height: "34px", maxHeight: "35px", padding: "10px 14px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "7px", backgroundColor: "var(--token-70c17056-82cb-4934-97c9-7213cf77c853, rgba(255, 255, 255, 0.1))", borderRadius: "8px", color: "rgb(0, 0, 238)", borderBottomLeftRadius: "8px", borderBottomRightRadius: "8px", borderTopLeftRadius: "8px", borderTopRightRadius: "8px", boxShadow: "var(--9xgf7k)", opacity: "1" } as CSSProperties} data-external-route="1" href={content.regular}>
                <div className="framer-o5mers" data-framer-name="Label" data-framer-component-type="RichTextContainer" style={{ width: "106.484px", height: "14px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 18, \"wght\" 540", "--extracted-r6o4lv": "var(--variable-reference-xdxfhd9wh-KsxdqjKwX)", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", "--variable-reference-rm8thjdvn-ksxdqjkwx": "14", "--variable-reference-xdxfhd9wh-ksxdqjkwx": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", opacity: "1", transform: "none" } as CSSProperties}>
                  <p dir="auto" className="framer-text" style={{ width: "106.484px", height: "14px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "14px", lineHeight: "14px", letterSpacing: "-0.28px", textAlign: "center", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTRMQ0FpZDJkb2RDSWdOVFF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on", "--framer-font-size": "calc(var(--variable-reference-rm8ThjdVN-KsxdqjKwX) * 1px)", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 18, \"wght\" 540)", "--framer-letter-spacing": "-0.02em", "--framer-line-height": "1em", "--framer-text-alignment": "center", "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-xdxfhd9wh-KsxdqjKwX))" } as CSSProperties}>
                    {content.label}
                  </p>
                </div>
              </a>
            </div>
          </div>
        </div>
      </header>
      <div className="ssr-variant hidden-apjvv1 hidden-rjquzb" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
        <div className="framer-4nrepp-container" style={{ width: "1200px", height: "910px", maxWidth: "1200px", position: "relative", zIndex: "1", display: "block", flexDirection: "row" } as CSSProperties}>
          <div className="framer-Ttldc framer-177rths framer-v-jmewvu" data-framer-name="Desktop No Fade" style={{ width: "100%", height: "910px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", overflow: "clip", mask: "none", opacity: "1" } as CSSProperties}>
            <div className="framer-jp78hk" style={{ width: "1200px", height: "450px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", overflowX: "clip", opacity: "1" } as CSSProperties}>
              <motion.ul style={{ width: "100%", height: "100%", maxWidth: "100%", maxHeight: "100%", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", gap: "10px", transform: "translateX(-69.186px)", transformOrigin: "600px 225px", listStyleType: "none", padding: "0px", margin: "0px", opacity: "1" } as CSSProperties} initial={{ opacity: 0, x: -10 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}>
                <li className="ticker-item" aria-hidden="false" aria-posinset={1} aria-setsize={6} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                  <div className="framer-1uyl8kt" data-border="true" data-framer-name="Site" style={{ width: "700px", height: "449.992px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "1.55556 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                    <div style={{ width: "700px", height: "449.992px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                      <img decoding="auto" loading="lazy" width="2800" height="1804" sizes="(min-width: 1200px) 700px, (max-width: 809.98px) 404.4444px, (min-width: 810px) and (max-width: 1199.98px) 528.8889px" srcSet={"/images/fdd01f87-QSALLMZz20lUztB4mySTDLq6mE.avif?scale-down-to=512&width=2800&height=1804 512w,/images/fdd01f87-QSALLMZz20lUztB4mySTDLq6mE.avif?scale-down-to=1024&width=2800&height=1804 1024w,/images/fdd01f87-QSALLMZz20lUztB4mySTDLq6mE.avif?scale-down-to=2048&width=2800&height=1804 2048w,/images/fdd01f87-QSALLMZz20lUztB4mySTDLq6mE.avif?width=2800&height=1804 2800w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2800 / 1804", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.site.src} alt={content.site.alt} />
                    </div>
                  </div>
                </li>
                <li className="ticker-item" aria-hidden="false" aria-posinset={2} aria-setsize={6} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                  <div className="framer-1duxum7" data-border="true" data-framer-name="Mobile" style={{ width: "220px", height: "450px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "0.488889 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                    <div style={{ width: "220px", height: "450px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                      <img decoding="auto" loading="lazy" width="884" height="1894" sizes="(min-width: 1200px) 220px, (max-width: 809.98px) 127.1111px, (min-width: 810px) and (max-width: 1199.98px) 166.2222px" srcSet={"/images/295d3607-ordt7SZDaUEWKA368UbAGtdIno.avif?width=884&height=1894 884w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", objectPosition: "center top", aspectRatio: "auto 884 / 1894", cornerShape: "inherit" } as CSSProperties} src={content.mobile.src} alt={content.mobile.alt} />
                    </div>
                  </div>
                </li>
                <li className="ticker-item" aria-hidden="false" aria-posinset={3} aria-setsize={6} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                  <div className="framer-18a4s4" data-border="true" data-framer-name="Site" style={{ width: "700px", height: "449.992px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "1.55556 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                    <div style={{ width: "700px", height: "449.992px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                      <img decoding="auto" loading="lazy" width="2796" height="1808" sizes="(min-width: 1200px) 700px, (max-width: 809.98px) 404.4444px, (min-width: 810px) and (max-width: 1199.98px) 528.8889px" srcSet={"/images/e2a27a27-a1daVaOmbl26jqNCw1Q0P3vhWZQ.avif?scale-down-to=512&width=2796&height=1808 512w,/images/e2a27a27-a1daVaOmbl26jqNCw1Q0P3vhWZQ.avif?scale-down-to=1024&width=2796&height=1808 1024w,/images/e2a27a27-a1daVaOmbl26jqNCw1Q0P3vhWZQ.avif?scale-down-to=2048&width=2796&height=1808 2048w,/images/e2a27a27-a1daVaOmbl26jqNCw1Q0P3vhWZQ.avif?width=2796&height=1808 2796w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", objectPosition: "center top", aspectRatio: "auto 2796 / 1808", cornerShape: "inherit" } as CSSProperties} src={content.site_2.src} alt={content.site_2.alt} />
                    </div>
                  </div>
                </li>
                <li className="ticker-item" aria-hidden="false" aria-posinset={4} aria-setsize={6} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                  <div className="framer-f0k9mw" data-border="true" data-framer-name="Mobile" style={{ width: "220px", height: "450px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "0.488889 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                    <div style={{ width: "220px", height: "450px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                      <img decoding="async" loading="lazy" width="880" height="1806" sizes="(min-width: 1200px) 220px, (max-width: 809.98px) 127.1111px, (min-width: 810px) and (max-width: 1199.98px) 166.2222px" srcSet={"/images/89574182-qgcb6nXCOIxXxk9CLxf9WOoOk.avif?width=880&height=1806 880w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", aspectRatio: "auto 880 / 1806", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.mobile_2.src} alt={content.mobile_2.alt} />
                    </div>
                  </div>
                </li>
                <li className="ticker-item" aria-hidden="false" aria-posinset={5} aria-setsize={6} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                  <div className="framer-1xt0is0" data-border="true" data-framer-name="Site" style={{ width: "700px", height: "449.992px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "1.55556 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                    <div style={{ width: "700px", height: "449.992px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                      <img decoding="async" loading="lazy" width="3222" height="2078" sizes="(min-width: 1200px) 700px, (max-width: 809.98px) 404.4444px, (min-width: 810px) and (max-width: 1199.98px) 528.8889px" srcSet={"/images/02e19d2b-wVxwU0qi5YsLHBFbDaX8c3jTcU.avif?scale-down-to=512&width=3222&height=2078 512w,/images/02e19d2b-wVxwU0qi5YsLHBFbDaX8c3jTcU.avif?scale-down-to=1024&width=3222&height=2078 1024w,/images/02e19d2b-wVxwU0qi5YsLHBFbDaX8c3jTcU.avif?scale-down-to=2048&width=3222&height=2078 2048w,/images/02e19d2b-wVxwU0qi5YsLHBFbDaX8c3jTcU.avif?width=3222&height=2078 3222w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", objectPosition: "center top", aspectRatio: "auto 3222 / 2078", cornerShape: "inherit" } as CSSProperties} src={content.site_3.src} alt={content.site_3.alt} />
                    </div>
                  </div>
                </li>
                <li className="ticker-item" aria-hidden="false" aria-posinset={6} aria-setsize={6} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                  <div className="framer-pggy8n" data-border="true" data-framer-name="Mobile" style={{ width: "220px", height: "450px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "0.488889 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                    <div style={{ width: "220px", height: "450px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                      <img decoding="async" loading="lazy" width="928" height="1846" sizes="(min-width: 1200px) 220px, (max-width: 809.98px) 127.1111px, (min-width: 810px) and (max-width: 1199.98px) 166.2222px" srcSet={"https://framerusercontent.com/images/AfVrJxeJkkgPpnO71Nw1tpmiiyI.jpg?scale-down-to=1024&width=928&height=1846 514w,https://framerusercontent.com/images/AfVrJxeJkkgPpnO71Nw1tpmiiyI.jpg?width=928&height=1846 928w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", aspectRatio: "auto 928 / 1846", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.mobile_3.src} alt={content.mobile_3.alt} />
                    </div>
                  </div>
                </li>
              </motion.ul>
            </div>
            {" "}
            <div className="framer-14rjcff" style={{ width: "1200px", height: "450px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", overflowX: "clip", opacity: "1" } as CSSProperties}>
              <motion.ul style={{ width: "100%", height: "100%", maxWidth: "100%", maxHeight: "100%", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", gap: "10px", transform: "translateX(-2738.33px)", transformOrigin: "600px 225px", listStyleType: "none", padding: "0px", margin: "0px", opacity: "1" } as CSSProperties} initial={{ opacity: 0, x: -10 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}>
                <li className="ticker-item" aria-hidden="false" aria-posinset={1} aria-setsize={6} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", transformOrigin: "110px 225px", flexGrow: "0", flexShrink: "0" } as CSSProperties}>
                  <div className="framer-13ttiqh" data-border="true" data-framer-name="Mobile" style={{ width: "220px", height: "450px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "0.488889 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                    <div style={{ width: "220px", height: "450px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                      <img decoding="auto" loading="lazy" width="880" height="1808" sizes="(min-width: 1200px) 220px, (max-width: 809.98px) 127.1111px, (min-width: 810px) and (max-width: 1199.98px) 166.2222px" srcSet={"/images/ab7c8e15-RtheNIazFJm6EqfeKh66Bi7wyGI.avif?width=880&height=1808 880w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", aspectRatio: "auto 880 / 1808", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.mobile_4.src} alt={content.mobile_4.alt} />
                    </div>
                  </div>
                </li>
                <li className="ticker-item" aria-hidden="false" aria-posinset={2} aria-setsize={6} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", transformOrigin: "350px 224.996px", flexGrow: "0", flexShrink: "0" } as CSSProperties}>
                  <div className="framer-10vl1mt" data-border="true" data-framer-name="Site" style={{ width: "700px", height: "449.992px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "1.55556 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                    <div style={{ width: "700px", height: "449.992px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                      <img decoding="auto" loading="lazy" width="2874" height="1834" sizes="(min-width: 1200px) 700px, (max-width: 809.98px) 404.4444px, (min-width: 810px) and (max-width: 1199.98px) 528.8889px" srcSet={"/images/e1161846-CC3vnYoPhqbdIEFTrhc9At8bgWo.avif?scale-down-to=512&width=2874&height=1834 512w,/images/e1161846-CC3vnYoPhqbdIEFTrhc9At8bgWo.avif?scale-down-to=1024&width=2874&height=1834 1024w,/images/e1161846-CC3vnYoPhqbdIEFTrhc9At8bgWo.avif?scale-down-to=2048&width=2874&height=1834 2048w,/images/e1161846-CC3vnYoPhqbdIEFTrhc9At8bgWo.avif?width=2874&height=1834 2874w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2874 / 1834", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.site_4.src} alt={content.site_4.alt} />
                    </div>
                  </div>
                </li>
                <li className="ticker-item" aria-hidden="false" aria-posinset={3} aria-setsize={6} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", transformOrigin: "110px 225px", flexGrow: "0", flexShrink: "0" } as CSSProperties}>
                  <div className="framer-1y2las4" data-border="true" data-framer-name="Mobile" style={{ width: "220px", height: "450px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "0.488889 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                    <div style={{ width: "220px", height: "450px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                      <img decoding="auto" loading="lazy" width="880" height="1782" sizes="(min-width: 1200px) 220px, (max-width: 809.98px) 127.1111px, (min-width: 810px) and (max-width: 1199.98px) 166.2222px" srcSet={"/images/ae55d8fc-YCWnviU2EZwsP64iysymO773I.avif?width=880&height=1782 880w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", aspectRatio: "auto 880 / 1782", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.mobile_5.src} alt={content.mobile_5.alt} />
                    </div>
                  </div>
                </li>
                <li className="ticker-item" aria-hidden="false" aria-posinset={4} aria-setsize={6} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", transformOrigin: "350px 224.996px", flexGrow: "0", flexShrink: "0" } as CSSProperties}>
                  <div className="framer-7uwymb" data-border="true" data-framer-name="Site" style={{ width: "700px", height: "449.992px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "1.55556 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                    <div style={{ width: "700px", height: "449.992px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                      <img decoding="auto" loading="lazy" width="2800" height="1804" sizes="(min-width: 1200px) 700px, (max-width: 809.98px) 404.4444px, (min-width: 810px) and (max-width: 1199.98px) 528.8889px" srcSet={"/images/2c927f17-wbyAS4r6FWaI1G1ena314OJs.avif?scale-down-to=512&width=2800&height=1804 512w,/images/2c927f17-wbyAS4r6FWaI1G1ena314OJs.avif?scale-down-to=1024&width=2800&height=1804 1024w,/images/2c927f17-wbyAS4r6FWaI1G1ena314OJs.avif?scale-down-to=2048&width=2800&height=1804 2048w,/images/2c927f17-wbyAS4r6FWaI1G1ena314OJs.avif?width=2800&height=1804 2800w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2800 / 1804", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.site_5.src} alt={content.site_5.alt} />
                    </div>
                  </div>
                </li>
                <li className="ticker-item" aria-hidden="false" aria-posinset={5} aria-setsize={6} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", transformOrigin: "110px 225px", flexGrow: "0", flexShrink: "0" } as CSSProperties}>
                  <div className="framer-1nv22qs hv-1684" data-border="true" data-framer-name="Mobile" style={{ width: "220px", height: "450px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "0.488889 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                    <div style={{ width: "220px", height: "450px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                      <img decoding="async" loading="lazy" width="880" height="1806" sizes="(min-width: 1200px) 220px, (max-width: 809.98px) 127.1111px, (min-width: 810px) and (max-width: 1199.98px) 166.2222px" srcSet={"/images/acfb726f-Y6F5zkargty3ahKr9VGtA83ujXU.avif?width=880&height=1806 880w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", aspectRatio: "auto 880 / 1806", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.mobile_6.src} alt={content.mobile_6.alt} />
                    </div>
                  </div>
                </li>
                <li className="ticker-item" aria-hidden="false" aria-posinset={6} aria-setsize={6} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                  <div className="framer-1o9dl4s" data-border="true" data-framer-name="Site" style={{ width: "700px", height: "449.992px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "1.55556 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                    <div style={{ width: "700px", height: "449.992px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                      <img decoding="auto" loading="lazy" width="3200" height="2072" sizes="(min-width: 1200px) 700px, (max-width: 809.98px) 404.4444px, (min-width: 810px) and (max-width: 1199.98px) 528.8889px" srcSet={"/images/65d04a13-WDlxZ5aairNkZSH0cyHqAzB2w.avif?scale-down-to=512&width=3200&height=2072 512w,/images/65d04a13-WDlxZ5aairNkZSH0cyHqAzB2w.avif?scale-down-to=1024&width=3200&height=2072 1024w,/images/65d04a13-WDlxZ5aairNkZSH0cyHqAzB2w.avif?scale-down-to=2048&width=3200&height=2072 2048w,/images/65d04a13-WDlxZ5aairNkZSH0cyHqAzB2w.avif?width=3200&height=2072 3200w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", aspectRatio: "auto 3200 / 2072", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.site_6.src} alt={content.site_6.alt} />
                    </div>
                  </div>
                </li>
              </motion.ul>
            </div>
            {" "}
          </div>
        </div>
      </div>
    </section>
  );
}
