// route module for /publish — generated by `extract-site rebuild-site`
import { useEffect } from "react";
import { animate } from "framer-motion";
import { Page } from "./page";
import { runEntryAnimations } from "./animations";
import "./framer-baseline.css";
import "./app.css";

export default function Route() {
  useEffect(() => {
    runEntryAnimations(animate);
  }, []);
  return <Page />;
}
