// Tickers.tsx — section converted to a real JSX component by extract-site.
// Editable React: entrance animations are inline framer-motion props with the
// MEASURED timing from the original site; hover effects live in hover.css.
// Copy, photos, and links live in the sibling content module — edit there to
// re-skin this section without touching layout/motion.
import type { CSSProperties } from "react";
import { motion } from "framer-motion";
import content from "../content/04-Tickers";

export function Tickers() {
  return (
    <div className="framer-1sh9lqi" data-framer-name="Tickers" style={{ width: "1440px", height: "846.797px", padding: "120px 0px", position: "relative", zIndex: "1", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "40px" } as CSSProperties}>
      <header className="framer-1c6ufw8" data-framer-name="Header" style={{ width: "1200px", height: "96.7969px", maxWidth: "1200px", padding: "0px 20px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end", alignContent: "flex-end" } as CSSProperties}>
        <div className="framer-ot3wdd" data-framer-component-type="RichTextContainer" style={{ width: "444px", height: "96.7969px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", transform: "none" } as CSSProperties}>
          <h2 className="framer-text framer-styles-preset-fbtpvo" data-styles-preset="qRN7MgZKk" dir="auto" style={{ width: "444px", height: "96.7969px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"GT Walsheim Medium\", \"GT Walsheim Medium Placeholder\", sans-serif", fontSize: "44px", fontWeight: "500", lineHeight: "48.4px", letterSpacing: "-1.76px", textAlign: "left", color: "rgb(255, 255, 255)", "--framer-text-alignment": "left", "--framer-text-color": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))" } as CSSProperties}>
            {content.header}
          </h2>
        </div>
        <div className="ssr-variant" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
          <motion.div className="framer-w80qsc-container" data-framer-appear-id="w80qsc" style={{ width: "164.242px", height: "34px", position: "relative", zIndex: "2", display: "block", flexDirection: "row", opacity: "1", transform: "none", willChange: "transform" } as CSSProperties} initial={{ opacity: 0.001 }} whileInView={{ opacity: 1 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}>
            <a className="framer-B1iAE framer-11816n4 framer-v-11816n4 framer-b89n3n hv-985" data-framer-name="Regular" data-highlight="true" data-reset="button" tabIndex={0} style={{ width: "164.242px", height: "34px", padding: "10px 14px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "6px", backgroundColor: "rgba(255, 255, 255, 0.1)", borderRadius: "10px", color: "rgb(0, 0, 238)", overflow: "hidden", borderBottomLeftRadius: "10px", borderBottomRightRadius: "10px", borderTopLeftRadius: "10px", borderTopRightRadius: "10px", boxShadow: "var(--9xgf7k)", opacity: "1" } as CSSProperties} data-external-route="1" href={content.regular}>
              <div className="framer-1gwemsj" data-framer-name="Default" data-framer-component-type="RichTextContainer" style={{ width: "136.242px", height: "14px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 18, \"wght\" 560", "--extracted-r6o4lv": "var(--variable-reference-xdxfhd9wh-fpJV3zp1q)", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", "--variable-reference-xdxfhd9wh-fpjv3zp1q": "rgb(255, 255, 255)", transform: "none", opacity: "1" } as CSSProperties}>
                <p dir="auto" className="framer-text" style={{ width: "136.242px", height: "14px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "14px", lineHeight: "14px", letterSpacing: "-0.28px", textAlign: "center", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTRMQ0FpZDJkb2RDSWdOVFl3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv01' on, 'cv09' on, 'cv11' on", "--framer-font-size": "14px", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 18, \"wght\" 560)", "--framer-letter-spacing": "-0.02em", "--framer-line-height": "1em", "--framer-text-alignment": "center", "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-xdxfhd9wh-fpJV3zp1q))" } as CSSProperties}>
                  {content.default}
                </p>
              </div>
            </a>
          </motion.div>
        </div>
      </header>
      <div className="framer-11mioq8" style={{ width: "1440px", height: "470px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "10px", overflow: "clip", overflowX: "clip" } as CSSProperties}>
        <motion.ul style={{ width: "100%", height: "100%", maxWidth: "100%", maxHeight: "100%", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "flex-start", gap: "10px", transform: "translateX(-46.348px)", transformOrigin: "720px 235px", listStyleType: "none", padding: "0px", margin: "0px", opacity: "1" } as CSSProperties} initial={{ opacity: 0, x: -10 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}>
          <li className="ticker-item" aria-hidden="false" aria-posinset={1} aria-setsize={8} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
            <div className="ssr-variant hidden-l9fig7 hidden-1xcf01h" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
              <div className="framer-150gub4-container" style={{ width: "360px", height: "470px", position: "relative", display: "block", flexDirection: "row" } as CSSProperties}>
                <a className="framer-uKENX framer-rw0a82 framer-v-rw0a82 framer-kr7h0s hv-993" data-framer-name="Desktop" target="_blank" style={{ width: "100%", height: "470px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "20px", color: "rgb(0, 0, 238)", opacity: "1" } as CSSProperties} href={content.desktop}>
                  <div className="framer-1yk3mjg" style={{ width: "360px", height: "470px", position: "relative", zIndex: "10", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", borderRadius: "15px", overflow: "clip", "--border-bottom-width": "0px", "--border-color": "rgba(0, 0, 0, 0)", "--border-left-width": "0px", "--border-right-width": "0px", "--border-style": "solid", "--border-top-width": "0px", opacity: "1" } as CSSProperties}>
                    <div className="framer-vn7vf0 hvt-995" data-border="true" data-framer-name="Screenshot 2026-03-18 at 10.12.44" style={{ width: "360px", height: "470px", position: "relative", zIndex: "10", display: "block", flexDirection: "row", borderRadius: "15px", filter: "blur(0px)", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", WebkitFilter: "blur(0px)", borderBottomLeftRadius: "15px", borderBottomRightRadius: "15px", borderTopLeftRadius: "15px", borderTopRightRadius: "15px", opacity: "1" } as CSSProperties}>
                      <div style={{ width: "360px", height: "470px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="auto" loading="lazy" width="1556" height="2038" sizes="(min-width: 1200px) 360px, (min-width: 810px) and (max-width: 1199.98px) 250px, (max-width: 809.98px) 250px" srcSet={"/images/fe0aba1c-prYOTbuQKUG4KyWKeJjVbspyw.avif?scale-down-to=1024&width=1556&height=2038 781w,/images/fe0aba1c-prYOTbuQKUG4KyWKeJjVbspyw.avif?width=1556&height=2038 1556w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", aspectRatio: "auto 1556 / 2038", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.screenshot20260318At101244.src} alt={content.screenshot20260318At101244.alt} />
                      </div>
                    </div>
                    <div className="framer-1pjzeam hvt-998" data-framer-name="Image" style={{ width: "auto", height: "27px", position: "absolute", top: "235px", right: "78.75px", bottom: "208px", left: "180px", zIndex: "10", inset: "235px 78.75px 208px 180px", display: "block", flexDirection: "row", opacity: "0", transform: "translate(-50%, -50%)", transformOrigin: "50.625px 13.5px", aspectRatio: "3.75" } as CSSProperties}>
                      <div style={{ width: "101.25px", height: "27px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="auto" loading="lazy" width="165" height="44" style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 165 / 44", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.image.src} alt={content.image.alt} />
                      </div>
                    </div>
                    <div className="framer-1904vvb hvt-1001" data-framer-name="CTA 2026" style={{ width: "89.6797px", height: "21.6016px", position: "absolute", top: "408.398px", right: "90.3203px", bottom: "40px", left: "180px", zIndex: "10", inset: "408.398px 90.3203px 40px 180px", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "6px", opacity: "0", transform: "translateX(-50%)", transformOrigin: "44.8398px 10.8008px", overflow: "hidden" } as CSSProperties}>
                      <div className="framer-1f2gita" data-framer-component-type="RichTextContainer" style={{ width: "67.6797px", height: "21.6016px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-a0htzi": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--extracted-zfisys": "\"opsz\" 32, \"wght\" 500", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none", opacity: "1" } as CSSProperties}>
                        <h3 dir="auto" className="framer-text" style={{ width: "67.6797px", height: "21.6016px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "21.6px", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv11' on", "--framer-font-size": "18px", "--framer-font-variation-axes": "var(--extracted-zfisys, \"opsz\" 32, \"wght\" 500)", "--framer-text-color": "var(--extracted-a0htzi, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.cta2026}
                        </h3>
                      </div>
                      <div className="framer-791z8e" style={{ width: "16px", height: "18px", padding: "2px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "20px", opacity: "1" } as CSSProperties}>
                        <svg data-framer-name="CTA Icon" className="framer-ooj1j framer-1xvftmc" role="presentation" viewBox="0 0 20 20" style={{ width: "16px", height: "16px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)", "--17kkcf8": "rgba(255, 255, 255, 0)", opacity: "1" } as CSSProperties}>
                          <use href="#1825208344" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                        </svg>
                      </div>
                    </div>
                  </div>
                </a>
              </div>
            </div>
          </li>
          <li className="ticker-item" aria-hidden="false" aria-posinset={2} aria-setsize={8} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
            <div className="ssr-variant hidden-l9fig7 hidden-1xcf01h" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
              <div className="framer-1qidpf3-container" style={{ width: "360px", height: "470px", position: "relative", display: "block", flexDirection: "row" } as CSSProperties}>
                <a className="framer-uKENX framer-rw0a82 framer-v-rw0a82 framer-kr7h0s hv-1010" data-framer-name="Desktop" style={{ width: "100%", height: "470px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "20px", color: "rgb(0, 0, 238)", opacity: "1" } as CSSProperties} data-external-route="1" href={content.desktop_2}>
                  <div className="framer-1yk3mjg" style={{ width: "360px", height: "470px", position: "relative", zIndex: "10", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", borderRadius: "15px", overflow: "clip", "--border-bottom-width": "0px", "--border-color": "rgba(0, 0, 0, 0)", "--border-left-width": "0px", "--border-right-width": "0px", "--border-style": "solid", "--border-top-width": "0px", opacity: "1" } as CSSProperties}>
                    <div className="framer-vn7vf0 hvt-1012" data-border="true" data-framer-name="Screenshot 2026-03-18 at 10.12.44" style={{ width: "360px", height: "470px", position: "relative", zIndex: "10", display: "block", flexDirection: "row", borderRadius: "15px", filter: "blur(0px)", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", WebkitFilter: "blur(0px)", borderBottomLeftRadius: "15px", borderBottomRightRadius: "15px", borderTopLeftRadius: "15px", borderTopRightRadius: "15px", opacity: "1" } as CSSProperties}>
                      <div style={{ width: "360px", height: "470px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="auto" loading="lazy" width="1082" height="1444" sizes="(min-width: 1200px) 360px, (min-width: 810px) and (max-width: 1199.98px) 250px, (max-width: 809.98px) 250px" srcSet={"/images/582fb333-IqNlBQa4g0IgjSHXyZIDN9J50.avif?scale-down-to=1024&width=1082&height=1444 767w,/images/582fb333-IqNlBQa4g0IgjSHXyZIDN9J50.avif?width=1082&height=1444 1082w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", aspectRatio: "auto 1082 / 1444", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.screenshot20260318At101244_2.src} alt={content.screenshot20260318At101244_2.alt} />
                      </div>
                    </div>
                    <div className="framer-1pjzeam hvt-1015" data-framer-name="Image" style={{ width: "auto", height: "27px", position: "absolute", top: "235px", right: "41.3203px", bottom: "208px", left: "180px", zIndex: "10", inset: "235px 41.3203px 208px 180px", display: "block", flexDirection: "row", opacity: "0", transform: "translate(-50%, -50%)", transformOrigin: "69.3398px 13.5px", aspectRatio: "5.136363636363637" } as CSSProperties}>
                      <div style={{ width: "138.68px", height: "27px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="auto" loading="lazy" width="226" height="44" style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 226 / 44", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.image_2.src} alt={content.image_2.alt} />
                      </div>
                    </div>
                    <div className="framer-1904vvb hvt-1018" data-framer-name="CTA 2026" style={{ width: "108.539px", height: "21.6016px", position: "absolute", top: "408.398px", right: "71.4609px", bottom: "40px", left: "180px", zIndex: "10", inset: "408.398px 71.4609px 40px 180px", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "6px", opacity: "0", transform: "translateX(-50%)", transformOrigin: "54.2695px 10.8008px", overflow: "hidden" } as CSSProperties}>
                      <div className="framer-1f2gita" data-framer-component-type="RichTextContainer" style={{ width: "86.5391px", height: "21.6016px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-a0htzi": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--extracted-zfisys": "\"opsz\" 32, \"wght\" 500", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none", opacity: "1" } as CSSProperties}>
                        <h3 dir="auto" className="framer-text" style={{ width: "86.5391px", height: "21.6016px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "21.6px", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv11' on", "--framer-font-size": "18px", "--framer-font-variation-axes": "var(--extracted-zfisys, \"opsz\" 32, \"wght\" 500)", "--framer-text-color": "var(--extracted-a0htzi, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.cta2026_2}
                        </h3>
                      </div>
                      <div className="framer-791z8e" style={{ width: "16px", height: "18px", padding: "2px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "20px", opacity: "1" } as CSSProperties}>
                        <svg data-framer-name="CTA Icon" className="framer-ooj1j framer-1xvftmc" role="presentation" viewBox="0 0 20 20" style={{ width: "16px", height: "16px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)", "--17kkcf8": "rgba(255, 255, 255, 0)", opacity: "1" } as CSSProperties}>
                          <use href="#1825208344" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                        </svg>
                      </div>
                    </div>
                  </div>
                </a>
              </div>
            </div>
          </li>
          <li className="ticker-item" aria-hidden="false" aria-posinset={3} aria-setsize={8} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
            <div className="ssr-variant hidden-l9fig7 hidden-1xcf01h" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
              <div className="framer-1e3nfit-container" style={{ width: "360px", height: "470px", position: "relative", display: "block", flexDirection: "row" } as CSSProperties}>
                <a className="framer-uKENX framer-rw0a82 framer-v-rw0a82 framer-kr7h0s hv-1027" data-framer-name="Desktop" target="_blank" style={{ width: "100%", height: "470px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "20px", color: "rgb(0, 0, 238)", opacity: "1" } as CSSProperties} href={content.desktop_3}>
                  <div className="framer-1yk3mjg" style={{ width: "360px", height: "470px", position: "relative", zIndex: "10", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", borderRadius: "15px", overflow: "clip", "--border-bottom-width": "0px", "--border-color": "rgba(0, 0, 0, 0)", "--border-left-width": "0px", "--border-right-width": "0px", "--border-style": "solid", "--border-top-width": "0px", opacity: "1" } as CSSProperties}>
                    <div className="framer-vn7vf0 hvt-1029" data-border="true" data-framer-name="Screenshot 2026-03-18 at 10.12.44" style={{ width: "360px", height: "470px", position: "relative", zIndex: "10", display: "block", flexDirection: "row", borderRadius: "15px", filter: "blur(0px)", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", WebkitFilter: "blur(0px)", borderBottomLeftRadius: "15px", borderBottomRightRadius: "15px", borderTopLeftRadius: "15px", borderTopRightRadius: "15px", opacity: "1" } as CSSProperties}>
                      <div style={{ width: "360px", height: "470px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="auto" loading="lazy" width="1298" height="1778" sizes="(min-width: 1200px) 360px, (min-width: 810px) and (max-width: 1199.98px) 250px, (max-width: 809.98px) 250px" srcSet={"/images/00f633e4-ea5P80FHZqsSGMCsYLyPqjeQdo.avif?scale-down-to=1024&width=1298&height=1778 747w,/images/00f633e4-ea5P80FHZqsSGMCsYLyPqjeQdo.avif?width=1298&height=1778 1298w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", objectPosition: "49.4% 0%", aspectRatio: "auto 1298 / 1778", cornerShape: "inherit" } as CSSProperties} src={content.screenshot20260318At101244_3.src} alt={content.screenshot20260318At101244_3.alt} />
                      </div>
                    </div>
                    <div className="framer-1pjzeam hvt-1032" data-framer-name="Image" style={{ width: "auto", height: "27px", position: "absolute", top: "235px", right: "40.0938px", bottom: "208px", left: "180px", zIndex: "10", inset: "235px 40.0938px 208px 180px", display: "block", flexDirection: "row", opacity: "0", transform: "translate(-50%, -50%)", transformOrigin: "69.9531px 13.5px", aspectRatio: "5.181818181818182" } as CSSProperties}>
                      <div style={{ width: "139.906px", height: "27px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="auto" loading="lazy" width="228" height="44" style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 228 / 44", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.image_3.src} alt={content.image_3.alt} />
                      </div>
                    </div>
                    <div className="framer-1904vvb hvt-1035" data-framer-name="CTA 2026" style={{ width: "89.6797px", height: "21.6016px", position: "absolute", top: "408.398px", right: "90.3203px", bottom: "40px", left: "180px", zIndex: "10", inset: "408.398px 90.3203px 40px 180px", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "6px", opacity: "0", transform: "translateX(-50%)", transformOrigin: "44.8398px 10.8008px", overflow: "hidden" } as CSSProperties}>
                      <div className="framer-1f2gita" data-framer-component-type="RichTextContainer" style={{ width: "67.6797px", height: "21.6016px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-a0htzi": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--extracted-zfisys": "\"opsz\" 32, \"wght\" 500", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none", opacity: "1" } as CSSProperties}>
                        <h3 dir="auto" className="framer-text" style={{ width: "67.6797px", height: "21.6016px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "21.6px", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv11' on", "--framer-font-size": "18px", "--framer-font-variation-axes": "var(--extracted-zfisys, \"opsz\" 32, \"wght\" 500)", "--framer-text-color": "var(--extracted-a0htzi, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.cta2026_3}
                        </h3>
                      </div>
                      <div className="framer-791z8e" style={{ width: "16px", height: "18px", padding: "2px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "20px", opacity: "1" } as CSSProperties}>
                        <svg data-framer-name="CTA Icon" className="framer-ooj1j framer-1xvftmc" role="presentation" viewBox="0 0 20 20" style={{ width: "16px", height: "16px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)", "--17kkcf8": "rgba(255, 255, 255, 0)", opacity: "1" } as CSSProperties}>
                          <use href="#1825208344" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                        </svg>
                      </div>
                    </div>
                  </div>
                </a>
              </div>
            </div>
          </li>
          <li className="ticker-item" aria-hidden="false" aria-posinset={4} aria-setsize={8} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
            <div className="ssr-variant hidden-l9fig7 hidden-1xcf01h" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
              <div className="framer-169xksw-container" style={{ width: "360px", height: "470px", position: "relative", display: "block", flexDirection: "row" } as CSSProperties}>
                <a className="framer-uKENX framer-rw0a82 framer-v-rw0a82 framer-kr7h0s hv-1044" data-framer-name="Desktop" target="_blank" style={{ width: "100%", height: "470px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "20px", color: "rgb(0, 0, 238)", opacity: "1" } as CSSProperties} href={content.desktop_4}>
                  <div className="framer-1yk3mjg" style={{ width: "360px", height: "470px", position: "relative", zIndex: "10", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", borderRadius: "15px", overflow: "clip", "--border-bottom-width": "0px", "--border-color": "rgba(0, 0, 0, 0)", "--border-left-width": "0px", "--border-right-width": "0px", "--border-style": "solid", "--border-top-width": "0px", opacity: "1" } as CSSProperties}>
                    <div className="framer-vn7vf0 hvt-1046" data-border="true" data-framer-name="Screenshot 2026-03-18 at 10.12.44" style={{ width: "360px", height: "470px", position: "relative", zIndex: "10", display: "block", flexDirection: "row", borderRadius: "15px", filter: "blur(0px)", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", WebkitFilter: "blur(0px)", borderBottomLeftRadius: "15px", borderBottomRightRadius: "15px", borderTopLeftRadius: "15px", borderTopRightRadius: "15px", opacity: "1" } as CSSProperties}>
                      <div style={{ width: "360px", height: "470px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="auto" loading="lazy" width="720" height="940" sizes="(min-width: 1200px) 360px, (min-width: 810px) and (max-width: 1199.98px) 250px, (max-width: 809.98px) 250px" srcSet={"/images/450b29bf-81LyeTvdrfMKGfh3sDUD9Ni2ms.avif?width=720&height=940 720w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", aspectRatio: "auto 720 / 940", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.screenshot20260318At101244_4.src} alt={content.screenshot20260318At101244_4.alt} />
                      </div>
                    </div>
                    <div className="framer-1pjzeam hvt-1049" data-framer-name="Image" style={{ width: "auto", height: "27px", position: "absolute", top: "235px", right: "63.4141px", bottom: "208px", left: "180px", zIndex: "10", inset: "235px 63.4141px 208px 180px", display: "block", flexDirection: "row", opacity: "0", transform: "translate(-50%, -50%)", transformOrigin: "58.293px 13.5px", aspectRatio: "4.318181818181818" } as CSSProperties}>
                      <div style={{ width: "116.586px", height: "27px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="auto" loading="lazy" width="190" height="44" style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 190 / 44", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.image_4.src} alt={content.image_4.alt} />
                      </div>
                    </div>
                    <div className="framer-1904vvb hvt-1052" data-framer-name="CTA 2026" style={{ width: "89.6797px", height: "21.6016px", position: "absolute", top: "408.398px", right: "90.3203px", bottom: "40px", left: "180px", zIndex: "10", inset: "408.398px 90.3203px 40px 180px", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "6px", opacity: "0", transform: "translateX(-50%)", transformOrigin: "44.8398px 10.8008px", overflow: "hidden" } as CSSProperties}>
                      <div className="framer-1f2gita" data-framer-component-type="RichTextContainer" style={{ width: "67.6797px", height: "21.6016px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-a0htzi": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--extracted-zfisys": "\"opsz\" 32, \"wght\" 500", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none", opacity: "1" } as CSSProperties}>
                        <h3 dir="auto" className="framer-text" style={{ width: "67.6797px", height: "21.6016px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "21.6px", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv11' on", "--framer-font-size": "18px", "--framer-font-variation-axes": "var(--extracted-zfisys, \"opsz\" 32, \"wght\" 500)", "--framer-text-color": "var(--extracted-a0htzi, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.cta2026_4}
                        </h3>
                      </div>
                      <div className="framer-791z8e" style={{ width: "16px", height: "18px", padding: "2px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "20px", opacity: "1" } as CSSProperties}>
                        <svg data-framer-name="CTA Icon" className="framer-ooj1j framer-1xvftmc" role="presentation" viewBox="0 0 20 20" style={{ width: "16px", height: "16px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)", "--17kkcf8": "rgba(255, 255, 255, 0)", opacity: "1" } as CSSProperties}>
                          <use href="#1825208344" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                        </svg>
                      </div>
                    </div>
                  </div>
                </a>
              </div>
            </div>
          </li>
          <li className="ticker-item" aria-hidden="false" aria-posinset={5} aria-setsize={8} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
            <div className="ssr-variant hidden-l9fig7 hidden-1xcf01h" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
              <div className="framer-anpl67-container" style={{ width: "360px", height: "470px", position: "relative", display: "block", flexDirection: "row" } as CSSProperties}>
                <a className="framer-uKENX framer-rw0a82 framer-v-rw0a82 framer-kr7h0s" data-framer-name="Desktop" target="_blank" style={{ width: "100%", height: "470px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "20px", color: "rgb(0, 0, 238)", opacity: "1" } as CSSProperties} data-external-route="1" href={content.desktop_5}>
                  <div className="framer-1yk3mjg" style={{ width: "360px", height: "470px", position: "relative", zIndex: "10", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", borderRadius: "15px", overflow: "clip", "--border-bottom-width": "0px", "--border-color": "rgba(0, 0, 0, 0)", "--border-left-width": "0px", "--border-right-width": "0px", "--border-style": "solid", "--border-top-width": "0px", opacity: "1" } as CSSProperties}>
                    <div className="framer-vn7vf0" data-border="true" data-framer-name="Screenshot 2026-03-18 at 10.12.44" style={{ width: "360px", height: "470px", position: "relative", zIndex: "10", display: "block", flexDirection: "row", borderRadius: "15px", filter: "blur(0px)", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", WebkitFilter: "blur(0px)", borderBottomLeftRadius: "15px", borderBottomRightRadius: "15px", borderTopLeftRadius: "15px", borderTopRightRadius: "15px", opacity: "1" } as CSSProperties}>
                      <div style={{ width: "360px", height: "470px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="auto" loading="lazy" width="720" height="940" sizes="(min-width: 1200px) 360px, (min-width: 810px) and (max-width: 1199.98px) 250px, (max-width: 809.98px) 250px" srcSet={"/images/954ecccc-dmZq8bH8DDYEVu3GbrEBdRuhg.avif?width=720&height=940 720w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", aspectRatio: "auto 720 / 940", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.screenshot20260318At101244_5.src} alt={content.screenshot20260318At101244_5.alt} />
                      </div>
                    </div>
                    <div className="framer-1pjzeam" data-framer-name="Image" style={{ width: "auto", height: "27px", position: "absolute", top: "235px", right: "90.4141px", bottom: "208px", left: "180px", zIndex: "10", inset: "235px 90.4141px 208px 180px", display: "block", flexDirection: "row", opacity: "0", transform: "translate(-50%, -50%)", transformOrigin: "44.793px 13.5px", aspectRatio: "3.3181818181818183" } as CSSProperties}>
                      <div style={{ width: "89.5859px", height: "27px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="async" loading="lazy" width="146" height="44" style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 146 / 44", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.image_5.src} alt={content.image_5.alt} />
                      </div>
                    </div>
                    <div className="framer-1904vvb" data-framer-name="CTA 2026" style={{ width: "108.539px", height: "21.6016px", position: "absolute", top: "408.398px", right: "71.4609px", bottom: "40px", left: "180px", zIndex: "10", inset: "408.398px 71.4609px 40px 180px", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "6px", opacity: "0", transform: "translateX(-50%)", transformOrigin: "54.2695px 10.8008px", overflow: "hidden" } as CSSProperties}>
                      <div className="framer-1f2gita" data-framer-component-type="RichTextContainer" style={{ width: "86.5391px", height: "21.6016px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-a0htzi": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--extracted-zfisys": "\"opsz\" 32, \"wght\" 500", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none", opacity: "1" } as CSSProperties}>
                        <h3 dir="auto" className="framer-text" style={{ width: "86.5391px", height: "21.6016px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "21.6px", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv11' on", "--framer-font-size": "18px", "--framer-font-variation-axes": "var(--extracted-zfisys, \"opsz\" 32, \"wght\" 500)", "--framer-text-color": "var(--extracted-a0htzi, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.cta2026_5}
                        </h3>
                      </div>
                      <div className="framer-791z8e" style={{ width: "16px", height: "18px", padding: "2px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "20px", opacity: "1" } as CSSProperties}>
                        <svg data-framer-name="CTA Icon" className="framer-ooj1j framer-1xvftmc" role="presentation" viewBox="0 0 20 20" style={{ width: "16px", height: "16px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)", "--17kkcf8": "rgba(255, 255, 255, 0)", opacity: "1" } as CSSProperties}>
                          <use href="#1825208344" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                        </svg>
                      </div>
                    </div>
                  </div>
                </a>
              </div>
            </div>
          </li>
          <li className="ticker-item" aria-hidden="false" aria-posinset={6} aria-setsize={8} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
            <div className="ssr-variant hidden-l9fig7 hidden-1xcf01h" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
              <div className="framer-18yx8f6-container" style={{ width: "360px", height: "470px", position: "relative", display: "block", flexDirection: "row" } as CSSProperties}>
                <a className="framer-uKENX framer-rw0a82 framer-v-rw0a82 framer-kr7h0s" data-framer-name="Desktop" target="_blank" style={{ width: "100%", height: "470px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "20px", color: "rgb(0, 0, 238)", opacity: "1" } as CSSProperties} href={content.desktop_6}>
                  <div className="framer-1yk3mjg" style={{ width: "360px", height: "470px", position: "relative", zIndex: "10", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", borderRadius: "15px", overflow: "clip", "--border-bottom-width": "0px", "--border-color": "rgba(0, 0, 0, 0)", "--border-left-width": "0px", "--border-right-width": "0px", "--border-style": "solid", "--border-top-width": "0px", opacity: "1" } as CSSProperties}>
                    <div className="framer-vn7vf0" data-border="true" data-framer-name="Screenshot 2026-03-18 at 10.12.44" style={{ width: "360px", height: "470px", position: "relative", zIndex: "10", display: "block", flexDirection: "row", borderRadius: "15px", filter: "blur(0px)", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", WebkitFilter: "blur(0px)", borderBottomLeftRadius: "15px", borderBottomRightRadius: "15px", borderTopLeftRadius: "15px", borderTopRightRadius: "15px", opacity: "1" } as CSSProperties}>
                      <div style={{ width: "360px", height: "470px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="async" loading="lazy" width="1100" height="1460" sizes="(min-width: 1200px) 360px, (min-width: 810px) and (max-width: 1199.98px) 250px, (max-width: 809.98px) 250px" srcSet={"https://framerusercontent.com/images/u0dr02PjWV8lcJCE06d6zvhMo4o.png?scale-down-to=1024&width=1100&height=1460 771w,https://framerusercontent.com/images/u0dr02PjWV8lcJCE06d6zvhMo4o.png?width=1100&height=1460 1100w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", aspectRatio: "auto 1100 / 1460", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.screenshot20260318At101244_6.src} alt={content.screenshot20260318At101244_6.alt} />
                      </div>
                    </div>
                    <div className="framer-1pjzeam" data-framer-name="Image" style={{ width: "auto", height: "27px", position: "absolute", top: "235px", right: "-38.4531px", bottom: "208px", left: "180px", zIndex: "10", inset: "235px -38.4531px 208px 180px", display: "block", flexDirection: "row", opacity: "0", transform: "translate(-50%, -50%)", transformOrigin: "109.227px 13.5px", aspectRatio: "8.090909090909092" } as CSSProperties}>
                      <div style={{ width: "218.453px", height: "27px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="async" loading="lazy" width="356" height="44" style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 356 / 44", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.image_6.src} alt={content.image_6.alt} />
                      </div>
                    </div>
                    <div className="framer-1904vvb" data-framer-name="CTA 2026" style={{ width: "89.6797px", height: "21.6016px", position: "absolute", top: "408.398px", right: "90.3203px", bottom: "40px", left: "180px", zIndex: "10", inset: "408.398px 90.3203px 40px 180px", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "6px", opacity: "0", transform: "translateX(-50%)", transformOrigin: "44.8398px 10.8008px", overflow: "hidden" } as CSSProperties}>
                      <div className="framer-1f2gita" data-framer-component-type="RichTextContainer" style={{ width: "67.6797px", height: "21.6016px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-a0htzi": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--extracted-zfisys": "\"opsz\" 32, \"wght\" 500", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none", opacity: "1" } as CSSProperties}>
                        <h3 dir="auto" className="framer-text" style={{ width: "67.6797px", height: "21.6016px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "21.6px", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv11' on", "--framer-font-size": "18px", "--framer-font-variation-axes": "var(--extracted-zfisys, \"opsz\" 32, \"wght\" 500)", "--framer-text-color": "var(--extracted-a0htzi, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.cta2026_6}
                        </h3>
                      </div>
                      <div className="framer-791z8e" style={{ width: "16px", height: "18px", padding: "2px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "20px", opacity: "1" } as CSSProperties}>
                        <svg data-framer-name="CTA Icon" className="framer-ooj1j framer-1xvftmc" role="presentation" viewBox="0 0 20 20" style={{ width: "16px", height: "16px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)", "--17kkcf8": "rgba(255, 255, 255, 0)", opacity: "1" } as CSSProperties}>
                          <use href="#1825208344" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                        </svg>
                      </div>
                    </div>
                  </div>
                </a>
              </div>
            </div>
          </li>
          <li className="ticker-item" aria-hidden="false" aria-posinset={7} aria-setsize={8} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
            <div className="ssr-variant hidden-l9fig7 hidden-1xcf01h" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
              <div className="framer-1msb5d1-container" style={{ width: "360px", height: "470px", position: "relative", display: "block", flexDirection: "row" } as CSSProperties}>
                <a className="framer-uKENX framer-rw0a82 framer-v-rw0a82 framer-kr7h0s" data-framer-name="Desktop" style={{ width: "100%", height: "470px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "20px", color: "rgb(0, 0, 238)", opacity: "1" } as CSSProperties} data-external-route="1" href={content.desktop_7}>
                  <div className="framer-1yk3mjg" style={{ width: "360px", height: "470px", position: "relative", zIndex: "10", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", borderRadius: "15px", overflow: "clip", "--border-bottom-width": "0px", "--border-color": "rgba(0, 0, 0, 0)", "--border-left-width": "0px", "--border-right-width": "0px", "--border-style": "solid", "--border-top-width": "0px", opacity: "1" } as CSSProperties}>
                    <div className="framer-vn7vf0" data-border="true" data-framer-name="Screenshot 2026-03-18 at 10.12.44" style={{ width: "360px", height: "470px", position: "relative", zIndex: "10", display: "block", flexDirection: "row", borderRadius: "15px", filter: "blur(0px)", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", WebkitFilter: "blur(0px)", borderBottomLeftRadius: "15px", borderBottomRightRadius: "15px", borderTopLeftRadius: "15px", borderTopRightRadius: "15px", opacity: "1" } as CSSProperties}>
                      <div style={{ width: "360px", height: "470px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="async" loading="lazy" width="720" height="940" sizes="(min-width: 1200px) 360px, (min-width: 810px) and (max-width: 1199.98px) 250px, (max-width: 809.98px) 250px" srcSet={"https://framerusercontent.com/images/ED1u34oKVzLor2eMzFDxdtfKo.jpg?width=720&height=940 720w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", aspectRatio: "auto 720 / 940", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.screenshot20260318At101244_7.src} alt={content.screenshot20260318At101244_7.alt} />
                      </div>
                    </div>
                    <div className="framer-1pjzeam" data-framer-name="Image" style={{ width: "auto", height: "27px", position: "absolute", top: "235px", right: "41.3203px", bottom: "208px", left: "180px", zIndex: "10", inset: "235px 41.3203px 208px 180px", display: "block", flexDirection: "row", opacity: "0", transform: "translate(-50%, -50%)", transformOrigin: "69.3398px 13.5px", aspectRatio: "5.136363636363637" } as CSSProperties}>
                      <div style={{ width: "138.68px", height: "27px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="async" loading="lazy" width="226" height="44" style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 226 / 44", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.image_7.src} alt={content.image_7.alt} />
                      </div>
                    </div>
                    <div className="framer-1904vvb" data-framer-name="CTA 2026" style={{ width: "108.539px", height: "21.6016px", position: "absolute", top: "408.398px", right: "71.4609px", bottom: "40px", left: "180px", zIndex: "10", inset: "408.398px 71.4609px 40px 180px", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "6px", opacity: "0", transform: "translateX(-50%)", transformOrigin: "54.2695px 10.8008px", overflow: "hidden" } as CSSProperties}>
                      <div className="framer-1f2gita" data-framer-component-type="RichTextContainer" style={{ width: "86.5391px", height: "21.6016px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-a0htzi": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--extracted-zfisys": "\"opsz\" 32, \"wght\" 500", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none", opacity: "1" } as CSSProperties}>
                        <h3 dir="auto" className="framer-text" style={{ width: "86.5391px", height: "21.6016px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "21.6px", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv11' on", "--framer-font-size": "18px", "--framer-font-variation-axes": "var(--extracted-zfisys, \"opsz\" 32, \"wght\" 500)", "--framer-text-color": "var(--extracted-a0htzi, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.cta2026_7}
                        </h3>
                      </div>
                      <div className="framer-791z8e" style={{ width: "16px", height: "18px", padding: "2px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "20px", opacity: "1" } as CSSProperties}>
                        <svg data-framer-name="CTA Icon" className="framer-ooj1j framer-1xvftmc" role="presentation" viewBox="0 0 20 20" style={{ width: "16px", height: "16px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)", "--17kkcf8": "rgba(255, 255, 255, 0)", opacity: "1" } as CSSProperties}>
                          <use href="#1825208344" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                        </svg>
                      </div>
                    </div>
                  </div>
                </a>
              </div>
            </div>
          </li>
          <li className="ticker-item" aria-hidden="false" aria-posinset={8} aria-setsize={8} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
            <div className="ssr-variant hidden-l9fig7 hidden-1xcf01h" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
              <div className="framer-86e1vf-container" style={{ width: "360px", height: "470px", position: "relative", display: "block", flexDirection: "row" } as CSSProperties}>
                <a className="framer-uKENX framer-rw0a82 framer-v-rw0a82 framer-kr7h0s" data-framer-name="Desktop" target="_blank" style={{ width: "100%", height: "470px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "20px", color: "rgb(0, 0, 238)", opacity: "1" } as CSSProperties} href={content.desktop_8}>
                  <div className="framer-1yk3mjg" style={{ width: "360px", height: "470px", position: "relative", zIndex: "10", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", borderRadius: "15px", overflow: "clip", "--border-bottom-width": "0px", "--border-color": "rgba(0, 0, 0, 0)", "--border-left-width": "0px", "--border-right-width": "0px", "--border-style": "solid", "--border-top-width": "0px", opacity: "1" } as CSSProperties}>
                    <div className="framer-vn7vf0" data-border="true" data-framer-name="Screenshot 2026-03-18 at 10.12.44" style={{ width: "360px", height: "470px", position: "relative", zIndex: "10", display: "block", flexDirection: "row", borderRadius: "15px", filter: "blur(0px)", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", WebkitFilter: "blur(0px)", borderBottomLeftRadius: "15px", borderBottomRightRadius: "15px", borderTopLeftRadius: "15px", borderTopRightRadius: "15px", opacity: "1" } as CSSProperties}>
                      <div style={{ width: "360px", height: "470px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="async" loading="lazy" width="720" height="940" sizes="(min-width: 1200px) 360px, (min-width: 810px) and (max-width: 1199.98px) 250px, (max-width: 809.98px) 250px" srcSet={"https://framerusercontent.com/images/teozeGtHJpQiTQif1LrppRdrg.png?width=720&height=940 720w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", aspectRatio: "auto 720 / 940", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.screenshot20260318At101244_8.src} alt={content.screenshot20260318At101244_8.alt} />
                      </div>
                    </div>
                    <div className="framer-1pjzeam" data-framer-name="Image" style={{ width: "auto", height: "27px", position: "absolute", top: "235px", right: "30.2734px", bottom: "208px", left: "180px", zIndex: "10", inset: "235px 30.2734px 208px 180px", display: "block", flexDirection: "row", opacity: "0", transform: "translate(-50%, -50%)", transformOrigin: "74.8633px 13.5px", aspectRatio: "5.545454545454546" } as CSSProperties}>
                      <div style={{ width: "149.727px", height: "27px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                        <img decoding="async" loading="lazy" width="244" height="44" style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 244 / 44", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.image_8.src} alt={content.image_8.alt} />
                      </div>
                    </div>
                    <div className="framer-1904vvb" data-framer-name="CTA 2026" style={{ width: "89.6797px", height: "21.6016px", position: "absolute", top: "408.398px", right: "90.3203px", bottom: "40px", left: "180px", zIndex: "10", inset: "408.398px 90.3203px 40px 180px", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "6px", opacity: "0", transform: "translateX(-50%)", transformOrigin: "44.8398px 10.8008px", overflow: "hidden" } as CSSProperties}>
                      <div className="framer-1f2gita" data-framer-component-type="RichTextContainer" style={{ width: "67.6797px", height: "21.6016px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-a0htzi": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--extracted-zfisys": "\"opsz\" 32, \"wght\" 500", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none", opacity: "1" } as CSSProperties}>
                        <h3 dir="auto" className="framer-text" style={{ width: "67.6797px", height: "21.6016px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "21.6px", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv11' on", "--framer-font-size": "18px", "--framer-font-variation-axes": "var(--extracted-zfisys, \"opsz\" 32, \"wght\" 500)", "--framer-text-color": "var(--extracted-a0htzi, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.cta2026_8}
                        </h3>
                      </div>
                      <div className="framer-791z8e" style={{ width: "16px", height: "18px", padding: "2px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "20px", opacity: "1" } as CSSProperties}>
                        <svg data-framer-name="CTA Icon" className="framer-ooj1j framer-1xvftmc" role="presentation" viewBox="0 0 20 20" style={{ width: "16px", height: "16px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)", "--17kkcf8": "rgba(255, 255, 255, 0)", opacity: "1" } as CSSProperties}>
                          <use href="#1825208344" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                        </svg>
                      </div>
                    </div>
                  </div>
                </a>
              </div>
            </div>
          </li>
        </motion.ul>
      </div>
      {" "}
    </div>
  );
}
