// content for the "UI" section — extracted by extract-site.
// Edit values here to re-skin the "UI" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "A freeform canvas, powered by agents",
  regular: "https://framer-ai.com/r/signup",
  label: "Get started for free",
  canvas: "Canvas",
  default: "Site",
  default_2: "·",
  off: "main",
  number: "12",
  team: { src: "/images/67795d4b-UnfUTFiycUvyLiWVaZSTQX3S7kA73f7.png?width=335&height=335", alt: "Interface preview in 2026 UI/Canvas UI/App UI Top Bar." },
  team_2: { src: "/images/02612926-23W7URwXzeyNBGr6KAR1Ovou6V44395.png?width=475&height=475", alt: "Interface preview in 2026 UI/Canvas UI/App UI Top Bar." },
  team_3: { src: "/images/9081ee25-HpuIynUBjhAJSaXjaIesR9XZ7fMdb13.png?scale-down-to=512&width=2160&height=2160", alt: "Interface preview in 2026 UI/Canvas UI/App UI Top Bar." },
  invite: "Invite",
  publish: "Publish",
  on: "Pages",
  off_2: "Layers",
  off_3: "Assets",
  input: "Search…",
  pageHeader: "Pages",
  activePage: "Home",
  page: "/product",
  subPage: "Product Pages",
  page_2: "/support",
  page_3: "/learn",
  page_4: "/get-access",
  page_5: "/updates",
  page_6: "/legal",
  subPage_2: "/privacy",
  subPage_3: "/terms",
  subPage_4: "/accessibility",
  page_7: "/disclosures",
  zoom: "100%",
  off_4: "Desktop",
  off_5: "1200",
  intro2x: { src: "../../framerusercontent.com/images/fxBwL6c5xiFZMHDj4lZMzPAXwrY7b6a.jpg?width=2400&height=2530", alt: "Intro interface preview in 2026 Design Poge/Design Hero Site." },
  logo: "Parallel®",
  dropdown: "Product",
  links: "Support",
  button: "Login",
  button_2: "Get access",
  header_2: "Investing",
  header_3: "simplified.",
  text: "Built for the future.",
  text_2: "Parallel is your AI co-pilot for smarter investing. It analyzes markets, manages risk, and grows your portfolio 24/7.",
  image3: { src: "/images/e2ab092c-Aj6faC09I7L2HCjiL12UAInFQUA.avif?width=1792&height=2688", alt: "Image 3 interface preview in 2026 Design Poge/Design Hero Site." },
  portfolio: "Balanced portfolio",
  portfolio_2: "Equities",
  portfolio_3: "Global Bonds",
  portfolio_4: "Cash",
  portfolio_5: "Other",
  off_6: "Tablet",
  off_7: "810",
  default_3: { src: "../../framerusercontent.com/images/ICi2m2zyPai1LKwz9XZEkgSzQbacd.jpg?width=1620&height=140", alt: "Default interface preview in 2026 Frontpage/Home Hero Site Tablet." },
  hero: "https://framerusercontent.com/assets/tIWm3IhzJNTfEtVL9lEqnFZAy58.mp4",
  about: { src: "../../framerusercontent.com/images/HMvEeofMOWYzHDwChgXFgpYcs9a75.jpg?width=1620&height=370", alt: "About interface preview in 2026 Frontpage/Home Hero Site Tablet." },
  heroVideo: { src: "../../framerusercontent.com/images/VDou7Mwa4dcffjzYvoa80Cmi7438ca.jpg?width=1620&height=960", alt: "Hero Video interface preview in 2026 Frontpage/Home Hero Site Tablet." },
  list: { src: "../../framerusercontent.com/images/MvPPd7I4xJxeNO5ievRfaoAEdd78.jpg?width=1620&height=1180", alt: "List interface preview in 2026 Frontpage/Home Hero Site Tablet." },
  footer: { src: "../../framerusercontent.com/images/I4HWeSzUbC3vy22QykEaieasPYbacd.jpg?width=1620&height=140", alt: "Interface preview in 2026 Frontpage/Home Hero Site Tablet." },
  tab: "Agent",
  tab_2: "Style",
  positionHeader: "Position",
  top: "400",
  top_2: "T",
  bottom: "400",
  bottom_2: "B",
  left: "600",
  left_2: "L",
  right: "600",
  right_2: "R",
  type: "Type",
  type_2: "Absolute",
  sizeHeader: "Size",
  width: "Width",
  width_2: "200",
  width_3: "Fixed",
  height: "Height",
  height_2: "100",
  height_3: "Fit",
  minMax: "Min Max",
  minMax_2: "Add…",
  layout: "Layout",
  stylesHeader: "Styles",
  visible: "Visible",
  visible_2: "Yes",
  visible_3: "No",
  opacity: "Opacity",
  opacity_2: "0.5",
  fill: "Fill",
  fill_2: "999999",
  border: "Border",
  border_2: "Add…",
  shadows: "Shadows",
  shadows_2: "Add…",
  radius: "Radius",
  radius_2: "20",
  padding: "Padding",
  padding_2: "20",
  filters: "Filters",
  filters_2: "Add…",
  sorting: "Sorting",
  sorting_2: "Add…",
  pagination: "Pagination",
  pagination_2: "Add…",
};
