// content for the "Benefits" section — extracted by extract-site.
// Edit values here to re-skin the "Benefits" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "Design with AI. Control every detail.",
  row: { src: "/images/7013e865-A1HGvTdwcqcQ5fggStJ9fUU9889fa.jpg?width=200&height=140", alt: "Landscape" },
  text: "Market rise",
  text_2: "AI-led growth",
  text_3: "2026",
  row_2: { src: "/images/bad66d9d-h8A5RDOo2mAXizrlBptvF7YzWA89fa.jpg?width=200&height=140", alt: "Landscape" },
  text_4: "Horizon shift",
  text_5: "Adaptive strategy",
  text_6: "2025",
  row_3: { src: "/images/3c7fe939-u0TLATSrFDHFjSKpDEuSkPJQxM89fa.jpg?width=200&height=140", alt: "Landscape" },
  text_7: "Capital forms",
  text_8: "Early signals",
  text_9: "2024",
  l: "https://framer-ai.com/academy/lessons/framer-fundamentals-stacks-and-relative-positioning",
  l_2: "Flexible layouts",
  text_10: "Build responsive layouts with auto-layout stacks and fully customizable grids. Everything snaps, scales, and responds exactly how you’d expect it to.",
  branches: "Branches",
  input: "Search…",
  dropdown: "All",
  main: "main",
  main_2: "1m",
  branch: { src: "/images/8d225e32-PNKbO6dGnRRwEvctPlhddS3H2s20cf.png?width=512&height=512", alt: "Framer user avatar" },
  branch_2: "home-2026",
  branch_3: "3m",
  branch_4: { src: "/images/96913bcf-OmKDjH7juzfJ8ETRwLy9hglwa0f73b.png?width=192&height=192", alt: "Framer user avatar" },
  branch_5: "use-cases",
  subBranch: { src: "/images/8d225e32-PNKbO6dGnRRwEvctPlhddS3H2s20cf.png?width=512&height=512", alt: "Framer user avatar" },
  subBranch_2: "publishing",
  subBranch_3: "8m",
  subBranch_4: { src: "/images/1ea3b48d-kFiEvDg0LczTmqWVkfNUFTc5020cf.png?width=512&height=512", alt: "Framer user avatar" },
  subBranch_5: "content",
  subBranch_6: "10m",
  changes: "Changes",
  change: "Home",
  change_2: { src: "/images/96913bcf-OmKDjH7juzfJ8ETRwLy9hglwa0f73b.png?width=192&height=192", alt: "Framer user avatar" },
  change_3: "/pricing",
  change_4: { src: "/images/96913bcf-OmKDjH7juzfJ8ETRwLy9hglwa0f73b.png?width=192&height=192", alt: "Framer user avatar" },
  change_5: "Updates",
  change_6: { src: "/images/9df3bd04-56Di5cRNO9igcAj63PSR0NxPQ12f3.png?width=400&height=400", alt: "Framer user avatar" },
  change_7: { src: "/images/1ea3b48d-kFiEvDg0LczTmqWVkfNUFTc5020cf.png?width=512&height=512", alt: "Framer user avatar" },
  cmsChange: "Shaders",
  cmsChange_2: { src: "/images/9df3bd04-56Di5cRNO9igcAj63PSR0NxPQ12f3.png?width=400&height=400", alt: "Framer user avatar" },
  cmsChange_3: "Vectors",
  cmsChange_4: { src: "/images/1ea3b48d-kFiEvDg0LczTmqWVkfNUFTc5020cf.png?width=512&height=512", alt: "Framer user avatar" },
  button: "Merge",
  button_2: "to main",
  l_3: "/collaborate",
  l_4: "Design together, ship together",
  text_11: "Invite teammates, leave comments, and design together in real time. Branch off to explore ideas without touching the main project, then merge when it’s ready to ship.",
  topBar: "Parallel®",
  variant1: "Product",
  variant1_2: "Support",
  variant1_3: "Get access",
  variant1_4: "Login",
  image3: { src: "../../framerusercontent.com/images/UBF85ytILrra5y9lutZNqB9ZveQ90ee.png?width=1024&height=1024", alt: "Menu preview image" },
  button_3: "How it works",
  borderTop: "Menu",
  l_5: "https://framer-ai.com/academy/lessons/framer-fundamentals-components",
  l_6: "Reusable, interactive components",
  text_12: "Build components by hand or with the agent. Add variants, interactions, and properties so every instance works exactly as intended.",
  newAppIcon: { src: "../../framerusercontent.com/images/RzcbNfzZxCBy0B6rQgkGlnatLcf4d4.png?lossless=1&width=1648&height=1648", alt: "Framer app icon" },
  l_7: "https://framer-ai.com/downloads",
  l_8: "Desktop app",
  text_13: "Export images and SVGs directly from the canvas. A native Mac and Windows app built for speed and serious design work.",
};
