// content for the "Bento" section — extracted by extract-site.
// Edit values here to re-skin the "Bento" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "Details worth obsessing over",
  shader: { src: "/images/bae7d0dd-OXB354fGrbZRkiAZgdw7el4TQQ.avif?width=360&height=360", alt: "" },
  bentoCard: "Shaders.",
  bentoCard_2: "Drop in gradients, glass, and particles for a premium feel.",
  orbit: { src: "/images/e038a5c5-YvR6U1LEyYYOjsZ0U06QqY0Gfr8e41a.png?width=180&height=180", alt: "" },
  orbit_2: { src: "/images/450fc117-zgFdDM3StVlFLfjBawlbGqOSNAoe41a.png?width=180&height=180", alt: "" },
  orbit_3: { src: "/images/16f55c87-GRiwGanr0DJZf6JVMJpJnQsGAxQe41a.png?width=180&height=180", alt: "" },
  orbit_4: { src: "/images/fffb0aa1-40tihnbKPuOt1goBg6bcM4Hbt8e41a.png?width=180&height=180", alt: "" },
  orbit_5: { src: "/images/a32e9dfc-dE6UyNuNxmItKjfqFf4OP83WMAe41a.png?width=180&height=180", alt: "" },
  orbit_6: { src: "/images/24731825-OP6EFgZ3WSYQC1A7fcrqLYBA60e41a.png?width=180&height=180", alt: "" },
  title: "Loop Effect",
  label: "Type",
  show: "Loop",
  hide: "Mirror",
  radiusTitle: "Delay",
  controlValue: "0",
  controlLabel: "S",
  label_2: "Opacity",
  controlValue_2: "1",
  controlLabel_2: "S",
  label_3: "Scale",
  controlValue_3: "1",
  controlLabel_3: "S",
  label_4: "Rotate",
  controlValue_4: "360",
  show_2: "2D",
  hide_2: "3D",
  label_5: "Skew",
  controlValue_5: "0°",
  controlLabel_4: "X",
  controlValue_6: "0°",
  controlLabel_5: "Y",
  label_6: "Offset",
  controlValue_7: "0°",
  controlLabel_6: "X",
  controlValue_8: "0°",
  controlLabel_7: "Y",
  label_7: "Off Screen",
  hide_3: "Play",
  show_3: "Pause",
  borderTitle: "Transition",
  controlValue_9: "Linear",
  bentoCard_3: "Animations.",
  bentoCard_4: "Best-in-class web animations that are easy to set up and performant out of the box.",
  artDirection: "Growth",
  artDirection_2: "Savings",
  artDirection_3: "Balance",
  artDirection_4: "Future",
  image4: { src: "/images/0741bf0e-jK21Sjy9P1p1iFp5wcRYYbz9Vg.avif?width=1024&height=1024", alt: "a red disk drive sitting on top of a rock" },
  image4_2: { src: "/images/35467ab8-s6n79wGDtW1MrJPEz2fipom3n4E.avif?width=2688&height=1792", alt: "Interaction gallery image" },
  bentoCard_5: "Interactions.",
  bentoCard_6: "Clicks, hovers, and taps that make your site respond.",
  title_2: "Variable",
  label_8: "Weight",
  numberControl: "900",
  numberControl_2: "300",
  label_9: "Italic",
  numberControl_3: "0",
  numberControl_4: "20",
  weight: "Variable",
  bentoCard_7: "Variable fonts.",
  bentoCard_8: "Dial in weight, width, and optical size with total precision.",
  titile: "OpenType",
  opentype: "H₂O",
  siblingFrame1Title: "Search…",
  titile_2: "Stylistic Sets",
  radiusTitle_2: "Stylistic Set 1",
  hide_4: "Yes",
  show_4: "No",
  radiusTitle_3: "Stylistic Set 2",
  hide_5: "Yes",
  show_5: "No",
  titile_3: "Character Variants",
  overflowTitle: "Alternates",
  hide_6: "Yes",
  show_6: "No",
  overflowTitle_2: "Inferiors",
  show_7: "Yes",
  hide_7: "No",
  titile_4: "Ligatures",
  overflowTitle_3: "Standard",
  hide_8: "Yes",
  show_8: "No",
  overflowTitle_4: "Discretionary",
  show_9: "Yes",
  hide_9: "No",
  overflowTitle_5: "Historical",
  hide_10: "Yes",
  show_10: "No",
  titile_5: "Numbers",
  overflowTitle_6: "Tabular",
  hide_11: "Yes",
  show_11: "No",
  overflowTitle_7: "Denominators",
  show_12: "Yes",
  hide_12: "No",
  overflowTitle_8: "Fractions",
  show_13: "Yes",
  hide_13: "No",
  overflowTitle_9: "Proportional",
  show_14: "Yes",
  hide_14: "No",
  overflowTitle_10: "Numerator",
  hide_15: "Yes",
  show_15: "No",
  overflowTitle_11: "Ordinals",
  hide_16: "Yes",
  show_16: "No",
  overflowTitle_12: "Subscript",
  hide_17: "Yes",
  show_17: "No",
  overflowTitle_13: "Superscript",
  hide_18: "Yes",
  show_18: "No",
  bentoCard_9: "OpenType.",
  bentoCard_10: "Unlock ligatures, alternates, and more from any font.",
  header_2: "Apply now",
  fields: "Name",
  fields_2: "Email",
  fields_3: "Location",
  button: "Submit",
  title_3: "Input",
  widthTitle: "Name",
  controlValue_10: "Location",
  radiusTitle_4: "Required",
  show_19: "Yes",
  hide_19: "No",
  widthTitle_2: "Options",
  controlValue_11: "Select…",
  widthTitle_3: "Subject",
  controlValue_12: "Amsterdam",
  widthTitle_4: "Subject",
  controlValue_13: "Barcelona",
  widthTitle_5: "Subject",
  controlValue_14: "Add…",
  bentoCard_11: "Forms.",
  bentoCard_12: "Design text fields, checkboxes, dropdowns, and more. Publish them as fully working forms.",
  title_4: "Mask",
  res: "Resolution",
  dropdown: "Auto",
  type: "Type",
  dropdown_2: "Fill",
  mode: "Mode",
  dropdown_3: "Alpha",
  position: "Position",
  dropdown_4: "Center",
  bentoCard_13: "Layer masks.",
  bentoCard_14: "Clip any element to a custom shape for creative layouts.",
  card: { src: "../../framerusercontent.com/images/GfBFVOtE6JjUhugOkrqy1o2iEGE19d8.png?width=830&height=1200", alt: "Design feature card image" },
  button_2: "Read article",
  bentoCard_15: "Custom cursors.",
  bentoCard_16: "Replace the default cursor with any image or element.",
  header_3: "Framer Icon Set",
  search: "Search…",
  bentoCard_17: "Vector sets",
  bentoCard_18: ". Draw, edit, and manage icons.",
};
