// content for the "Extras NEW" section — extracted by extract-site.
// Edit values here to re-skin the "Extras NEW" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "All the tools to make it yours",
  default: "https://framer-ai.com/dictionary/plugins",
  title: "Plugins",
  default_2: "https://framer-ai.com/dictionary/scroll-effects",
  title_2: "Scroll effects",
  default_3: "https://framer-ai.com/dictionary/dark-mode",
  title_3: "Dark mode",
  default_4: "https://framer-ai.com/dictionary/smart-components",
  title_4: "Smart components",
  default_5: "https://framer-ai.com/dictionary/bento-grids",
  title_5: "Bento grids",
  default_6: "https://framer-ai.com/dictionary/blend-modes",
  title_6: "Blend modes",
  default_7: "https://framer-ai.com/dictionary/3d-transforms",
  title_7: "3D transforms",
  default_8: "https://framer-ai.com/dictionary/background-blur",
  title_8: "Background blur",
  default_9: "https://framer-ai.com/dictionary/overlays",
  title_9: "Overlays",
  default_10: "https://framer-ai.com/dictionary/masonry-layouts",
  title_10: "Masonry layouts",
  default_11: "https://framer-ai.com/dictionary/filters",
  title_11: "Filters",
  default_12: "https://framer-ai.com/dictionary/vector-drawing",
  title_12: "Vector drawing",
  default_13: "https://framer-ai.com/dictionary/radial-gradients",
  title_13: "Radial gradients",
  default_14: "https://framer-ai.com/dictionary/auto-sizing",
  title_14: "Auto sizing",
  default_15: "https://framer-ai.com/dictionary/sticky-positioning",
  title_15: "Sticky positioning",
  default_16: "https://framer-ai.com/dictionary/tickers",
  title_16: "Tickers",
  default_17: "https://framer-ai.com/dictionary/p3-colors",
  title_17: "P3 colors",
  default_18: "https://framer-ai.com/dictionary/export-layers",
  title_18: "Export layers",
  default_19: "https://framer-ai.com/dictionary/comments",
  title_19: "Comments",
  default_20: "https://framer-ai.com/dictionary/flow-effect",
  title_20: "Flow effect",
  default_21: "https://framer-ai.com/dictionary/text-decoration",
  title_21: "Text decoration",
  default_22: "https://framer-ai.com/dictionary/text-balance",
  title_22: "Text balance",
  default_23: "https://framer-ai.com/dictionary/selection-color",
  title_23: "Selection color",
  default_24: "https://framer-ai.com/dictionary/squircle-corners",
  title_24: "Squircle corners",
  default_25: "https://framer-ai.com/dictionary/layout-templates",
  title_25: "Layout templates",
  default_26: "https://framer-ai.com/dictionary/link-styles",
  title_26: "Link styles",
  default_27: "https://framer-ai.com/dictionary/truncation",
  title_27: "Truncation",
  default_28: "https://framer-ai.com/dictionary/custom-cursor",
  title_28: "Custom cursor",
  default_29: "https://framer-ai.com/dictionary/masks",
  title_29: "Masks",
  default_30: "https://framer-ai.com/dictionary/svg-animations",
  title_30: "SVG animations",
};
