// content for the "Header" section — extracted by extract-site.
// Edit values here to re-skin the "Header" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  content: "AI website builder for designers and teams",
  regular: "https://framer-ai.com/r/signup",
  label: "Get started for free",
  regular_2: "https://updates.framer.com/electron/darwin/arm64/Framer.zip?_ga=2.113395847.1447313862.1646043056-273660571.1642151053",
  label_2: "Download app",
  m: "https://framer-ai.com/academy/lessons/framer-agents-generation-layout-style",
  m_2: "Watch demo",
  canvas: "Canvas",
  default: "Site",
  default_2: "·",
  off: "main",
  number: "12",
  team: { src: "/images/67795d4b-UnfUTFiycUvyLiWVaZSTQX3S7kA73f7.png?width=335&height=335", alt: "Interface preview in 2026 UI/Canvas UI/App UI Top Bar." },
  team_2: { src: "/images/02612926-23W7URwXzeyNBGr6KAR1Ovou6V44395.png?width=475&height=475", alt: "Interface preview in 2026 UI/Canvas UI/App UI Top Bar." },
  team_3: { src: "/images/9081ee25-HpuIynUBjhAJSaXjaIesR9XZ7fMdb13.png?scale-down-to=512&width=2160&height=2160", alt: "Interface preview in 2026 UI/Canvas UI/App UI Top Bar." },
  invite: "Invite",
  publish: "Publish",
  on: "Pages",
  off_2: "Layers",
  off_3: "Assets",
  input: "Search…",
  pageHeader: "Pages",
  activePage: "Home",
  page: "/research",
  subPage: "Research Pages",
  page_2: "/commitments",
  page_3: "/learn",
  page_4: "/support",
  page_5: "/news",
  page_6: "/legal",
  subPage_2: "/privacy",
  subPage_3: "/terms",
  page_7: "/try-bloom",
  subPage_4: "News Pages",
  zoom: "100%",
  off_4: "Desktop",
  off_5: "1200",
  default_3: { src: "../../framerusercontent.com/images/ECdEQNeQvqfbO5UXVML2syuogw50d5.jpg?width=2400&height=200", alt: "Default interface preview in 2026 AI Page/AI Hero Site New." },
  topBottom: { src: "/images/1850628c-79UBm8aYjB7mr4PUg8Fc4q7vsOA.avif?width=2400&height=1980", alt: "Top Bottom interface preview in 2026 AI Page/AI Hero Site New." },
  stickyScroll: { src: "../../framerusercontent.com/images/BAdq5mZDf3ZijxgeLpmux5JThY8ed1.jpg?width=2400&height=2480", alt: "Sticky Scroll interface preview in 2026 AI Page/AI Hero Site New." },
  agent: "Agent",
  style: "Style",
  dropdown: "Vertical Hero Layout",
  chat: "Change the hero to a vertical stack layout, then replace the hero image with the image attached.",
  chat_2: { src: "/images/eb6d2905-RVr1VRko89bsmVp6lwTZ8gmtQeb4e.png?width=160&height=160", alt: "Interface preview in 2026 AI Page/AI Hero Bloom 2026." },
  top: "Thinking...",
  top_2: "Thinking...",
  top_3: "Switching the hero to a vertical stack and swapping the cover image for the new asset you attached.",
  top_4: "Edited 7 layers, removed 2",
  top_5: "9s",
  top_6: "I’m polishing the layout after the swap so the stacked hero stays clean.",
  top_7: "Edited 2 layers",
  top_8: "13s",
  chat_3: "Viewed Home",
  chat_4: "6s",
  bottom: "Edited 7 layers, removed 2",
  bottom_2: "9s",
  bottom_3: "Done! The hero section is now a vertical stack: heading and “Try Bloom” CTA on top, with the new gradient image full-width below.",
  promptInput: "._Rmddmnalra6l5dp_::placeholder { color: var(--token-f5637926-8ee6-41cb-a320-ec3462d62cd5, rgba(255, 255, 255, 0.4)); opacity: 1; }",
  aiModel: "GPT 5.6",
  aiModel_2: "Terra",
  m_3: "/stories",
  m_4: "Meet our customers",
};
