// content for the "Agents" section — extracted by extract-site.
// Edit values here to re-skin the "Agents" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "Create with AI. Stay in control from canvas to publish.",
  agent: "@keyframes ghostFlow { 0%, 18% { opacity: 1; } 35% { opacity: 0.6; } 50%, 100% { opacity: 0.3; } } @keyframes doubleSlow { 0%, 100% { opacity: 0.3; } 8% { opacity: 0.72; } 16%, 24% { opacity: 1; } 34%, 50% { opacity: 0.3; } 58% { opacity: 0.58; } 66%, 74% { opacity: 0.96; } 84% { opacity: 0.48; } } @keyframes danceSpark { 0%, 6% { opacity: 1; } 18% { opacity: 0.45; } 24%, 100% { opacity: 0.3; } }",
  agent_2: "Desktop",
  agent_3: "1200",
  default: { src: "../../framerusercontent.com/images/ECdEQNeQvqfbO5UXVML2syuogw50d5.jpg?width=2400&height=200", alt: "Default interface preview in 2026 AI Page/AI Hero Site New." },
  title2x: { src: "../../framerusercontent.com/images/jEetDbh3tO5NtfY22n0bRc58f407.png?width=1100&height=450", alt: "CMS design interface title preview." },
  buttons2x: { src: "/images/fc1e979d-7dqIDJaeSPY01VrufOCUCpAPyO8a989.png?width=470&height=60", alt: "CMS design interface button controls preview." },
  image2x: { src: "../../framerusercontent.com/images/KttE1cygUBaLx5BkDpHVBa3ch8636f.png?width=1100&height=1680", alt: "CMS design interface image preview." },
  copy: "How Framer’s AI website builder works",
  copy_2: "Describe the website, page, or update you need. Framer’s AI agent creates editable pages, sections, copy, and visuals directly in your project. Keep refining in the conversation, or take over on the canvas at any point.",
  m: "https://framer-ai.com/signup",
  m_2: "Start with Agents",
  end: "Featured models",
  row: { src: "../../framerusercontent.com/images/iePjwFmmdOppWQd5iQSbr8O4UQI81b8.png?width=2560&height=1440", alt: "Landscape" },
  text: "Petal 3.1",
  text_2: "Builds and ships",
  row_2: { src: "../../framerusercontent.com/images/UaPzgqwWZ6DsLMWhA9pkHRKNxq881b8.png?width=2560&height=1440", alt: "Landscape" },
  text_3: "Ember 4.7",
  text_4: "Fast and efficient",
  row_3: { src: "../../framerusercontent.com/images/lk4lwfSeQMCxwTVOCqzwauSVvjQ81b8.png?width=2560&height=1440", alt: "Landscape" },
  text_5: "Horizon 2.1",
  text_6: "For complex work",
  copy_3: "Design responsive websites with AI and full control",
  copy_4: "Start from a prompt and use the Framer canvas to refine layouts, typography, components, breakpoints, spacing, color, and effects. AI helps you move faster while you make the final design decisions.",
  m_3: "https://framer-ai.com/signup",
  m_4: "Start with Agents",
  topbar2: "CMS",
  default_2: "Site",
  default_3: "·",
  off: "main",
  topbar2_2: { src: "/images/1534cc3a-LPkXlDTlZn3Gg3nOt0vzCxLJXU20cf.png?width=512&height=512", alt: "Top bar of the Framer interface." },
  topbar2_3: "Invite",
  topbar2_4: "Publish",
  collectionsPanel: "Collections",
  collectionsPanel_2: "Fields",
  collectionsPanel_3: "Plugins",
  collectionsPanel_4: "Careers",
  collectionsPanel_5: "Documentation",
  collectionsPanel_6: "Articles",
  collectionsPanel_7: "39",
  collectionsPanel_8: "39",
  collectionsPanel_9: "Learn",
  collectionsPanel_10: "Models",
  collectionsPanel_11: "News",
  collectionsPanel_12: "Research",
  collectionsPanel_13: "Add...",
  tableHeader: "Title",
  tableHeader_2: "Image",
  tableHeader_3: "Category",
  tableHeader_4: "Introduction",
  title: "Quickstart guide",
  image: { src: "/images/1b6a117c-zsqM5P2FZlpSrKPtTI3elZzGIe2f6.png?width=274&height=274", alt: "" },
  dark: "Guide",
  bio: "In this",
  title_2: "Choosing a model",
  image_2: { src: "/images/c5d4facf-xDolHZqXBny6HVIMD2RQjdmUncQe2f6.png?width=274&height=274", alt: "" },
  dark_2: "Tutorial",
  bio_2: "Motion",
  title_3: "Data and privacy",
  image_3: { src: "/images/874ebad4-ozATLH77aKD4KiiMbGSGC1XMuoe2f6.png?width=274&height=274", alt: "" },
  dark_3: "Systems",
  bio_3: "In this",
  title_4: "Cost optimization",
  image_4: { src: "/images/d3b95d49-EYfdP3twHu23fmpyPO73N5arhU5be1.png?width=200&height=200", alt: "" },
  dark_4: "Tips",
  bio_4: "We",
  title_5: "Connect your data",
  image_5: { src: "/images/f2dbbedc-vqKg4XbGBo8LM2m5n7kxcpEaSc5be1.png?width=200&height=200", alt: "" },
  dark_5: "Tutorial",
  bio_5: "Testing",
  title_6: "Tokens explained",
  image_6: { src: "/images/26ea9e7a-xuf7SYSNikhzXM25UOeS54zPcFQ5be1.png?width=200&height=200", alt: "" },
  dark_6: "Guide",
  bio_6: "In this",
  sidebar: { src: "../../framerusercontent.com/images/8rpKpXq0OyDdFohd7e3NCN8oQDs6407.png?width=520&height=1400", alt: "Sidebar of the Framer CMS editor interface." },
  header_2: { src: "../../framerusercontent.com/images/R2z0U8jUYeP0JRpapIeGR1mGKdA3e2d.png?width=2760&height=150", alt: "Header area of the Framer CMS editor interface." },
  searchRow: { src: "../../framerusercontent.com/images/jYDmxYKBes4MJG04lZ1OFXEBc83e2d.png?width=2760&height=150", alt: "Search row in the Framer CMS interface." },
  cmsItem1: { src: "../../framerusercontent.com/images/kqnlrwFlDazht592YihJC3J0K00f15.png?width=2670&height=150", alt: "CMS Item 1 in the Framer CMS content list." },
  cmsItem2: { src: "../../framerusercontent.com/images/1XXeRAVlMnRbQ1WWneq1d9Nl5lQ0f15.png?width=2670&height=150", alt: "CMS Item 2 in the Framer CMS content list." },
  cmsItem3: { src: "../../framerusercontent.com/images/sK1zK3HACiMnQYVCxeZrOZskuY0f15.png?width=2670&height=150", alt: "CMS Item 3 in the Framer CMS content list." },
  cmsItem4: { src: "../../framerusercontent.com/images/v9pwGgBVZkUx2owTzQRkVHmtZdM0f15.png?width=2670&height=150", alt: "CMS Item 4 in the Framer CMS content list." },
  cmsItem5: { src: "../../framerusercontent.com/images/imtvP46cYCj0aPxb5qXA0GWKeHs0f15.png?width=2670&height=150", alt: "CMS Item 5 in the Framer CMS content list." },
  cmsItem6: { src: "../../framerusercontent.com/images/sku8XSsM7FaTRvUjyXn0bl7FxRM0f15.png?width=2670&height=150", alt: "CMS Item 6 in the Framer CMS content list." },
  cmsItem7: { src: "../../framerusercontent.com/images/DpJGCRixy5rN6iW9UL3GdMwWuY0f15.png?width=2670&height=150", alt: "CMS Item 7 in the Framer CMS content list." },
  cmsItem8: { src: "../../framerusercontent.com/images/kHLjCnG1LcrqAcRDmY9L7O8WQhQ0f15.png?width=2670&height=150", alt: "CMS Item 8 in the Framer CMS content list." },
  cmsItem9: { src: "../../framerusercontent.com/images/YdiKOgEO0YR0SpypfJJ5bZIeIHY0f15.png?width=2670&height=150", alt: "CMS Item 9 in the Framer CMS content list." },
  cmsItem10: { src: "../../framerusercontent.com/images/6eQfOdmS9duVZhhQ1GV5bWSEY0f15.png?width=2670&height=150", alt: "CMS Item 10 in the Framer CMS content list." },
  copy_5: "Manage website content with AI agents",
  copy_6: "Create collections, populate CMS content, and keep your site organized. Framer’s AI agent works directly with your CMS and canvas, so content, design, and publishing workflows stay connected.",
  m_5: "https://framer-ai.com/signup",
  m_6: "Start with Agents",
  desktop: "ImageSlider",
  desktop_2: { src: "../../framerusercontent.com/images/ZT5acGDfTQ2RTjBzzRGbObBu1wbc73.jpg?width=2400&height=1792", alt: "After image" },
  desktop_3: { src: "../../framerusercontent.com/images/ZJZ48houolIMxnjsfsznqCSg7782.jpg?width=2896&height=2168", alt: "Before image" },
  copy_7: "Build custom code with an AI agent",
  copy_8: "Describe the interaction or live feature you need, and the AI agent can build a code component for your site. Review the result, refine it in Framer, and keep it connected to your design system.",
  m_7: "https://framer-ai.com/signup",
  m_8: "Start with Agents",
  agent_4: "@keyframes ghostFlow { 0%, 18% { opacity: 1; } 35% { opacity: 0.6; } 50%, 100% { opacity: 0.3; } } @keyframes doubleSlow { 0%, 100% { opacity: 0.3; } 8% { opacity: 0.72; } 16%, 24% { opacity: 1; } 34%, 50% { opacity: 0.3; } 58% { opacity: 0.58; } 66%, 74% { opacity: 0.96; } 84% { opacity: 0.48; } } @keyframes danceSpark { 0%, 6% { opacity: 1; } 18% { opacity: 0.45; } 24%, 100% { opacity: 0.3; } }",
  agent_5: "Desktop",
  agent_6: "1200",
  variant1: "News",
  variant1_2: "/",
  variant1_3: "Announcement",
  variant1_4: "Introducing Bloom Horizon 2.1",
  aiSpellCheck: "Bloom Horizon 2.1 is here. Our latest",
  aiSpellCheck_2: "forcasting",
  aiSpellCheck_3: "model helps teams",
  aiSpellCheck_4: "antitcipate",
  aiSpellCheck_5: "risks across public health, education, and support, so decisions come earlier and with more",
  aiSpellCheck_6: "confidance",
  aiSpellCheck_7: ".",
  variant1_5: "Olivia Lindqvist",
  variant1_6: "•",
  variant1_7: "Research Lead",
  bgImage: { src: "../../framerusercontent.com/images/lk4lwfSeQMCxwTVOCqzwauSVvjQ81b8.png?width=2560&height=1440", alt: "Framer canvas preview used behind the AI review interface." },
  navigation: "Bloom®",
  links: "Research",
  links_2: "Commitments",
  links_3: "Learn",
  links_4: "News",
  links_5: "Try Bloom ↗",
  copy_9: "Review and improve your website with AI",
  copy_10: "Ask the AI agent to review your site before publishing. It can identify contrast issues, typos, missing alt text, SEO gaps, and inconsistent styles, then help you fix them in the same project.",
  m_9: "https://framer-ai.com/signup",
  m_10: "Start with Agents",
  agent_7: "@keyframes ghostFlow { 0%, 18% { opacity: 1; } 35% { opacity: 0.6; } 50%, 100% { opacity: 0.3; } } @keyframes doubleSlow { 0%, 100% { opacity: 0.3; } 8% { opacity: 0.72; } 16%, 24% { opacity: 1; } 34%, 50% { opacity: 0.3; } 58% { opacity: 0.58; } 66%, 74% { opacity: 0.96; } 84% { opacity: 0.48; } } @keyframes danceSpark { 0%, 6% { opacity: 1; } 18% { opacity: 0.45; } 24%, 100% { opacity: 0.3; } }",
  agent_8: "Desktop",
  agent_9: "1200",
  navigation_2: "Bloom®",
  links_6: "Research",
  links_7: "Commitments",
  links_8: "Learn",
  links_9: "News",
  links_10: "Try Bloom ↗",
  site: "Simple pricing based on your needs",
  site_2: "Monthly",
  site_3: "Yearly",
  site_4: "Starter",
  site_5: "$29",
  site_6: "/month",
  site_7: "For solo builders getting started",
  site_8: "Professional",
  site_9: "$49",
  site_10: "/month",
  site_11: "For growing teams that ship fast",
  site_12: "Enterprise",
  site_13: "$119",
  site_14: "/month",
  site_15: "For organizations running analysis at scale",
  copy_11: "Use AI analytics to improve your website",
  copy_12: "Ask the AI agent to analyze traffic and turn it into practical next steps. Review top pages, drop-offs, search intent, and conversion gaps, then refine the site directly in Framer.",
  m_11: "https://framer-ai.com/signup",
  m_12: "Start with Agents",
  promptInput: "._R5jbelraal5dp_::placeholder { color: var(--token-f5637926-8ee6-41cb-a320-ec3462d62cd5, rgba(255, 255, 255, 0.4)); opacity: 1; }",
  aiModel: "GPT 5.6",
  aiModel_2: "Terra",
  top: "Generate a homepage",
  fpAgentsChatBox: "for Bloom, an AI research organization for human wellbeing. Make it minimalistic and dark, with releases, research themes, public trust, and CTAs.",
  thinking: "Thinking...",
  thinking_2: "Thinking...",
  designPlan: "Created a design plan",
  designPlan_2: "2s",
  fpAgentsChatResponse: "Dark minimal opening with Bloom identity, research statement, CTAs, and trust signals.",
  fpAgentsChatResponse_2: "Releases section with publication style cards.",
  fpAgentsChatResponse_3: "Research themes and public trust sections.",
  fpAgentsChatResponse_4: "Closing CTA and homepage metadata.",
  fpAgentsChatResponse_5: "Created the Bloom homepage on",
  fpAgentsChatResponse_6: "Home",
  fpAgentsChatResponse_7: ".",
  fpAgentsChatResponse_8: "Would you like me to add tablet and phone breakpoints next?",
};
