// content for the "Features" section — extracted by extract-site.
// Edit values here to re-skin the "Features" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "All the control you need, right where you work",
  skills: "Skills",
  skills_2: "/cms",
  skills_3: "Write content",
  skills_4: "/component",
  skills_5: "With variants",
  skills_6: "/code",
  skills_7: "Custom component",
  modal: "GPT 5.6 Terra",
  bentoCard: "Skills",
  bentoCard_2: ". Type",
  bentoCard_3: "/",
  bentoCard_4: "to run AI actions for layouts, CMS, and more.",
  variant7: "Agents",
  modal_2: "Agents",
  modal_3: "Sonnet 4.6",
  modal_4: "Agents",
  modal_5: "GPT 5.6 Terra",
  bentoCard_5: "Contexts.",
  bentoCard_6: "Select layers on the canvas and add them as context to your chat.",
  chats2x: { src: "../../framerusercontent.com/images/YGpNqiZeTDm3mR5Wu4EXIyB9dg8161.png?width=674&height=714", alt: "Chat interface for working with AI agents in Framer." },
  bentoCard_7: "Chats",
  bentoCard_8: ".",
  bentoCard_9: "Start a new one for each task to keep the agent focused.",
  models2x: { src: "../../framerusercontent.com/images/PUqtETbbS09YldTynzBona6Hrg8161.png?width=674&height=714", alt: "Model picker interface for choosing an AI model in Framer." },
  bentoCard_10: "Models.",
  bentoCard_11: "Choose GPT, Sonnet, Opus, or Fable depending on the task.",
  skills_8: "Skills",
  skills_9: "/cms",
  skills_10: "Write content",
  skills_11: "/component",
  skills_12: "With variants",
  skills_13: "/code",
  skills_14: "Custom component",
  modal_6: "GPT 5.6 Terra",
  bentoCard_12: "Mentions.",
  bentoCard_13: "Type",
  bentoCard_14: "@",
  bentoCard_15: "to reference pages, CMS collections, styles, or assets.",
  text3: "Redesign my footer using these",
  text3_2: "images as a reference.",
  modal_7: { src: "/images/622e1747-bpcTK14Q5FHUeueY7pX2uskOWg.avif?width=411&height=395", alt: "AI file management preview" },
  modal_8: "GPT 5.6 Terra",
  googleSheets2020LogoSvg: { src: "/images/ecd0e572-0MKr6LOGY3ELX5n4AOEiBFsAheM9eb2.png?lossless=1&width=298&height=368", alt: "Google Sheets file icon" },
  paragraph1: "blog",
  text1: ".csv",
  googleSheets2020LogoSvg_2: { src: "/images/dc41410a-xQAugbEjOsz03Dfywue7L0EwDJM0d5d.png?width=196&height=270", alt: "Google Sheets file icon" },
  paragraph2: "DESIGN",
  text2: ".md",
  image1: { src: "/images/727bc80f-SEiY1UIr27Zx5IOtiQceucHmgWQ231a.png?width=100&height=100", alt: "AI file management preview" },
  paragraph3: "shader",
  text3_3: ".mp4",
  googleSheets2020LogoSvg_3: { src: "/images/7c952a98-HqhpYalvutcc7AdEFGtQGexFwM0d5d.png?width=196&height=270", alt: "Google Sheets file icon" },
  text4: "data",
  paragraph4: ".json",
  googleSheets2020LogoSvg_4: { src: "/images/df4a3b3a-roMzqQzv6zt82Nf6hwVhNYFdCY62a7.png?lossless=1&width=196&height=270", alt: "Google Sheets file icon" },
  paragraph5: "component",
  text5: ".tsx",
  image2: { src: "/images/826be7ba-bpcTK14Q5FHUeueY7pX2uskOWgdaaf.png?width=411&height=395", alt: "AI file management preview" },
  paragraph6: "screenshot",
  text6: ".png",
  googleSheets2020LogoSvg_5: { src: "/images/ecd0e572-0MKr6LOGY3ELX5n4AOEiBFsAheM9eb2.png?lossless=1&width=298&height=368", alt: "Google Sheets file icon" },
  paragraph7: "blog",
  text7: ".csv",
  googleSheets2020LogoSvg_6: { src: "/images/dc41410a-xQAugbEjOsz03Dfywue7L0EwDJM0d5d.png?width=196&height=270", alt: "Google Sheets file icon" },
  paragraph8: "DESIGN",
  text8: ".md",
  image3: { src: "/images/3e1ec715-8g3xxGt9M0DZ1pjRquaYUjsLWM5be1.jpg?width=200&height=200", alt: "AI file management preview" },
  paragraph9: "shader",
  text9: ".mp4",
  googleSheets2020LogoSvg_7: { src: "/images/7c952a98-HqhpYalvutcc7AdEFGtQGexFwM0d5d.png?width=196&height=270", alt: "Google Sheets file icon" },
  text10: "data",
  paragraph10: ".json",
  googleSheets2020LogoSvg_8: { src: "/images/df4a3b3a-roMzqQzv6zt82Nf6hwVhNYFdCY62a7.png?lossless=1&width=196&height=270", alt: "Google Sheets file icon" },
  paragraph11: "component",
  text11: ".tsx",
  image4: { src: "/images/826be7ba-bpcTK14Q5FHUeueY7pX2uskOWgdaaf.png?width=411&height=395", alt: "AI file management preview" },
  paragraph12: "screenshot",
  text12: ".png",
  googleSheets2020LogoSvg_9: { src: "/images/ecd0e572-0MKr6LOGY3ELX5n4AOEiBFsAheM9eb2.png?lossless=1&width=298&height=368", alt: "Google Sheets file icon" },
  paragraph13: "blog",
  text13: ".csv",
  bentoCard_16: "References",
  bentoCard_17: ". Upload images, files, or URLs to guide AI toward the exact result you want.",
  branches2x: { src: "../../framerusercontent.com/images/gPeqXdDVQp7LZxK4KIzdNp0CkNM38dc.png?width=672&height=714", alt: "Branches panel showing agent changes ready for review." },
  bentoCard_18: "/collaborate",
  bentoCard_19: "Branches",
  bentoCard_20: ".",
  bentoCard_21: "Iterate safely by moving AI agent edits to a branch.",
};
