// Header.tsx — section converted to a real JSX component by extract-site.
// Editable React: entrance animations are inline framer-motion props with the
// MEASURED timing from the original site; hover effects live in hover.css.
// Copy, photos, and links live in the sibling content module — edit there to
// re-skin this section without touching layout/motion.
import type { CSSProperties } from "react";
import { motion } from "framer-motion";
import content from "../content/02-Header";

export function Header() {
  return (
    <header className="framer-1a4c4cp" data-framer-name="Header" style={{ width: "1440px", height: "1550.7px", padding: "100px 0px 80px", position: "relative", zIndex: "2", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "60px", backgroundColor: "rgb(0, 0, 0)" } as CSSProperties}>
      <div className="framer-voj2po" style={{ width: "1440px", height: "167px", padding: "0px 20px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", overflow: "clip" } as CSSProperties}>
        <div className="framer-z1pscj" data-framer-name="Text" style={{ width: "1200px", height: "167px", maxWidth: "1200px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", gap: "25px" } as CSSProperties}>
          <div className="framer-1o2fkwe" data-framer-component-type="RichTextContainer" style={{ width: "740px", height: "108px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", transform: "none" } as CSSProperties}>
            <h1 className="framer-text framer-styles-preset-1gzpg4m" data-styles-preset="gM4yNG9Qq" dir="auto" style={{ width: "740px", height: "108px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"GT Walsheim Medium\", \"GT Walsheim Medium Placeholder\", sans-serif", fontSize: "54px", fontWeight: "500", lineHeight: "54px", letterSpacing: "-2.16px", textAlign: "left", color: "rgb(255, 255, 255)", "--framer-text-alignment": "left" } as CSSProperties}>
              {content.text}
            </h1>
          </div>
          <div className="framer-1ezb6me" data-framer-name="CTA" style={{ width: "149.25px", height: "34px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "10px" } as CSSProperties}>
            <div className="framer-16bu9g1-container" style={{ width: "149.25px", height: "34px", position: "relative", zIndex: "1", display: "block", flexDirection: "row" } as CSSProperties}>
              <a className="framer-k8Dz4 framer-qkzqfa framer-v-qkzqfa framer-lt5xhr hv-98" data-framer-name="Regular" data-highlight="true" data-reset="button" tabIndex={0} style={{ width: "149.25px", height: "34px", maxHeight: "35px", padding: "10px 14px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "7px", backgroundColor: "rgb(255, 255, 255)", borderRadius: "8px", color: "rgb(0, 0, 238)", borderBottomLeftRadius: "8px", borderBottomRightRadius: "8px", borderTopLeftRadius: "8px", borderTopRightRadius: "8px", boxShadow: "var(--9xgf7k)", opacity: "1" } as CSSProperties} data-external-route="1" href={content.regular}>
                <div className="framer-o5mers" data-framer-name="Label" data-framer-component-type="RichTextContainer" style={{ width: "121.25px", height: "14px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 18, \"wght\" 540", "--extracted-r6o4lv": "var(--variable-reference-xdxfhd9wh-KsxdqjKwX)", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", "--variable-reference-rm8thjdvn-ksxdqjkwx": "14", "--variable-reference-xdxfhd9wh-ksxdqjkwx": "rgb(0, 0, 0)", opacity: "1", transform: "none" } as CSSProperties}>
                  <p dir="auto" className="framer-text" style={{ width: "121.25px", height: "14px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "14px", lineHeight: "14px", letterSpacing: "-0.28px", textAlign: "center", color: "rgb(0, 0, 0)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTRMQ0FpZDJkb2RDSWdOVFF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on", "--framer-font-size": "calc(var(--variable-reference-rm8ThjdVN-KsxdqjKwX) * 1px)", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 18, \"wght\" 540)", "--framer-letter-spacing": "-0.02em", "--framer-line-height": "1em", "--framer-text-alignment": "center", "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-xdxfhd9wh-KsxdqjKwX))" } as CSSProperties}>
                    {content.label}
                  </p>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div className="framer-exwb0f" style={{ width: "1440px", height: "1143.7px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "30px", overflow: "clip" } as CSSProperties}>
        <div className="framer-f9ve9f" data-framer-name="Grid" style={{ width: "1440px", height: "910px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", overflow: "clip" } as CSSProperties}>
          <div className="ssr-variant hidden-ju81s0" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
            <div className="framer-1tpdrg2-container" data-framer-name="Solutions Gallery Designers" style={{ width: "1440px", height: "910px", position: "relative", display: "block", flexDirection: "row" } as CSSProperties}>
              <div className="ssr-variant hidden-1uuy1mt" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
                <section className="framer-JAXAj framer-e6nlaa framer-v-e6nlaa" data-framer-name="Desktop" style={{ width: "100%", height: "910px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "40px", opacity: "1" } as CSSProperties}>
                  <div className="framer-e5d0wa" data-framer-name="Sites" style={{ width: "1440px", height: "910px", position: "relative", zIndex: "1", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", overflow: "clip", opacity: "1" } as CSSProperties}>
                    <div className="framer-cuxnso" data-framer-name="Ticker Left" style={{ width: "1440px", height: "450px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "10px", overflow: "clip", overflowX: "clip", borderRadius: "0px", opacity: "1" } as CSSProperties}>
                      <motion.ul style={{ width: "100%", height: "100%", maxWidth: "100%", maxHeight: "100%", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", gap: "10px", transform: "translateX(-468.301px)", transformOrigin: "720px 225px", listStyleType: "none", padding: "0px", margin: "0px", opacity: "1", willChange: "transform" } as CSSProperties} initial={{ opacity: 0, x: -10 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                        <li className="ticker-item" aria-hidden="false" aria-posinset={1} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                          <div className="framer-5ru16e" data-border="true" data-framer-name="Example" style={{ width: "720px", height: "450px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "1.6 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                            <div className="framer-1192llx" style={{ width: "720px", height: "450px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                              <div style={{ width: "720px", height: "450px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                                <img decoding="auto" width="2750" height="1718" sizes="(min-width: 1200px) 720px, (min-width: 810px) and (max-width: 1199.98px) 530px, (max-width: 809.98px) 360px" srcSet={"/images/4e9c6729-3hhHzx5C3vi8lG45rSu6hcXwA.avif?scale-down-to=512&width=2750&height=1718 512w,/images/4e9c6729-3hhHzx5C3vi8lG45rSu6hcXwA.avif?scale-down-to=1024&width=2750&height=1718 1024w,/images/4e9c6729-3hhHzx5C3vi8lG45rSu6hcXwA.avif?scale-down-to=2048&width=2750&height=1718 2048w,/images/4e9c6729-3hhHzx5C3vi8lG45rSu6hcXwA.avif?width=2750&height=1718 2750w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2750 / 1718", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.example.src} alt={content.example.alt} />
                              </div>
                            </div>
                          </div>
                        </li>
                        <li className="ticker-item" aria-hidden="false" aria-posinset={2} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                          <div className="framer-1oy8si1-container" style={{ width: "250px", height: "450px", position: "relative", display: "block", flexDirection: "row", aspectRatio: "0.555556 / 1", opacity: "1" } as CSSProperties}>
                            <div className="framer-YbP5S framer-kipbz3 framer-v-1h71p1w" data-border="true" data-framer-name="Play" style={{ width: "100%", height: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                              <div className="framer-iuaieu-container" style={{ width: "250px", height: "450px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                                <video loop preload="auto" poster={"/images/15420f37-S1Yx9W76QrhFD6VJLx6CVhHXsM2aed.png?width=506&height=900"} muted playsInline style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", cursor: "auto", borderRadius: "0px", backgroundColor: "rgba(0, 0, 0, 0)", objectPosition: "50% 50%" } as CSSProperties} src={content.play} />
                              </div>
                            </div>
                          </div>
                        </li>
                        <li className="ticker-item" aria-hidden="false" aria-posinset={3} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                          <div className="framer-17pzg43" data-border="true" data-framer-name="Example" style={{ width: "720px", height: "450px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "1.6 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                            <div className="framer-182t4ic" style={{ width: "720px", height: "450px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                              <div style={{ width: "720px", height: "450px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                                <img decoding="auto" width="2750" height="1718" sizes="(min-width: 1200px) 720px, (min-width: 810px) and (max-width: 1199.98px) 530px, (max-width: 809.98px) 360px" srcSet={"/images/fe8187fd-ALYslhuu5wgytt7ctYvPtAlkinQ.avif?scale-down-to=512&width=2750&height=1718 512w,/images/fe8187fd-ALYslhuu5wgytt7ctYvPtAlkinQ.avif?scale-down-to=1024&width=2750&height=1718 1024w,/images/fe8187fd-ALYslhuu5wgytt7ctYvPtAlkinQ.avif?scale-down-to=2048&width=2750&height=1718 2048w,/images/fe8187fd-ALYslhuu5wgytt7ctYvPtAlkinQ.avif?width=2750&height=1718 2750w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2750 / 1718", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.example_2.src} alt={content.example_2.alt} />
                              </div>
                            </div>
                          </div>
                        </li>
                        <li className="ticker-item" aria-hidden="false" aria-posinset={4} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                          <div className="framer-1s5w8tu-container" style={{ width: "625px", height: "449.992px", position: "relative", display: "block", flexDirection: "row", aspectRatio: "1.38889 / 1", opacity: "1" } as CSSProperties}>
                            <div className="framer-YbP5S framer-kipbz3 framer-v-1h71p1w" data-border="true" data-framer-name="Play" style={{ width: "100%", height: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                              <div className="framer-iuaieu-container" style={{ width: "625px", height: "449.992px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                                <video loop preload="auto" poster={"/images/60555e45-s3NFmI62MIkWUnGOfSgS6I74iIfe33.png?width=1022&height=720"} muted playsInline style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", cursor: "auto", borderRadius: "0px", backgroundColor: "rgba(0, 0, 0, 0)", objectPosition: "50% 50%" } as CSSProperties} src={content.play_2} />
                              </div>
                            </div>
                          </div>
                        </li>
                        <li className="ticker-item" aria-hidden="false" aria-posinset={5} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                          <div className="framer-na7p6d" data-border="true" data-framer-name="Example" style={{ width: "720px", height: "450px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "1.6 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                            <div className="framer-8i29ty" style={{ width: "720px", height: "450px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                              <div style={{ width: "720px", height: "450px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                                <img decoding="auto" width="2750" height="1718" sizes="(min-width: 1200px) 720px, (min-width: 810px) and (max-width: 1199.98px) 530px, (max-width: 809.98px) 360px" srcSet={"/images/66c35b4a-Mkr68H5LtwvTGOW4VuxDXBw.avif?scale-down-to=512&width=2750&height=1718 512w,/images/66c35b4a-Mkr68H5LtwvTGOW4VuxDXBw.avif?scale-down-to=1024&width=2750&height=1718 1024w,/images/66c35b4a-Mkr68H5LtwvTGOW4VuxDXBw.avif?scale-down-to=2048&width=2750&height=1718 2048w,/images/66c35b4a-Mkr68H5LtwvTGOW4VuxDXBw.avif?width=2750&height=1718 2750w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2750 / 1718", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.example_3.src} alt={content.example_3.alt} />
                              </div>
                            </div>
                          </div>
                        </li>
                      </motion.ul>
                    </div>
                    {" "}
                    <div className="framer-ypm7t8" data-framer-name="Ticker Right" style={{ width: "1440px", height: "450px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "10px", overflow: "clip", overflowX: "clip", borderRadius: "0px", opacity: "1" } as CSSProperties}>
                      <motion.ul style={{ width: "100%", height: "100%", maxWidth: "100%", maxHeight: "100%", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", gap: "10px", transform: "translateX(-2544.37px)", transformOrigin: "720px 225px", listStyleType: "none", padding: "0px", margin: "0px", opacity: "1", willChange: "transform" } as CSSProperties} initial={{ opacity: 0, x: -10 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                        <li className="ticker-item" aria-hidden="false" aria-posinset={1} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", transformOrigin: "125px 225px", flexGrow: "0", flexShrink: "0" } as CSSProperties}>
                          <div className="framer-1mdp1cg-container" style={{ width: "250px", height: "450px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                            <div className="framer-YbP5S framer-kipbz3 framer-v-kipbz3" data-border="true" data-framer-name="Pause" style={{ width: "100%", height: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                              <div className="framer-iuaieu-container" style={{ width: "250px", height: "450px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                                <video loop preload="metadata" poster={"/images/28a71090-MTNWLPyxhVqHufypxWWfDiX884Qe316.png?width=720&height=1280"} muted playsInline style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", cursor: "auto", borderRadius: "0px", backgroundColor: "rgba(0, 0, 0, 0)", objectPosition: "50% 50%" } as CSSProperties} src={content.pause} />
                              </div>
                            </div>
                          </div>
                        </li>
                        <li className="ticker-item" aria-hidden="false" aria-posinset={2} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", transformOrigin: "360px 225px", flexGrow: "0", flexShrink: "0" } as CSSProperties}>
                          <div className="framer-s98dis" data-border="true" data-framer-name="Example" style={{ width: "720px", height: "450px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "1.6 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                            <div className="framer-en7nzh" style={{ width: "720px", height: "450px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                              <div style={{ width: "720px", height: "450px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                                <img decoding="auto" width="2750" height="1718" sizes="(min-width: 1200px) 720px, (min-width: 810px) and (max-width: 1199.98px) 530px, (max-width: 809.98px) 360px" srcSet={"/images/a393fb0c-um6xOghEDN9ZQxpO2aBBpiPkcV8.avif?scale-down-to=512&width=2750&height=1718 512w,/images/a393fb0c-um6xOghEDN9ZQxpO2aBBpiPkcV8.avif?scale-down-to=1024&width=2750&height=1718 1024w,/images/a393fb0c-um6xOghEDN9ZQxpO2aBBpiPkcV8.avif?scale-down-to=2048&width=2750&height=1718 2048w,/images/a393fb0c-um6xOghEDN9ZQxpO2aBBpiPkcV8.avif?width=2750&height=1718 2750w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2750 / 1718", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.example_4.src} alt={content.example_4.alt} />
                              </div>
                            </div>
                          </div>
                        </li>
                        <li className="ticker-item" aria-hidden="false" aria-posinset={3} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", transformOrigin: "360px 225px", flexGrow: "0", flexShrink: "0" } as CSSProperties}>
                          <div className="framer-g2er8i" data-border="true" data-framer-name="Example" style={{ width: "720px", height: "450px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "1.6 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                            <div className="framer-1fzj3jl" style={{ width: "720px", height: "450px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                              <div style={{ width: "720px", height: "450px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                                <img decoding="auto" width="2750" height="1718" sizes="(min-width: 1200px) 720px, (min-width: 810px) and (max-width: 1199.98px) 530px, (max-width: 809.98px) 360px" srcSet={"/images/21f1488b-ubhY6w22Yd37IyvQ2G7RAEIvs.avif?scale-down-to=512&width=2750&height=1718 512w,/images/21f1488b-ubhY6w22Yd37IyvQ2G7RAEIvs.avif?scale-down-to=1024&width=2750&height=1718 1024w,/images/21f1488b-ubhY6w22Yd37IyvQ2G7RAEIvs.avif?scale-down-to=2048&width=2750&height=1718 2048w,/images/21f1488b-ubhY6w22Yd37IyvQ2G7RAEIvs.avif?width=2750&height=1718 2750w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2750 / 1718", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.example_5.src} alt={content.example_5.alt} />
                              </div>
                            </div>
                          </div>
                        </li>
                        <li className="ticker-item" aria-hidden="false" aria-posinset={4} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", transformOrigin: "360px 225px", flexGrow: "0", flexShrink: "0" } as CSSProperties}>
                          <div className="framer-ao6h8c" data-border="true" data-framer-name="Example" style={{ width: "720px", height: "450px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "1.6 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                            <div className="framer-1fgau91" style={{ width: "720px", height: "450px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                              <div style={{ width: "720px", height: "450px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                                <img decoding="auto" width="2750" height="1718" sizes="(min-width: 1200px) 720px, (min-width: 810px) and (max-width: 1199.98px) 530px, (max-width: 809.98px) 360px" srcSet={"/images/f8154b3c-f9WONOXuv6O63cVnwX91fkiHGus.avif?scale-down-to=512&width=2750&height=1718 512w,/images/f8154b3c-f9WONOXuv6O63cVnwX91fkiHGus.avif?scale-down-to=1024&width=2750&height=1718 1024w,/images/f8154b3c-f9WONOXuv6O63cVnwX91fkiHGus.avif?scale-down-to=2048&width=2750&height=1718 2048w,/images/f8154b3c-f9WONOXuv6O63cVnwX91fkiHGus.avif?width=2750&height=1718 2750w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2750 / 1718", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.example_6.src} alt={content.example_6.alt} />
                              </div>
                            </div>
                          </div>
                        </li>
                        <li className="ticker-item" aria-hidden="false" aria-posinset={5} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                          <div className="framer-ykugf-container" style={{ width: "575px", height: "449.992px", position: "relative", display: "block", flexDirection: "row", aspectRatio: "1.27778 / 1", opacity: "1" } as CSSProperties}>
                            <div className="framer-YbP5S framer-kipbz3 framer-v-kipbz3" data-border="true" data-framer-name="Pause" style={{ width: "100%", height: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                              <div className="framer-iuaieu-container" style={{ width: "575px", height: "449.992px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                                <video loop preload="metadata" poster={"/images/1a71a709-0tqKzALZ8gu4FKfEi0jeJUTUxOs136e.png?width=958&height=720"} muted playsInline style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", cursor: "auto", borderRadius: "0px", backgroundColor: "rgba(0, 0, 0, 0)", objectPosition: "50% 50%" } as CSSProperties} src={content.pause_2} />
                              </div>
                            </div>
                          </div>
                        </li>
                      </motion.ul>
                    </div>
                    {" "}
                  </div>
                </section>
              </div>
            </div>
          </div>
        </div>
        <div className="framer-xbcg8h" data-framer-name="Sticky" style={{ width: "1440px", height: "203.703px", padding: "20px", position: "sticky", zIndex: "1", inset: "auto auto 0px", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px" } as CSSProperties}>
          <div className="framer-1433hm5" data-border="true" data-framer-name="Bottom" style={{ width: "1200px", height: "163.703px", maxWidth: "1200px", padding: "1px", position: "relative", zIndex: "1", display: "grid", flexDirection: "row", justifyContent: "center", gridTemplateColumns: "299.5px 299.5px 299.5px 299.5px", gridTemplateRows: "161.703px", borderRadius: "25px", backdropFilter: "blur(5px)", overflow: "clip" } as CSSProperties}>
            <div className="framer-pr3wl3" data-border="true" data-framer-name="Logo Card" style={{ width: "299.5px", height: "161.703px", padding: "40px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", gap: "10px", backgroundColor: "rgba(255, 255, 255, 0)", overflow: "hidden" } as CSSProperties}>
              <div className="framer-5cy9mr" data-framer-name="Logo" style={{ width: "34px", height: "30px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px" } as CSSProperties}>
                <div data-framer-component-type="SVG" className="framer-qi2xzx" aria-hidden="true" style={{ width: "34px", height: "18px", position: "relative", display: "block", flexDirection: "row", imageRendering: "pixelated", flexShrink: "0", backgroundSize: "100% 100%", backgroundImage: "url('data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 xmlns:xlink=%22http://www.w3.org/1999/xlink%22 viewBox=%220 0 33.75 18%22 overflow=%22visible%22><path d=%22M 20.7 0 L 17.547 12.212 L 14.57 0 L 10.507 0 L 7.53 12.212 L 4.379 0 L 0 0 L 5.638 17.788 L 9.492 17.788 L 12.538 6.282 L 15.586 17.788 L 19.439 17.788 L 25.076 0 L 20.698 0 Z M 27.866 15.036 C 27.866 16.73 29.126 18 30.808 18 C 32.489 18 33.75 16.729 33.75 15.036 C 33.75 13.341 32.49 12.07 30.808 12.07 C 29.126 12.07 27.866 13.341 27.866 15.036 Z%22 fill=%22rgb(255, 255, 255)%22></path></svg>')" } as CSSProperties} />
              </div>
              <div className="framer-p5ri1g" data-framer-component-type="RichTextContainer" style={{ width: "157px", height: "40.5px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre-wrap", transform: "none" } as CSSProperties}>
                <p className="framer-text framer-styles-preset-4eptxb" data-styles-preset="XHuCPIQKc" dir="auto" style={{ width: "157px", height: "40.5px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "15px", lineHeight: "20.25px", letterSpacing: "-0.1px", textAlign: "left", color: "rgba(255, 255, 255, 0.6)", "--framer-text-alignment": "left", "--framer-text-color": "var(--token-8f5eb515-7a13-452b-a4ab-f35e2208a3f3, rgba(255, 255, 255, 0.6))" } as CSSProperties}>
                  <strong className="framer-text" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties}>
                    {content.logoCard}
                  </strong>
                  {" "}{content.logoCard_2}
                </p>
              </div>
            </div>
            <div className="framer-1g4djj5" data-border="true" data-framer-name="Logo Card" style={{ width: "299.5px", height: "161.703px", padding: "40px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", gap: "10px", backgroundColor: "rgba(255, 255, 255, 0)", overflow: "hidden" } as CSSProperties}>
              <div className="ssr-variant hidden-1uuy1mt" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
                <div className="framer-qud7j-container" style={{ width: "200px", height: "30px", maxWidth: "100%", position: "relative", display: "block", flexDirection: "row" } as CSSProperties}>
                  <div className="framer-nJSdh framer-1tu40ub framer-v-1j3wez3" data-framer-name="Variant 3" data-highlight="true" style={{ width: "100%", height: "100%", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "30px", opacity: "1" } as CSSProperties}>
                    <div data-framer-component-type="SVG" data-framer-name="Spotify" className="framer-1fo5js3" aria-hidden="true" style={{ imageRendering: "pixelated", flexShrink: "0", backgroundSize: "100% 100%", backgroundImage: "url(\"data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 xmlns:xlink=%22http://www.w3.org/1999/xlink%22 viewBox=%220 0 21.998 21.998%22 overflow=%22visible%22><path d=%22M 10.999 0 C 4.925 0 0 4.924 0 10.999 C 0 17.074 4.925 21.998 10.999 21.998 C 17.074 21.998 21.998 17.074 21.998 10.999 C 21.998 4.925 17.074 0.001 10.999 0.001 Z M 16.043 15.864 C 15.948 16.019 15.796 16.13 15.619 16.173 C 15.442 16.215 15.255 16.186 15.1 16.091 C 12.518 14.513 9.267 14.156 5.438 15.031 C 5.069 15.115 4.701 14.884 4.617 14.515 C 4.577 14.337 4.608 14.151 4.705 13.997 C 4.802 13.843 4.956 13.734 5.133 13.694 C 9.323 12.736 12.917 13.149 15.816 14.921 C 16.139 15.119 16.242 15.541 16.043 15.864 Z M 17.389 12.868 C 17.141 13.272 16.613 13.4 16.21 13.151 C 13.253 11.334 8.747 10.807 5.25 11.869 C 4.796 12.006 4.317 11.75 4.179 11.298 C 4.043 10.844 4.299 10.366 4.751 10.228 C 8.746 9.016 13.712 9.603 17.107 11.69 C 17.51 11.938 17.638 12.466 17.389 12.868 Z M 17.505 9.75 C 13.96 7.644 8.111 7.451 4.727 8.478 C 4.183 8.643 3.609 8.336 3.444 7.792 C 3.279 7.249 3.586 6.674 4.13 6.509 C 8.015 5.33 14.474 5.557 18.555 7.98 C 18.79 8.119 18.96 8.346 19.027 8.61 C 19.095 8.875 19.054 9.155 18.915 9.39 C 18.626 9.879 17.993 10.04 17.506 9.75 Z%22 fill=%22rgb(255, 255, 255)%22></path></svg>\")", opacity: "1" } as CSSProperties} />
                  </div>
                </div>
              </div>
              <div className="framer-12lf557" data-framer-component-type="RichTextContainer" style={{ width: "205px", height: "40.5px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre-wrap", transform: "none" } as CSSProperties}>
                <p className="framer-text framer-styles-preset-4eptxb" data-styles-preset="XHuCPIQKc" dir="auto" style={{ width: "205px", height: "40.5px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "15px", lineHeight: "20.25px", letterSpacing: "-0.1px", textAlign: "left", color: "rgba(255, 255, 255, 0.6)", "--framer-text-alignment": "left", "--framer-text-color": "var(--token-8f5eb515-7a13-452b-a4ab-f35e2208a3f3, rgba(255, 255, 255, 0.6))" } as CSSProperties}>
                  {content.logoCard_3}
                </p>
              </div>
            </div>
            <div className="framer-1yrktmj hv-177" data-framer-name="Logo Card" id="1yrktmj" tabIndex={0} style={{ width: "599px", height: "161.703px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", gridArea: "auto / span 2" } as CSSProperties}>
              <div className="framer-1tfk18r" style={{ width: "426px", height: "161.703px", padding: "40px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", gap: "10px", overflow: "clip" } as CSSProperties}>
                <div className="framer-111noha" style={{ width: "346px", height: "31.2031px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "8px", overflow: "clip" } as CSSProperties}>
                  <div className="framer-1ihsgsx" data-border="true" data-framer-name="Image" style={{ width: "30px", height: "30px", position: "relative", display: "block", flexDirection: "row", borderRadius: "100px", aspectRatio: "1 / 1" } as CSSProperties}>
                    <div style={{ width: "30px", height: "30px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                      <img decoding="auto" loading="lazy" width="400" height="400" style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", borderRadius: "inherit", overflow: "clip", objectFit: "cover", aspectRatio: "auto 400 / 400", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.image.src} alt={content.image.alt} />
                    </div>
                  </div>
                  <div className="framer-1jbo2gx" style={{ width: "308px", height: "31.2031px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", overflow: "clip" } as CSSProperties}>
                    <div className="framer-sb00e" data-framer-component-type="RichTextContainer" style={{ width: "205px", height: "15.6016px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre-wrap", transform: "none" } as CSSProperties}>
                      <p dir="auto" style={{ width: "205px", height: "15.6016px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", lineHeight: "15.6px", letterSpacing: "-0.1px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTBMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv11' on, 'ss03' on, 'ss07' on, 'cv01' on, 'cv09' on, 'cv05' on", "--framer-font-size": "12px", "--framer-font-variation-axes": "\"opsz\" 14, \"wght\" 500", "--framer-letter-spacing": "-0.1px", "--framer-line-height": "1.3em", "--framer-text-alignment": "left", "--framer-text-color": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))" } as CSSProperties} className="framer-text">
                        {content.logoCard_4}
                      </p>
                    </div>
                    <div className="framer-1b1n4pn" data-framer-component-type="RichTextContainer" style={{ width: "205px", height: "15.6016px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre-wrap", transform: "none" } as CSSProperties}>
                      <p dir="auto" style={{ width: "205px", height: "15.6016px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", lineHeight: "15.6px", letterSpacing: "-0.1px", textAlign: "left", color: "rgba(255, 255, 255, 0.6)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTBMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv11' on, 'ss03' on, 'ss07' on, 'cv01' on, 'cv09' on, 'cv05' on", "--framer-font-size": "12px", "--framer-font-variation-axes": "\"opsz\" 14, \"wght\" 500", "--framer-letter-spacing": "-0.1px", "--framer-line-height": "1.3em", "--framer-text-alignment": "left", "--framer-text-color": "var(--token-8f5eb515-7a13-452b-a4ab-f35e2208a3f3, rgba(255, 255, 255, 0.6))" } as CSSProperties} className="framer-text">
                        {content.logoCard_5}
                      </p>
                    </div>
                  </div>
                </div>
                <div className="framer-2hc7zo" data-framer-component-type="RichTextContainer" style={{ width: "337px", height: "40.5px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre-wrap", transform: "none" } as CSSProperties}>
                  <p className="framer-text framer-styles-preset-4eptxb" data-styles-preset="XHuCPIQKc" dir="auto" style={{ width: "337px", height: "40.5px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "15px", lineHeight: "20.25px", letterSpacing: "-0.1px", textAlign: "left", color: "rgba(255, 255, 255, 0.6)", "--framer-text-alignment": "left", "--framer-text-color": "var(--token-8f5eb515-7a13-452b-a4ab-f35e2208a3f3, rgba(255, 255, 255, 0.6))" } as CSSProperties}>
                    {content.logoCard_6}
                  </p>
                </div>
              </div>
              <div className="framer-1e9agkf" data-cs-id="190" style={{ width: "173px", height: "161.703px", position: "relative", zIndex: "0", display: "block", flexDirection: "row" } as CSSProperties}>
                <div className="ssr-variant" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
                  <div className="framer-1b4w74u-container" data-cs-id="192" style={{ width: "36px", height: "36px", position: "absolute", top: "80.8516px", right: "50.5px", bottom: "44.8516px", left: "86.5px", zIndex: "1", inset: "80.8516px 50.5px 44.8516px 86.5px", display: "block", flexDirection: "row", transform: "matrix(1, 0, 0, 1, -18, -18)", transformOrigin: "18px 18px" } as CSSProperties}>
                    <div className="framer-BDH4j framer-8ouk7h framer-v-10oy7ph" data-framer-name="Variant 2" data-highlight="true" tabIndex={0} style={{ width: "36px", height: "36px", padding: "0px 0px 0px 1.44px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "3.7px 0.2px", rowGap: "3.7px", columnGap: "0.2px", backgroundColor: "rgba(0, 0, 0, 0.15)", borderRadius: "72px", boxShadow: "rgba(255, 255, 255, 0.15) 0px 0px 3px 0px inset, rgba(255, 255, 255, 0.15) 0px 0.72px 0px 0px inset", backdropFilter: "blur(7px)", overflow: "clip", opacity: "1" } as CSSProperties} data-cs-id="193">
                      <svg data-framer-name="Icon L" className="framer-HY60O framer-su4xho" role="presentation" viewBox="0 0 20 20" style={{ width: "13px", height: "13px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--17kkcf8": "rgb(255, 255, 255)", "--1iwhep7": "2", "--1l3yetw": "rgb(255, 255, 255)", opacity: "1" } as CSSProperties}>
                        <use href="#102597446" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                      </svg>
                    </div>
                  </div>
                </div>
                <div className="framer-6sh2uy-container" style={{ width: "175px", height: "163.703px", position: "absolute", top: "-1px", right: "-2px", bottom: "-1px", inset: "-1px -2px -1px 0px", display: "block", flexDirection: "row" } as CSSProperties}>
                  <video loop preload="auto" poster={"/images/01c56490-mwlkoCPSAMJw2fUV5Gp1yk61Y7867.png?width=482&height=320"} muted playsInline style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", cursor: "auto", borderRadius: "0px", backgroundColor: "rgba(0, 0, 0, 0)", objectPosition: "50% 50%" } as CSSProperties} autoPlay src={content.logoCard_7} />
                </div>
              </div>
            </div>
          </div>
          <div className="framer-pzg6iy" data-framer-name="Fade" style={{ width: "1441px", height: "401.703px", position: "absolute", top: "-198px", right: "-1px", zIndex: "0", inset: "-198px -1px 0px 0px", display: "block", flexDirection: "row", overflow: "clip" } as CSSProperties} />
          <div className="framer-2ft8vh" data-framer-name="Fade" style={{ width: "1441px", height: "401.703px", position: "absolute", top: "-198px", right: "-1px", zIndex: "0", inset: "-198px -1px 0px 0px", display: "block", flexDirection: "row", overflow: "clip" } as CSSProperties} />
          <div className="framer-v15pnu" data-framer-name="Fade" style={{ width: "1441px", height: "401.703px", position: "absolute", top: "-198px", right: "-1px", zIndex: "0", inset: "-198px -1px 0px 0px", display: "block", flexDirection: "row", overflow: "clip" } as CSSProperties} />
        </div>
      </div>
    </header>
  );
}
