// content for the "Bento" section — extracted by extract-site.
// Edit values here to re-skin the "Bento" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  hide: "Staging",
  show: "Production",
  layerTitle: "www.framer.com",
  enumValue: "1m ago · by Benjamin den Boer",
  enumValue_2: "2 changes",
  label: "Deploy",
  bentoCard: "Atomic deploys.",
  bentoCard_2: "Every publish is immutable, isolated, and swapped live with zero downtime.",
  variant2: "Branches",
  variant2_2: "Search…",
  variant2_3: "All",
  variant2_4: "main",
  variant2_5: "1m",
  variant2_6: { src: "/images/8d225e32-PNKbO6dGnRRwEvctPlhddS3H2s20cf.png?width=512&height=512", alt: "Collaborator avatar" },
  variant2_7: "home-2026",
  variant2_8: "3m",
  variant2_9: { src: "/images/96913bcf-OmKDjH7juzfJ8ETRwLy9hglwa0f73b.png?width=192&height=192", alt: "Collaborator avatar" },
  variant2_10: "july-update",
  variant2_11: { src: "/images/a09b97cf-bLr4L0D7KbviHw51ILsGdJP1XUf73b.png?width=192&height=192", alt: "Collaborator avatar" },
  variant2_12: "pricing-2026",
  variant2_13: "3h",
  variant2_14: { src: "/images/8e6e198b-Udxs5uxr847mI2VCKNCu5adxuRgf73b.png?width=192&height=192", alt: "Collaborator avatar" },
  variant2_15: "perf-test",
  variant2_16: "2d",
  variant2_17: { src: "/images/9df3bd04-56Di5cRNO9igcAj63PSR0NxPQ12f3.png?width=400&height=400", alt: "Collaborator avatar" },
  variant2_18: "update-shaders",
  variant2_19: "3d",
  variant2_20: "Changes",
  variant2_21: "Updates",
  variant2_22: { src: "/images/efd2a8c4-56Di5cRNO9igcAj63PSR0NxPQ.avif?width=400&height=400", alt: "Collaborator avatar" },
  variant2_23: { src: "/images/d65e19cc-kFiEvDg0LczTmqWVkfNUFTc50.avif?width=512&height=512", alt: "Collaborator avatar" },
  variant2_24: "Shaders",
  variant2_25: { src: "/images/efd2a8c4-56Di5cRNO9igcAj63PSR0NxPQ.avif?width=400&height=400", alt: "Collaborator avatar" },
  variant2_26: "Vectors",
  variant2_27: { src: "/images/d65e19cc-kFiEvDg0LczTmqWVkfNUFTc50.avif?width=512&height=512", alt: "Collaborator avatar" },
  variant2_28: "Video",
  variant2_29: { src: "/images/4820a2a4-HpuIynUBjhAJSaXjaIesR9XZ7fM.avif?scale-down-to=512&width=2160&height=2160", alt: "Collaborator avatar" },
  variant2_30: "Apply",
  variant2_31: "to Main",
  bentoCard_3: "/collaborate",
  bentoCard_4: "Branching",
  bentoCard_5: ".",
  bentoCard_6: "Explore ideas in a branch without touching the main project. Merge when it’s ready to ship.",
  dynamicIsland: { src: "/images/0a2a7cfb-sHQsKwHsePaBOMy5WRzZXEPX42abb.png?width=190&height=60", alt: "Mobile interface detail in a Framer site preview" },
  searchBar: "website.com/notes",
  top: "Guides",
  typewriter: "Publish with staging",
  typewriter_2: "|",
  image: { src: "../../framerusercontent.com/images/7Bve0br7qUoPAMoWNELDgkUqcQ90ee.png?width=1024&height=1024", alt: "Framer collaboration feature preview" },
  bentoCard_7: "On-page editing.",
  bentoCard_8: "Update content directly on your live site and publish instantly.",
  show_2: "Staging",
  hide_2: "Production",
  layerTitle_2: "stale-gift…new-pricing.framer.app",
  enumValue_3: "3m ago · by Benjamin den Boer",
  enumValue_4: "3 changes",
  label_2: "Update",
  bentoCard_9: "Staging environments.",
  bentoCard_10: "Test changes securely on a framer.app domain before pushing live.",
  author: "Enter password to access the site.",
  input: "• • • • • • •",
  input_2: "|",
  text: "Submit",
  bentoCard_11: "Password protection.",
  bentoCard_12: "Control who gets access when sharing with clients, partners, or your team.",
  enumValue_5: "955g4th33",
  enumValue_6: "Optimizing",
  enumValue_7: "1m ago by Monika",
  enumValue_8: "870f8tm34",
  enumValue_9: "Optimized",
  enumValue_10: "2m ago by Jurre",
  enumValue_11: "19g59t4r2",
  enumValue_12: "Optimized",
  enumValue_13: "31m ago by Joseph",
  enumValue_14: "99g58t4d2",
  enumValue_15: "Optimized",
  enumValue_16: "1d ago by Floris",
  enumValue_17: "369f5h4y7",
  enumValue_18: "Optimized",
  enumValue_19: "2d ago by",
  enumControl: "Benjamin",
  enumValue_20: "548tj5790",
  enumValue_21: "Optimized",
  enumValue_22: "4d ago by Andy",
  enumValue_23: "16fd9t797",
  enumValue_24: "Optimized",
  enumValue_25: "7d ago by Jurre",
  bentoCard_13: "Version history and rollback.",
  bentoCard_14: "Every site change is saved automatically, so you can restore any version in seconds.",
};
