// content for the "Bento" section — extracted by extract-site.
// Edit values here to re-skin the "Bento" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  webVitals: "Warm pools",
  webVitals_2: "ready",
  webVitals_3: "Pre-warmed capacity",
  webVitals_4: "High",
  webVitals_5: "Cold start protection",
  webVitals_6: "Full",
  bentoCard: "Fluid capacity.",
  bentoCard_2: "Traffic spikes are absorbed instantly with no cold starts or manual scaling.",
  url: "Home",
  url_2: "/features",
  url_3: "/blog",
  url_4: "/support",
  bentoCard_3: "Smart pre-rendering.",
  bentoCard_4: "Popular pages are cached globally, while quieter pages render on demand.",
  end: { src: "../../framerusercontent.com/images/bNFIj27yrNBg5hMur3BHFapVqiUa60a.jpg?width=1200&height=1378", alt: "Website example" },
  blue1: { src: "../../framerusercontent.com/images/6jRvqoRmEJSdUYNTOvPB1dWBrlMa60a.jpg?width=1200&height=1378", alt: "Website example" },
  blue2: { src: "../../framerusercontent.com/images/dYXgkRDEqTDB2JjbfTnwqmVPloa60a.jpg?width=1200&height=1378", alt: "Website example" },
  blue3: { src: "../../framerusercontent.com/images/yL89SMfsZYHG8tsFvge8d7yKd0a60a.jpg?width=1200&height=1378", alt: "Website example" },
  bentoCard_5: "Virtual DOM simulation.",
  bentoCard_6: "We predict image size and layout early for zero shift and instant paint.",
  image1: { src: "../../framerusercontent.com/images/X7zpVDjeTuS4BC9vit2Y29qbSzI4123.png?lossless=1&width=1768&height=2124", alt: "Abstract architectural hosting visual" },
  image: "AVIF: 94kb",
  image_2: "PNG: 492KB",
  image_3: "saved",
  image_4: "81%",
  bentoCard_7: "Dynamic image optimization.",
  bentoCard_8: "Upload once. Framer resizes and serves",
  bentoCard_9: "WebP",
  bentoCard_10: "and",
  bentoCard_11: "AVIF",
  bentoCard_12: "at the edge.",
  optimization: "HTML",
  optimization_2: "CSS",
  optimization_3: "JS",
  optimization_4: "Fonts",
  optimization_5: "Brotli",
  optimization_6: "Brotli",
  optimization_7: "Brotli",
  optimization_8: "WOFF2",
  optimization_9: "20",
  optimization_10: "kB",
  optimization_11: "10 kB",
  optimization_12: "60 kB",
  optimization_13: "35 kB",
  bentoCard_13: "Automated optimization.",
  bentoCard_14: "Brotli, Gzip, and",
  bentoCard_15: "WOFF2",
  bentoCard_16: "font optimization run automatically for every site.",
  variant4: "Hosting",
  variant4_2: "Domains",
  variant4_3: "Storage",
  variant4_4: "Network",
  bentoCard_17: "Powered by",
  bentoCard_18: "https://motion.dev/",
  bentoCard_19: "Motion",
  bentoCard_20: ".",
  bentoCard_21: "GPU-accelerated Motion keeps every transition smooth across devices.",
  url_5: "<!doctype html>",
  url_6: "<!-- Made in Framer · framer.com ✨ -->",
  url_7: "<!-- Published Jun 26, 2026, 1:43 PM UTC -->",
  url_8: "<html",
  url_9: "lang=”en” data-redirect-timezone=”1”",
  url_10: ">",
  url_11: "<head>",
  url_12: "<meta",
  url_13: "charset=”utf-8”",
  url_14: ">",
  url_15: "<meta",
  url_16: "name=”viewport” content=”width=device-width”",
  url_17: ">",
  url_18: "<meta",
  url_19: "name=”generator” content=”Framer 8c11dda”",
  url_20: ">",
  url_21: "<title>",
  url_22: "Framer: AI website builder for professional sites",
  url_23: "</title>",
  url_24: "<meta",
  url_25: "name=”framer-search-index” content=”https://framerusercontent.com/sites/3BJ9zINIeWtEEVRMAcoTL8/searchIndex-awp2WuOFzxb5.json”",
  url_26: ">",
  url_27: "<meta",
  url_28: "name=”framer-search-index-fallback” content=”https://framerusercontent.com/sites/3BJ9zINIeWtEEVRMAcoTL8/searchIndex-TnkuwPa8CNRT.json”",
  url_29: ">",
  url_30: "<meta",
  url_31: "name=”framer-html-plugin” content=”disable”",
  url_32: ">",
  url_33: "<link",
  url_34: "href=\"",
  url_35: "https://framerusercontent.com/images/Io89FonxEaWg4nxvQQllVLwPUUI.png",
  url_36: "\" rel=\"icon\" media=\"(prefers-color-scheme: light)\"",
  url_37: ">",
  url_38: "<link",
  url_39: "href=\"",
  url_40: "https://framerusercontent.com/images/IWSWAkpF5evn8F9z67GntQanjk.png",
  url_41: "\" rel=\"icon\" media=\"(prefers-color-scheme: dark)\"",
  url_42: ">",
  url_43: "<link",
  url_44: "rel=\"apple-touch-icon\" href=\"",
  url_45: "https://framerusercontent.com/images/aXvo6HfUhqvR7oFjFL8b4AcyGfg.png",
  url_46: "\"",
  url_47: ">",
  url_48: "<!-- Open Graph -->",
  url_49: "<link",
  url_50: "property=\"og:type\" content=\"website\"",
  url_51: ">",
  url_52: "<link",
  url_53: "property=\"og:title\" content=\"Framer: AI website builder for professional sites\"",
  url_54: ">",
  url_55: "<link",
  url_56: "property=\"og:description\" content=\"Create a professional website with Framer’s no-code AI website builder. Design freely, manage CMS content, optimize SEO, collaborate, and publish fast.\"",
  url_57: ">",
  bentoCard_22: "Clean source output.",
  bentoCard_23: "Framer publishes clean HTML, CSS, and assets for fast, crawlable pages.",
};
