// content for the "Bento" section — extracted by extract-site.
// Edit values here to re-skin the "Bento" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "Deploy with total confidence",
  hide: "Staging",
  show: "Production",
  layerTitle: "www.framer.com",
  enumValue: "1m ago · by Benjamin den Boer",
  enumValue_2: "2 changes",
  label: "Deploy",
  bentoCard: "Atomic deploys.",
  bentoCard_2: "Every publish is immutable, isolated, and swapped live with zero downtime.",
  enumValue_3: "955g4th33",
  enumValue_4: "Optimizing",
  enumValue_5: "1m ago by Monika",
  enumValue_6: "870f8tm34",
  enumValue_7: "Optimized",
  enumValue_8: "2m ago by Jurre",
  enumValue_9: "19g59t4r2",
  enumValue_10: "Optimized",
  enumValue_11: "31m ago by Joseph",
  enumValue_12: "99g58t4d2",
  enumValue_13: "Optimized",
  enumValue_14: "1d ago by Floris",
  enumValue_15: "369f5h4y7",
  enumValue_16: "Optimized",
  enumValue_17: "2d ago by",
  enumControl: "Benjamin",
  enumValue_18: "548tj5790",
  enumValue_19: "Optimized",
  enumValue_20: "4d ago by Andy",
  enumValue_21: "16fd9t797",
  enumValue_22: "Optimized",
  enumValue_23: "7d ago by Jurre",
  bentoCard_3: "Instant rollbacks.",
  bentoCard_4: "Revert to any healthy version in seconds with full deployment history.",
  branches: "Branches",
  branches_2: "Search…",
  branches_3: "All",
  branches_4: "main",
  branches_5: "1m",
  branches_6: { src: "/images/8d225e32-PNKbO6dGnRRwEvctPlhddS3H2s20cf.png?width=512&height=512", alt: "Collaborator avatar" },
  branches_7: "home-2026",
  branches_8: "3m",
  branches_9: { src: "/images/96913bcf-OmKDjH7juzfJ8ETRwLy9hglwa0f73b.png?width=192&height=192", alt: "Collaborator avatar" },
  branches_10: "july-update",
  branches_11: { src: "/images/8d225e32-PNKbO6dGnRRwEvctPlhddS3H2s20cf.png?width=512&height=512", alt: "Collaborator avatar" },
  branches_12: "publishing",
  branches_13: "8m",
  branches_14: { src: "/images/1ea3b48d-kFiEvDg0LczTmqWVkfNUFTc5020cf.png?width=512&height=512", alt: "Collaborator avatar" },
  branches_15: "content",
  branches_16: "10m",
  branches_17: { src: "/images/a09b97cf-bLr4L0D7KbviHw51ILsGdJP1XUf73b.png?width=192&height=192", alt: "Collaborator avatar" },
  branches_18: "pricing-2026",
  branches_19: "3h",
  branches_20: "Changes",
  branches_21: "Home",
  branches_22: { src: "/images/96913bcf-OmKDjH7juzfJ8ETRwLy9hglwa0f73b.png?width=192&height=192", alt: "Collaborator avatar" },
  branches_23: "/pricing",
  branches_24: { src: "/images/96913bcf-OmKDjH7juzfJ8ETRwLy9hglwa0f73b.png?width=192&height=192", alt: "Collaborator avatar" },
  branches_25: "Locales",
  branches_26: { src: "../../framerusercontent.com/images/56Di5cRNO9igcAj63PSR0NxPQ12f3.png?width=400&height=400", alt: "Collaborator avatar" },
  branches_27: "Glossary",
  branches_28: { src: "../../framerusercontent.com/images/56Di5cRNO9igcAj63PSR0NxPQ12f3.png?width=400&height=400", alt: "Collaborator avatar" },
  branches_29: "Updates",
  branches_30: { src: "../../framerusercontent.com/images/56Di5cRNO9igcAj63PSR0NxPQ12f3.png?width=400&height=400", alt: "Collaborator avatar" },
  branches_31: { src: "/images/1ea3b48d-kFiEvDg0LczTmqWVkfNUFTc5020cf.png?width=512&height=512", alt: "Collaborator avatar" },
  branches_32: "Shaders",
  branches_33: { src: "../../framerusercontent.com/images/56Di5cRNO9igcAj63PSR0NxPQ12f3.png?width=400&height=400", alt: "Collaborator avatar" },
  branches_34: "Vectors",
  branches_35: { src: "/images/1ea3b48d-kFiEvDg0LczTmqWVkfNUFTc5020cf.png?width=512&height=512", alt: "Collaborator avatar" },
  branches_36: "Apply",
  branches_37: "to Main",
  bentoCard_5: "/collaborate",
  bentoCard_6: "Branching",
  bentoCard_7: ".",
  bentoCard_8: "Explore ideas in a branch without touching the main project. Merge when it’s ready to ship.",
  gradient: { src: "../../framerusercontent.com/images/CQsZ1v3Cg7a8s5gQ8zH4usL7HU2cf8.png?width=774&height=480", alt: "Hosting Background" },
  text: "99.99%",
  text_2: "uptime",
  bentoCard_9: "99.99% uptime.",
  bentoCard_10: "Infrastructure is monitored around the clock with real-time status updates.",
  show_2: "Staging",
  hide_2: "Production",
  layerTitle_2: "stale-gift…new-pricing.framer.app",
  enumValue_24: "3m ago · by Benjamin den Boer",
  enumValue_25: "3 changes",
  label_2: "Update",
  bentoCard_11: "Staging environments.",
  bentoCard_12: "Test changes securely on a framer.app domain before pushing live.",
};
