// content for the "Body" section — extracted by extract-site.
// Edit values here to re-skin the "Body" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  body: "The best place to learn Framer",
  academy: "Search lessons...",
  body_2: "https://framer-ai.com/courses/get-started-with-framer-agents",
  cover: "Get Started with Framer Agents",
  cover_2: "Start using Framer Agents to generate layouts, refine site structure, work with project context, and connect external AI tools to your Framer workflow.",
  cover_3: { src: "../../framerusercontent.com/images/WUOFsuTEwWrZoYMz4ume4lzOkcd01.png?width=3840&height=2160", alt: "Get Started with Framer Agents — course cover image" },
  header: "Courses",
  m: "https://framer-ai.com/courses",
  m_2: "All courses",
  course: "https://framer-ai.com/courses/fundamentals",
  cover_4: { src: "../../framerusercontent.com/images/08jnbLvQzszyBh4UcdVN4wOEW5gcd01.png?width=3840&height=2160", alt: "Framer Fundamentals — course cover image" },
  time: "4h 6m",
  course_2: "Framer Fundamentals",
  paragraph1: "In this Framer course, you’ll learn how to design and publish fully responsive websites without code. From mastering layout and styling to adding content, creating components, and optimizing for launch—this course gives you everything you need to confidently build in Framer.",
  course_3: "https://framer-ai.com/courses/getting-started-with-framer-cms",
  cover_5: { src: "../../framerusercontent.com/images/eZbVsO0oCFEgc80FOV6IJ6RnVYcd01.png?width=3840&height=2160", alt: "Get Started with the Framer CMS — course cover image" },
  time_2: "26m",
  course_4: "Framer CMS Basics",
  paragraph2: "Framer’s CMS keeps your site’s content all in one place, making it easy to create, organize, and update.",
  course_5: "https://framer-ai.com/courses/mastering-animations-and-interactions-in-framer",
  cover_6: { src: "../../framerusercontent.com/images/zJFvXCmd3RAEVly7GCojwF2cQNc88ac.png?width=1920&height=1080", alt: "Mastering Animations and Interactions in Framer — course cover image" },
  time_3: "2h 35m",
  course_6: "Animations and Interactions in Framer",
  paragraph3: "Animation isn’t just about making things move — it’s bringing things to life with meaning. In this course, we’ll explore how to use motion and interaction to guide attention, create smoother experiences, and add personality to your designs. Whether it’s a subtle hover effect or a fully choreographed transition, you’ll learn how to bring your site to life with intention and clarity using Framer.",
  course_7: "https://framer-ai.com/courses/mastering-vectors-in-framer",
  cover_7: { src: "../../framerusercontent.com/images/FM3gs6WjGCPFabPBJnyPUomCpls88ac.png?width=1920&height=1080", alt: "Mastering Vectors in Framer Course — course cover image" },
  course_8: "Vectors in Framer",
  paragraph4: "This course covers everything from creating clean vector paths to building reusable vector sets, using variables, and adding subtle motion with the Stroke Effect. Perfect for designers who want scalable icons, flexible graphics, and more polished UI motion—without the mess.",
  course_9: "https://framer-ai.com/courses/fundamentals",
  cover_8: { src: "../../framerusercontent.com/images/08jnbLvQzszyBh4UcdVN4wOEW5gcd01.png?width=3840&amp;height=2160", alt: "Framer Fundamentals — course cover image" },
  time_4: "4h 6m",
  course_10: "Framer Fundamentals",
  paragraph5: "In this Framer course, you’ll learn how to design and publish fully responsive websites without code. From mastering layout and styling to adding content, creating components, and optimizing for launch—this course gives you everything you need to confidently build in Framer.",
  course_11: "https://framer-ai.com/courses/getting-started-with-framer-cms",
  cover_9: { src: "../../framerusercontent.com/images/eZbVsO0oCFEgc80FOV6IJ6RnVYcd01.png?width=3840&amp;height=2160", alt: "Get Started with the Framer CMS — course cover image" },
  time_5: "26m",
  course_12: "Framer CMS Basics",
  paragraph6: "Framer’s CMS keeps your site’s content all in one place, making it easy to create, organize, and update.",
  course_13: "https://framer-ai.com/courses/mastering-animations-and-interactions-in-framer",
  cover_10: { src: "../../framerusercontent.com/images/zJFvXCmd3RAEVly7GCojwF2cQNc88ac.png?width=1920&amp;height=1080", alt: "Mastering Animations and Interactions in Framer — course cover image" },
  time_6: "2h 35m",
  course_14: "Animations and Interactions in Framer",
  paragraph7: "Animation isn’t just about making things move — it’s bringing things to life with meaning. In this course, we’ll explore how to use motion and interaction to guide attention, create smoother experiences, and add personality to your designs. Whether it’s a subtle hover effect or a fully choreographed transition, you’ll learn how to bring your site to life with intention and clarity using Framer.",
  course_15: "https://framer-ai.com/courses/mastering-vectors-in-framer",
  cover_11: { src: "../../framerusercontent.com/images/FM3gs6WjGCPFabPBJnyPUomCpls88ac.png?width=1920&amp;height=1080", alt: "Mastering Vectors in Framer Course — course cover image" },
  course_16: "Vectors in Framer",
  paragraph8: "This course covers everything from creating clean vector paths to building reusable vector sets, using variables, and adding subtle motion with the Stroke Effect. Perfect for designers who want scalable icons, flexible graphics, and more polished UI motion—without the mess.",
  course_17: "https://framer-ai.com/courses/fundamentals",
  cover_12: { src: "../../framerusercontent.com/images/08jnbLvQzszyBh4UcdVN4wOEW5gcd01.png?width=3840&amp;height=2160", alt: "Framer Fundamentals — course cover image" },
  time_7: "4h 6m",
  course_18: "Framer Fundamentals",
  paragraph9: "In this Framer course, you’ll learn how to design and publish fully responsive websites without code. From mastering layout and styling to adding content, creating components, and optimizing for launch—this course gives you everything you need to confidently build in Framer.",
  course_19: "https://framer-ai.com/courses/getting-started-with-framer-cms",
  cover_13: { src: "../../framerusercontent.com/images/eZbVsO0oCFEgc80FOV6IJ6RnVYcd01.png?width=3840&amp;height=2160", alt: "Get Started with the Framer CMS — course cover image" },
  time_8: "26m",
  course_20: "Framer CMS Basics",
  paragraph10: "Framer’s CMS keeps your site’s content all in one place, making it easy to create, organize, and update.",
  course_21: "https://framer-ai.com/courses/mastering-animations-and-interactions-in-framer",
  cover_14: { src: "../../framerusercontent.com/images/zJFvXCmd3RAEVly7GCojwF2cQNc88ac.png?width=1920&amp;height=1080", alt: "Mastering Animations and Interactions in Framer — course cover image" },
  time_9: "2h 35m",
  course_22: "Animations and Interactions in Framer",
  paragraph11: "Animation isn’t just about making things move — it’s bringing things to life with meaning. In this course, we’ll explore how to use motion and interaction to guide attention, create smoother experiences, and add personality to your designs. Whether it’s a subtle hover effect or a fully choreographed transition, you’ll learn how to bring your site to life with intention and clarity using Framer.",
  course_23: "https://framer-ai.com/courses/mastering-vectors-in-framer",
  cover_15: { src: "../../framerusercontent.com/images/FM3gs6WjGCPFabPBJnyPUomCpls88ac.png?width=1920&amp;height=1080", alt: "Mastering Vectors in Framer Course — course cover image" },
  course_24: "Vectors in Framer",
  paragraph12: "This course covers everything from creating clean vector paths to building reusable vector sets, using variables, and adding subtle motion with the Stroke Effect. Perfect for designers who want scalable icons, flexible graphics, and more polished UI motion—without the mess.",
  course_25: "https://framer-ai.com/courses/fundamentals",
  cover_16: { src: "../../framerusercontent.com/images/08jnbLvQzszyBh4UcdVN4wOEW5gcd01.png?width=3840&amp;height=2160", alt: "Framer Fundamentals — course cover image" },
  time_10: "4h 6m",
  course_26: "Framer Fundamentals",
  paragraph13: "In this Framer course, you’ll learn how to design and publish fully responsive websites without code. From mastering layout and styling to adding content, creating components, and optimizing for launch—this course gives you everything you need to confidently build in Framer.",
  course_27: "https://framer-ai.com/courses/getting-started-with-framer-cms",
  cover_17: { src: "../../framerusercontent.com/images/eZbVsO0oCFEgc80FOV6IJ6RnVYcd01.png?width=3840&amp;height=2160", alt: "Get Started with the Framer CMS — course cover image" },
  time_11: "26m",
  course_28: "Framer CMS Basics",
  paragraph14: "Framer’s CMS keeps your site’s content all in one place, making it easy to create, organize, and update.",
  course_29: "https://framer-ai.com/courses/mastering-animations-and-interactions-in-framer",
  cover_18: { src: "../../framerusercontent.com/images/zJFvXCmd3RAEVly7GCojwF2cQNc88ac.png?width=1920&amp;height=1080", alt: "Mastering Animations and Interactions in Framer — course cover image" },
  time_12: "2h 35m",
  course_30: "Animations and Interactions in Framer",
  paragraph15: "Animation isn’t just about making things move — it’s bringing things to life with meaning. In this course, we’ll explore how to use motion and interaction to guide attention, create smoother experiences, and add personality to your designs. Whether it’s a subtle hover effect or a fully choreographed transition, you’ll learn how to bring your site to life with intention and clarity using Framer.",
  course_31: "https://framer-ai.com/courses/mastering-vectors-in-framer",
  cover_19: { src: "../../framerusercontent.com/images/FM3gs6WjGCPFabPBJnyPUomCpls88ac.png?width=1920&amp;height=1080", alt: "Mastering Vectors in Framer Course — course cover image" },
  course_32: "Vectors in Framer",
  paragraph16: "This course covers everything from creating clean vector paths to building reusable vector sets, using variables, and adding subtle motion with the Stroke Effect. Perfect for designers who want scalable icons, flexible graphics, and more polished UI motion—without the mess.",
  topic: { src: "/images/b8ac445b-6tTbkXggWgQCAJ4DO2QEdXXmgM.svg?arrow=left", alt: "Back Arrow" },
  topic_2: { src: "/images/69eb8cee-11KSGbIZoRSg4pjdnUoif6MKHI.svg?arrow=right", alt: "Next Arrow" },
  header_2: "Get started with Framer",
  m_3: "https://framer-ai.com/courses/fundamentals",
  m_4: "All",
  lesson: "https://framer-ai.com/lessons/framer-fundamentals-framer-interface",
  cover_20: { src: "../../framerusercontent.com/images/XRlUQJhIPBJL5pe9M72SzSWEf7e0.png?width=1280&height=720", alt: "Getting familiar with the Framer interface — lesson cover image" },
  level: "5:16",
  time_13: "5:16",
  lesson_2: "Getting familiar with the Framer interface",
  level_2: "Last year",
  lesson_3: "https://framer-ai.com/lessons/framer-fundamentals-thinking-in-frames",
  cover_21: { src: "../../framerusercontent.com/images/LTx5Ibat5mvNngcwILzm4Z4nfiof7e0.png?width=1280&height=720", alt: "Thinking in frames — lesson cover image" },
  level_3: "3:53",
  time_14: "3:53",
  lesson_4: "Thinking in frames",
  level_4: "Last year",
  lesson_5: "https://framer-ai.com/lessons/framer-fundamentals-absolute-positioning",
  cover_22: { src: "../../framerusercontent.com/images/N9opDztdU0yszZIIFTS4KmEayDUf7e0.png?width=1280&height=720", alt: "Absolute positioning in Framer — lesson cover image" },
  level_5: "7:39",
  time_15: "7:39",
  lesson_6: "Absolute positioning in Framer",
  level_6: "Last year",
  lesson_7: "https://framer-ai.com/lessons/framer-fundamentals-stacks-and-relative-positioning",
  cover_23: { src: "../../framerusercontent.com/images/7V0yX3D91rwLSO6zVOJTXoa5eoo88ac.jpg?width=1920&height=1080", alt: "Stacks and relative positioning in Framer — lesson cover image" },
  level_7: "8:05",
  time_16: "8:05",
  lesson_8: "Stacks and relative positioning in Framer",
  level_8: "Last year",
  lesson_9: "https://framer-ai.com/lessons/framer-fundamentals-sizing-to-fill-and-fit-content",
  cover_24: { src: "../../framerusercontent.com/images/XYrbgFqEMhHhX8KStZRAUQfsbc88ac.jpg?width=1920&height=1080", alt: "Sizing to fill and fit content in Framer — lesson cover image" },
  level_9: "7:37",
  time_17: "7:37",
  lesson_10: "Sizing to fill and fit content in Framer",
  level_10: "Last year",
  lesson_11: "https://framer-ai.com/lessons/framer-fundamentals-stacks-vs-grids",
  cover_25: { src: "../../framerusercontent.com/images/QVT8ACbNpagBEzDSB4DWXfH088ac.jpg?width=1920&height=1080", alt: "Stacks vs grids in Framer — lesson cover image" },
  level_11: "7:45",
  time_18: "7:45",
  lesson_12: "Stacks vs grids in Framer",
  level_12: "Last year",
  lesson_13: "https://framer-ai.com/lessons/framer-fundamentals-framer-interface",
  cover_26: { src: "../../framerusercontent.com/images/XRlUQJhIPBJL5pe9M72SzSWEf7e0.png?width=1280&amp;height=720", alt: "Getting familiar with the Framer interface — lesson cover image" },
  level_13: "5:16",
  time_19: "5:16",
  lesson_14: "Getting familiar with the Framer interface",
  level_14: "Last year",
  lesson_15: "https://framer-ai.com/lessons/framer-fundamentals-thinking-in-frames",
  cover_27: { src: "../../framerusercontent.com/images/LTx5Ibat5mvNngcwILzm4Z4nfiof7e0.png?width=1280&amp;height=720", alt: "Thinking in frames — lesson cover image" },
  level_15: "3:53",
  time_20: "3:53",
  lesson_16: "Thinking in frames",
  level_16: "Last year",
  lesson_17: "https://framer-ai.com/lessons/framer-fundamentals-absolute-positioning",
  cover_28: { src: "../../framerusercontent.com/images/N9opDztdU0yszZIIFTS4KmEayDUf7e0.png?width=1280&amp;height=720", alt: "Absolute positioning in Framer — lesson cover image" },
  level_17: "7:39",
  time_21: "7:39",
  lesson_18: "Absolute positioning in Framer",
  level_18: "Last year",
  lesson_19: "https://framer-ai.com/lessons/framer-fundamentals-stacks-and-relative-positioning",
  cover_29: { src: "../../framerusercontent.com/images/7V0yX3D91rwLSO6zVOJTXoa5eoo88ac.jpg?width=1920&amp;height=1080", alt: "Stacks and relative positioning in Framer — lesson cover image" },
  level_19: "8:05",
  time_22: "8:05",
  lesson_20: "Stacks and relative positioning in Framer",
  level_20: "Last year",
  lesson_21: "https://framer-ai.com/lessons/framer-fundamentals-sizing-to-fill-and-fit-content",
  cover_30: { src: "../../framerusercontent.com/images/XYrbgFqEMhHhX8KStZRAUQfsbc88ac.jpg?width=1920&amp;height=1080", alt: "Sizing to fill and fit content in Framer — lesson cover image" },
  level_21: "7:37",
  time_23: "7:37",
  lesson_22: "Sizing to fill and fit content in Framer",
  level_22: "Last year",
  lesson_23: "https://framer-ai.com/lessons/framer-fundamentals-stacks-vs-grids",
  cover_31: { src: "../../framerusercontent.com/images/QVT8ACbNpagBEzDSB4DWXfH088ac.jpg?width=1920&amp;height=1080", alt: "Stacks vs grids in Framer — lesson cover image" },
  level_23: "7:45",
  time_24: "7:45",
  lesson_24: "Stacks vs grids in Framer",
  level_24: "Last year",
  lesson_25: "https://framer-ai.com/lessons/framer-fundamentals-framer-interface",
  cover_32: { src: "../../framerusercontent.com/images/XRlUQJhIPBJL5pe9M72SzSWEf7e0.png?width=1280&amp;height=720", alt: "Getting familiar with the Framer interface — lesson cover image" },
  level_25: "5:16",
  time_25: "5:16",
  lesson_26: "Getting familiar with the Framer interface",
  level_26: "Last year",
  lesson_27: "https://framer-ai.com/lessons/framer-fundamentals-thinking-in-frames",
  cover_33: { src: "../../framerusercontent.com/images/LTx5Ibat5mvNngcwILzm4Z4nfiof7e0.png?width=1280&amp;height=720", alt: "Thinking in frames — lesson cover image" },
  level_27: "3:53",
  time_26: "3:53",
  lesson_28: "Thinking in frames",
  level_28: "Last year",
  lesson_29: "https://framer-ai.com/lessons/framer-fundamentals-absolute-positioning",
  cover_34: { src: "../../framerusercontent.com/images/N9opDztdU0yszZIIFTS4KmEayDUf7e0.png?width=1280&amp;height=720", alt: "Absolute positioning in Framer — lesson cover image" },
  level_29: "7:39",
  time_27: "7:39",
  lesson_30: "Absolute positioning in Framer",
  level_30: "Last year",
  lesson_31: "https://framer-ai.com/lessons/framer-fundamentals-stacks-and-relative-positioning",
  cover_35: { src: "../../framerusercontent.com/images/7V0yX3D91rwLSO6zVOJTXoa5eoo88ac.jpg?width=1920&amp;height=1080", alt: "Stacks and relative positioning in Framer — lesson cover image" },
  level_31: "8:05",
  time_28: "8:05",
  lesson_32: "Stacks and relative positioning in Framer",
  level_32: "Last year",
  lesson_33: "https://framer-ai.com/lessons/framer-fundamentals-sizing-to-fill-and-fit-content",
  cover_36: { src: "../../framerusercontent.com/images/XYrbgFqEMhHhX8KStZRAUQfsbc88ac.jpg?width=1920&amp;height=1080", alt: "Sizing to fill and fit content in Framer — lesson cover image" },
  level_33: "7:37",
  time_29: "7:37",
  lesson_34: "Sizing to fill and fit content in Framer",
  level_34: "Last year",
  lesson_35: "https://framer-ai.com/lessons/framer-fundamentals-stacks-vs-grids",
  cover_37: { src: "../../framerusercontent.com/images/QVT8ACbNpagBEzDSB4DWXfH088ac.jpg?width=1920&amp;height=1080", alt: "Stacks vs grids in Framer — lesson cover image" },
  level_35: "7:45",
  time_30: "7:45",
  lesson_36: "Stacks vs grids in Framer",
  level_36: "Last year",
  lesson_37: "https://framer-ai.com/lessons/framer-fundamentals-framer-interface",
  cover_38: { src: "../../framerusercontent.com/images/XRlUQJhIPBJL5pe9M72SzSWEf7e0.png?width=1280&amp;height=720", alt: "Getting familiar with the Framer interface — lesson cover image" },
  level_37: "5:16",
  time_31: "5:16",
  lesson_38: "Getting familiar with the Framer interface",
  level_38: "Last year",
  lesson_39: "https://framer-ai.com/lessons/framer-fundamentals-thinking-in-frames",
  cover_39: { src: "../../framerusercontent.com/images/LTx5Ibat5mvNngcwILzm4Z4nfiof7e0.png?width=1280&amp;height=720", alt: "Thinking in frames — lesson cover image" },
  level_39: "3:53",
  time_32: "3:53",
  lesson_40: "Thinking in frames",
  level_40: "Last year",
  lesson_41: "https://framer-ai.com/lessons/framer-fundamentals-absolute-positioning",
  cover_40: { src: "../../framerusercontent.com/images/N9opDztdU0yszZIIFTS4KmEayDUf7e0.png?width=1280&amp;height=720", alt: "Absolute positioning in Framer — lesson cover image" },
  level_41: "7:39",
  time_33: "7:39",
  lesson_42: "Absolute positioning in Framer",
  level_42: "Last year",
  lesson_43: "https://framer-ai.com/lessons/framer-fundamentals-stacks-and-relative-positioning",
  cover_41: { src: "../../framerusercontent.com/images/7V0yX3D91rwLSO6zVOJTXoa5eoo88ac.jpg?width=1920&amp;height=1080", alt: "Stacks and relative positioning in Framer — lesson cover image" },
  level_43: "8:05",
  time_34: "8:05",
  lesson_44: "Stacks and relative positioning in Framer",
  level_44: "Last year",
  lesson_45: "https://framer-ai.com/lessons/framer-fundamentals-sizing-to-fill-and-fit-content",
  cover_42: { src: "../../framerusercontent.com/images/XYrbgFqEMhHhX8KStZRAUQfsbc88ac.jpg?width=1920&amp;height=1080", alt: "Sizing to fill and fit content in Framer — lesson cover image" },
  level_45: "7:37",
  time_35: "7:37",
  lesson_46: "Sizing to fill and fit content in Framer",
  level_46: "Last year",
  lesson_47: "https://framer-ai.com/lessons/framer-fundamentals-stacks-vs-grids",
  cover_43: { src: "../../framerusercontent.com/images/QVT8ACbNpagBEzDSB4DWXfH088ac.jpg?width=1920&amp;height=1080", alt: "Stacks vs grids in Framer — lesson cover image" },
  level_47: "7:45",
  time_36: "7:45",
  lesson_48: "Stacks vs grids in Framer",
  level_48: "Last year",
  course_33: { src: "/images/b8ac445b-6tTbkXggWgQCAJ4DO2QEdXXmgM.svg?arrow=left", alt: "Back Arrow" },
  course_34: { src: "/images/69eb8cee-11KSGbIZoRSg4pjdnUoif6MKHI.svg?arrow=right", alt: "Next Arrow" },
  header_3: "Latest lessons",
  m_5: "https://framer-ai.com/lessons",
  m_6: "All",
  lesson_49: "https://framer-ai.com/lessons/polish-your-page-with-agents",
  cover_44: { src: "../../framerusercontent.com/images/n2mSpeAc3lUIRBNNURkTATSAo88ac.jpg?width=1920&height=1080", alt: "" },
  level_49: "2:14",
  time_37: "2:14",
  lesson_50: "Polish your Pages with Agents",
  level_50: "2 months ago",
  lesson_51: "https://framer-ai.com/lessons/external-agents-with-framer",
  cover_45: { src: "../../framerusercontent.com/images/1nYmAWqWblGQJzl0GpbiAWbeyeI88ac.jpg?width=1920&height=1080", alt: "Connect Framer to Claude Code, Codex, Cursor, and more — lesson cover image" },
  level_51: "7:13",
  time_38: "7:13",
  lesson_52: "Connect Framer to Claude Code, ChatGPT Codex, Cursor, and more",
  level_52: "3 months ago",
  lesson_53: "https://framer-ai.com/lessons/framer-agents-content-scale",
  cover_46: { src: "../../framerusercontent.com/images/uADiL603F0zh18Kr2kwpf71pkrAcd01.jpg?width=3840&height=2160", alt: "Content, Components, and CMS with Framer Agents — lesson cover image" },
  level_53: "8:25",
  time_39: "8:25",
  lesson_54: "Content, Components, and CMS with Framer Agents",
  level_54: "3 months ago",
  lesson_55: "https://framer-ai.com/lessons/framer-agents-generation-layout-style",
  cover_47: { src: "../../framerusercontent.com/images/1QznpGq3xVnPPsG8DIOcQ72ytHQ88ac.jpg?width=1920&height=1080", alt: "Generation, layout, and styling with Framer Agents — lesson cover image" },
  level_55: "15:13",
  time_40: "15:13",
  lesson_56: "Generation, layout, and styling with Framer Agents",
  level_56: "3 months ago",
  lesson_57: "https://framer-ai.com/lessons/8-framer-shortcuts-to-learn",
  cover_48: { src: "../../framerusercontent.com/images/OUavwpSjGPahtCg8MOjDdxnY7888ac.jpg?width=1920&height=1080", alt: "8 Framer shortcuts you’re probably sleeping on — lesson cover image" },
  level_57: "4:19",
  time_41: "4:19",
  lesson_58: "8 Framer shortcuts you’re probably sleeping on",
  level_58: "5 months ago",
  lesson_59: "https://framer-ai.com/lessons/adding-a-locale",
  cover_49: { src: "../../framerusercontent.com/images/iZ50rEYMQ6ILdYqQUvyjMSHif3gcd01.jpg?width=3840&height=2160", alt: "Adding a Locale in Framer — lesson cover image" },
  level_59: "5:18",
  time_42: "5:18",
  lesson_60: "Adding a Locale in Framer",
  level_60: "5 months ago",
  lesson_61: "https://framer-ai.com/lessons/polish-your-page-with-agents",
  cover_50: { src: "../../framerusercontent.com/images/n2mSpeAc3lUIRBNNURkTATSAo88ac.jpg?width=1920&amp;height=1080", alt: "" },
  level_61: "2:14",
  time_43: "2:14",
  lesson_62: "Polish your Pages with Agents",
  level_62: "2 months ago",
  lesson_63: "https://framer-ai.com/lessons/external-agents-with-framer",
  cover_51: { src: "../../framerusercontent.com/images/1nYmAWqWblGQJzl0GpbiAWbeyeI88ac.jpg?width=1920&amp;height=1080", alt: "Connect Framer to Claude Code, Codex, Cursor, and more — lesson cover image" },
  level_63: "7:13",
  time_44: "7:13",
  lesson_64: "Connect Framer to Claude Code, ChatGPT Codex, Cursor, and more",
  level_64: "3 months ago",
  lesson_65: "https://framer-ai.com/lessons/framer-agents-content-scale",
  cover_52: { src: "../../framerusercontent.com/images/uADiL603F0zh18Kr2kwpf71pkrAcd01.jpg?width=3840&amp;height=2160", alt: "Content, Components, and CMS with Framer Agents — lesson cover image" },
  level_65: "8:25",
  time_45: "8:25",
  lesson_66: "Content, Components, and CMS with Framer Agents",
  level_66: "3 months ago",
  lesson_67: "https://framer-ai.com/lessons/framer-agents-generation-layout-style",
  cover_53: { src: "../../framerusercontent.com/images/1QznpGq3xVnPPsG8DIOcQ72ytHQ88ac.jpg?width=1920&amp;height=1080", alt: "Generation, layout, and styling with Framer Agents — lesson cover image" },
  level_67: "15:13",
  time_46: "15:13",
  lesson_68: "Generation, layout, and styling with Framer Agents",
  level_68: "3 months ago",
  lesson_69: "https://framer-ai.com/lessons/8-framer-shortcuts-to-learn",
  cover_54: { src: "../../framerusercontent.com/images/OUavwpSjGPahtCg8MOjDdxnY7888ac.jpg?width=1920&amp;height=1080", alt: "8 Framer shortcuts you’re probably sleeping on — lesson cover image" },
  level_69: "4:19",
  time_47: "4:19",
  lesson_70: "8 Framer shortcuts you’re probably sleeping on",
  level_70: "5 months ago",
  lesson_71: "https://framer-ai.com/lessons/adding-a-locale",
  cover_55: { src: "../../framerusercontent.com/images/iZ50rEYMQ6ILdYqQUvyjMSHif3gcd01.jpg?width=3840&amp;height=2160", alt: "Adding a Locale in Framer — lesson cover image" },
  level_71: "5:18",
  time_48: "5:18",
  lesson_72: "Adding a Locale in Framer",
  level_72: "5 months ago",
  lesson_73: "https://framer-ai.com/lessons/polish-your-page-with-agents",
  cover_56: { src: "../../framerusercontent.com/images/n2mSpeAc3lUIRBNNURkTATSAo88ac.jpg?width=1920&amp;height=1080", alt: "" },
  level_73: "2:14",
  time_49: "2:14",
  lesson_74: "Polish your Pages with Agents",
  level_74: "2 months ago",
  lesson_75: "https://framer-ai.com/lessons/external-agents-with-framer",
  cover_57: { src: "../../framerusercontent.com/images/1nYmAWqWblGQJzl0GpbiAWbeyeI88ac.jpg?width=1920&amp;height=1080", alt: "Connect Framer to Claude Code, Codex, Cursor, and more — lesson cover image" },
  level_75: "7:13",
  time_50: "7:13",
  lesson_76: "Connect Framer to Claude Code, ChatGPT Codex, Cursor, and more",
  level_76: "3 months ago",
  lesson_77: "https://framer-ai.com/lessons/framer-agents-content-scale",
  cover_58: { src: "../../framerusercontent.com/images/uADiL603F0zh18Kr2kwpf71pkrAcd01.jpg?width=3840&amp;height=2160", alt: "Content, Components, and CMS with Framer Agents — lesson cover image" },
  level_77: "8:25",
  time_51: "8:25",
  lesson_78: "Content, Components, and CMS with Framer Agents",
  level_78: "3 months ago",
  lesson_79: "https://framer-ai.com/lessons/framer-agents-generation-layout-style",
  cover_59: { src: "../../framerusercontent.com/images/1QznpGq3xVnPPsG8DIOcQ72ytHQ88ac.jpg?width=1920&amp;height=1080", alt: "Generation, layout, and styling with Framer Agents — lesson cover image" },
  level_79: "15:13",
  time_52: "15:13",
  lesson_80: "Generation, layout, and styling with Framer Agents",
  level_80: "3 months ago",
  lesson_81: "https://framer-ai.com/lessons/8-framer-shortcuts-to-learn",
  cover_60: { src: "../../framerusercontent.com/images/OUavwpSjGPahtCg8MOjDdxnY7888ac.jpg?width=1920&amp;height=1080", alt: "8 Framer shortcuts you’re probably sleeping on — lesson cover image" },
  level_81: "4:19",
  time_53: "4:19",
  lesson_82: "8 Framer shortcuts you’re probably sleeping on",
  level_82: "5 months ago",
  lesson_83: "https://framer-ai.com/lessons/adding-a-locale",
  cover_61: { src: "../../framerusercontent.com/images/iZ50rEYMQ6ILdYqQUvyjMSHif3gcd01.jpg?width=3840&amp;height=2160", alt: "Adding a Locale in Framer — lesson cover image" },
  level_83: "5:18",
  time_54: "5:18",
  lesson_84: "Adding a Locale in Framer",
  level_84: "5 months ago",
  lesson_85: "https://framer-ai.com/lessons/polish-your-page-with-agents",
  cover_62: { src: "../../framerusercontent.com/images/n2mSpeAc3lUIRBNNURkTATSAo88ac.jpg?width=1920&amp;height=1080", alt: "" },
  level_85: "2:14",
  time_55: "2:14",
  lesson_86: "Polish your Pages with Agents",
  level_86: "2 months ago",
  lesson_87: "https://framer-ai.com/lessons/external-agents-with-framer",
  cover_63: { src: "../../framerusercontent.com/images/1nYmAWqWblGQJzl0GpbiAWbeyeI88ac.jpg?width=1920&amp;height=1080", alt: "Connect Framer to Claude Code, Codex, Cursor, and more — lesson cover image" },
  level_87: "7:13",
  time_56: "7:13",
  lesson_88: "Connect Framer to Claude Code, ChatGPT Codex, Cursor, and more",
  level_88: "3 months ago",
  lesson_89: "https://framer-ai.com/lessons/framer-agents-content-scale",
  cover_64: { src: "../../framerusercontent.com/images/uADiL603F0zh18Kr2kwpf71pkrAcd01.jpg?width=3840&amp;height=2160", alt: "Content, Components, and CMS with Framer Agents — lesson cover image" },
  level_89: "8:25",
  time_57: "8:25",
  lesson_90: "Content, Components, and CMS with Framer Agents",
  level_90: "3 months ago",
  lesson_91: "https://framer-ai.com/lessons/framer-agents-generation-layout-style",
  cover_65: { src: "../../framerusercontent.com/images/1QznpGq3xVnPPsG8DIOcQ72ytHQ88ac.jpg?width=1920&amp;height=1080", alt: "Generation, layout, and styling with Framer Agents — lesson cover image" },
  level_91: "15:13",
  time_58: "15:13",
  lesson_92: "Generation, layout, and styling with Framer Agents",
  level_92: "3 months ago",
  lesson_93: "https://framer-ai.com/lessons/8-framer-shortcuts-to-learn",
  cover_66: { src: "../../framerusercontent.com/images/OUavwpSjGPahtCg8MOjDdxnY7888ac.jpg?width=1920&amp;height=1080", alt: "8 Framer shortcuts you’re probably sleeping on — lesson cover image" },
  level_93: "4:19",
  time_59: "4:19",
  lesson_94: "8 Framer shortcuts you’re probably sleeping on",
  level_94: "5 months ago",
  lesson_95: "https://framer-ai.com/lessons/adding-a-locale",
  cover_67: { src: "../../framerusercontent.com/images/iZ50rEYMQ6ILdYqQUvyjMSHif3gcd01.jpg?width=3840&amp;height=2160", alt: "Adding a Locale in Framer — lesson cover image" },
  level_95: "5:18",
  time_60: "5:18",
  lesson_96: "Adding a Locale in Framer",
  level_96: "5 months ago",
  topic_3: { src: "/images/b8ac445b-6tTbkXggWgQCAJ4DO2QEdXXmgM.svg?arrow=left", alt: "Back Arrow" },
  topic_4: { src: "/images/69eb8cee-11KSGbIZoRSg4pjdnUoif6MKHI.svg?arrow=right", alt: "Next Arrow" },
  header_4: "Framer CMS basics",
  m_7: "https://framer-ai.com/courses/getting-started-with-framer-cms",
  m_8: "All",
  lesson_97: "https://framer-ai.com/lessons/what-is-framer-cms",
  cover_68: { src: "../../framerusercontent.com/images/UphjcGBD4kvkGA70prOoZUU0cd01.jpg?width=3840&height=2160", alt: "What is the Framer CMS? — lesson cover image" },
  level_97: "2:45",
  time_61: "2:45",
  lesson_98: "What is the Framer CMS?",
  level_98: "Last year",
  lesson_99: "https://framer-ai.com/lessons/understanding-cms-collections-items-fields",
  cover_69: { src: "../../framerusercontent.com/images/VHEU755QCJJ7iLn3TXc1GHOYccd01.jpg?width=3840&height=2160", alt: "CMS collections, items & fields — lesson cover image" },
  level_99: "5:51",
  time_62: "5:51",
  lesson_100: "CMS collections, items & fields",
  level_100: "Last year",
  lesson_101: "https://framer-ai.com/lessons/cms-pages-dynamic-content",
  cover_70: { src: "../../framerusercontent.com/images/21AQC7cWJGQBKUt51R7I86Umy0cd01.jpg?width=3840&height=2160", alt: "CMS pages & dynamic content in Framer — lesson cover image" },
  level_101: "8:31",
  time_63: "8:31",
  lesson_102: "CMS pages & dynamic content in Framer",
  level_102: "Last year",
  lesson_103: "https://framer-ai.com/lessons/creating-cms-collection-lists",
  cover_71: { src: "../../framerusercontent.com/images/H57AXwLd3wwdt1kFsvg5cM88cd01.jpg?width=3840&height=2160", alt: "Utilizing collection lists in Framer — lesson cover image" },
  level_103: "9:17",
  time_64: "9:17",
  lesson_104: "Utilizing collection lists in Framer",
  level_104: "Last year",
  lesson_105: "https://framer-ai.com/lessons/what-is-framer-cms",
  cover_72: { src: "../../framerusercontent.com/images/UphjcGBD4kvkGA70prOoZUU0cd01.jpg?width=3840&amp;height=2160", alt: "What is the Framer CMS? — lesson cover image" },
  level_105: "2:45",
  time_65: "2:45",
  lesson_106: "What is the Framer CMS?",
  level_106: "Last year",
  lesson_107: "https://framer-ai.com/lessons/understanding-cms-collections-items-fields",
  cover_73: { src: "../../framerusercontent.com/images/VHEU755QCJJ7iLn3TXc1GHOYccd01.jpg?width=3840&amp;height=2160", alt: "CMS collections, items & fields — lesson cover image" },
  level_107: "5:51",
  time_66: "5:51",
  lesson_108: "CMS collections, items & fields",
  level_108: "Last year",
  lesson_109: "https://framer-ai.com/lessons/cms-pages-dynamic-content",
  cover_74: { src: "../../framerusercontent.com/images/21AQC7cWJGQBKUt51R7I86Umy0cd01.jpg?width=3840&amp;height=2160", alt: "CMS pages & dynamic content in Framer — lesson cover image" },
  level_109: "8:31",
  time_67: "8:31",
  lesson_110: "CMS pages & dynamic content in Framer",
  level_110: "Last year",
  lesson_111: "https://framer-ai.com/lessons/creating-cms-collection-lists",
  cover_75: { src: "../../framerusercontent.com/images/H57AXwLd3wwdt1kFsvg5cM88cd01.jpg?width=3840&amp;height=2160", alt: "Utilizing collection lists in Framer — lesson cover image" },
  level_111: "9:17",
  time_68: "9:17",
  lesson_112: "Utilizing collection lists in Framer",
  level_112: "Last year",
  lesson_113: "https://framer-ai.com/lessons/what-is-framer-cms",
  cover_76: { src: "../../framerusercontent.com/images/UphjcGBD4kvkGA70prOoZUU0cd01.jpg?width=3840&amp;height=2160", alt: "What is the Framer CMS? — lesson cover image" },
  level_113: "2:45",
  time_69: "2:45",
  lesson_114: "What is the Framer CMS?",
  level_114: "Last year",
  lesson_115: "https://framer-ai.com/lessons/understanding-cms-collections-items-fields",
  cover_77: { src: "../../framerusercontent.com/images/VHEU755QCJJ7iLn3TXc1GHOYccd01.jpg?width=3840&amp;height=2160", alt: "CMS collections, items & fields — lesson cover image" },
  level_115: "5:51",
  time_70: "5:51",
  lesson_116: "CMS collections, items & fields",
  level_116: "Last year",
  lesson_117: "https://framer-ai.com/lessons/cms-pages-dynamic-content",
  cover_78: { src: "../../framerusercontent.com/images/21AQC7cWJGQBKUt51R7I86Umy0cd01.jpg?width=3840&amp;height=2160", alt: "CMS pages & dynamic content in Framer — lesson cover image" },
  level_117: "8:31",
  time_71: "8:31",
  lesson_118: "CMS pages & dynamic content in Framer",
  level_118: "Last year",
  lesson_119: "https://framer-ai.com/lessons/creating-cms-collection-lists",
  cover_79: { src: "../../framerusercontent.com/images/H57AXwLd3wwdt1kFsvg5cM88cd01.jpg?width=3840&amp;height=2160", alt: "Utilizing collection lists in Framer — lesson cover image" },
  level_119: "9:17",
  time_72: "9:17",
  lesson_120: "Utilizing collection lists in Framer",
  level_120: "Last year",
  lesson_121: "https://framer-ai.com/lessons/what-is-framer-cms",
  cover_80: { src: "../../framerusercontent.com/images/UphjcGBD4kvkGA70prOoZUU0cd01.jpg?width=3840&amp;height=2160", alt: "What is the Framer CMS? — lesson cover image" },
  level_121: "2:45",
  time_73: "2:45",
  lesson_122: "What is the Framer CMS?",
  level_122: "Last year",
  lesson_123: "https://framer-ai.com/lessons/understanding-cms-collections-items-fields",
  cover_81: { src: "../../framerusercontent.com/images/VHEU755QCJJ7iLn3TXc1GHOYccd01.jpg?width=3840&amp;height=2160", alt: "CMS collections, items & fields — lesson cover image" },
  level_123: "5:51",
  time_74: "5:51",
  lesson_124: "CMS collections, items & fields",
  level_124: "Last year",
  lesson_125: "https://framer-ai.com/lessons/cms-pages-dynamic-content",
  cover_82: { src: "../../framerusercontent.com/images/21AQC7cWJGQBKUt51R7I86Umy0cd01.jpg?width=3840&amp;height=2160", alt: "CMS pages & dynamic content in Framer — lesson cover image" },
  level_125: "8:31",
  time_75: "8:31",
  lesson_126: "CMS pages & dynamic content in Framer",
  level_126: "Last year",
  lesson_127: "https://framer-ai.com/lessons/creating-cms-collection-lists",
  cover_83: { src: "../../framerusercontent.com/images/H57AXwLd3wwdt1kFsvg5cM88cd01.jpg?width=3840&amp;height=2160", alt: "Utilizing collection lists in Framer — lesson cover image" },
  level_127: "9:17",
  time_76: "9:17",
  lesson_128: "Utilizing collection lists in Framer",
  level_128: "Last year",
  course_35: { src: "/images/b8ac445b-6tTbkXggWgQCAJ4DO2QEdXXmgM.svg?arrow=left", alt: "Back Arrow" },
  course_36: { src: "/images/69eb8cee-11KSGbIZoRSg4pjdnUoif6MKHI.svg?arrow=right", alt: "Next Arrow" },
  topic_5: "Animations and interactions",
  m_9: "https://framer-ai.com/lessons88a8.html?topics=animations",
  m_10: "All",
  lesson_129: "https://framer-ai.com/lessons/building-an-expanding-article-stack",
  cover_84: { src: "../../framerusercontent.com/images/eOsXF8S3TB2Q1VdkomGBKSaPYko88ac.jpg?width=1920&height=1080", alt: "Building an Expanding Article Stack — lesson cover image" },
  level_129: "13:14",
  time_77: "13:14",
  lesson_130: "Building an Expanding Article Stack",
  level_130: "8 months ago",
  lesson_131: "https://framer-ai.com/lessons/scaling-a-clipped-image-on-hover-in-framer",
  cover_85: { src: "../../framerusercontent.com/images/NSptEJT3P2muf3RPx2wwcia46Y88ac.jpg?width=1920&height=1080", alt: "Scaling a clipped image on hover — lesson cover image" },
  level_131: "5:41",
  time_78: "5:41",
  lesson_132: "Scaling a clipped image on hover",
  level_132: "8 months ago",
  lesson_133: "https://framer-ai.com/lessons/making-elements-revolve",
  cover_86: { src: "../../framerusercontent.com/images/6LcW7oGyPhiZiHVcoP9NjQssR488ac.jpg?width=1920&height=1080", alt: "Making elements revolve in Framer — lesson cover image" },
  level_133: "3:37",
  time_79: "3:37",
  lesson_134: "Making elements revolve in Framer",
  level_134: "8 months ago",
  lesson_135: "https://framer-ai.com/lessons/triggering-video-playback-on-scroll",
  cover_87: { src: "../../framerusercontent.com/images/GS8o1T2heMg1Cx9fNZocnAEwqlAcd01.jpg?width=3840&height=2160", alt: "Triggering video playback on scroll in Framer — lesson cover image" },
  level_135: "3:45",
  time_80: "3:45",
  lesson_136: "Triggering video playback on scroll in Framer",
  level_136: "9 months ago",
  lesson_137: "https://framer-ai.com/lessons/framer-animations-vector-effects",
  cover_88: { src: "../../framerusercontent.com/images/i0MSNHOm9khO8stnx9cOJkbJk88ac.jpg?width=1920&height=1080", alt: "Animating vector paths in Framer — lesson cover image" },
  level_137: "14:36",
  time_81: "14:36",
  lesson_138: "Animating vector paths in Framer",
  level_138: "11 months ago",
  lesson_139: "https://framer-ai.com/lessons/get-the-most-out-of-framer-for-free",
  cover_89: { src: "../../framerusercontent.com/images/tWHpGCLHZiZa9xjm2hCPCg2lRHM88ac.png?width=1920&height=1080", alt: "How to get the most out of Framer for Free — lesson cover image" },
  level_139: "4:05",
  time_82: "4:05",
  lesson_140: "How to get the most out of Framer for Free",
  level_140: "11 months ago",
  lesson_141: "https://framer-ai.com/lessons/building-an-expanding-article-stack",
  cover_90: { src: "../../framerusercontent.com/images/eOsXF8S3TB2Q1VdkomGBKSaPYko88ac.jpg?width=1920&amp;height=1080", alt: "Building an Expanding Article Stack — lesson cover image" },
  level_141: "13:14",
  time_83: "13:14",
  lesson_142: "Building an Expanding Article Stack",
  level_142: "8 months ago",
  lesson_143: "https://framer-ai.com/lessons/scaling-a-clipped-image-on-hover-in-framer",
  cover_91: { src: "../../framerusercontent.com/images/NSptEJT3P2muf3RPx2wwcia46Y88ac.jpg?width=1920&amp;height=1080", alt: "Scaling a clipped image on hover — lesson cover image" },
  level_143: "5:41",
  time_84: "5:41",
  lesson_144: "Scaling a clipped image on hover",
  level_144: "8 months ago",
  lesson_145: "https://framer-ai.com/lessons/making-elements-revolve",
  cover_92: { src: "../../framerusercontent.com/images/6LcW7oGyPhiZiHVcoP9NjQssR488ac.jpg?width=1920&amp;height=1080", alt: "Making elements revolve in Framer — lesson cover image" },
  level_145: "3:37",
  time_85: "3:37",
  lesson_146: "Making elements revolve in Framer",
  level_146: "8 months ago",
  lesson_147: "https://framer-ai.com/lessons/triggering-video-playback-on-scroll",
  cover_93: { src: "../../framerusercontent.com/images/GS8o1T2heMg1Cx9fNZocnAEwqlAcd01.jpg?width=3840&amp;height=2160", alt: "Triggering video playback on scroll in Framer — lesson cover image" },
  level_147: "3:45",
  time_86: "3:45",
  lesson_148: "Triggering video playback on scroll in Framer",
  level_148: "9 months ago",
  lesson_149: "https://framer-ai.com/lessons/framer-animations-vector-effects",
  cover_94: { src: "../../framerusercontent.com/images/i0MSNHOm9khO8stnx9cOJkbJk88ac.jpg?width=1920&amp;height=1080", alt: "Animating vector paths in Framer — lesson cover image" },
  level_149: "14:36",
  time_87: "14:36",
  lesson_150: "Animating vector paths in Framer",
  level_150: "11 months ago",
  lesson_151: "https://framer-ai.com/lessons/get-the-most-out-of-framer-for-free",
  cover_95: { src: "../../framerusercontent.com/images/tWHpGCLHZiZa9xjm2hCPCg2lRHM88ac.png?width=1920&amp;height=1080", alt: "How to get the most out of Framer for Free — lesson cover image" },
  level_151: "4:05",
  time_88: "4:05",
  lesson_152: "How to get the most out of Framer for Free",
  level_152: "11 months ago",
  lesson_153: "https://framer-ai.com/lessons/building-an-expanding-article-stack",
  cover_96: { src: "../../framerusercontent.com/images/eOsXF8S3TB2Q1VdkomGBKSaPYko88ac.jpg?width=1920&amp;height=1080", alt: "Building an Expanding Article Stack — lesson cover image" },
  level_153: "13:14",
  time_89: "13:14",
  lesson_154: "Building an Expanding Article Stack",
  level_154: "8 months ago",
  lesson_155: "https://framer-ai.com/lessons/scaling-a-clipped-image-on-hover-in-framer",
  cover_97: { src: "../../framerusercontent.com/images/NSptEJT3P2muf3RPx2wwcia46Y88ac.jpg?width=1920&amp;height=1080", alt: "Scaling a clipped image on hover — lesson cover image" },
  level_155: "5:41",
  time_90: "5:41",
  lesson_156: "Scaling a clipped image on hover",
  level_156: "8 months ago",
  lesson_157: "https://framer-ai.com/lessons/making-elements-revolve",
  cover_98: { src: "../../framerusercontent.com/images/6LcW7oGyPhiZiHVcoP9NjQssR488ac.jpg?width=1920&amp;height=1080", alt: "Making elements revolve in Framer — lesson cover image" },
  level_157: "3:37",
  time_91: "3:37",
  lesson_158: "Making elements revolve in Framer",
  level_158: "8 months ago",
  lesson_159: "https://framer-ai.com/lessons/triggering-video-playback-on-scroll",
  cover_99: { src: "../../framerusercontent.com/images/GS8o1T2heMg1Cx9fNZocnAEwqlAcd01.jpg?width=3840&amp;height=2160", alt: "Triggering video playback on scroll in Framer — lesson cover image" },
  level_159: "3:45",
  time_92: "3:45",
  lesson_160: "Triggering video playback on scroll in Framer",
  level_160: "9 months ago",
  lesson_161: "https://framer-ai.com/lessons/framer-animations-vector-effects",
  cover_100: { src: "../../framerusercontent.com/images/i0MSNHOm9khO8stnx9cOJkbJk88ac.jpg?width=1920&amp;height=1080", alt: "Animating vector paths in Framer — lesson cover image" },
  level_161: "14:36",
  time_93: "14:36",
  lesson_162: "Animating vector paths in Framer",
  level_162: "11 months ago",
  lesson_163: "https://framer-ai.com/lessons/get-the-most-out-of-framer-for-free",
  cover_101: { src: "../../framerusercontent.com/images/tWHpGCLHZiZa9xjm2hCPCg2lRHM88ac.png?width=1920&amp;height=1080", alt: "How to get the most out of Framer for Free — lesson cover image" },
  level_163: "4:05",
  time_94: "4:05",
  lesson_164: "How to get the most out of Framer for Free",
  level_164: "11 months ago",
  lesson_165: "https://framer-ai.com/lessons/building-an-expanding-article-stack",
  cover_102: { src: "../../framerusercontent.com/images/eOsXF8S3TB2Q1VdkomGBKSaPYko88ac.jpg?width=1920&amp;height=1080", alt: "Building an Expanding Article Stack — lesson cover image" },
  level_165: "13:14",
  time_95: "13:14",
  lesson_166: "Building an Expanding Article Stack",
  level_166: "8 months ago",
  lesson_167: "https://framer-ai.com/lessons/scaling-a-clipped-image-on-hover-in-framer",
  cover_103: { src: "../../framerusercontent.com/images/NSptEJT3P2muf3RPx2wwcia46Y88ac.jpg?width=1920&amp;height=1080", alt: "Scaling a clipped image on hover — lesson cover image" },
  level_167: "5:41",
  time_96: "5:41",
  lesson_168: "Scaling a clipped image on hover",
  level_168: "8 months ago",
  lesson_169: "https://framer-ai.com/lessons/making-elements-revolve",
  cover_104: { src: "../../framerusercontent.com/images/6LcW7oGyPhiZiHVcoP9NjQssR488ac.jpg?width=1920&amp;height=1080", alt: "Making elements revolve in Framer — lesson cover image" },
  level_169: "3:37",
  time_97: "3:37",
  lesson_170: "Making elements revolve in Framer",
  level_170: "8 months ago",
  lesson_171: "https://framer-ai.com/lessons/triggering-video-playback-on-scroll",
  cover_105: { src: "../../framerusercontent.com/images/GS8o1T2heMg1Cx9fNZocnAEwqlAcd01.jpg?width=3840&amp;height=2160", alt: "Triggering video playback on scroll in Framer — lesson cover image" },
  level_171: "3:45",
  time_98: "3:45",
  lesson_172: "Triggering video playback on scroll in Framer",
  level_172: "9 months ago",
  lesson_173: "https://framer-ai.com/lessons/framer-animations-vector-effects",
  cover_106: { src: "../../framerusercontent.com/images/i0MSNHOm9khO8stnx9cOJkbJk88ac.jpg?width=1920&amp;height=1080", alt: "Animating vector paths in Framer — lesson cover image" },
  level_173: "14:36",
  time_99: "14:36",
  lesson_174: "Animating vector paths in Framer",
  level_174: "11 months ago",
  lesson_175: "https://framer-ai.com/lessons/get-the-most-out-of-framer-for-free",
  cover_107: { src: "../../framerusercontent.com/images/tWHpGCLHZiZa9xjm2hCPCg2lRHM88ac.png?width=1920&amp;height=1080", alt: "How to get the most out of Framer for Free — lesson cover image" },
  level_175: "4:05",
  time_100: "4:05",
  lesson_176: "How to get the most out of Framer for Free",
  level_176: "11 months ago",
  topic_6: { src: "/images/b8ac445b-6tTbkXggWgQCAJ4DO2QEdXXmgM.svg?arrow=left", alt: "Back Arrow" },
  topic_7: { src: "/images/69eb8cee-11KSGbIZoRSg4pjdnUoif6MKHI.svg?arrow=right", alt: "Next Arrow" },
  header_5: "Topics",
  topic_8: "https://framer-ai.com/topics/agents",
  title: "Agents",
  shortTitle: "4 videos",
  topic_9: "https://framer-ai.com/topics/ai",
  title_2: "AI",
  shortTitle_2: "3 videos",
  topic_10: "https://framer-ai.com/topics/analytics",
  title_3: "Analytics",
  shortTitle_3: "3 videos",
  topic_11: "https://framer-ai.com/topics/animations",
  title_4: "Animations",
  shortTitle_4: "35 videos",
  topic_12: "https://framer-ai.com/topics/cms",
  title_5: "CMS",
  shortTitle_5: "13 videos",
  topic_13: "https://framer-ai.com/topics/forms",
  title_6: "Forms",
  shortTitle_6: "6 videos",
  topic_14: "https://framer-ai.com/topics/insert",
  title_7: "Insert Menu",
  shortTitle_7: "6 videos",
  topic_15: "https://framer-ai.com/topics/design",
  title_8: "Layout & Design",
  shortTitle_8: "63 videos",
  topic_16: "https://framer-ai.com/topics/localization",
  title_9: "Localization",
  shortTitle_9: "5 videos",
  topic_17: "https://framer-ai.com/topics/navigation",
  title_10: "Navigation",
  shortTitle_10: "9 videos",
  topic_18: "https://framer-ai.com/topics/plugins",
  title_11: "Plugins",
  shortTitle_11: "3 videos",
  topic_19: "https://framer-ai.com/topics/management",
  title_12: "Publishing & Settings",
  shortTitle_12: "25 videos",
  topic_20: "https://framer-ai.com/topics/quick-tips",
  title_13: "Quick Tips",
  shortTitle_13: "3 videos",
  topic_21: "https://framer-ai.com/topics/scroll",
  title_14: "Scroll",
  shortTitle_14: "6 videos",
  topic_22: "https://framer-ai.com/topics/seo",
  title_15: "SEO",
  shortTitle_15: "11 videos",
  topic_23: "https://framer-ai.com/topics/templates",
  title_16: "Templates",
  shortTitle_16: "4 videos",
  header_6: "New in Framer",
  lesson_177: "https://framer-ai.com/updates/plugins-4-1",
  cover_108: { src: "../../framerusercontent.com/images/WuTpw3eBRPBx1SORN18I6NaUVXMc483.png?lossless=1&width=1600&height=900", alt: "Plugin 4.1 APIs" },
  lesson_178: "Branching and Publishing APIs",
  level_177: "4 weeks ago",
  lesson_179: "https://framer-ai.com/updates/july-update-2026",
  cover_109: { src: "../../framerusercontent.com/images/716xCbEmLLLfO0hTsGANX654WQc483.png?lossless=1&width=1600&height=900", alt: "July Update of Agents in Framer 2026" },
  lesson_180: "July Update",
  level_178: "2 months ago",
  lesson_181: "https://framer-ai.com/updates/opus-5",
  cover_110: { src: "../../framerusercontent.com/images/ozXmc7h48m9fsnnUvGhcMU42Lcc483.png?lossless=1&width=1600&height=900", alt: "Opus 5 update cover image showing the new AI model announcement in Framer" },
  lesson_182: "Opus 5",
  level_179: "2 months ago",
  lesson_183: "https://framer-ai.com/updates/agent-credit-usage",
  cover_111: { src: "../../framerusercontent.com/images/pjmpROSmNAIg08DgIgRQd0Ppvg84b8f.png?width=900&height=900", alt: "" },
  lesson_184: "Agents Efficiency",
  level_180: "2 months ago",
  lesson_185: "https://framer-ai.com/updates/interactive-shaders-liquid-logo",
  cover_112: { src: "../../framerusercontent.com/images/Fn3HcGoFEhUJRWVzSss20R5YpyIda33.png?width=1600&height=900", alt: "" },
  lesson_186: "Interactive Shaders: Liquid Gradient & Logo Gradient",
  level_181: "2 months ago",
  lesson_187: "https://framer-ai.com/updates/cms-3",
  cover_113: { src: "../../framerusercontent.com/images/k6xCc1VeBDGJTeind5JgrukG53kda33.png?width=1600&height=900", alt: "" },
  lesson_188: "CMS Update: Quickly Add Items",
  level_182: "2 months ago",
  lesson_189: "https://framer-ai.com/updates/plugins-4-1",
  cover_114: { src: "../../framerusercontent.com/images/WuTpw3eBRPBx1SORN18I6NaUVXMc483.png?lossless=1&amp;width=1600&amp;height=900", alt: "Plugin 4.1 APIs" },
  lesson_190: "Branching and Publishing APIs",
  level_183: "4 weeks ago",
  lesson_191: "https://framer-ai.com/updates/july-update-2026",
  cover_115: { src: "../../framerusercontent.com/images/716xCbEmLLLfO0hTsGANX654WQc483.png?lossless=1&amp;width=1600&amp;height=900", alt: "July Update of Agents in Framer 2026" },
  lesson_192: "July Update",
  level_184: "2 months ago",
  lesson_193: "https://framer-ai.com/updates/opus-5",
  cover_116: { src: "../../framerusercontent.com/images/ozXmc7h48m9fsnnUvGhcMU42Lcc483.png?lossless=1&amp;width=1600&amp;height=900", alt: "Opus 5 update cover image showing the new AI model announcement in Framer" },
  lesson_194: "Opus 5",
  level_185: "2 months ago",
  lesson_195: "https://framer-ai.com/updates/agent-credit-usage",
  cover_117: { src: "../../framerusercontent.com/images/pjmpROSmNAIg08DgIgRQd0Ppvg84b8f.png?width=900&amp;height=900", alt: "" },
  lesson_196: "Agents Efficiency",
  level_186: "2 months ago",
  lesson_197: "https://framer-ai.com/updates/interactive-shaders-liquid-logo",
  cover_118: { src: "../../framerusercontent.com/images/Fn3HcGoFEhUJRWVzSss20R5YpyIda33.png?width=1600&amp;height=900", alt: "" },
  lesson_198: "Interactive Shaders: Liquid Gradient & Logo Gradient",
  level_187: "2 months ago",
  lesson_199: "https://framer-ai.com/updates/cms-3.1",
  cover_119: { src: "../../framerusercontent.com/images/k6xCc1VeBDGJTeind5JgrukG53kda33.png?width=1600&amp;height=900", alt: "" },
  lesson_200: "CMS Update: Quickly Add Items",
  level_188: "2 months ago",
  lesson_201: "https://framer-ai.com/updates/plugins-4-1",
  cover_120: { src: "../../framerusercontent.com/images/WuTpw3eBRPBx1SORN18I6NaUVXMc483.png?lossless=1&amp;width=1600&amp;height=900", alt: "Plugin 4.1 APIs" },
  lesson_202: "Branching and Publishing APIs",
  level_189: "4 weeks ago",
  lesson_203: "https://framer-ai.com/updates/july-update-2026",
  cover_121: { src: "../../framerusercontent.com/images/716xCbEmLLLfO0hTsGANX654WQc483.png?lossless=1&amp;width=1600&amp;height=900", alt: "July Update of Agents in Framer 2026" },
  lesson_204: "July Update",
  level_190: "2 months ago",
  lesson_205: "https://framer-ai.com/updates/opus-5",
  cover_122: { src: "../../framerusercontent.com/images/ozXmc7h48m9fsnnUvGhcMU42Lcc483.png?lossless=1&amp;width=1600&amp;height=900", alt: "Opus 5 update cover image showing the new AI model announcement in Framer" },
  lesson_206: "Opus 5",
  level_191: "2 months ago",
  lesson_207: "https://framer-ai.com/updates/agent-credit-usage",
  cover_123: { src: "../../framerusercontent.com/images/pjmpROSmNAIg08DgIgRQd0Ppvg84b8f.png?width=900&amp;height=900", alt: "" },
  lesson_208: "Agents Efficiency",
  level_192: "2 months ago",
  lesson_209: "https://framer-ai.com/updates/interactive-shaders-liquid-logo",
  cover_124: { src: "../../framerusercontent.com/images/Fn3HcGoFEhUJRWVzSss20R5YpyIda33.png?width=1600&amp;height=900", alt: "" },
  lesson_210: "Interactive Shaders: Liquid Gradient & Logo Gradient",
  level_193: "2 months ago",
  lesson_211: "https://framer-ai.com/updates/cms-3.1",
  cover_125: { src: "../../framerusercontent.com/images/k6xCc1VeBDGJTeind5JgrukG53kda33.png?width=1600&amp;height=900", alt: "" },
  lesson_212: "CMS Update: Quickly Add Items",
  level_194: "2 months ago",
  lesson_213: "https://framer-ai.com/updates/plugins-4-1",
  cover_126: { src: "../../framerusercontent.com/images/WuTpw3eBRPBx1SORN18I6NaUVXMc483.png?lossless=1&amp;width=1600&amp;height=900", alt: "Plugin 4.1 APIs" },
  lesson_214: "Branching and Publishing APIs",
  level_195: "4 weeks ago",
  lesson_215: "https://framer-ai.com/updates/july-update-2026",
  cover_127: { src: "../../framerusercontent.com/images/716xCbEmLLLfO0hTsGANX654WQc483.png?lossless=1&amp;width=1600&amp;height=900", alt: "July Update of Agents in Framer 2026" },
  lesson_216: "July Update",
  level_196: "2 months ago",
  lesson_217: "https://framer-ai.com/updates/opus-5",
  cover_128: { src: "../../framerusercontent.com/images/ozXmc7h48m9fsnnUvGhcMU42Lcc483.png?lossless=1&amp;width=1600&amp;height=900", alt: "Opus 5 update cover image showing the new AI model announcement in Framer" },
  lesson_218: "Opus 5",
  level_197: "2 months ago",
  lesson_219: "https://framer-ai.com/updates/agent-credit-usage",
  cover_129: { src: "../../framerusercontent.com/images/pjmpROSmNAIg08DgIgRQd0Ppvg84b8f.png?width=900&amp;height=900", alt: "" },
  lesson_220: "Agents Efficiency",
  level_198: "2 months ago",
  lesson_221: "https://framer-ai.com/updates/interactive-shaders-liquid-logo",
  cover_130: { src: "../../framerusercontent.com/images/Fn3HcGoFEhUJRWVzSss20R5YpyIda33.png?width=1600&amp;height=900", alt: "" },
  lesson_222: "Interactive Shaders: Liquid Gradient & Logo Gradient",
  level_199: "2 months ago",
  lesson_223: "https://framer-ai.com/updates/cms-3.1",
  cover_131: { src: "../../framerusercontent.com/images/k6xCc1VeBDGJTeind5JgrukG53kda33.png?width=1600&amp;height=900", alt: "" },
  lesson_224: "CMS Update: Quickly Add Items",
  level_200: "2 months ago",
  topic_24: { src: "/images/b8ac445b-6tTbkXggWgQCAJ4DO2QEdXXmgM.svg?arrow=left", alt: "Back Arrow" },
  topic_25: { src: "/images/69eb8cee-11KSGbIZoRSg4pjdnUoif6MKHI.svg?arrow=right", alt: "Next Arrow" },
};
