// content for the "Desktop" section — extracted by extract-site.
// Edit values here to re-skin the "Desktop" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  on: "/",
  on_2: "Framer",
  item: "Product",
  label: "/ai",
  item_2: "AI",
  small: "New",
  label_2: "/agents",
  item_3: "Agents",
  small_2: "New",
  label_3: "https://framer-ai.com/agents/external",
  item_4: "External Agents",
  small_3: "New",
  label_4: "/design",
  item_5: "Design",
  label_5: "/collaborate",
  item_6: "Collaborate",
  small_4: "New",
  label_6: "/cms",
  item_7: "CMS",
  label_7: "/hosting",
  item_8: "Hosting",
  label_8: "/performance",
  item_9: "Performance",
  label_9: "/seo",
  item_10: "SEO",
  label_10: "https://framer-ai.com/convert",
  item_11: "Convert",
  label_11: "/publish",
  item_12: "Publish",
  label_12: "https://framer-ai.com/updates",
  item_13: "Updates",
  small_5: "New",
  item_14: "Resources",
  label_13: "/",
  item_15: "Academy",
  label_14: "https://framer-ai.com/guides",
  item_16: "Guides",
  label_15: "https://framer-ai.com/downloads",
  item_17: "Desktop app",
  label_16: "https://framer-ai.com/blog",
  item_18: "Blog",
  label_17: "https://framer-ai.com/newsletter",
  item_19: "Newsletter",
  label_18: "/stories",
  item_20: "Stories",
  label_19: "https://framer-ai.com/developers",
  item_21: "Developers",
  label_20: "https://framer-ai.com/creators",
  item_22: "Creators",
  label_21: "https://framer-ai.com/expert/apply",
  item_23: "Experts",
  label_22: "https://framer-ai.com/education/students",
  item_24: "Students",
  label_23: "https://framer-ai.com/education/ambassadors",
  item_25: "Ambassadors",
  label_24: "https://framer-ai.com/state-of-sites-2026",
  item_26: "State of Sites",
  label_25: "https://framer-ai.com/help",
  item_27: "Help Articles",
  label_26: "https://framer-ai.com/contact",
  item_28: "Contact",
  item_29: "Business",
  label_27: "https://framer-ai.com/pricing",
  item_30: "Pricing",
  label_28: "/enterprise",
  item_31: "Enterprise",
  label_29: "https://framer-ai.com/startups",
  item_32: "Startups",
  label_30: "https://framer-ai.com/agencies",
  item_33: "Agencies",
  label_31: "https://framer-ai.com/switch",
  item_34: "Switch",
  item_35: "Company",
  label_32: "https://framer-ai.com/careers",
  item_36: "Careers",
  label_33: "https://framer-ai.com/brand",
  item_37: "Brand",
  label_34: "https://framer-ai.com/store",
  item_38: "Store",
  label_35: "https://framer-ai.com/legal/security",
  item_39: "Security",
  label_36: "mailto:abuse@framer.com",
  item_40: "Abuse",
  label_37: "https://framer-ai.com/legal/community-terms",
  item_41: "Legal",
  label_38: "https://app.eu.vanta.com/framer.com/trust/ow67ujg7iav0t6qtd1o6r2",
  item_42: "Trust",
  item_43: "Solutions",
  label_39: "/solutions/designers",
  item_44: "Designers",
  label_40: "https://framer-ai.com/solutions/agencies",
  item_45: "Agencies",
  label_41: "https://framer-ai.com/solutions/marketers",
  item_46: "Marketers",
  label_42: "https://framer-ai.com/solutions/growth",
  item_47: "Growth",
  label_43: "https://framer-ai.com/solutions/builders",
  item_48: "Builders",
  label_44: "https://framer-ai.com/solutions/engineers",
  item_49: "Engineers",
  label_45: "https://framer-ai.com/solutions/site-teams",
  item_50: "Site Teams",
  label_46: "https://framer-ai.com/solutions/founders",
  item_51: "Founders",
  label_47: "https://framer-ai.com/solutions/ai-website-builder",
  item_52: "AI website builder",
  label_48: "https://framer-ai.com/solutions/ai-designer",
  item_53: "AI design agent",
  label_49: "https://framer-ai.com/solutions/website-builder",
  item_54: "Website builder",
  label_50: "https://framer-ai.com/solutions/landing-pages",
  item_55: "Landing pages",
  label_51: "https://framer-ai.com/solutions/portfolio-website",
  item_56: "Portfolio maker",
  label_52: "https://framer-ai.com/solutions/ui-ux-design",
  item_57: "UI/UX design",
  label_53: "https://framer-ai.com/solutions/no-code-website-builder",
  item_58: "No-code",
  item_59: "Compare",
  label_54: "https://framer-ai.com/compare",
  item_60: "Overview",
  label_55: "https://framer-ai.com/compare/framer-vs-webflow",
  item_61: "Webflow",
  label_56: "https://framer-ai.com/compare/framer-vs-figma",
  item_62: "Figma",
  label_57: "https://framer-ai.com/compare/framer-vs-wix",
  item_63: "Wix",
  label_58: "https://framer-ai.com/compare/framer-vs-squarespace",
  item_64: "Squarespace",
  label_59: "https://framer-ai.com/compare/framer-vs-wordpress",
  item_65: "WordPress",
  label_60: "https://framer-ai.com/compare/framer-vs-readymag",
  item_66: "Readymag",
  label_61: "https://framer-ai.com/compare/framer-vs-ceros",
  item_67: "Ceros",
  label_62: "https://framer-ai.com/compare/framer-vs-unbounce",
  item_68: "Unbounce",
  label_63: "https://framer-ai.com/compare/framer-vs-lovable",
  item_69: "Lovable",
  label_64: "https://framer-ai.com/compare/framer-vs-claude-code",
  item_70: "Claude Code",
  label_65: "https://framer-ai.com/compare/framer-vs-chatgpt",
  item_71: "ChatGPT",
  label_66: "https://framer-ai.com/compare/framer-vs-codex",
  item_72: "Codex",
  label_67: "https://framer-ai.com/compare/framer-vs-contentful",
  item_73: "Contentful",
  label_68: "https://framer-ai.com/compare/framer-vs-sanity",
  item_74: "Sanity",
  label_69: "https://framer-ai.com/compare/framer-vs-adobe-experience-manager",
  item_75: "AEM",
  label_70: "https://framer-ai.com/compare/framer-vs-replit",
  item_76: "Replit",
  item_77: "Community",
  label_71: "https://framer-ai.com/community/marketplace",
  item_78: "Marketplace",
  label_72: "https://framer-ai.com/community/marketplace/templates",
  item_79: "Templates",
  label_73: "https://framer-ai.com/community/marketplace/components",
  item_80: "Components",
  label_74: "https://framer-ai.com/community/marketplace/plugins",
  item_81: "Plugins",
  label_75: "https://framer-ai.com/community/marketplace/vectors",
  item_82: "Vectors",
  label_76: "https://framer-ai.com/community/feed",
  item_83: "Feed",
  label_77: "https://framer-ai.com/community/hype",
  item_84: "Hype",
  label_78: "https://framer-ai.com/community/gallery",
  item_85: "Gallery",
  label_79: "https://framer-ai.com/community/contests",
  item_86: "Contests",
  label_80: "https://framer-ai.com/community/members",
  item_87: "Members",
  label_81: "https://framer-ai.com/meetups",
  item_88: "Meetups",
  label_82: "https://framer-ai.com/updates/community",
  item_89: "Updates",
  item_90: "Tools",
  label_83: "https://framer-ai.com/solutions/figma-to-html",
  item_91: "Figma to HTML",
  label_84: "https://framer-ai.com/aeo",
  item_92: "AEO scanner",
  label_85: "https://www.linkpreview.app/",
  item_93: "Meta Tags",
  label_86: "https://framer-ai.com/domains",
  item_94: "Free domains",
  label_87: "https://framer-ai.com/canvasbench",
  item_95: "CanvasBench",
  label_88: "https://framer-ai.com/shortcuts",
  item_96: "Shortcuts",
  footerBar: "Follow us",
  x: "https://x.com/framer",
  youtube: "https://www.youtube.com/@Framer",
  instagram: "https://www.instagram.com/framer/",
  linkedin: "https://www.linkedin.com/company/framer/",
  threads: "https://www.threads.com/@framer",
  trustedByText: "Trusted by",
  trustIcons: "https://app.eu.vanta.com/framer.com/trust/ow67ujg7iav0t6qtd1o6r2",
  layerTitle: "CCPA",
  loading: "https://www.framerstatus.com/",
  item_97: "Checking status",
  footerBar_2: "https://openrouter.ai/apps/framer",
  footerBar_3: "349B",
  update: "tokens processed this week",
  variant1: "2026",
  variant1_2: "Framer",
};
