// AEO.tsx — section converted to a real JSX component by extract-site.
// Editable React: entrance animations are inline framer-motion props with the
// MEASURED timing from the original site; hover effects live in hover.css.
// Copy, photos, and links live in the sibling content module — edit there to
// re-skin this section without touching layout/motion.
import type { CSSProperties } from "react";
import { motion } from "framer-motion";
import content from "../content/06-AEO";

export function AEO() {
  return (
    <div className="framer-xbwelo" data-framer-name="AEO" id="top" style={{ width: "1440px", height: "920.797px", padding: "120px 20px", position: "relative", zIndex: "1", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "40px" } as CSSProperties}>
      <div className="framer-1ywnqlr" data-framer-name="Hero Intro" style={{ width: "1200px", height: "96.7969px", maxWidth: "1200px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "flex-end", alignContent: "flex-end", gap: "20px" } as CSSProperties}>
        <div className="framer-h5oit5" style={{ width: "1061.36px", height: "96.7969px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", gap: "20px" } as CSSProperties}>
          <div className="framer-59rbfm" data-framer-component-type="RichTextContainer" style={{ width: "285px", height: "96.7969px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", transform: "none" } as CSSProperties}>
            <h2 className="framer-text framer-styles-preset-fbtpvo" data-styles-preset="qRN7MgZKk" dir="auto" style={{ width: "285px", height: "96.7969px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"GT Walsheim Medium\", \"GT Walsheim Medium Placeholder\", sans-serif", fontSize: "44px", fontWeight: "500", lineHeight: "48.4px", letterSpacing: "-1.76px", textAlign: "left", color: "rgb(255, 255, 255)", "--framer-text-alignment": "left" } as CSSProperties}>
              {content.heroIntro}
            </h2>
          </div>
        </div>
        <div className="ssr-variant hidden-y2u6ev" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
          <div className="framer-1rer7ns-container" data-framer-name="Button" style={{ width: "118.641px", height: "34px", position: "relative", zIndex: "1", display: "block", flexDirection: "row" } as CSSProperties}>
            <a className="framer-k8Dz4 framer-qkzqfa framer-v-qkzqfa framer-lt5xhr" data-framer-name="Regular" data-highlight="true" data-reset="button" tabIndex={0} style={{ width: "118.641px", height: "34px", maxHeight: "35px", padding: "10px 14px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "7px", backgroundColor: "rgb(255, 255, 255)", borderRadius: "8px", color: "rgb(0, 0, 238)", borderBottomLeftRadius: "8px", borderBottomRightRadius: "8px", borderTopLeftRadius: "8px", borderTopRightRadius: "8px", boxShadow: "var(--9xgf7k)", opacity: "1" } as CSSProperties} data-external-route="1" href={content.regular}>
              <div className="framer-o5mers" data-framer-name="Label" data-framer-component-type="RichTextContainer" style={{ width: "90.6406px", height: "14px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 18, \"wght\" 540", "--extracted-r6o4lv": "var(--variable-reference-xdxfhd9wh-KsxdqjKwX)", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", "--variable-reference-rm8thjdvn-ksxdqjkwx": "14", "--variable-reference-xdxfhd9wh-ksxdqjkwx": "rgb(0, 0, 0)", opacity: "1", transform: "none" } as CSSProperties}>
                <p dir="auto" className="framer-text" style={{ width: "90.6406px", height: "14px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "14px", lineHeight: "14px", letterSpacing: "-0.28px", textAlign: "center", color: "rgb(0, 0, 0)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTRMQ0FpZDJkb2RDSWdOVFF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on", "--framer-font-size": "calc(var(--variable-reference-rm8ThjdVN-KsxdqjKwX) * 1px)", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 18, \"wght\" 540)", "--framer-letter-spacing": "-0.02em", "--framer-line-height": "1em", "--framer-text-alignment": "center", "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-xdxfhd9wh-KsxdqjKwX))" } as CSSProperties}>
                  {content.label}
                </p>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div className="framer-a50z8l" data-border="true" data-framer-name="Hero Container" style={{ width: "1200px", height: "544px", maxWidth: "1200px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", borderRadius: "25px", overflow: "clip" } as CSSProperties}>
        <div className="framer-1jty206 hv-1603" data-framer-name="Hero Table Body" style={{ width: "1200px", height: "544px", position: "relative", display: "grid", flexDirection: "row", justifyContent: "center", gridTemplateColumns: "300px 300px 300px 300px", gridTemplateRows: "272px 272px", overflow: "hidden" } as CSSProperties}>
          <div className="framer-19zdf65" data-border="true" data-framer-name="Benefit / Pro and Enterprise" style={{ width: "300px", height: "272px", minHeight: "170px", maxWidth: "100%", padding: "30px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "space-between", alignItems: "flex-start", alignContent: "flex-start", overflow: "hidden" } as CSSProperties}>
            <svg className="framer-4E5dL framer-y4e9tq" role="presentation" viewBox="0 0 20 20" style={{ width: "20px", height: "20px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1" } as CSSProperties}>
              <use href="#3797874707" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
            </svg>
            <div className="framer-gineq1" data-framer-name="Text" style={{ width: "220px", height: "145.781px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", overflow: "hidden" } as CSSProperties}>
              <div className="framer-1pjyq5i" data-framer-component-type="RichTextContainer" style={{ width: "220px", height: "48.5938px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", transform: "none" } as CSSProperties}>
                <h3 className="framer-text framer-styles-preset-ojsfn5" data-styles-preset="VQBQVu8qk" dir="auto" style={{ width: "220px", height: "48.5938px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "24.3px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--framer-text-alignment": "left", "--framer-text-color": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)" } as CSSProperties}>
                  {content.text}{" "}
                  <a className="framer-text framer-styles-preset-8rmpkv" data-styles-preset="uT_bT0pMG" data-external-route="1" style={{ position: "static", display: "inline", flexDirection: "row", textDecoration: "underline 1px rgba(255, 255, 255, 0.3)" } as CSSProperties} href={content.text_2}>
                    {content.text_3}
                  </a>
                </h3>
              </div>
              <div className="framer-1gmogjx" data-framer-component-type="RichTextContainer" style={{ width: "220px", height: "97.1875px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", transform: "none" } as CSSProperties}>
                <p className="framer-text framer-styles-preset-vn6u90" data-styles-preset="kuibWYBoM" dir="auto" style={{ width: "220px", height: "97.1875px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "24.3px", letterSpacing: "-0.2px", textAlign: "left", color: "rgba(255, 255, 255, 0.6)", "--framer-text-alignment": "left", "--framer-text-color": "var(--token-8f5eb515-7a13-452b-a4ab-f35e2208a3f3)" } as CSSProperties}>
                  {content.text_4}
                </p>
              </div>
            </div>
          </div>
          <div className="framer-1yfxjgf" data-border="true" data-framer-name="Switch From Platforms" style={{ width: "300px", height: "272px", minHeight: "170px", maxWidth: "100%", padding: "30px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "space-between", alignItems: "flex-start", alignContent: "flex-start", overflow: "hidden" } as CSSProperties}>
            <svg className="framer-nROxc framer-17fxgde" role="presentation" viewBox="0 0 20 20" data-cs-id="1614" style={{ width: "20px", height: "20px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1" } as CSSProperties}>
              <use href="#919011021" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
            </svg>
            <div className="framer-15j38kw" data-framer-name="Text" style={{ width: "220px", height: "145.781px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", overflow: "hidden" } as CSSProperties}>
              <div className="framer-1lyb9f" data-framer-component-type="RichTextContainer" style={{ width: "220px", height: "48.5938px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", transform: "none" } as CSSProperties}>
                <h3 className="framer-text framer-styles-preset-ojsfn5" data-styles-preset="VQBQVu8qk" dir="auto" style={{ width: "220px", height: "48.5938px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "24.3px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--framer-text-alignment": "left", "--framer-text-color": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)" } as CSSProperties}>
                  {content.text_5}
                </h3>
              </div>
              <div className="framer-1ijha8i" data-framer-component-type="RichTextContainer" style={{ width: "220px", height: "97.1875px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", transform: "none" } as CSSProperties}>
                <motion.p className="framer-text framer-styles-preset-vn6u90" data-styles-preset="kuibWYBoM" dir="auto" style={{ width: "220px", height: "97.1875px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "24.3px", letterSpacing: "-0.2px", textAlign: "left", color: "rgba(255, 255, 255, 0.6)", "--framer-text-alignment": "left", "--framer-text-color": "var(--token-8f5eb515-7a13-452b-a4ab-f35e2208a3f3, rgba(255, 255, 255, 0.6))" } as CSSProperties} initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 1, ease: [0.16, 1, 0.3, 1] }}>
                  {content.text_6}
                </motion.p>
              </div>
            </div>
          </div>
          <div className="ssr-variant hidden-1a0inom" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
            <div className="framer-rddpux" data-nosnippet="true" style={{ width: "600px", height: "544px", maxWidth: "100%", padding: "60px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "20px", gridArea: "span 2 / span 2", overflow: "clip" } as CSSProperties}>
              <div className="framer-1k82xqs" data-nosnippet="true" style={{ width: "370px", height: "424px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", gap: "30px", overflow: "clip" } as CSSProperties}>
                <div className="ssr-variant hidden-y2u6ev" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
                  <div className="framer-1329zvw-container" style={{ width: "370px", height: "424px", position: "relative", display: "block", flexDirection: "row" } as CSSProperties}>
                    <a className="framer-h3fR2 framer-br0m3n framer-v-br0m3n framer-1hedy7b" data-border="true" data-framer-name="Variant 1" data-highlight="true" style={{ width: "100%", height: "424px", padding: "30px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "flex-end", alignContent: "flex-end", gap: "24px", backgroundColor: "rgba(0, 0, 0, 0.82)", borderRadius: "25px", color: "rgb(0, 0, 238)", "--border-bottom-width": "1px", "--border-color": "var(--token-5e0b3b72-9a97-43f8-96f2-85d741f3d8ca, rgb(29, 29, 29))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.variant1}>
                      <div className="framer-13no3te" data-framer-name="Score Layout" style={{ width: "310px", height: "108px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "16px", opacity: "1" } as CSSProperties}>
                        <div className="framer-j5trfo" data-framer-name="Score Number Row" style={{ width: "310px", height: "56px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end", alignContent: "flex-end", opacity: "1" } as CSSProperties}>
                          <div className="framer-gqshm5" data-framer-name="Score Number" style={{ width: "175.25px", height: "56px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "flex-end", alignContent: "flex-end", gap: "1px", opacity: "0", overflow: "clip", willChange: "transform" } as CSSProperties}>
                            <div className="framer-nl6pxy" style={{ width: "63px", height: "56px", minHeight: "56px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties} />
                            <div className="framer-jfj1vs" data-framer-component-type="RichTextContainer" style={{ width: "35.7422px", height: "25.6016px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "var(--token-8f5eb515-7a13-452b-a4ab-f35e2208a3f3, rgba(255, 255, 255, 0.6))", transform: "none", opacity: "1" } as CSSProperties}>
                              <p dir="auto" className="framer-text" style={{ width: "35.7422px", height: "25.6016px", position: "static", display: "block", flexDirection: "row", fontFamily: "Inter, \"Inter Placeholder\", sans-serif", fontSize: "16px", fontWeight: "500", lineHeight: "25.6px", letterSpacing: "-0.32px", color: "rgba(255, 255, 255, 0.6)", "--font-selector": "SW50ZXItTWVkaXVt", "--framer-font-open-type-features": "'tnum' on", "--framer-font-weight": "500", "--framer-letter-spacing": "-0.02em", "--framer-line-height": "1.6em", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-8f5eb515-7a13-452b-a4ab-f35e2208a3f3, rgba(255, 255, 255, 0.6)))" } as CSSProperties}>
                                {content.scoreNumber}
                              </p>
                            </div>
                          </div>
                          <div className="framer-1cobkwc" data-framer-component-type="RichTextContainer" style={{ width: "134.75px", height: "25.6016px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "var(--token-8f5eb515-7a13-452b-a4ab-f35e2208a3f3, rgba(255, 255, 255, 0.6))", transform: "none", opacity: "1" } as CSSProperties}>
                            <p dir="auto" className="framer-text" style={{ width: "134.75px", height: "25.6016px", position: "static", display: "block", flexDirection: "row", fontFamily: "Inter, \"Inter Placeholder\", sans-serif", fontSize: "16px", fontWeight: "500", lineHeight: "25.6px", letterSpacing: "-0.32px", color: "rgba(255, 255, 255, 0.6)", "--font-selector": "SW50ZXItTWVkaXVt", "--framer-font-open-type-features": "'tnum' on", "--framer-font-weight": "500", "--framer-letter-spacing": "-0.02em", "--framer-line-height": "1.6em", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-8f5eb515-7a13-452b-a4ab-f35e2208a3f3, rgba(255, 255, 255, 0.6)))" } as CSSProperties}>
                              {content.scoreNumberRow}
                            </p>
                          </div>
                        </div>
                        <div className="framer-1ce8uw2" data-framer-name="ScoreBar" style={{ width: "310px", height: "36px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "4px", overflow: "clip", opacity: "1" } as CSSProperties}>
                          <div className="framer-k1vifb" style={{ width: "7.21094px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-515vhq" style={{ width: "7.21875px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-1gjj2rc" style={{ width: "7.21094px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-bos3sa" style={{ width: "7.21875px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-9fy4ue" style={{ width: "7.21094px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-1tlkp1o" style={{ width: "7.21875px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-10yxyuj" style={{ width: "7.21094px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-61yf8x" style={{ width: "7.21875px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-1wa00zv" style={{ width: "7.21094px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-17zp1g7" style={{ width: "7.21875px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-213ugb" style={{ width: "7.21094px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-1shzyxp" style={{ width: "7.21875px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-14r0luh" style={{ width: "7.21094px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-u80m7s" style={{ width: "7.21875px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-1goak4g" style={{ width: "7.21094px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-zh9ss8" style={{ width: "7.21875px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-1mav7s1" style={{ width: "7.21094px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-t7fw35" style={{ width: "7.21875px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-ke6kq0" style={{ width: "7.21094px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                          <div className="framer-1il2his" style={{ width: "7.21875px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                          <div className="framer-i9j2x8" style={{ width: "7.21094px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                          <div className="framer-1exsqby" style={{ width: "7.21875px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                          <div className="framer-oxbigr" style={{ width: "7.21094px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                          <div className="framer-1umafw7" style={{ width: "7.21875px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                          <div className="framer-1dkl5lu" style={{ width: "7.21094px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                          <div className="framer-4ekfar" style={{ width: "7.21094px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                          <div className="framer-1ak8gl5" style={{ width: "7.21094px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                          <div className="framer-19dholx" style={{ width: "7.21094px", height: "36px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.12)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                        </div>
                      </div>
                      <div className="framer-4m2udb" data-framer-name="Pillar Score Rows" style={{ width: "310px", height: "232px", padding: "10px 0px 0px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "24px", opacity: "1" } as CSSProperties}>
                        <div className="framer-126g9mt" style={{ width: "310px", height: "37.5px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", gap: "15px", opacity: "1" } as CSSProperties}>
                          <div className="framer-y3pmt7" style={{ width: "310px", height: "37.5px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", gap: "10px", opacity: "1" } as CSSProperties}>
                            <div className="framer-1i3fnmy" style={{ width: "310px", height: "19.5px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                              <div className="framer-1o3hv53" style={{ width: "310px", height: "19.5px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                                <div className="framer-jp9fkq" data-framer-component-type="RichTextContainer" style={{ width: "58.4062px", height: "19.5px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 30, \"wght\" 520", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", transform: "none", opacity: "1" } as CSSProperties}>
                                  <p dir="auto" className="framer-text" style={{ width: "58.4062px", height: "19.5px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "15px", lineHeight: "19.5px", letterSpacing: "-0.01px", textAlign: "left", color: "rgb(255, 255, 255)", whiteSpace: "pre-wrap", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXdMQ0FpZDJkb2RDSWdOVEl3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss03' on, 'ss07' on, 'cv11' on, 'cv05' on, 'cv01' on, 'cv09' on", "--framer-font-size": "15px", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 30, \"wght\" 520)", "--framer-letter-spacing": "-0.01px", "--framer-line-height": "1.3em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                                    {content.pillarScoreRows}
                                  </p>
                                </div>
                                <div className="framer-1h9qj07" data-framer-name="PillarFindableRating" data-framer-component-type="RichTextContainer" style={{ width: "33.1641px", height: "15.6016px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "rgb(76, 217, 99)", transform: "none", opacity: "1" } as CSSProperties}>
                                  <p dir="auto" className="framer-text" style={{ width: "33.1641px", height: "15.6016px", position: "static", display: "block", flexDirection: "row", fontFamily: "Inter, \"Inter Placeholder\", sans-serif", fontSize: "13px", fontWeight: "600", lineHeight: "15.6px", letterSpacing: "-0.13px", color: "rgb(76, 217, 99)", "--font-selector": "SW50ZXItU2VtaUJvbGQ=", "--framer-font-size": "13px", "--framer-font-weight": "600", "--framer-letter-spacing": "-0.01em", "--framer-text-color": "var(--extracted-r6o4lv, rgb(76, 217, 99))" } as CSSProperties}>
                                    {content.pillarfindablerating}
                                  </p>
                                </div>
                              </div>
                            </div>
                            <div className="framer-vgo4h3" data-framer-name="PillarFindableBar" style={{ width: "310px", height: "8px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "3px", opacity: "1" } as CSSProperties}>
                              <div className="framer-nhinp8" style={{ width: "17.8594px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                              <div className="framer-12dsb" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                              <div className="framer-rsixfo" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                              <div className="framer-12a3ud3" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                              <div className="framer-1dvd31o" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                              <div className="framer-1ufzcez" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                              <div className="framer-th7t60" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                              <div className="framer-1jnqudw" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                              <div className="framer-7iw8vu" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                              <div className="framer-1x2w6iw" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                              <div className="framer-azawdy" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                              <div className="framer-9mufxu" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                              <div className="framer-1ott2x" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                              <div className="framer-xa5dcw" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                              <div className="framer-ofy8jf" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                            </div>
                          </div>
                        </div>
                        <div className="framer-1ltdq6i" data-framer-name="Quotable Row" style={{ width: "310px", height: "37.5px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "20px", opacity: "1" } as CSSProperties}>
                          <div className="framer-hw0fw9" style={{ width: "310px", height: "37.5px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", gap: "15px", opacity: "1" } as CSSProperties}>
                            <div className="framer-1i9uh84" style={{ width: "310px", height: "37.5px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                              <div className="framer-h9sp76" style={{ width: "310px", height: "19.5px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                                <div className="framer-1dwja8t" data-framer-component-type="RichTextContainer" style={{ width: "62.4141px", height: "19.5px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 30, \"wght\" 520", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", transform: "none", opacity: "1" } as CSSProperties}>
                                  <p dir="auto" className="framer-text" style={{ width: "62.4141px", height: "19.5px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "15px", lineHeight: "19.5px", letterSpacing: "-0.01px", textAlign: "left", color: "rgb(255, 255, 255)", whiteSpace: "pre-wrap", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXdMQ0FpZDJkb2RDSWdOVEl3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss03' on, 'ss07' on, 'cv11' on, 'cv05' on, 'cv01' on, 'cv09' on", "--framer-font-size": "15px", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 30, \"wght\" 520)", "--framer-letter-spacing": "-0.01px", "--framer-line-height": "1.3em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                                    {content.quotableRow}
                                  </p>
                                </div>
                                <div className="framer-bzvhmf" data-framer-name="PillarQuotableRating" data-framer-component-type="RichTextContainer" style={{ width: "33.1641px", height: "15.6016px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "rgb(76, 217, 99)", transform: "none", opacity: "1" } as CSSProperties}>
                                  <p dir="auto" className="framer-text" style={{ width: "33.1641px", height: "15.6016px", position: "static", display: "block", flexDirection: "row", fontFamily: "Inter, \"Inter Placeholder\", sans-serif", fontSize: "13px", fontWeight: "600", lineHeight: "15.6px", letterSpacing: "-0.13px", color: "rgb(76, 217, 99)", "--font-selector": "SW50ZXItU2VtaUJvbGQ=", "--framer-font-size": "13px", "--framer-font-weight": "600", "--framer-letter-spacing": "-0.01em", "--framer-text-color": "var(--extracted-r6o4lv, rgb(76, 217, 99))" } as CSSProperties}>
                                    {content.pillarquotablerating}
                                  </p>
                                </div>
                              </div>
                              <div className="framer-1os6l66" data-framer-name="PillarQuotableBar" style={{ width: "310px", height: "8px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "3px", opacity: "1" } as CSSProperties}>
                                <div className="framer-1w2ipeb" style={{ width: "17.8594px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                <div className="framer-odp757" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                <div className="framer-3x7xnm" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                <div className="framer-gkg6lw" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                <div className="framer-aggb3o" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                <div className="framer-1boq1o8" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                <div className="framer-wijja9" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                <div className="framer-13jixga" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                <div className="framer-1ke6tqk" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                <div className="framer-1vjnqm4" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                                <div className="framer-im8d5p" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                                <div className="framer-skw2p2" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                                <div className="framer-pqoa3c" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                                <div className="framer-wfw08z" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                                <div className="framer-12thlh" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="framer-1bflnxj" data-framer-name="Understandable Row" style={{ width: "310px", height: "37.5px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "20px", opacity: "1" } as CSSProperties}>
                          <div className="framer-bob684" style={{ width: "310px", height: "37.5px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", gap: "15px", opacity: "1" } as CSSProperties}>
                            <div className="framer-1didx1d" style={{ width: "310px", height: "37.5px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                              <div className="framer-1bm8usb" style={{ width: "310px", height: "19.5px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                                <div className="framer-lfmx4y" data-framer-component-type="RichTextContainer" style={{ width: "109.023px", height: "19.5px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 30, \"wght\" 520", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", transform: "none", opacity: "1" } as CSSProperties}>
                                  <p dir="auto" className="framer-text" style={{ width: "109.023px", height: "19.5px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "15px", lineHeight: "19.5px", letterSpacing: "-0.01px", textAlign: "left", color: "rgb(255, 255, 255)", whiteSpace: "pre-wrap", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXdMQ0FpZDJkb2RDSWdOVEl3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss03' on, 'ss07' on, 'cv11' on, 'cv05' on, 'cv01' on, 'cv09' on", "--framer-font-size": "15px", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 30, \"wght\" 520)", "--framer-letter-spacing": "-0.01px", "--framer-line-height": "1.3em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                                    {content.understandableRow}
                                  </p>
                                </div>
                                <div className="framer-1n6oukt" data-framer-name="PillarUnderstandableRating" data-framer-component-type="RichTextContainer" style={{ width: "51.0703px", height: "15.6016px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "rgb(255, 180, 50)", transform: "none", opacity: "1" } as CSSProperties}>
                                  <p dir="auto" className="framer-text" style={{ width: "51.0703px", height: "15.6016px", position: "static", display: "block", flexDirection: "row", fontFamily: "Inter, \"Inter Placeholder\", sans-serif", fontSize: "13px", fontWeight: "600", lineHeight: "15.6px", letterSpacing: "-0.13px", color: "rgb(255, 180, 50)", "--font-selector": "SW50ZXItU2VtaUJvbGQ=", "--framer-font-size": "13px", "--framer-font-weight": "600", "--framer-letter-spacing": "-0.01em", "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 180, 50))" } as CSSProperties}>
                                    {content.pillarunderstandablerating}
                                  </p>
                                </div>
                              </div>
                              <div className="framer-4xq3o5" data-framer-name="PillarUnderstandableBar" style={{ width: "310px", height: "8px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "3px", opacity: "1" } as CSSProperties}>
                                <div className="framer-1yndge9" style={{ width: "17.8594px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 180, 50, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                <div className="framer-g2a0e7" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 180, 50, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                <div className="framer-biqw0y" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 180, 50, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                <div className="framer-17ixdts" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 180, 50, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                <div className="framer-uejpek" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 180, 50, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                <div className="framer-jw51sb" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 180, 50, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                <div className="framer-1xe3bog" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 180, 50, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                <div className="framer-130zsd8" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 180, 50, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                <div className="framer-mcnl5l" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 180, 50, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                                <div className="framer-5ceyus" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 180, 50, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                                <div className="framer-ge3pbn" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 180, 50, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                                <div className="framer-1l13iqz" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 180, 50, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                                <div className="framer-1xjommt" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 180, 50, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                                <div className="framer-2oerm0" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 180, 50, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                                <div className="framer-14kvu69" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 180, 50, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="framer-78vs8o" data-framer-name="Trustworthy Row" style={{ width: "310px", height: "37.5px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "20px", opacity: "1" } as CSSProperties}>
                          <div className="framer-1kx3b2q" style={{ width: "310px", height: "37.5px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", gap: "15px", opacity: "1" } as CSSProperties}>
                            <div className="framer-sp4c5c" style={{ width: "310px", height: "37.5px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                              <div className="framer-ey8q04" style={{ width: "310px", height: "19.5px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                                <div className="framer-o6uq4c" data-framer-component-type="RichTextContainer" style={{ width: "81.4219px", height: "19.5px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 30, \"wght\" 520", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", transform: "none", opacity: "1" } as CSSProperties}>
                                  <p dir="auto" className="framer-text" style={{ width: "81.4219px", height: "19.5px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "15px", lineHeight: "19.5px", letterSpacing: "-0.01px", textAlign: "left", color: "rgb(255, 255, 255)", whiteSpace: "pre-wrap", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXdMQ0FpZDJkb2RDSWdOVEl3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss03' on, 'ss07' on, 'cv11' on, 'cv05' on, 'cv01' on, 'cv09' on", "--framer-font-size": "15px", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 30, \"wght\" 520)", "--framer-letter-spacing": "-0.01px", "--framer-line-height": "1.3em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                                    {content.trustworthyRow}
                                  </p>
                                </div>
                                <div className="framer-1wlrnkn" data-framer-name="PillarTrustworthyRating" data-framer-component-type="RichTextContainer" style={{ width: "33.1641px", height: "15.6016px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "rgb(76, 217, 99)", transform: "none", opacity: "1" } as CSSProperties}>
                                  <p dir="auto" className="framer-text" style={{ width: "33.1641px", height: "15.6016px", position: "static", display: "block", flexDirection: "row", fontFamily: "Inter, \"Inter Placeholder\", sans-serif", fontSize: "13px", fontWeight: "600", lineHeight: "15.6px", letterSpacing: "-0.13px", color: "rgb(76, 217, 99)", "--font-selector": "SW50ZXItU2VtaUJvbGQ=", "--framer-font-size": "13px", "--framer-font-weight": "600", "--framer-letter-spacing": "-0.01em", "--framer-text-color": "var(--extracted-r6o4lv, rgb(76, 217, 99))" } as CSSProperties}>
                                    {content.pillartrustworthyrating}
                                  </p>
                                </div>
                              </div>
                              <div className="framer-u08xu2" data-framer-name="PillarTrustworthyBar" style={{ width: "310px", height: "8px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "3px", opacity: "1" } as CSSProperties}>
                                <div className="framer-1b6ysqa" style={{ width: "310px", height: "8px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "3px", opacity: "1" } as CSSProperties}>
                                  <div className="framer-jvx1rs" style={{ width: "17.8594px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                  <div className="framer-1qu8z1o" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                  <div className="framer-u2k5uu" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                  <div className="framer-ncw4eh" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                  <div className="framer-m59x60" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                  <div className="framer-kim3ut" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                  <div className="framer-1lmxw1y" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                  <div className="framer-xhadu7" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                  <div className="framer-mfv36n" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                  <div className="framer-urfc7k" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1", willChange: "auto" } as CSSProperties} />
                                  <div className="framer-mbtqqz" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                                  <div className="framer-i4xmsq" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                                  <div className="framer-1tmc0d7" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                                  <div className="framer-ocuj00" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                                  <div className="framer-9gc1qf" style={{ width: "17.8672px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(76, 217, 99, 0.2)", borderRadius: "2px", opacity: "1" } as CSSProperties} />
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="framer-1cbb99b" data-border="true" data-framer-name="Benefit / Year One Credit" style={{ width: "300px", height: "272px", minHeight: "170px", maxWidth: "100%", padding: "30px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "space-between", alignItems: "flex-start", alignContent: "flex-start", overflow: "hidden" } as CSSProperties}>
            <svg className="framer-1Uapm framer-jukdlu" role="presentation" viewBox="0 0 20 20" style={{ width: "20px", height: "20px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1" } as CSSProperties}>
              <use href="#1915987791" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
            </svg>
            <div className="framer-16astad" data-framer-name="Text" style={{ width: "220px", height: "145.781px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", overflow: "hidden" } as CSSProperties}>
              <div className="framer-1k3tbq2" data-framer-component-type="RichTextContainer" style={{ width: "220px", height: "48.5938px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", transform: "none" } as CSSProperties}>
                <h3 className="framer-text framer-styles-preset-ojsfn5" data-styles-preset="VQBQVu8qk" dir="auto" style={{ width: "220px", height: "48.5938px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "24.3px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--framer-text-alignment": "left", "--framer-text-color": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)" } as CSSProperties}>
                  {content.text_7}
                </h3>
              </div>
              <div className="framer-5z5qbx" data-framer-component-type="RichTextContainer" style={{ width: "220px", height: "97.1875px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", transform: "none" } as CSSProperties}>
                <p className="framer-text framer-styles-preset-vn6u90" data-styles-preset="kuibWYBoM" dir="auto" style={{ width: "220px", height: "97.1875px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "24.3px", letterSpacing: "-0.2px", textAlign: "left", color: "rgba(255, 255, 255, 0.6)", "--framer-text-alignment": "left", "--framer-text-color": "var(--token-8f5eb515-7a13-452b-a4ab-f35e2208a3f3)" } as CSSProperties}>
                  {content.text_8}{" "}
                  <a className="framer-text framer-styles-preset-17uz1e6" data-styles-preset="lauDPxbHX" data-framer-page-link-current="true" style={{ position: "static", display: "inline", flexDirection: "row", textDecoration: "underline 1px rgba(255, 255, 255, 0.3)" } as CSSProperties} href={content.text_9}>
                    {content.text_10}
                  </a>
                  {" "}{content.text_11}{" "}
                  <a className="framer-text framer-styles-preset-17uz1e6" data-styles-preset="lauDPxbHX" style={{ position: "static", display: "inline", flexDirection: "row", textDecoration: "underline 1px rgba(255, 255, 255, 0.3)" } as CSSProperties} href={content.text_12}>
                    {content.text_13}
                  </a>
                  {" "}{content.text_14}
                </p>
              </div>
            </div>
          </div>
          <div className="framer-1v5xl3p" data-border="true" data-framer-name="Benefit / AI Tokens" style={{ width: "300px", height: "272px", minHeight: "170px", maxWidth: "100%", padding: "30px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "space-between", alignItems: "flex-start", alignContent: "flex-start", overflow: "hidden" } as CSSProperties}>
            <svg className="framer-vqnL3 framer-1dwsgzm" role="presentation" viewBox="0 0 20 20" style={{ width: "20px", height: "20px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1" } as CSSProperties}>
              <use href="#1770930775" data-cs-id="1774" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
            </svg>
            <div className="framer-1vbcv0x" data-framer-name="Text" data-cs-id="1775" style={{ width: "220px", height: "145.781px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", overflow: "hidden" } as CSSProperties}>
              <div className="framer-1f7hr53" data-framer-component-type="RichTextContainer" style={{ width: "220px", height: "48.5938px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", transform: "none" } as CSSProperties}>
                <h3 className="framer-text framer-styles-preset-ojsfn5" data-styles-preset="VQBQVu8qk" dir="auto" style={{ width: "220px", height: "48.5938px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "24.3px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--framer-text-alignment": "left", "--framer-text-color": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4)" } as CSSProperties}>
                  {content.text_15}
                </h3>
              </div>
              <div className="framer-4x8ak6" data-framer-component-type="RichTextContainer" style={{ width: "220px", height: "97.1875px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", transform: "none" } as CSSProperties}>
                <p className="framer-text framer-styles-preset-vn6u90" data-styles-preset="kuibWYBoM" dir="auto" style={{ width: "220px", height: "97.1875px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "18px", lineHeight: "24.3px", letterSpacing: "-0.2px", textAlign: "left", color: "rgba(255, 255, 255, 0.6)", "--framer-text-alignment": "left", "--framer-text-color": "var(--token-8f5eb515-7a13-452b-a4ab-f35e2208a3f3)" } as CSSProperties}>
                  {content.text_16}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
