// content for the "Header" section — extracted by extract-site.
// Edit values here to re-skin the "Header" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  content: "Create, manage, and publish dynamic sites with AI agents",
  regular: "https://framer-ai.com/r/signup",
  label: "Get started for free",
  regular_2: "https://updates.framer.com/electron/darwin/arm64/Framer.zip?_ga=2.113395847.1447313862.1646043056-273660571.1642151053",
  label_2: "Download app",
  topbar2: "CMS",
  default: "Site",
  default_2: "·",
  off: "main",
  topbar2_2: { src: "/images/6dde01a3-K4yrdjJQvo3DYnGv4QVR6Ymexco9579.jpg?width=314&height=314", alt: "CMS hero background image" },
  topbar2_3: "Invite",
  topbar2_4: "Publish",
  collectionsPanel: "Collections",
  collectionsPanel_2: "Fields",
  collectionsPanel_3: "Plugins",
  collectionsPanel_4: "Blog",
  collectionsPanel_5: "Careers",
  collectionsPanel_6: "Docs",
  collectionsPanel_7: "Guides",
  collectionsPanel_8: "Help",
  collectionsPanel_9: "Startups",
  collectionsPanel_10: "Use Cases",
  collectionsPanel_11: "Articles",
  collectionsPanel_12: "39",
  collectionsPanel_13: "39",
  collectionsPanel_14: "Categories",
  collectionsPanel_15: "10",
  collectionsPanel_16: "10",
  collectionsPanel_17: "Add...",
  tableHeader: "Title",
  tableHeader_2: "Image",
  tableHeader_3: "Category",
  tableHeader_4: "Featured",
  title: "How Perplexity launched their AI search brand site",
  image: { src: "/images/8784dabd-CEy21VDgfjBsqXFxkpFKn1lpg7e05.jpg?width=136&height=59", alt: "CMS table row thumbnail" },
  dark: "AI",
  title_2: "How DoorDash redesigned their marketing site",
  image_2: { src: "/images/7fe331d5-PPOwZ7ulw8JBvZs3Wm3SuoELvc7e05.jpg?width=136&height=59", alt: "CMS table row thumbnail" },
  dark_2: "Enterprise",
  title_3: "How NBA launched a global fan experience",
  image_3: { src: "/images/5cf7d6ba-EsnqSMEsCLKRUzAf0d0vjgV6Ek7e05.jpg?width=136&height=59", alt: "CMS table row thumbnail" },
  dark_3: "Sports",
  title_4: "How Dribbble rebuilt their community platform",
  image_4: { src: "/images/841b09ed-FZ41nTcp9zMYUPgpta9yeNxp2A7e05.jpg?width=136&height=59", alt: "CMS table row thumbnail" },
  dark_4: "Design",
  title_5: "How Zapier ships landing pages 10x faster",
  image_5: { src: "/images/60b72632-nV3fKfq0FhEbi4R8Tcrb6IyyRE7e05.jpg?width=136&height=59", alt: "CMS table row thumbnail" },
  dark_5: "SaaS",
  title_6: "How Microsoft powers brand design at scale",
  image_6: { src: "/images/685722d1-9gHFSbV7LlSx8nX3aNc2bh1Rfc7e05.jpg?width=136&height=59", alt: "CMS table row thumbnail" },
  dark_6: "Enterprise",
  title_7: "How Huel grew their direct-to-consumer storefront",
  image_7: { src: "/images/89c65fe3-k0kQXkWQieCERiRWz3JXV9431XM7e05.jpg?width=136&height=59", alt: "CMS table row thumbnail" },
  dark_7: "Consumer",
  title_8: "How Mixpanel launched their new product site",
  image_8: { src: "/images/6da9c947-zxUQryRqPtPQETVbxTPPxbiz687e05.jpg?width=136&height=59", alt: "CMS table row thumbnail" },
  dark_8: "SaaS",
  title_9: "How Cal.com ships a world-class docs experience",
  image_9: { src: "/images/ee2ac972-9wpN9aV4xW0h55NE9Epxub5Y47e05.jpg?width=136&height=59", alt: "CMS table row thumbnail" },
  dark_9: "Startup",
  title_10: "How Loops builds email SaaS pages in days",
  image_10: { src: "/images/def48f37-s7PdgAwUhXLBvi0lUWMOfAVjoI7e05.jpg?width=136&height=59", alt: "CMS table row thumbnail" },
  dark_10: "SaaS",
  title_11: "How Contra launched a freelancer marketplace",
  image_11: { src: "/images/f854e4b4-hv8Ak0FnkeOyFLxW9RSKTQMR87e05.jpg?width=136&height=59", alt: "CMS table row thumbnail" },
  dark_11: "Startup",
  title_12: "How Miro ships marketing pages without engineering",
  image_12: { src: "/images/9e5ae97b-koEwNpQ6O7w9V2usCS90wmGy87e05.jpg?width=136&height=59", alt: "CMS table row thumbnail" },
  dark_12: "SaaS",
  multiSelection: "Add to Agent",
  multiSelection_2: "⌃A",
  agent: "Agent",
  history: "Updates",
  fpAgentPrompt: "Use",
  fpAgentPrompt_2: "use-cases",
  fpAgentPrompt_3: ".csv",
  fpAgentPrompt_4: "to create Use Case Articles and Categories collections. Populate fields and match each article to a category.",
  thought1: "Thinking...",
  thought1_2: "Thinking...",
  result: "I’ll create two CMS collections from the attached CSV.",
  conversation: "Added 82 layers 44s",
  conversation_2: "Done — I added two linked collections:",
  conversation_3: "Articles — 39 CSV rows imported.",
  conversation_4: "Categories — 10 rows added and linked to Articles as multi-select tags.",
  chat: "Changes",
  chat_2: "Undo",
  chat_3: "Articles",
  chat_4: "39 Items",
  chat_5: "Categories",
  chat_6: "10 Items",
  promptInput: "._ru_::placeholder { color: var(--token-f5637926-8ee6-41cb-a320-ec3462d62cd5, rgba(255, 255, 255, 0.4)); opacity: 1; }",
  aiModel: "GPT 5.6",
  aiModel_2: "Terra",
  m: "/stories",
  m_2: "Meet our customers",
};
