// content for the "Agent" section — extracted by extract-site.
// Edit values here to re-skin the "Agent" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "Create, update and import your content. Manually or with a prompt.",
  topbar2: "CMS",
  default: "Site",
  default_2: "·",
  off: "main",
  topbar2_2: { src: "/images/1534cc3a-LPkXlDTlZn3Gg3nOt0vzCxLJXU20cf.png?width=512&height=512", alt: "CMS interface preview image" },
  topbar2_3: "Invite",
  topbar2_4: "Publish",
  collectionsPanel: "Collections",
  collectionsPanel_2: "Fields",
  collectionsPanel_3: "Plugins",
  collectionsPanel_4: "Academy",
  collectionsPanel_5: "Blog",
  collectionsPanel_6: "Articles",
  collectionsPanel_7: "320",
  collectionsPanel_8: "Authors",
  collectionsPanel_9: "39",
  collectionsPanel_10: "39",
  collectionsPanel_11: "Categories",
  collectionsPanel_12: "18",
  collectionsPanel_13: "Styles",
  collectionsPanel_14: "7",
  collectionsPanel_15: "Developers",
  collectionsPanel_16: "Startups",
  collectionsPanel_17: "Help",
  collectionsPanel_18: "Add...",
  cmsAuthors: "Name",
  cmsAuthors_2: "Bio",
  cmsAuthors_3: "Avatar",
  cmsAuthors_4: "Department",
  title: "Jurre Houtkamp",
  image: { src: "/images/e9f471f8-Qmgj3M1wKdUN21KeMuSnVcLlYcf73b.png?width=192&height=192", alt: "CMS author portrait" },
  dark: "Design",
  bio: "Leads the Marketing team at Framer",
  title_2: "Ashley Worth",
  image_2: { src: "/images/3ae5a1d4-06Pge5o1rjcipul2wCi4XwIVc20cf.png?width=512&height=512", alt: "Ashley Worth author portrait" },
  dark_2: "Partnerships",
  bio_2: "Agency partnerships manager",
  title_3: "Edoardo Mercati",
  image_3: { src: "/images/1ea3b48d-kFiEvDg0LczTmqWVkfNUFTc5020cf.png?width=512&height=512", alt: "CMS author portrait" },
  dark_3: "Design",
  bio_3: "Product lead of CMS and Localization",
  title_4: "Andy Orsow",
  image_4: { src: "/images/a29e82b8-35w0ro3rgy9viKmF4jLbaj8EgpM20cf.png?width=512&height=512", alt: "CMS author portrait" },
  dark_4: "Design",
  bio_4: "Video marketeer at Framer",
  title_5: "Sophia Cassidy",
  image_5: { src: "/images/4af12b2d-31ams7N2G9aEJFBVnZ5ptVmBI20cf.png?width=512&height=512", alt: "CMS author portrait" },
  dark_5: "Education",
  bio_5: "Education and startups partnerships manager",
  title_6: "Tom Watson",
  image_6: { src: "/images/9583f407-Qt0O5L27sLv217q3LxvksD9Lw6s20cf.png?width=512&height=512", alt: "CMS author portrait" },
  dark_6: "Engineering",
  bio_6: "Staff product engineer",
  sidebar: { src: "../../framerusercontent.com/images/8rpKpXq0OyDdFohd7e3NCN8oQDs6407.png?width=520&height=1400", alt: "CMS editor sidebar preview" },
  header_2: { src: "../../framerusercontent.com/images/R2z0U8jUYeP0JRpapIeGR1mGKdA3e2d.png?width=2760&height=150", alt: "CMS editor header preview" },
  searchRow: { src: "../../framerusercontent.com/images/jYDmxYKBes4MJG04lZ1OFXEBc83e2d.png?width=2760&height=150", alt: "CMS search row preview" },
  cmsItem1: { src: "../../framerusercontent.com/images/kqnlrwFlDazht592YihJC3J0K00f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem2: { src: "../../framerusercontent.com/images/1XXeRAVlMnRbQ1WWneq1d9Nl5lQ0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem3: { src: "../../framerusercontent.com/images/sK1zK3HACiMnQYVCxeZrOZskuY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem4: { src: "../../framerusercontent.com/images/v9pwGgBVZkUx2owTzQRkVHmtZdM0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem5: { src: "../../framerusercontent.com/images/imtvP46cYCj0aPxb5qXA0GWKeHs0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem6: { src: "../../framerusercontent.com/images/sku8XSsM7FaTRvUjyXn0bl7FxRM0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem7: { src: "../../framerusercontent.com/images/DpJGCRixy5rN6iW9UL3GdMwWuY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem8: { src: "../../framerusercontent.com/images/kHLjCnG1LcrqAcRDmY9L7O8WQhQ0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem9: { src: "../../framerusercontent.com/images/YdiKOgEO0YR0SpypfJJ5bZIeIHY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem10: { src: "../../framerusercontent.com/images/6eQfOdmS9duVZhhQ1GV5bWSEY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  text: "Create a collection in seconds",
  text_2: "Describe what you want to store and the agent creates the collection, adds the right field types, and sets up slugs automatically.",
  visual: "Publish",
  visual_2: "Title",
  visual_3: "Vibe-coding interactive components",
  visual_4: "Date",
  visual_5: "9/5/2026",
  visual_6: "Image",
  image_7: { src: "../../framerusercontent.com/images/Fum9UBQ47ZvEKY4vPblCc5Dsrxobd12.jpg?width=640&height=427", alt: "CMS interface preview image" },
  visual_7: "Categories",
  chip4: "Tutorials",
  chip4_2: "AI",
  visual_8: "Content",
  visual_9: "I",
  visual_10: "n",
  visual_11: "t",
  visual_12: "e",
  visual_13: "r",
  visual_14: "a",
  visual_15: "c",
  visual_16: "t",
  visual_17: "i",
  visual_18: "v",
  visual_19: "e",
  visual_20: "c",
  visual_21: "o",
  visual_22: "m",
  visual_23: "p",
  visual_24: "o",
  visual_25: "n",
  visual_26: "e",
  visual_27: "n",
  visual_28: "t",
  visual_29: "s",
  visual_30: "u",
  visual_31: "s",
  visual_32: "e",
  visual_33: "d",
  visual_34: "t",
  visual_35: "o",
  visual_36: "r",
  visual_37: "e",
  visual_38: "q",
  visual_39: "u",
  visual_40: "i",
  visual_41: "r",
  visual_42: "e",
  visual_43: "h",
  visual_44: "o",
  visual_45: "u",
  visual_46: "r",
  visual_47: "s",
  visual_48: "o",
  visual_49: "f",
  visual_50: "c",
  visual_51: "a",
  visual_52: "r",
  visual_53: "e",
  visual_54: "f",
  visual_55: "u",
  visual_56: "l",
  visual_57: "s",
  visual_58: "t",
  visual_59: "a",
  visual_60: "t",
  visual_61: "e",
  visual_62: "m",
  visual_63: "a",
  visual_64: "n",
  visual_65: "a",
  visual_66: "g",
  visual_67: "e",
  visual_68: "m",
  visual_69: "e",
  visual_70: "n",
  visual_71: "t",
  visual_72: "a",
  visual_73: "n",
  visual_74: "d",
  visual_75: "a",
  visual_76: "n",
  visual_77: "i",
  visual_78: "m",
  visual_79: "a",
  visual_80: "t",
  visual_81: "i",
  visual_82: "o",
  visual_83: "n",
  visual_84: "l",
  visual_85: "o",
  visual_86: "g",
  visual_87: "i",
  visual_88: "c",
  visual_89: ".",
  visual_90: "W",
  visual_91: "i",
  visual_92: "t",
  visual_93: "h",
  visual_94: "v",
  visual_95: "i",
  visual_96: "b",
  visual_97: "e",
  visual_98: "-",
  visual_99: "c",
  visual_100: "o",
  visual_101: "d",
  visual_102: "i",
  visual_103: "n",
  visual_104: "g",
  visual_105: "i",
  visual_106: "n",
  visual_107: "F",
  visual_108: "r",
  visual_109: "a",
  visual_110: "m",
  visual_111: "e",
  visual_112: "r",
  visual_113: ",",
  visual_114: "y",
  visual_115: "o",
  visual_116: "u",
  visual_117: "d",
  visual_118: "e",
  visual_119: "s",
  visual_120: "c",
  visual_121: "r",
  visual_122: "i",
  visual_123: "b",
  visual_124: "e",
  visual_125: "w",
  visual_126: "h",
  visual_127: "a",
  visual_128: "t",
  visual_129: "y",
  visual_130: "o",
  visual_131: "u",
  visual_132: "w",
  visual_133: "a",
  visual_134: "n",
  visual_135: "t",
  visual_136: "i",
  visual_137: "n",
  visual_138: "Slug",
  visual_139: "translation models",
  visual_140: "framer.com/blog/translation-models",
  visual_141: "Status",
  live: "Live",
  visual_142: "Tint",
  visual_143: "6200D9",
  visual_144: "Featured",
  darkFp: "Title",
  darkFp_2: "Status",
  darkFp_3: "Image",
  darkFp_4: "Category",
  title_7: "Vibe-coding interactive components",
  live_2: "Draft",
  dark_7: "Tutorials",
  title_8: "10 animation techniques every designer should know",
  live_3: "Live",
  dark_8: "Inspiration",
  title_9: "Behind the scenes: building a design system at scale",
  live_4: "Live",
  dark_9: "Product",
  title_10: "The art of micro-interactions: small details, big impact",
  live_5: "Live",
  dark_10: "Inspiration",
  title_11: "How to keep your design system in sync",
  live_6: "Live",
  dark_11: "Guide",
  title_12: "Typography first: why type sets the tone for everything",
  live_7: "Live",
  dark_12: "Design",
  title_13: "Empowering next generation of designers",
  live_8: "Live",
  image_8: { src: "../../framerusercontent.com/images/Ls5eXLTjF0MKun6iZFw9KVqDHfUbd12.jpg?width=640&height=427", alt: "CMS item thumbnail" },
  dark_13: "Inspiration",
  sidebar_2: { src: "../../framerusercontent.com/images/8rpKpXq0OyDdFohd7e3NCN8oQDs6407.png?width=520&height=1400", alt: "CMS editor sidebar preview" },
  header_3: { src: "../../framerusercontent.com/images/R2z0U8jUYeP0JRpapIeGR1mGKdA3e2d.png?width=2760&height=150", alt: "CMS editor header preview" },
  searchRow_2: { src: "../../framerusercontent.com/images/jYDmxYKBes4MJG04lZ1OFXEBc83e2d.png?width=2760&height=150", alt: "CMS search row preview" },
  cmsItem1_2: { src: "../../framerusercontent.com/images/kqnlrwFlDazht592YihJC3J0K00f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem2_2: { src: "../../framerusercontent.com/images/1XXeRAVlMnRbQ1WWneq1d9Nl5lQ0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem3_2: { src: "../../framerusercontent.com/images/sK1zK3HACiMnQYVCxeZrOZskuY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem4_2: { src: "../../framerusercontent.com/images/v9pwGgBVZkUx2owTzQRkVHmtZdM0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem5_2: { src: "../../framerusercontent.com/images/imtvP46cYCj0aPxb5qXA0GWKeHs0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem6_2: { src: "../../framerusercontent.com/images/sku8XSsM7FaTRvUjyXn0bl7FxRM0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem7_2: { src: "../../framerusercontent.com/images/DpJGCRixy5rN6iW9UL3GdMwWuY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem8_2: { src: "../../framerusercontent.com/images/kHLjCnG1LcrqAcRDmY9L7O8WQhQ0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem9_2: { src: "../../framerusercontent.com/images/YdiKOgEO0YR0SpypfJJ5bZIeIHY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem10_2: { src: "../../framerusercontent.com/images/6eQfOdmS9duVZhhQ1GV5bWSEY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  text_3: "Populate collections with real content",
  text_4: "Ask the agent to fill your collection with sample data and it generates structured, realistic items. Titles, descriptions, dates, and categories ready to preview.",
  agent: "@keyframes ghostFlow { 0%, 18% { opacity: 1; } 35% { opacity: 0.6; } 50%, 100% { opacity: 0.3; } } @keyframes doubleSlow { 0%, 100% { opacity: 0.3; } 8% { opacity: 0.72; } 16%, 24% { opacity: 1; } 34%, 50% { opacity: 0.3; } 58% { opacity: 0.58; } 66%, 74% { opacity: 0.96; } 84% { opacity: 0.48; } } @keyframes danceSpark { 0%, 6% { opacity: 1; } 18% { opacity: 0.45; } 24%, 100% { opacity: 0.3; } }",
  agent_2: "Desktop",
  agent_3: "1200",
  blogPage2x: { src: "../../framerusercontent.com/images/6ySwo6LgsvifEMaNDivh9wNhXob4a2.jpg?width=1200&height=1586", alt: "Blog" },
  stack2xTitle: { src: "../../framerusercontent.com/images/WEqlHzRVwLp1Gvcp81Msxdg8rNs0fac.png?width=1320&height=532", alt: "CMS stack title preview" },
  stack2xTitle_2: { src: "/images/76e5a6ad-3myRAtTBZmGhRM41hYsQt6JHeA8c836.png?width=506&height=280", alt: "CMS stack title preview" },
  blogBar: "Blog",
  blogBar_2: "web-interactions",
  blogBar_3: "Draft",
  text_5: "A fully designed detail page, wired to your content",
  text_6: "Ask for a detail page and the agent creates the route, maps every field, and wires the full layout. No URLs or variables to set up manually.",
  topbar2_5: "CMS",
  default_3: "Site",
  default_4: "·",
  off_2: "main",
  topbar2_6: { src: "/images/1534cc3a-LPkXlDTlZn3Gg3nOt0vzCxLJXU20cf.png?width=512&height=512", alt: "CMS interface preview image" },
  topbar2_7: "Invite",
  topbar2_8: "Publish",
  collectionsPanel_19: "Collections",
  collectionsPanel_20: "Fields",
  collectionsPanel_21: "Plugins",
  collectionsPanel_22: "Blog",
  collectionsPanel_23: "Careers",
  collectionsPanel_24: "Case Studies",
  collectionsPanel_25: "Articles",
  collectionsPanel_26: "48",
  collectionsPanel_27: "48",
  collectionsPanel_28: "Categories",
  collectionsPanel_29: "18",
  collectionsPanel_30: "18",
  collectionsPanel_31: "Guides",
  collectionsPanel_32: "Help",
  collectionsPanel_33: "Updates",
  collectionsPanel_34: "Add...",
  cmsFiles: "Title",
  cmsFiles_2: "Status",
  cmsFiles_3: "Date",
  cmsFiles_4: "Icon",
  cmsFiles_5: "Type",
  title_14: "How Zapier unified their marketing site in 8 weeks",
  live_9: "Live",
  image_9: { src: "/images/60b72632-nV3fKfq0FhEbi4R8Tcrb6IyyRE7e05.jpg?width=136&height=59", alt: "CMS item thumbnail" },
  dark_14: "SaaS",
  date: "16/06/26",
  title_15: "Scaling Mixpanel’s design system to 500+ components",
  live_10: "Live",
  image_10: { src: "/images/6da9c947-zxUQryRqPtPQETVbxTPPxbiz687e05.jpg?width=136&height=59", alt: "CMS item thumbnail" },
  dark_15: "Analytics",
  date_2: "13/06/26",
  title_16: "Bird's zero-downtime deployment pipeline",
  live_11: "Live",
  image_11: { src: "/images/6cffb781-eY1sCXz9jGch9wYZB594kPmQiPk7e05.jpg?width=136&height=59", alt: "CMS item thumbnail" },
  dark_16: "Fintech",
  date_3: "10/06/26",
  title_17: "StackAI’s approach to real-time inference at scale",
  live_12: "Live",
  image_12: { src: "/images/f6db7c00-LsI8jBI0C5LU9w7RmbqniDHW4t07e05.jpg?width=136&height=59", alt: "CMS item thumbnail" },
  dark_17: "AI",
  date_4: "07/06/26",
  title_18: "How Miro shipped a new marketing site without compromising on design",
  live_13: "Live",
  image_13: { src: "/images/9e5ae97b-koEwNpQ6O7w9V2usCS90wmGy87e05.jpg?width=136&height=59", alt: "CMS item thumbnail" },
  dark_18: "Collaboration",
  date_5: "04/06/26",
  title_19: "Designer Fund’s portfolio platform from 0 to launch",
  live_14: "Live",
  dark_19: "John Doe",
  date_6: "01/06/26",
  sidebar_3: { src: "../../framerusercontent.com/images/8rpKpXq0OyDdFohd7e3NCN8oQDs6407.png?width=520&height=1400", alt: "CMS editor sidebar preview" },
  header_4: { src: "../../framerusercontent.com/images/R2z0U8jUYeP0JRpapIeGR1mGKdA3e2d.png?width=2760&height=150", alt: "CMS editor header preview" },
  searchRow_3: { src: "../../framerusercontent.com/images/jYDmxYKBes4MJG04lZ1OFXEBc83e2d.png?width=2760&height=150", alt: "CMS search row preview" },
  cmsItem1_3: { src: "../../framerusercontent.com/images/kqnlrwFlDazht592YihJC3J0K00f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem2_3: { src: "../../framerusercontent.com/images/1XXeRAVlMnRbQ1WWneq1d9Nl5lQ0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem3_3: { src: "../../framerusercontent.com/images/sK1zK3HACiMnQYVCxeZrOZskuY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem4_3: { src: "../../framerusercontent.com/images/v9pwGgBVZkUx2owTzQRkVHmtZdM0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem5_3: { src: "../../framerusercontent.com/images/imtvP46cYCj0aPxb5qXA0GWKeHs0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem6_3: { src: "../../framerusercontent.com/images/sku8XSsM7FaTRvUjyXn0bl7FxRM0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem7_3: { src: "../../framerusercontent.com/images/DpJGCRixy5rN6iW9UL3GdMwWuY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem8_3: { src: "../../framerusercontent.com/images/kHLjCnG1LcrqAcRDmY9L7O8WQhQ0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem9_3: { src: "../../framerusercontent.com/images/YdiKOgEO0YR0SpypfJJ5bZIeIHY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem10_3: { src: "../../framerusercontent.com/images/6eQfOdmS9duVZhhQ1GV5bWSEY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  text_7: "Turn spreadsheets into dynamic website pages",
  text_8: "Drop in a",
  text_9: ".csv",
  text_10: "file and the agent reads your columns, creates the collection schema, maps every field, and populates all items. Your data is live and editable in seconds.",
  topbar2_9: "CMS",
  default_5: "Site",
  default_6: "·",
  off_3: "main",
  topbar2_10: { src: "/images/1534cc3a-LPkXlDTlZn3Gg3nOt0vzCxLJXU20cf.png?width=512&height=512", alt: "CMS interface preview image" },
  topbar2_11: "Invite",
  topbar2_12: "Publish",
  collectionsPanel_35: "Collections",
  collectionsPanel_36: "Fields",
  collectionsPanel_37: "Plugins",
  collectionsPanel_38: "Blog",
  collectionsPanel_39: "Careers",
  collectionsPanel_40: "Case Studies",
  collectionsPanel_41: "Changelog",
  collectionsPanel_42: "Updates",
  collectionsPanel_43: "51",
  collectionsPanel_44: "Categories",
  collectionsPanel_45: "3",
  collectionsPanel_46: "Guides",
  collectionsPanel_47: "Help",
  collectionsPanel_48: "Add...",
  tableHeader: "Title",
  tableHeader_2: "Category",
  tableHeader_3: "Date",
  tableHeader_4: "Status",
  title_20: "Fixed OAuth token refresh failing silently",
  dark_20: "Bug Fix",
  date_7: "16/06/26",
  live_15: "Live",
  title_21: "Redesigned onboarding flow for new workspaces",
  dark_21: "Improvement",
  date_8: "13/06/26",
  live_16: "Live",
  title_22: "Added real-time collaboration cursors",
  dark_22: "New Feature",
  date_9: "10/06/26",
  live_17: "Live",
  title_23: "Resolved memory leak in dashboard charts",
  dark_23: "Bug Fix",
  date_10: "07/06/26",
  live_18: "Live",
  title_24: "Introduced webhook retry with exponential backoff",
  dark_24: "New Feature",
  date_11: "04/06/26",
  live_19: "Live",
  sidebar_4: { src: "../../framerusercontent.com/images/8rpKpXq0OyDdFohd7e3NCN8oQDs6407.png?width=520&height=1400", alt: "CMS editor sidebar preview" },
  header_5: { src: "../../framerusercontent.com/images/R2z0U8jUYeP0JRpapIeGR1mGKdA3e2d.png?width=2760&height=150", alt: "CMS editor header preview" },
  searchRow_4: { src: "../../framerusercontent.com/images/jYDmxYKBes4MJG04lZ1OFXEBc83e2d.png?width=2760&height=150", alt: "CMS search row preview" },
  cmsItem1_4: { src: "../../framerusercontent.com/images/kqnlrwFlDazht592YihJC3J0K00f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem2_4: { src: "../../framerusercontent.com/images/1XXeRAVlMnRbQ1WWneq1d9Nl5lQ0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem3_4: { src: "../../framerusercontent.com/images/sK1zK3HACiMnQYVCxeZrOZskuY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem4_4: { src: "../../framerusercontent.com/images/v9pwGgBVZkUx2owTzQRkVHmtZdM0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem5_4: { src: "../../framerusercontent.com/images/imtvP46cYCj0aPxb5qXA0GWKeHs0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem6_4: { src: "../../framerusercontent.com/images/sku8XSsM7FaTRvUjyXn0bl7FxRM0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem7_4: { src: "../../framerusercontent.com/images/DpJGCRixy5rN6iW9UL3GdMwWuY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem8_4: { src: "../../framerusercontent.com/images/kHLjCnG1LcrqAcRDmY9L7O8WQhQ0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem9_4: { src: "../../framerusercontent.com/images/YdiKOgEO0YR0SpypfJJ5bZIeIHY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem10_4: { src: "../../framerusercontent.com/images/6eQfOdmS9duVZhhQ1GV5bWSEY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  text_11: "Bulk edits, rewrites, and migrations",
  text_12: "Move content between collections, wire up relations across hundreds of items, and rewrite or optimize copy. All in a single prompt.",
  fpAgentsChatBox: "Create a new Authors collection for the Blog with fields for name, avatar, department, bio, and social link.",
  thinking: "Thinking...",
  thinking_2: "Thinking...",
  fpAgentsChatResponse: "Setting up the Authors collection now. Adding fields for name, avatar, department, bio, and social link.",
  chat: "Changes",
  chat_2: "Undo",
  chat_3: "Authors",
  chat_4: "39 Items",
  promptInput: "._R5jbelraal5dp_::placeholder { color: var(--token-f5637926-8ee6-41cb-a320-ec3462d62cd5, rgba(255, 255, 255, 0.4)); opacity: 1; }",
  aiModel: "GPT 5.6",
  aiModel_2: "Terra",
};
