// content for the "Bento" section — extracted by extract-site.
// Edit values here to re-skin the "Bento" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "The details that make content feel alive",
  visual: "Websites with Best Interactive Design",
  visual_2: { src: "/images/98c94d75-JuHsKU14oQN4p8Mxq07JT1giYUQ4fc8.png?width=512&height=451", alt: "CMS interface preview image" },
  visual_3: "Juliet John",
  visual_4: "·",
  visual_5: "5 min read",
  default: "Blog",
  desktop: { src: "../../framerusercontent.com/images/rvUpuCYBRRnUbo59hYTdhBdhgf7c3.jpg?width=1130&height=1130", alt: "CMS desktop interface preview" },
  bentoCard: "Conditional Visibility.",
  bentoCard_2: "Show or hide elements automatically with CMS logic.",
  componentsRowTitle: "Locales",
  cmsCollectionItem: "NL",
  layerTitle: "Dutch",
  layerTitle_2: "35%",
  cmsCollectionItemCopy: "IT",
  layerTitle_3: "Italian",
  layerTitle_4: "100%",
  cmsCollectionItemCopy_2: "CN",
  layerTitle_5: "Chinese",
  layerTitle_6: "90%",
  cmsCollectionItemCopy_3: "FR",
  layerTitle_7: "French",
  layerTitle_8: "75%",
  cmsCollectionItemCopy_4: "ES",
  layerTitle_9: "Spanish",
  layerTitle_10: "15%",
  layerTitle_11: "Add...",
  layersRowTitle: "Search…",
  cmsTableHeader: "English",
  cmsTableHeader_2: "Dutch",
  cmsTableHeader_3: "All",
  center: "Articles",
  center_2: "In Progress",
  center_3: "Getting Started",
  center_4: "In Progress",
  center_5: "Aan de slag",
  center_6: "New",
  center_7: "getting-started",
  center_8: "To Review",
  center_9: "Je kunt kiezen…",
  center_10: "Done",
  center_11: "What’s New",
  center_12: "In Progress",
  bentoCard_3: "Built-in localization.",
  bentoCard_4: "Translate content across languages and serve the right version to the right audience automatically.",
  visual_6: "Academy",
  visual_7: "Case Studies",
  visual_8: "Case Studies",
  visual_9: "99",
  visual_10: "Industries",
  visual_11: "18",
  visual_12: "Companies",
  visual_13: "99",
  visual_14: "Solutions",
  visual_15: "47",
  visual_16: "Developers",
  visual_17: "Events",
  visual_18: "Help",
  visual_19: "Add...",
  bentoCard_5: "Data Collections.",
  bentoCard_6: "Store and organize all your content in one place.",
  deepFiltering: "Search guides…",
  deepFiltering_2: "Categories",
  deepFiltering_3: "All",
  deepFiltering_4: "Design",
  deepFiltering_5: "Components",
  deepFiltering_6: "SEO",
  deepFiltering_7: "Topic",
  deepFiltering_8: "Layout",
  deepFiltering_9: "Levels",
  deepFiltering_10: "Beginner",
  deepFiltering_11: "Intermediate",
  deepFiltering_12: "Advanced",
  bentoCard_7: "Dynamic Filters.",
  bentoCard_8: "Filter CMS lists with search, tabs, toggles, and dropdowns.",
  visual_20: "Categories",
  dark: "Personal",
  dark_2: "Portfolio",
  manyRefs: "Personal",
  manyRefs_2: "Portfolio",
  manyRefs_3: "Blog",
  manyRefs_4: "Business",
  manyRefs_5: "Landing",
  manyRefs_6: "SaaS",
  bentoCard_9: "Unlimited References.",
  bentoCard_10: "Connect collections for flexible content.",
  cmsSorting: "Title",
  cmsSorting_2: "Status",
  cmsSorting_3: "Date",
  title: "Marketing websites with rapid iteration cycles",
  draft: "Draft",
  date: "20/05/26",
  title_2: "E-commerce storefronts with dynamic product catalogs",
  draft_2: "Draft",
  date_2: "15/05/26",
  title_3: "Internal dashboards for real-time team metrics",
  live: "Live",
  date_3: "10/05/26",
  title_4: "Client portals with role-based access control",
  live_2: "Live",
  date_4: "05/05/26",
  title_5: "Documentation hubs with versioned content",
  live_3: "Live",
  date_5: "30/04/26",
  title_6: "Improved search indexing speed by 40%",
  live_4: "Live",
  dark_3: "John Doe",
  date_6: "01/06/26",
  sidebar: { src: "../../framerusercontent.com/images/8rpKpXq0OyDdFohd7e3NCN8oQDs6407.png?width=520&height=1400", alt: "CMS editor sidebar preview" },
  header_2: { src: "../../framerusercontent.com/images/R2z0U8jUYeP0JRpapIeGR1mGKdA3e2d.png?width=2760&height=150", alt: "CMS editor header preview" },
  searchRow: { src: "../../framerusercontent.com/images/jYDmxYKBes4MJG04lZ1OFXEBc83e2d.png?width=2760&height=150", alt: "CMS search row preview" },
  cmsItem1: { src: "../../framerusercontent.com/images/kqnlrwFlDazht592YihJC3J0K00f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem2: { src: "../../framerusercontent.com/images/1XXeRAVlMnRbQ1WWneq1d9Nl5lQ0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem3: { src: "../../framerusercontent.com/images/sK1zK3HACiMnQYVCxeZrOZskuY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem4: { src: "../../framerusercontent.com/images/v9pwGgBVZkUx2owTzQRkVHmtZdM0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem5: { src: "../../framerusercontent.com/images/imtvP46cYCj0aPxb5qXA0GWKeHs0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem6: { src: "../../framerusercontent.com/images/sku8XSsM7FaTRvUjyXn0bl7FxRM0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem7: { src: "../../framerusercontent.com/images/DpJGCRixy5rN6iW9UL3GdMwWuY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem8: { src: "../../framerusercontent.com/images/kHLjCnG1LcrqAcRDmY9L7O8WQhQ0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem9: { src: "../../framerusercontent.com/images/YdiKOgEO0YR0SpypfJJ5bZIeIHY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  cmsItem10: { src: "../../framerusercontent.com/images/6eQfOdmS9duVZhhQ1GV5bWSEY0f15.png?width=2670&height=150", alt: "CMS collection item row preview" },
  sort: "Sorting",
  sort_2: "Status",
  sort_3: "Draft → Live",
  sort_4: "Date",
  sort_5: "New → Old",
  sort_6: "Add…",
  sort_7: "Discard",
  sort_8: "Save",
  sort_9: "Sort by any field.",
  sort_10: "Order by text, date, number, or boolean and combine multiple rules.",
  visual_21: "Collections",
  visual_22: "Fields",
  visual_23: "Plugins",
  visual_24: "Articles",
  visual_25: "Fields",
  visual_26: "Title",
  visual_27: "Slug",
  visual_28: "Image",
  visual_29: "Reference",
  visual_30: "Toggle",
  visual_31: "Icon",
  visual_32: "Color",
  visual_33: "File",
  visual_34: "Link",
  bentoCard_11: "Rich field types.",
  bentoCard_12: "Text, images, rich text, dates, references, and more.",
};
