// content for the "Header" section — extracted by extract-site.
// Edit values here to re-skin the "Header" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  text: "AI agents for designing, updating, and improving sites",
  regular: "https://framer-ai.com/r/signup",
  label: "Start with agents for free",
  regular_2: "https://updates.framer.com/electron/darwin/arm64/Framer.zip?_ga=2.113395847.1447313862.1646043056-273660571.1642151053",
  label_2: "Download app",
  simple: "https://framer-ai.com/index.html#update",
  m: "Update your existing site",
  simple_2: "https://framer-ai.com/index.html#design",
  s: "Style your site",
  simple_3: "https://framer-ai.com/index.html#new-sites",
  m_2: "Build new sites from scratch",
  simple_4: "https://framer-ai.com/index.html#migrate",
  m_3: "Migrate from another tool",
  simple_5: "https://framer-ai.com/index.html#responsive",
  m_4: "Make your site responsive",
  simple_6: "https://framer-ai.com/index.html#components",
  m_5: "Build custom components",
  simple_7: "https://framer-ai.com/index.html#seo",
  l: "Add SEO and gain analytics insights",
  simple_8: "https://framer-ai.com/index.html#cms",
  m_6: "Manage CMS content",
  simple_9: "https://framer-ai.com/index.html#audit",
  s_2: "Fix and audit your site",
  simple_10: "https://framer-ai.com/index.html#external",
  l_2: "Connect Claude & Codex to Framer",
  active: "https://framer-ai.com/index.html#update",
  inactive: "https://framer-ai.com/index.html#design",
  inactive_2: "https://framer-ai.com/index.html#new-sites",
  inactive_3: "https://framer-ai.com/index.html#migrate",
  inactive_4: "https://framer-ai.com/index.html#responsive",
  inactive_5: "https://framer-ai.com/index.html#components",
  inactive_6: "https://framer-ai.com/index.html#seo",
  inactive_7: "https://framer-ai.com/index.html#cms",
  inactive_8: "https://framer-ai.com/index.html#audit",
  inactive_9: "https://framer-ai.com/index.html#external",
  update: { src: "../../framerusercontent.com/images/roRKZ3e9bgsCCBhCdgI94zH62tc4975.png?width=745&height=942", alt: "Agent workflow preview image" },
  update_2: "Update your existing site",
  update_3: "The agent updates copy, structure, sections, and layout across your site while keeping everything editable on the canvas.",
  cards: "Content updates",
  default: "Replace all mentions of “Acme Corp” with “Nebula Labs” across the entire site.",
  copy: "Copy prompt",
  copy_2: "Copy prompt",
  default_2: "Update the pricing page. Change the Pro plan from $29/mo to $39/mo and add a new Enterprise tier with custom pricing.",
  copy_3: "Copy prompt",
  copy_4: "Copy prompt",
  default_3: "Find all text that says “2025” and update it to “2026” across the entire project.",
  copy_5: "Copy prompt",
  copy_6: "Copy prompt",
  upload: "/videos/b0105a24-Hv1hfCwqPMjJBxPjlGRk3L1GZY.mp4",
  cards_2: "Layout changes",
  default_4: "Reorganize the features section from a list layout to a 2x3 grid of feature cards.",
  copy_7: "Copy prompt",
  copy_8: "Copy prompt",
  default_5: "Reorganize the homepage flow based on conversion best practices. Move social proof higher, put pricing before the FAQ, and make sure every section leads naturally into the next with a clear CTA.",
  copy_9: "Copy prompt",
  copy_10: "Copy prompt",
  default_6: "Redesign the homepage layout so the hero takes full viewport height, features stack in an alternating left-right pattern, and the CTA section spans full width with a background image.",
  copy_11: "Copy prompt",
  copy_12: "Copy prompt",
  cards_3: "New sections",
  default_7: "Add a contact form section with name, email, and message fields, and a submit button that shows a success message.",
  copy_13: "Copy prompt",
  copy_14: "Copy prompt",
  default_8: "Add an FAQ section at the bottom of the homepage with 6 questions and answers about our product.",
  copy_15: "Copy prompt",
  copy_16: "Copy prompt",
  default_9: "Add a testimonials carousel section between the features and CTA sections using 3 placeholder testimonials with photos, names, and roles.",
  copy_17: "Copy prompt",
  copy_18: "Copy prompt",
  default_10: "Insert a banner at the top of every page announcing “Black Friday: 40% off all plans. Ends Monday.”",
  copy_19: "Copy prompt",
  copy_20: "Copy prompt",
  design: { src: "../../framerusercontent.com/images/3Z5s3zrjMxb0KdPNibUKh9nATZoc5a1.png?width=742&height=937", alt: "Agent workflow preview image" },
  design_2: "Style your site",
  design_3: "Describe the look you want. The agent takes care of colors, fonts, component styles, motion and effects across your site.",
  upload_2: "https://framerusercontent.com/assets/fjTk71X7GuE2dUNIsH1owtLLrp4.mp4",
  cards_4: "Colors & styles",
  default_11: "Replace all instances of the old orange accent (#FF5733) with our new brand color (#E94560) everywhere on the site.",
  copy_21: "Copy prompt",
  copy_22: "Copy prompt",
  default_12: "Update the entire site to use our new brand colors: primary #1A1A2E, accent #E94560, and light background #F5F5F5.",
  copy_23: "Copy prompt",
  copy_24: "Copy prompt",
  default_13: "Switch the site from light mode to dark mode with dark backgrounds, light text, and updated component colors throughout.",
  copy_25: "Copy prompt",
  copy_26: "Copy prompt",
  cards_5: "Typography",
  default_14: "Update the entire site’s typography. Use Fraunces for headings and Inter for body text.",
  copy_27: "Copy prompt",
  copy_28: "Copy prompt",
  default_15: "Find a font that feels like a luxury fashion magazine, elegant and editorial with italic support, and apply it to all headings.",
  copy_29: "Copy prompt",
  copy_30: "Copy prompt",
  default_16: "Establish a consistent type scale: H1 = 64px, H2 = 48px, H3 = 36px, body = 18px. Apply it across all pages.",
  copy_31: "Copy prompt",
  copy_32: "Copy prompt",
  cards_6: "Style components",
  default_17: "Update all buttons on the site to match our new brand style: fully rounded, filled with the new primary color, and white text.",
  copy_33: "Copy prompt",
  copy_34: "Copy prompt",
  default_18: "Refresh the card components. Update the corner radius, shadow style, and border colors to match the new brand.",
  copy_35: "Copy prompt",
  copy_36: "Copy prompt",
  default_19: "Update the footer design to match the new brand with new colors, updated font styles, and a refreshed layout.",
  copy_37: "Copy prompt",
  copy_38: "Copy prompt",
  cards_7: "Animations & effects",
  default_20: "Add a liquid gradient shader to the hero background with slow, ambient motion.",
  copy_39: "Copy prompt",
  copy_40: "Copy prompt",
  default_21: "Set up staggered animations on the feature cards so each one fades in slightly after the previous.",
  copy_41: "Copy prompt",
  copy_42: "Copy prompt",
  default_22: "Add scroll-triggered animations to every section so each one fades in and slides up as it enters the viewport.",
  copy_43: "Copy prompt",
  copy_44: "Copy prompt",
  default_23: "Add a parallax effect to the hero background so it scrolls slower than the content above it.",
  copy_45: "Copy prompt",
  copy_46: "Copy prompt",
  newSites: { src: "../../framerusercontent.com/images/uTBgxwAhoAACj8gFmNaHhyLHYc5a1.png?width=742&height=937", alt: "Agent workflow preview image" },
  newSites_2: "Build new sites from scratch",
  newSites_3: "The agent creates pages, navigation, sections, typography, colors, images, and layout from a description or reference.",
  upload_3: "https://framerusercontent.com/assets/y9ScI4YwgE4Nc6p5mWx6xQqokNI.mp4",
  cards_8: "Simple landing pages",
  default_24: "Build a landing page for a coffee roastery called “Ember Roast” with a hero featuring a large background image, a “What We Roast” section with 3 coffee blends, testimonials, and a contact form.",
  copy_47: "Copy prompt",
  copy_48: "Copy prompt",
  default_25: "Create a one-page site for a freelance photographer. Minimal black and white design, full-screen photo grid, about section, and inquiry form.",
  copy_49: "Copy prompt",
  copy_50: "Copy prompt",
  default_26: "Make a pre-launch coming soon page for an app called Flowdeck. Dark theme, waitlist email signup, animated gradient background, and a countdown timer.",
  copy_51: "Copy prompt",
  copy_52: "Copy prompt",
  cards_9: "Multi-page sites",
  default_27: "Build a full website for a design agency with these pages: Home, Work, About, Services, Contact. Modern sans-serif font, blue/charcoal color scheme.",
  copy_53: "Copy prompt",
  copy_54: "Copy prompt",
  default_28: "Create a 4-page site for a SaaS product: a landing page with feature sections, pricing with 3 tiers, a blog index page connected to CMS, and a changelog.",
  copy_55: "Copy prompt",
  copy_56: "Copy prompt",
  default_29: "Build a restaurant website with a homepage, menu page pulled from CMS, reservations page with a form, and a gallery.",
  copy_57: "Copy prompt",
  copy_58: "Copy prompt",
  cards_10: "Specific industries",
  default_30: "Create a law firm website. Professional design. Include a hero with a “Schedule a Consultation” CTA, practice areas, attorney profiles, and a contact form.",
  copy_59: "Copy prompt",
  copy_60: "Copy prompt",
  default_31: "Build a personal portfolio for a product designer with case studies as large cards, an experience timeline, and a working contact form.",
  copy_61: "Copy prompt",
  copy_62: "Copy prompt",
  default_32: "Make a site for a real estate agent with property listings from CMS with filters, an agent bio, testimonials, and a contact form.",
  copy_63: "Copy prompt",
  copy_64: "Copy prompt",
  cards_11: "From references",
  default_33: "Here’s a screenshot of a competitor’s site. Build something similar but with our brand colors and logo.",
  copy_65: "Copy prompt",
  copy_66: "Copy prompt",
  default_34: "Reference the layout and structure of example.com/contact as a guide for this page. Use our brand language for the copy.",
  copy_67: "Copy prompt",
  copy_68: "Copy prompt",
  default_35: "Here’s my current WordPress site. Rebuild it in Framer with the same structure and content but a more modern design.",
  copy_69: "Copy prompt",
  copy_70: "Copy prompt",
  migration: { src: "../../framerusercontent.com/images/ooYL52EQxCVriKS1TJesIlV6Ns8a06.png?width=743&height=938", alt: "Agent workflow preview image" },
  migration_2: "Migrate from another tool",
  migration_3: "The agent recreates pages, structure, and CMS content in Framer from a live site, export, or reference.",
  migration_4: { src: "/images/20bd9ae0-twgTURfNMSyM10rDMHDgiClHtg.avif?width=760&height=960", alt: "" },
  cards_12: "From live sites",
  default_36: "Here’s a URL of our current site. Rebuild its structure and visual style in Framer, using our existing brand colors.",
  copy_71: "Copy prompt",
  copy_72: "Copy prompt",
  default_37: "I’m attaching a screenshot of our Webflow site. Rebuild it as closely as possible in Framer.",
  copy_73: "Copy prompt",
  copy_74: "Copy prompt",
  default_38: "Our WordPress site is at this URL. Rebuild the homepage and services page in Framer.",
  copy_75: "Copy prompt",
  copy_76: "Copy prompt",
  cards_13: "Pages and structure",
  default_39: "Recreate these 5 pages from our old site: Home, About, Services, Blog, and Contact. Match the information hierarchy.",
  copy_77: "Copy prompt",
  copy_78: "Copy prompt",
  default_40: "Rebuild our navigation structure with a top nav with dropdowns and a matching footer with grouped links.",
  copy_79: "Copy prompt",
  copy_80: "Copy prompt",
  default_41: "Set up the same page hierarchy we had in Webflow: Home > Services > [Service Name].",
  copy_81: "Copy prompt",
  copy_82: "Copy prompt",
  cards_14: "CMS and content",
  default_42: "Migrate our WordPress blog posts into a Framer CMS Blog collection. Map the post title, body, date, and featured image.",
  copy_83: "Copy prompt",
  copy_84: "Copy prompt",
  default_43: "Move our Contentful content model into Framer CMS. Here are the fields for each collection.",
  copy_85: "Copy prompt",
  copy_86: "Copy prompt",
  default_44: "Import our old FAQ data from a spreadsheet and populate a new Framer FAQ collection.",
  copy_87: "Copy prompt",
  copy_88: "Copy prompt",
  responsive: { src: "../../framerusercontent.com/images/wIMcRPunUhvY1t5ApmFnTpuxwK04cba.png?width=739&height=933", alt: "Agent workflow preview image" },
  responsive_2: "Make your site responsive",
  responsive_3: "The agent improves layouts, spacing, hierarchy, and breakpoints across your site for tablet and mobile screens.",
  upload_4: "https://framerusercontent.com/assets/OsrYQdZJwkTVrEYjJEDTeZBY00.mp4",
  cards_15: "Full responsive pass",
  default_45: "Make the entire site responsive. Set up tablet and mobile breakpoints, stack columns vertically on mobile, and resize text for readability.",
  copy_89: "Copy prompt",
  copy_90: "Copy prompt",
  default_46: "Do a full responsive pass on all pages and fix any layouts that break at tablet or mobile widths.",
  copy_91: "Copy prompt",
  copy_92: "Copy prompt",
  default_47: "Reset all responsive breakpoints and rebuild from scratch with a mobile-first approach.",
  copy_93: "Copy prompt",
  copy_94: "Copy prompt",
  cards_16: "Breakpoints and spacing",
  default_48: "The features grid should go from 3 columns on desktop to 2 on tablet to 1 on mobile.",
  copy_95: "Copy prompt",
  copy_96: "Copy prompt",
  default_49: "The nav should collapse into a hamburger menu on tablet and mobile.",
  copy_97: "Copy prompt",
  copy_98: "Copy prompt",
  default_50: "On mobile, hide the sidebar and make the main content full width.",
  copy_99: "Copy prompt",
  copy_100: "Copy prompt",
  cards_17: "Cleanups",
  default_51: "Fix the hero section on mobile. The headline is too large, the image overlaps the text, and the CTA button is too small.",
  copy_101: "Copy prompt",
  copy_102: "Copy prompt",
  default_52: "The mobile version looks off. Go through each section and fix any overlaps, text truncation, or layout issues.",
  copy_103: "Copy prompt",
  copy_104: "Copy prompt",
  default_53: "Clean up spacing inconsistencies across breakpoints. Some sections have too much padding on mobile, others too little.",
  copy_105: "Copy prompt",
  copy_106: "Copy prompt",
  components: { src: "../../framerusercontent.com/images/96YnYarfaXDEY7pUCIMXIGfH8yUc96a.png?width=745&height=941", alt: "Agent workflow preview image" },
  components_2: "Build custom components",
  components_3: "The agent builds custom components from creative interactions to practical tools, including animations, calculators, forms, and dynamic content.",
  upload_5: "https://framerusercontent.com/assets/zft4DYOLHdvImJg981zDtfJnw.mp4",
  cards_18: "No-code components",
  default_54: "Make an FAQ accordion where each row expands and collapses when clicked.",
  copy_107: "Copy prompt",
  copy_108: "Copy prompt",
  default_55: "Create a tabbed pricing section that switches between Monthly and Yearly plans.",
  copy_109: "Copy prompt",
  copy_110: "Copy prompt",
  default_56: "Build a multi-step onboarding card with Back and Next buttons that steps through 3 screens.",
  copy_111: "Copy prompt",
  copy_112: "Copy prompt",
  cards_19: "Advanced code components",
  default_57: "Build a cursor trail where images follow the mouse, getting smaller and fading out as they fall behind, with a soft delay so it feels smooth.",
  copy_113: "Copy prompt",
  copy_114: "Copy prompt",
  default_58: "Build a 3D carousel that displays images in a draggable, rotating ring that speeds up on scroll and gently decelerates when released.",
  copy_115: "Copy prompt",
  copy_116: "Copy prompt",
  default_59: "Add a confetti burst animation that fires when the waitlist form is submitted successfully.",
  copy_117: "Copy prompt",
  copy_118: "Copy prompt",
  seo: { src: "../../framerusercontent.com/images/oaHqRmPkOcioKxyADgCJp7aWy4Yad60.png?width=756&height=960", alt: "Agent workflow preview image" },
  seo_2: "Add SEO and gain analytics insights",
  seo_3: "The agent handles titles, descriptions, alt text, and Open Graph content, and surfaces analytics insights so every page is discoverable and measurable.",
  cards_20: "Site-wide SEO",
  default_60: "Set up SEO metadata for every page including the page title, meta description, and Open Graph image.",
  copy_119: "Copy prompt",
  copy_120: "Copy prompt",
  default_61: "Audit the site for SEO basics. Check all pages have unique titles, descriptions, and proper heading hierarchy.",
  copy_121: "Copy prompt",
  copy_122: "Copy prompt",
  default_62: "Check this page for missing semantic HTML tags. Set proper tags on frames (header, nav, section, article, footer etc.) and headers (h1–h6) for better structure.",
  copy_123: "Copy prompt",
  copy_124: "Copy prompt",
  cards_21: "Metadata & Open Graph",
  default_63: "Write compelling meta descriptions for all 5 pages, under 160 characters, with relevant keywords.",
  copy_125: "Copy prompt",
  copy_126: "Copy prompt",
  default_64: "Add Open Graph tags to the homepage so it previews correctly when shared on social. Set the OG title, description, and image.",
  copy_127: "Copy prompt",
  copy_128: "Copy prompt",
  default_65: "Make a pre-launch coming soon page for an app called Flowdeck. Dark theme, waitlist email signup, animated gradient background, and a countdown timer.",
  copy_129: "Copy prompt",
  copy_130: "Copy prompt",
  cards_22: "Alt text",
  default_66: "Add alt text to every image on this site based on its context and surrounding content.",
  copy_131: "Copy prompt",
  copy_132: "Copy prompt",
  default_67: "Create a one-page site for a freelance photographer. Minimal black and white design, full-screen photo grid, about section, and inquiry form.",
  copy_133: "Copy prompt",
  copy_134: "Copy prompt",
  default_68: "Make a pre-launch coming soon page for an app called Flowdeck. Dark theme, waitlist email signup, animated gradient background, and a countdown timer.",
  copy_135: "Copy prompt",
  copy_136: "Copy prompt",
  cards_23: "Analytics",
  default_69: "What are my top traffic sources right now, and roughly how big is each one?",
  copy_137: "Copy prompt",
  copy_138: "Copy prompt",
  default_70: "What’s my overall bounce rate on the pricing page this month? Compare it to last month.",
  copy_139: "Copy prompt",
  copy_140: "Copy prompt",
  default_71: "Out of all my blog posts, which one is getting the most traffic this quarter?",
  copy_141: "Copy prompt",
  copy_142: "Copy prompt",
  default_72: "Did visitor numbers spike after I launched the new landing page on Tuesday?",
  copy_143: "Copy prompt",
  copy_144: "Copy prompt",
  default_73: "What’s my average session duration this year, and is it trending up or down?",
  copy_145: "Copy prompt",
  copy_146: "Copy prompt",
  cms: { src: "../../framerusercontent.com/images/d7J1LYwRQcByAYA4YvyLrlHTMs38ca.png?width=737&height=931", alt: "Agent workflow preview image" },
  cms_2: "Manage your CMS content",
  cms_3: "The agent creates collections, updates fields, imports content, and connects your CMS directly to pages on your site.",
  upload_6: "https://framerusercontent.com/assets/9c3jlD49UgvysLEHSTU5nXyf6Is.mp4",
  cards_24: "Collections",
  default_74: "Create a Blog CMS collection with fields: Title, Slug, Author, Category (dropdown), Publish Date, Featured Image, Body (rich text), and an “Is Featured” toggle.",
  copy_147: "Copy prompt",
  copy_148: "Copy prompt",
  default_75: "Set up a Team Members collection with: Name, Role, Department, Photo, Bio, LinkedIn URL, and Sort Order.",
  copy_149: "Copy prompt",
  copy_150: "Copy prompt",
  default_76: "Create a Jobs collection with: Title, Department, Location (dropdown), Type (Full-time/Contract), Description (rich text), and Application URL.",
  copy_151: "Copy prompt",
  copy_152: "Copy prompt",
  cards_25: "Field updates",
  default_77: "Add a “Read Time” field to the Blog collection and calculate it for all existing posts based on content length.",
  copy_153: "Copy prompt",
  copy_154: "Copy prompt",
  default_78: "Reorganize the CMS categories. Merge “UI Design” and “UX Design” into a single “Design” category across all posts.",
  copy_155: "Copy prompt",
  copy_156: "Copy prompt",
  default_79: "Add a “Published” toggle field to the Portfolio collection and set it to true for all existing items.",
  copy_157: "Copy prompt",
  copy_158: "Copy prompt",
  cards_26: "Content imports",
  default_80: "Move every item from the “News” collection into “Articles”, and convert the Category text field into a dropdown using its existing values.",
  copy_159: "Copy prompt",
  copy_160: "Copy prompt",
  default_81: "Import this CSV file into the Blog collection and match columns to the CMS fields Title, Slug, Author, Publish Date, and Body.",
  copy_161: "Copy prompt",
  copy_162: "Copy prompt",
  default_82: "Migrate all the blog content from my old site into the CMS using this JSON file.",
  copy_163: "Copy prompt",
  copy_164: "Copy prompt",
  audit: { src: "../../framerusercontent.com/images/M94bAhBqE045z6QIHWQWyM7Q88cc.png?width=739&height=934", alt: "Agent workflow preview image" },
  audit_2: "Fix and audit your site",
  audit_3: "The agent scans your site, catches broken links, accessibility issues, and inconsistencies, then fixes them.",
  upload_7: "https://framerusercontent.com/assets/J3F8922ojC5e5j2phNjjThFs6q8.mp4",
  cards_27: "Broken links & redirects",
  default_83: "Scan the entire site for broken external links and list any that return a 404.",
  copy_165: "Copy prompt",
  copy_166: "Copy prompt",
  default_84: "Find all internal links that point to pages that no longer exist and suggest replacements.",
  copy_167: "Copy prompt",
  copy_168: "Copy prompt",
  default_85: "Find any redirects that are chained together — where one redirect points to another — and make them go directly to the final destination.",
  copy_169: "Copy prompt",
  copy_170: "Copy prompt",
  cards_28: "Accessibility",
  default_86: "Add descriptive alt text to every image that’s missing it, using the surrounding content as context.",
  copy_171: "Copy prompt",
  copy_172: "Copy prompt",
  default_87: "Check all form fields have proper labels and that error messages are readable by screen readers.",
  copy_173: "Copy prompt",
  copy_174: "Copy prompt",
  default_88: "Check every page for text that’s too small or low contrast to read comfortably — fix anything that fails basic readability standards.",
  copy_175: "Copy prompt",
  copy_176: "Copy prompt",
  cards_29: "Consistency & QA",
  default_89: "Audit the site for consistency — heading sizes, button styles, and spacing should be uniform across all pages.",
  copy_177: "Copy prompt",
  copy_178: "Copy prompt",
  default_90: "Find every page where body text is smaller than 16px and fix it.",
  copy_179: "Copy prompt",
  copy_180: "Copy prompt",
  default_91: "Scan for any hardcoded colors that aren’t part of the design system and replace them with the correct tokens.",
  copy_181: "Copy prompt",
  copy_182: "Copy prompt",
  external: { src: "../../framerusercontent.com/images/iry0OmCvWEcHFk2SAmMLcJIT0c48bd.png?width=746&height=943", alt: "Agent workflow preview image" },
  external_2: "Connect external agents to Framer",
  external_3: "The agent connects Framer to tools like Claude, Cursor, and Codex so they can read, update, and help build your site.",
  regular_3: "https://framer-ai.com/external",
  label_3: "Get started with External Agents",
  upload_8: "https://framerusercontent.com/assets/ddhrdrtFtoAY3SOdwG7Sr3jIubQ.mp4",
  default_92: "Populate the Team CMS collection with headshots from my local /assets/headshots folder — match each image to the right team member by filename.",
  copy_183: "Copy prompt",
  copy_184: "Copy prompt",
  default_93: "Merge the landing page from my other Framer project into this one and remap all the text and color styles to match this project’s design system.",
  copy_185: "Copy prompt",
  copy_186: "Copy prompt",
  default_94: "Using Xquik, find 12 recent tweets praising @framer, build a tweet card component in dark mode, and create a fading ticker section with the tweets.",
  copy_187: "Copy prompt",
  copy_188: "Copy prompt",
  default_95: "Ensure every URL in this redirects spreadsheet has a redirect set up in Framer pointing to its new destination.",
  copy_189: "Copy prompt",
  copy_190: "Copy prompt",
  default_96: "Import the “Changelog” Notion database into the CMS using the Notion API. Sync every hour and update changed rows.",
  copy_191: "Copy prompt",
  copy_192: "Copy prompt",
};
