// content for the "Bento" section — extracted by extract-site.
// Edit values here to re-skin the "Bento" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "Your toolkit for building with Agents",
  regular: "https://framer-ai.com/ai",
  label: "Explore AI tools",
  skills: "Skills",
  skills_2: "/cms",
  skills_3: "Write content",
  skills_4: "/component",
  skills_5: "With variants",
  skills_6: "/code",
  skills_7: "Custom component",
  modal: "GPT 5.6 Terra",
  bentoCard: "Skills",
  bentoCard_2: ". Type",
  bentoCard_3: "/",
  bentoCard_4: "to run AI actions for layouts, CMS, and more.",
  variant5: "Agents",
  modal_2: "Agents",
  modal_3: "Sonnet 4.6",
  modal_4: "GPT 5.6 Terra",
  bentoCard_5: "Contexts.",
  bentoCard_6: "Select layers on the canvas and add them as context to your chat.",
  bentoCard_7: { src: "../../framerusercontent.com/images/dAFan1VxirMZunaMcFocuFwhBbce2ce.png?width=774&height=960", alt: "" },
  bentoCard_8: "Chats",
  bentoCard_9: ".",
  bentoCard_10: "Start a new one for each task to keep the agent focused.",
  bentoCard_11: { src: "../../framerusercontent.com/images/2Jdw0sFeSB2IPiI3Y0u7s2aQbbse2ce.png?width=774&height=960", alt: "" },
  bentoCard_12: { src: "../../framerusercontent.com/images/PUqtETbbS09YldTynzBona6Hrg8161.png?width=674&height=714", alt: "" },
  bentoCard_13: "Models.",
  bentoCard_14: "Choose between Sonnet, Opus, and GPT depending on the task.",
  visual: { src: "../../framerusercontent.com/images/wpnQdLIgQf5i1S8PVOlKs2hmdqcbc45.png?width=714&height=714", alt: "" },
  skills_8: "Skills",
  skills_9: "/cms",
  skills_10: "Write content",
  skills_11: "/component",
  skills_12: "With variants",
  skills_13: "/code",
  skills_14: "Custom component",
  modal_5: "GPT 5.6 Terra",
  bentoCard_15: "Mentions.",
  bentoCard_16: "Type",
  bentoCard_17: "@",
  bentoCard_18: "to reference pages, CMS collections, styles, or assets.",
  text2: "Turn the content of this",
  text2_2: "blog.csv",
  text2_3: "file into a new CMS collection.",
  modal_6: "GPT 5.6 Terra",
  googleSheets2020LogoSvg: { src: "/images/ecd0e572-0MKr6LOGY3ELX5n4AOEiBFsAheM9eb2.png?lossless=1&width=298&height=368", alt: "Google Sheets file icon" },
  paragraph1: "blog",
  text1: ".csv",
  googleSheets2020LogoSvg_2: { src: "/images/dc41410a-xQAugbEjOsz03Dfywue7L0EwDJM0d5d.png?width=196&height=270", alt: "Google Sheets file icon" },
  paragraph2: "DESIGN",
  text2_4: ".md",
  image1: { src: "../../framerusercontent.com/images/SEiY1UIr27Zx5IOtiQceucHmgWQ231a.png?width=100&height=100", alt: "AI file management preview" },
  paragraph3: "shader",
  text3: ".mp4",
  googleSheets2020LogoSvg_3: { src: "../../framerusercontent.com/images/HqhpYalvutcc7AdEFGtQGexFwM0d5d.png?width=196&height=270", alt: "Google Sheets file icon" },
  text4: "data",
  paragraph4: ".json",
  googleSheets2020LogoSvg_4: { src: "/images/df4a3b3a-roMzqQzv6zt82Nf6hwVhNYFdCY62a7.png?lossless=1&width=196&height=270", alt: "Google Sheets file icon" },
  paragraph5: "component",
  text5: ".tsx",
  image2: { src: "/images/826be7ba-bpcTK14Q5FHUeueY7pX2uskOWgdaaf.png?width=411&height=395", alt: "AI file management preview" },
  paragraph6: "screenshot",
  text6: ".png",
  googleSheets2020LogoSvg_5: { src: "/images/ecd0e572-0MKr6LOGY3ELX5n4AOEiBFsAheM9eb2.png?lossless=1&width=298&height=368", alt: "Google Sheets file icon" },
  paragraph7: "blog",
  text7: ".csv",
  googleSheets2020LogoSvg_6: { src: "/images/dc41410a-xQAugbEjOsz03Dfywue7L0EwDJM0d5d.png?width=196&height=270", alt: "Google Sheets file icon" },
  paragraph8: "DESIGN",
  text8: ".md",
  image3: { src: "/images/3e1ec715-8g3xxGt9M0DZ1pjRquaYUjsLWM5be1.jpg?width=200&height=200", alt: "AI file management preview" },
  paragraph9: "shader",
  text9: ".mp4",
  googleSheets2020LogoSvg_7: { src: "../../framerusercontent.com/images/HqhpYalvutcc7AdEFGtQGexFwM0d5d.png?width=196&height=270", alt: "Google Sheets file icon" },
  text10: "data",
  paragraph10: ".json",
  googleSheets2020LogoSvg_8: { src: "/images/df4a3b3a-roMzqQzv6zt82Nf6hwVhNYFdCY62a7.png?lossless=1&width=196&height=270", alt: "Google Sheets file icon" },
  paragraph11: "component",
  text11: ".tsx",
  image4: { src: "/images/826be7ba-bpcTK14Q5FHUeueY7pX2uskOWgdaaf.png?width=411&height=395", alt: "AI file management preview" },
  paragraph12: "screenshot",
  text12: ".png",
  googleSheets2020LogoSvg_9: { src: "/images/ecd0e572-0MKr6LOGY3ELX5n4AOEiBFsAheM9eb2.png?lossless=1&width=298&height=368", alt: "Google Sheets file icon" },
  paragraph13: "blog",
  text13: ".csv",
  bentoCard_19: "References",
  bentoCard_20: ". Upload images, files, or URLs to guide AI toward the exact result you want.",
  bentoCard_21: { src: "../../framerusercontent.com/images/AouULSaM4MsGwUBuwDJXdHCgYbb4d.png?width=1158&height=1440", alt: "" },
  bentoCard_22: "/collaborate",
  bentoCard_23: "Branches",
  bentoCard_24: ".",
  bentoCard_25: "Iterate safely by moving agent edits to a branch.",
};
