// content for the "Benefits" section — extracted by extract-site.
// Edit values here to re-skin the "Benefits" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "From design to deploy, together",
  layerTitle: "SOC 2",
  layerTitle_2: "ISO",
  layerTitle_3: "CCPA",
  layerTitle_4: "CCPA",
  layerTitle_5: "GDPR",
  l: "https://framer-ai.com/legal/security",
  l_2: "Enterprise-grade security",
  text: "SSO, role-based access, and enterprise-grade compliance keep everything protected. SOC 2 Type 2, ISO 27001, and GDPR compliance ensure your data stays secure.",
  breakpoint: "Desktop",
  top: "Create a few layout",
  chatBox: "variations of my site. Keep the content but try some different compositions.",
  thinking: "Thinking...",
  thinking_2: "Thinking...",
  designPlan: "Created a design plan",
  designPlan_2: "2s",
  text_2: "Placing layout variations side by side.",
  promptInput: "._Rmdepakil5dp_::placeholder { color: var(--token-f5637926-8ee6-41cb-a320-ec3462d62cd5, rgba(255, 255, 255, 0.4)); opacity: 1; }",
  aiModel: "GPT 5.6",
  aiModel_2: "Terra",
  l_3: "/ai",
  l_4: "Design with an agent",
  text_3: "Start from a prompt and watch the agent generate layouts, sections, and visual style directly on your canvas. Refine typography, spacing, and color until it looks exactly right.",
  branches: "Branches",
  input: "Search…",
  dropdown: "All",
  main: "main",
  main_2: "1m",
  branch: { src: "/images/8d225e32-PNKbO6dGnRRwEvctPlhddS3H2s20cf.png?width=512&height=512", alt: "Framer user avatar" },
  branch_2: "home-2026",
  branch_3: "3m",
  branch_4: { src: "/images/96913bcf-OmKDjH7juzfJ8ETRwLy9hglwa0f73b.png?width=192&height=192", alt: "Framer user avatar" },
  branch_5: "use-cases",
  subBranch: { src: "/images/8d225e32-PNKbO6dGnRRwEvctPlhddS3H2s20cf.png?width=512&height=512", alt: "Framer user avatar" },
  subBranch_2: "publishing",
  subBranch_3: "8m",
  subBranch_4: { src: "/images/1ea3b48d-kFiEvDg0LczTmqWVkfNUFTc5020cf.png?width=512&height=512", alt: "Framer user avatar" },
  subBranch_5: "content",
  subBranch_6: "10m",
  changes: "Changes",
  change: "Home",
  change_2: { src: "/images/96913bcf-OmKDjH7juzfJ8ETRwLy9hglwa0f73b.png?width=192&height=192", alt: "Framer user avatar" },
  change_3: "/pricing",
  change_4: { src: "/images/96913bcf-OmKDjH7juzfJ8ETRwLy9hglwa0f73b.png?width=192&height=192", alt: "Framer user avatar" },
  change_5: "Updates",
  change_6: { src: "/images/9df3bd04-56Di5cRNO9igcAj63PSR0NxPQ12f3.png?width=400&height=400", alt: "Framer user avatar" },
  change_7: { src: "/images/1ea3b48d-kFiEvDg0LczTmqWVkfNUFTc5020cf.png?width=512&height=512", alt: "Framer user avatar" },
  cmsChange: "Shaders",
  cmsChange_2: { src: "/images/9df3bd04-56Di5cRNO9igcAj63PSR0NxPQ12f3.png?width=400&height=400", alt: "Framer user avatar" },
  cmsChange_3: "Vectors",
  cmsChange_4: { src: "/images/1ea3b48d-kFiEvDg0LczTmqWVkfNUFTc5020cf.png?width=512&height=512", alt: "Framer user avatar" },
  button: "Merge",
  button_2: "to main",
  l_5: "/collaborate",
  l_6: "Design together, ship together",
  text_4: "Branch changes safely, stage before launch, and assign roles that match how your team actually designs, reviews, and ships work together.",
  webVitals: "Core Web Vitals",
  webVitals_2: "GOOD",
  webVitals_3: "LCP",
  webVitals_4: "1.1s",
  webVitals_5: "INP",
  webVitals_6: "95ms",
  webVitals_7: "CLS",
  webVitals_8: "0.01",
  l_7: "/hosting",
  l_8: "Your site grows with your team",
  text_5: "From startups to global teams, Framer scales effortlessly. Staging safeguards your work, while high-performance hosting ensures fast load times everywhere.",
};
