// content for the "Extras" section — extracted by extract-site.
// Edit values here to re-skin the "Extras" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "All the features you need to go from landing page to big .com",
  default: "https://framer-ai.com/dictionary/on-page-editing",
  title: "On-page editing",
  default_2: "https://framer-ai.com/dictionary/mobile-cms",
  title_2: "Mobile CMS",
  default_3: "https://framer-ai.com/dictionary/tables-in-rich-text",
  title_3: "Tables in rich text",
  default_4: "https://framer-ai.com/dictionary/bulk-operations",
  title_4: "Bulk operations",
  default_5: "https://framer-ai.com/dictionary/up-to-100k-items",
  title_5: "Up to 100K items",
  default_6: "https://framer-ai.com/dictionary/csv-import",
  title_6: "CSV import",
  default_7: "https://framer-ai.com/dictionary/code-blocks",
  title_7: "Code blocks",
  default_8: "https://framer-ai.com/dictionary/google-sheets-sync",
  title_8: "Google Sheets sync",
  default_9: "https://framer-ai.com/dictionary/airtable-sync",
  title_9: "Airtable sync",
  default_10: "https://framer-ai.com/dictionary/cms-galleries",
  title_10: "CMS Galleries",
  default_11: "https://framer-ai.com/dictionary/cms-agents",
  title_11: "CMS agents",
  default_12: "https://framer-ai.com/dictionary/sso",
  title_12: "SSO",
  default_13: "https://framer-ai.com/dictionary/asset-library",
  title_13: "Asset library",
  default_14: "https://framer-ai.com/dictionary/version-history",
  title_14: "Version history",
  default_15: "https://framer-ai.com/dictionary/team-workspaces",
  title_15: "Team workspaces",
  default_16: "https://framer-ai.com/dictionary/custom-domains",
  title_16: "Custom domains",
  default_17: "https://framer-ai.com/dictionary/password-protection",
  title_17: "Password protection",
  default_18: "https://framer-ai.com/dictionary/auto-save",
  title_18: "Auto-save",
  default_19: "https://framer-ai.com/dictionary/multiplayer-cursors",
  title_19: "Multiplayer cursors",
  default_20: "https://framer-ai.com/dictionary/comments",
  title_20: "Comments",
  default_21: "https://framer-ai.com/dictionary/auto-sizing",
  title_21: "Auto sizing",
  default_22: "https://framer-ai.com/dictionary/vector-drawing",
  title_22: "Vector drawing",
  default_23: "https://framer-ai.com/dictionary/smart-components",
  title_23: "Smart components",
  default_24: "https://framer-ai.com/dictionary/scroll-effects",
  title_24: "Scroll effects",
  default_25: "https://framer-ai.com/dictionary/plugins",
  title_25: "Plugins",
};
