// content for the "Stories" section — extracted by extract-site.
// Edit values here to re-skin the "Stories" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "Trusted by teams shipping big sites",
  regular: "/stories",
  label: "Read stories",
  desktop: "https://framer-ai.com/stories/miro",
  logo40px: { src: "/images/18bf3e70-Ll17Dg9HmF3p6UA1Us9m037NPiw.svg?width=57&height=21", alt: "Miro logo" },
  ctaLabel: "Read story",
  bgImage: { src: "../../framerusercontent.com/images/DL8hej2J0ENXehCcjm05h3CmA0975.png?width=2048&height=1070", alt: "Miro customer story preview image" },
  desktop_2: "https://framer-ai.com/stories/perplexity",
  logo40px_2: { src: "../../framerusercontent.com/images/Xflqz4b166Nn6flLSNwZ3YHpnAdce6.png?width=710&height=160", alt: "Perplexity logo" },
  ctaLabel_2: "Read story",
  bgImage_2: { src: "../../framerusercontent.com/images/eGoO50sQnLTjwFBzhi9LqDdU3vQ1112.png?width=2048&height=1152", alt: "Perplexity customer story preview image" },
  desktop_3: "https://framer-ai.com/stories/legora",
  logo30px: { src: "/images/58cf06de-nfqFxnwuHxDsKC4aq6bkL2C5Xc.svg?width=88&height=17", alt: "Legora logo" },
  ctaLabel_3: "Read story",
  bgImage_3: { src: "/images/f03c695a-jTtsVVBhSR0HphLKfSJpeVnmPos.avif?width=1000&height=1250", alt: "Legora customer story preview image" },
  desktop_4: "https://framer-ai.com/stories/mixpanel",
  logo40px_3: { src: "../../framerusercontent.com/images/438CGnEJ8fW9oxKnD8cAdepnjS0f1b8.png?width=556&height=132", alt: "Mixpanel logo" },
  ctaLabel_4: "Read story",
  bgImage_4: { src: "../../framerusercontent.com/images/sxoUHMyDJmczUkVs28JyYftbQGM7ed6.png?width=2680&height=1320", alt: "Mixpanel customer story preview image" },
  desktop_5: "https://framer-ai.com/stories/zapier",
  logo40px_4: { src: "/images/8b898721-HEGqsXen4lEDl1qKEvOdeRAnxQ.svg?width=110&height=30", alt: "Zapier logo" },
  ctaLabel_5: "Read story",
  bgImage_5: { src: "../../framerusercontent.com/images/2HcMn3WE6ABg2DKf1egvCVZpn6s7a70.png?width=2374&height=1746", alt: "Zapier customer story preview image" },
  desktop_6: "https://framer-ai.com/stories/flora",
  logo30px_2: { src: "../../framerusercontent.com/images/IHDPUOs7g9U4PEQJmkEUXMpbsMIab0e.png?width=600&height=96", alt: "Flora logo" },
  ctaLabel_6: "Read story",
  bgImage_6: { src: "../../framerusercontent.com/images/jmDZzRZa7eG7o6UwM4myFdsE668e.png?width=900&height=980", alt: "Flora customer story preview image" },
  desktop_7: "https://framer-ai.com/stories/mutiny",
  logo50px: { src: "/images/3c2468db-NzfMBw82styKJA2j3DPEV081U.svg?width=1000&height=481", alt: "Mutiny logo" },
  ctaLabel_7: "Read story",
  bgImage_7: { src: "../../framerusercontent.com/images/RFqRfs88P7646TFOvUgWoxE01c4d.png?width=648&height=752", alt: "Mutiny customer story preview image" },
  desktop_8: "https://framer-ai.com/stories/stackai",
  logo40px_5: { src: "../../framerusercontent.com/images/lUZ3uzIob6NgeCKawVZCpNKJjEa042.png?width=1052&height=245", alt: "StackAI logo" },
  ctaLabel_8: "Read story",
  bgImage_8: { src: "../../framerusercontent.com/images/u0RvuERtz1FFu2w5kUQAVWmyU7ee6.jpg?width=2460&height=1296", alt: "StackAI customer story preview image" },
};
