// Header.tsx — section converted to a real JSX component by extract-site.
// Editable React: entrance animations are inline framer-motion props with the
// MEASURED timing from the original site; hover effects live in hover.css.
// Copy, photos, and links live in the sibling content module — edit there to
// re-skin this section without touching layout/motion.
import type { CSSProperties } from "react";
import { motion } from "framer-motion";
import content from "../content/02-Header";

export function Header() {
  return (
    <div className="framer-tra9jr" data-framer-name="Header" style={{ width: "1440px", height: "1337px", padding: "0px 0px 100px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center" } as CSSProperties}>
      <section className="framer-1j68g2o" data-framer-name="Hero" id="hero" style={{ width: "1440px", height: "1237px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", backgroundColor: "rgb(0, 0, 0)" } as CSSProperties}>
        <header className="framer-fwyidx" data-framer-name="Header" style={{ width: "1440px", height: "327px", padding: "100px 20px 60px", position: "relative", zIndex: "2", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "20px" } as CSSProperties}>
          <div className="framer-s8hwmk" data-framer-name="Content" style={{ width: "1200px", height: "167px", maxWidth: "1200px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", gap: "25px" } as CSSProperties}>
            <div className="framer-1xg3qxd" data-framer-component-type="RichTextContainer" style={{ width: "587px", height: "108px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre-wrap", transform: "none" } as CSSProperties}>
              <h1 className="framer-text framer-styles-preset-1gzpg4m" data-styles-preset="gM4yNG9Qq" dir="auto" style={{ width: "587px", height: "108px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"GT Walsheim Medium\", \"GT Walsheim Medium Placeholder\", sans-serif", fontSize: "54px", fontWeight: "500", lineHeight: "54px", letterSpacing: "-2.16px", color: "rgb(255, 255, 255)", "--framer-text-alignment": "start" } as CSSProperties}>
                {content.content}
              </h1>
            </div>
            <div className="framer-4eugek" data-framer-name="CTA" style={{ width: "1200px", height: "34px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "10px" } as CSSProperties}>
              <div className="ssr-variant" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
                <div className="framer-8iceo7-container" style={{ width: "149.25px", height: "34px", position: "relative", zIndex: "1", display: "block", flexDirection: "row" } as CSSProperties}>
                  <a className="framer-k8Dz4 framer-qkzqfa framer-v-qkzqfa framer-lt5xhr hv-100" data-framer-name="Regular" data-highlight="true" data-reset="button" tabIndex={0} style={{ width: "149.25px", height: "34px", maxHeight: "35px", padding: "10px 14px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "7px", backgroundColor: "rgb(255, 255, 255)", borderRadius: "8px", color: "rgb(0, 0, 238)", borderBottomLeftRadius: "8px", borderBottomRightRadius: "8px", borderTopLeftRadius: "8px", borderTopRightRadius: "8px", boxShadow: "var(--9xgf7k)", opacity: "1" } as CSSProperties} data-external-route="1" href={content.regular}>
                    <div className="framer-o5mers" data-framer-name="Label" data-framer-component-type="RichTextContainer" style={{ width: "121.25px", height: "14px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 18, \"wght\" 540", "--extracted-r6o4lv": "var(--variable-reference-xdxfhd9wh-KsxdqjKwX)", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", "--variable-reference-rm8thjdvn-ksxdqjkwx": "14", "--variable-reference-xdxfhd9wh-ksxdqjkwx": "rgb(0, 0, 0)", opacity: "1", transform: "none" } as CSSProperties}>
                      <p dir="auto" className="framer-text" style={{ width: "121.25px", height: "14px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "14px", lineHeight: "14px", letterSpacing: "-0.28px", textAlign: "center", color: "rgb(0, 0, 0)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTRMQ0FpZDJkb2RDSWdOVFF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on", "--framer-font-size": "calc(var(--variable-reference-rm8ThjdVN-KsxdqjKwX) * 1px)", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 18, \"wght\" 540)", "--framer-letter-spacing": "-0.02em", "--framer-line-height": "1em", "--framer-text-alignment": "center", "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-xdxfhd9wh-KsxdqjKwX))" } as CSSProperties}>
                        {content.label}
                      </p>
                    </div>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </header>
        <div className="ssr-variant hidden-kkqok7" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
          <div className="framer-es4bri-container" data-framer-name="Solutions Gallery Designers" style={{ width: "1440px", height: "910px", position: "relative", display: "block", flexDirection: "row" } as CSSProperties}>
            <div className="ssr-variant hidden-r05htx" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
              <section className="framer-JAXAj framer-e6nlaa framer-v-e6nlaa" data-framer-name="Desktop" style={{ width: "100%", height: "910px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "40px", opacity: "1" } as CSSProperties}>
                <div className="framer-e5d0wa" data-framer-name="Sites" style={{ width: "1440px", height: "910px", position: "relative", zIndex: "1", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", overflow: "clip", opacity: "1" } as CSSProperties}>
                  <div className="framer-cuxnso" data-framer-name="Ticker Left" style={{ width: "1440px", height: "450px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "10px", overflow: "clip", overflowX: "clip", borderRadius: "0px", opacity: "1" } as CSSProperties}>
                    <motion.ul style={{ width: "100%", height: "100%", maxWidth: "100%", maxHeight: "100%", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", gap: "10px", transform: "translateX(-507.123px)", transformOrigin: "720px 225px", listStyleType: "none", padding: "0px", margin: "0px", opacity: "1", willChange: "transform" } as CSSProperties} initial={{ opacity: 0, x: -10 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                      <li className="ticker-item" aria-hidden="false" aria-posinset={1} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                        <div className="framer-5ru16e" data-border="true" data-framer-name="Example" style={{ width: "720px", height: "450px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "1.6 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                          <div className="framer-1192llx" style={{ width: "720px", height: "450px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                            <div style={{ width: "720px", height: "450px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                              <img decoding="auto" width="2750" height="1718" sizes="(min-width: 1200px) 720px, (min-width: 810px) and (max-width: 1199.98px) 530px, (max-width: 809.98px) 360px" srcSet={"/images/4e9c6729-3hhHzx5C3vi8lG45rSu6hcXwA.avif?scale-down-to=512&width=2750&height=1718 512w,/images/4e9c6729-3hhHzx5C3vi8lG45rSu6hcXwA.avif?scale-down-to=1024&width=2750&height=1718 1024w,/images/4e9c6729-3hhHzx5C3vi8lG45rSu6hcXwA.avif?scale-down-to=2048&width=2750&height=1718 2048w,/images/4e9c6729-3hhHzx5C3vi8lG45rSu6hcXwA.avif?width=2750&height=1718 2750w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2750 / 1718", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.example.src} alt={content.example.alt} />
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="ticker-item" aria-hidden="false" aria-posinset={2} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                        <div className="framer-1oy8si1-container" style={{ width: "250px", height: "450px", position: "relative", display: "block", flexDirection: "row", aspectRatio: "0.555556 / 1", opacity: "1" } as CSSProperties}>
                          <div className="framer-YbP5S framer-kipbz3 framer-v-1h71p1w" data-border="true" data-framer-name="Play" style={{ width: "100%", height: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                            <div className="framer-iuaieu-container" style={{ width: "250px", height: "450px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                              <video loop preload="auto" poster={"/images/15420f37-S1Yx9W76QrhFD6VJLx6CVhHXsM2aed.png?width=506&height=900"} muted playsInline style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", cursor: "auto", borderRadius: "0px", backgroundColor: "rgba(0, 0, 0, 0)", objectPosition: "50% 50%" } as CSSProperties} src={content.play} />
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="ticker-item" aria-hidden="false" aria-posinset={3} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                        <div className="framer-17pzg43" data-border="true" data-framer-name="Example" style={{ width: "720px", height: "450px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "1.6 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                          <div className="framer-182t4ic" style={{ width: "720px", height: "450px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                            <div style={{ width: "720px", height: "450px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                              <img decoding="auto" width="2750" height="1718" sizes="(min-width: 1200px) 720px, (min-width: 810px) and (max-width: 1199.98px) 530px, (max-width: 809.98px) 360px" srcSet={"/images/fe8187fd-ALYslhuu5wgytt7ctYvPtAlkinQ.avif?scale-down-to=512&width=2750&height=1718 512w,/images/fe8187fd-ALYslhuu5wgytt7ctYvPtAlkinQ.avif?scale-down-to=1024&width=2750&height=1718 1024w,/images/fe8187fd-ALYslhuu5wgytt7ctYvPtAlkinQ.avif?scale-down-to=2048&width=2750&height=1718 2048w,/images/fe8187fd-ALYslhuu5wgytt7ctYvPtAlkinQ.avif?width=2750&height=1718 2750w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2750 / 1718", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.example_2.src} alt={content.example_2.alt} />
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="ticker-item" aria-hidden="false" aria-posinset={4} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                        <div className="framer-1s5w8tu-container" style={{ width: "625px", height: "449.992px", position: "relative", display: "block", flexDirection: "row", aspectRatio: "1.38889 / 1", opacity: "1" } as CSSProperties}>
                          <div className="framer-YbP5S framer-kipbz3 framer-v-1h71p1w" data-border="true" data-framer-name="Play" style={{ width: "100%", height: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                            <div className="framer-iuaieu-container" style={{ width: "625px", height: "449.992px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                              <video loop preload="auto" poster={"/images/60555e45-s3NFmI62MIkWUnGOfSgS6I74iIfe33.png?width=1022&height=720"} muted playsInline style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", cursor: "auto", borderRadius: "0px", backgroundColor: "rgba(0, 0, 0, 0)", objectPosition: "50% 50%" } as CSSProperties} src={content.play_2} />
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="ticker-item" aria-hidden="false" aria-posinset={5} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                        <div className="framer-na7p6d" data-border="true" data-framer-name="Example" style={{ width: "720px", height: "450px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "1.6 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                          <div className="framer-8i29ty" style={{ width: "720px", height: "450px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                            <div style={{ width: "720px", height: "450px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                              <img decoding="auto" width="2750" height="1718" sizes="(min-width: 1200px) 720px, (min-width: 810px) and (max-width: 1199.98px) 530px, (max-width: 809.98px) 360px" srcSet={"/images/66c35b4a-Mkr68H5LtwvTGOW4VuxDXBw.avif?scale-down-to=512&width=2750&height=1718 512w,/images/66c35b4a-Mkr68H5LtwvTGOW4VuxDXBw.avif?scale-down-to=1024&width=2750&height=1718 1024w,/images/66c35b4a-Mkr68H5LtwvTGOW4VuxDXBw.avif?scale-down-to=2048&width=2750&height=1718 2048w,/images/66c35b4a-Mkr68H5LtwvTGOW4VuxDXBw.avif?width=2750&height=1718 2750w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2750 / 1718", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.example_3.src} alt={content.example_3.alt} />
                            </div>
                          </div>
                        </div>
                      </li>
                    </motion.ul>
                  </div>
                  {" "}
                  <div className="framer-ypm7t8" data-framer-name="Ticker Right" style={{ width: "1440px", height: "450px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "10px", overflow: "clip", overflowX: "clip", borderRadius: "0px", opacity: "1" } as CSSProperties}>
                    <motion.ul style={{ width: "100%", height: "100%", maxWidth: "100%", maxHeight: "100%", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", gap: "10px", transform: "translateX(-2503.9px)", transformOrigin: "720px 225px", listStyleType: "none", padding: "0px", margin: "0px", opacity: "1", willChange: "transform" } as CSSProperties} initial={{ opacity: 0, x: -10 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                      <li className="ticker-item" aria-hidden="false" aria-posinset={1} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", transformOrigin: "125px 225px", flexGrow: "0", flexShrink: "0" } as CSSProperties}>
                        <div className="framer-1mdp1cg-container" style={{ width: "250px", height: "450px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                          <div className="framer-YbP5S framer-kipbz3 framer-v-kipbz3" data-border="true" data-framer-name="Pause" style={{ width: "100%", height: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                            <div className="framer-iuaieu-container" style={{ width: "250px", height: "450px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                              <video loop preload="metadata" poster={"/images/28a71090-MTNWLPyxhVqHufypxWWfDiX884Qe316.png?width=720&height=1280"} muted playsInline style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", cursor: "auto", borderRadius: "0px", backgroundColor: "rgba(0, 0, 0, 0)", objectPosition: "50% 50%" } as CSSProperties} src={content.pause} />
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="ticker-item" aria-hidden="false" aria-posinset={2} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", transformOrigin: "360px 225px", flexGrow: "0", flexShrink: "0" } as CSSProperties}>
                        <div className="framer-s98dis" data-border="true" data-framer-name="Example" style={{ width: "720px", height: "450px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "1.6 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                          <div className="framer-en7nzh" style={{ width: "720px", height: "450px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                            <div style={{ width: "720px", height: "450px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                              <img decoding="auto" width="2750" height="1718" sizes="(min-width: 1200px) 720px, (min-width: 810px) and (max-width: 1199.98px) 530px, (max-width: 809.98px) 360px" srcSet={"/images/a393fb0c-um6xOghEDN9ZQxpO2aBBpiPkcV8.avif?scale-down-to=512&width=2750&height=1718 512w,/images/a393fb0c-um6xOghEDN9ZQxpO2aBBpiPkcV8.avif?scale-down-to=1024&width=2750&height=1718 1024w,/images/a393fb0c-um6xOghEDN9ZQxpO2aBBpiPkcV8.avif?scale-down-to=2048&width=2750&height=1718 2048w,/images/a393fb0c-um6xOghEDN9ZQxpO2aBBpiPkcV8.avif?width=2750&height=1718 2750w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2750 / 1718", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.example_4.src} alt={content.example_4.alt} />
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="ticker-item" aria-hidden="false" aria-posinset={3} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", transformOrigin: "360px 225px", flexGrow: "0", flexShrink: "0" } as CSSProperties}>
                        <div className="framer-g2er8i" data-border="true" data-framer-name="Example" style={{ width: "720px", height: "450px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "1.6 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                          <div className="framer-1fzj3jl" style={{ width: "720px", height: "450px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                            <div style={{ width: "720px", height: "450px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                              <img decoding="auto" width="2750" height="1718" sizes="(min-width: 1200px) 720px, (min-width: 810px) and (max-width: 1199.98px) 530px, (max-width: 809.98px) 360px" srcSet={"/images/21f1488b-ubhY6w22Yd37IyvQ2G7RAEIvs.avif?scale-down-to=512&width=2750&height=1718 512w,/images/21f1488b-ubhY6w22Yd37IyvQ2G7RAEIvs.avif?scale-down-to=1024&width=2750&height=1718 1024w,/images/21f1488b-ubhY6w22Yd37IyvQ2G7RAEIvs.avif?scale-down-to=2048&width=2750&height=1718 2048w,/images/21f1488b-ubhY6w22Yd37IyvQ2G7RAEIvs.avif?width=2750&height=1718 2750w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2750 / 1718", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.example_5.src} alt={content.example_5.alt} />
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="ticker-item" aria-hidden="false" aria-posinset={4} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", transformOrigin: "360px 225px", flexGrow: "0", flexShrink: "0" } as CSSProperties}>
                        <div className="framer-ao6h8c" data-border="true" data-framer-name="Example" style={{ width: "720px", height: "450px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", aspectRatio: "1.6 / 1", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                          <div className="framer-1fgau91" style={{ width: "720px", height: "450px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                            <div style={{ width: "720px", height: "450px", position: "absolute", display: "block", flexDirection: "row", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0" } as CSSProperties} data-framer-background-image-wrapper="true">
                              <img decoding="auto" width="2750" height="1718" sizes="(min-width: 1200px) 720px, (min-width: 810px) and (max-width: 1199.98px) 530px, (max-width: 809.98px) 360px" srcSet={"/images/f8154b3c-f9WONOXuv6O63cVnwX91fkiHGus.avif?scale-down-to=512&width=2750&height=1718 512w,/images/f8154b3c-f9WONOXuv6O63cVnwX91fkiHGus.avif?scale-down-to=1024&width=2750&height=1718 1024w,/images/f8154b3c-f9WONOXuv6O63cVnwX91fkiHGus.avif?scale-down-to=2048&width=2750&height=1718 2048w,/images/f8154b3c-f9WONOXuv6O63cVnwX91fkiHGus.avif?width=2750&height=1718 2750w"} style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", aspectRatio: "auto 2750 / 1718", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center" } as CSSProperties} src={content.example_6.src} alt={content.example_6.alt} />
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="ticker-item" aria-hidden="false" aria-posinset={5} aria-setsize={5} style={{ width: "fit-content", height: "fit-content", position: "relative", display: "list-item", flexDirection: "row", flexGrow: "0", flexShrink: "0", transform: "none" } as CSSProperties}>
                        <div className="framer-ykugf-container" style={{ width: "575px", height: "449.992px", position: "relative", display: "block", flexDirection: "row", aspectRatio: "1.27778 / 1", opacity: "1" } as CSSProperties}>
                          <div className="framer-YbP5S framer-kipbz3 framer-v-kipbz3" data-border="true" data-framer-name="Pause" style={{ width: "100%", height: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "15px", overflow: "clip", "--border-bottom-width": "1px", "--border-color": "var(--token-c534b380-e14e-4ddc-9802-ad88d1f94f8e, rgba(255, 255, 255, 0.1))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
                            <div className="framer-iuaieu-container" style={{ width: "575px", height: "449.992px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                              <video loop preload="metadata" poster={"/images/1a71a709-0tqKzALZ8gu4FKfEi0jeJUTUxOs136e.png?width=958&height=720"} muted playsInline style={{ width: "100%", height: "100%", position: "static", display: "block", flexDirection: "row", overflow: "clip", objectFit: "cover", cursor: "auto", borderRadius: "0px", backgroundColor: "rgba(0, 0, 0, 0)", objectPosition: "50% 50%" } as CSSProperties} src={content.pause_2} />
                            </div>
                          </div>
                        </div>
                      </li>
                    </motion.ul>
                  </div>
                  {" "}
                </div>
              </section>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
