// content for the "Case Studies" section — extracted by extract-site.
// Edit values here to re-skin the "Case Studies" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  doordash: { src: "../../framerusercontent.com/images/CzIt9BMelg2aZTj4oJO6F3lIMzU8f22.png?width=644&height=768", alt: "" },
  l: "https://auto.doordash.com/",
  l_2: "Visit site",
  dribbble: { src: "../../framerusercontent.com/images/CPFW3uiMfnXMVx2DxgHiZsnA459b3.png?width=868&height=932", alt: "" },
  l_3: "https://framer-ai.com/dribbble",
  l_4: "Read story",
  nba: { src: "../../framerusercontent.com/images/U5dfNq7wU60AQEebMnh2U09Ras86d6.png?width=1252&height=1534", alt: "" },
  l_5: "https://www.launchpad.nba.com/",
  l_6: "Visit site",
  zapier: { src: "../../framerusercontent.com/images/8pD68YvWk5laMvt1NjuOKaKKAMQb9c2.jpg?width=1872&height=1248", alt: "" },
  l_7: "https://groupme.com/",
  l_8: "Visit site",
  plaid: { src: "../../framerusercontent.com/images/vaTGvDavm2xy6HTQ0xZy1Ygaw77e5.jpg?width=789&height=994", alt: "" },
  l_9: "https://designedbyplaid.com/",
  l_10: "Visit site",
  huel: { src: "../../framerusercontent.com/images/BQFK0A786h9xx1ahqSkkAItcL01d14.png?width=523&height=717", alt: "" },
  l_11: "https://try.huel.com/uk/theoverlap",
  l_12: "Visit site",
  desktop3: { src: "../../framerusercontent.com/images/2wB5IrHzsTdbbt8ceqZSfaUz845f61.jpg?width=741&height=865", alt: "" },
  l_13: "https://play.runescape.com/",
  l_14: "Visit site",
  zapier_2: { src: "../../framerusercontent.com/images/RaJKHx0hAiYbu7i5mEAWz1GFnE6b44.png?width=734&height=798", alt: "" },
  l_15: "https://zapier.com/ai-transformation",
  l_16: "Visit site",
  elevenlabs: { src: "../../framerusercontent.com/images/eg6Yz93u9CA6WiUERkw07P9DEqI96c5.jpg?width=1900&height=1080", alt: "" },
  l_17: "https://chromaawards.com/",
  l_18: "Visit site",
  doordash_2: { src: "../../framerusercontent.com/images/CzIt9BMelg2aZTj4oJO6F3lIMzU8f22.png?width=644&height=768", alt: "" },
  l_19: "https://auto.doordash.com/",
  l_20: "Visit site",
  dribbble_2: { src: "../../framerusercontent.com/images/CPFW3uiMfnXMVx2DxgHiZsnA459b3.png?width=868&height=932", alt: "" },
  l_21: "https://framer-ai.com/dribbble",
  l_22: "Read story",
  nba_2: { src: "../../framerusercontent.com/images/U5dfNq7wU60AQEebMnh2U09Ras86d6.png?width=1252&height=1534", alt: "" },
  l_23: "https://www.launchpad.nba.com/",
  l_24: "Visit site",
  zapier_3: { src: "../../framerusercontent.com/images/8pD68YvWk5laMvt1NjuOKaKKAMQb9c2.jpg?width=1872&height=1248", alt: "" },
  l_25: "https://groupme.com/",
  l_26: "Visit site",
  plaid_2: { src: "../../framerusercontent.com/images/vaTGvDavm2xy6HTQ0xZy1Ygaw77e5.jpg?width=789&height=994", alt: "" },
  l_27: "https://designedbyplaid.com/",
  l_28: "Visit site",
  huel_2: { src: "../../framerusercontent.com/images/BQFK0A786h9xx1ahqSkkAItcL01d14.png?width=523&height=717", alt: "" },
  l_29: "https://try.huel.com/uk/theoverlap",
  l_30: "Visit site",
  desktop3_2: { src: "../../framerusercontent.com/images/2wB5IrHzsTdbbt8ceqZSfaUz845f61.jpg?width=741&height=865", alt: "" },
  l_31: "https://play.runescape.com/",
  l_32: "Visit site",
  zapier_4: { src: "../../framerusercontent.com/images/RaJKHx0hAiYbu7i5mEAWz1GFnE6b44.png?width=734&height=798", alt: "" },
  l_33: "https://zapier.com/ai-transformation",
  l_34: "Visit site",
  elevenlabs_2: { src: "../../framerusercontent.com/images/eg6Yz93u9CA6WiUERkw07P9DEqI96c5.jpg?width=1900&height=1080", alt: "" },
  l_35: "https://chromaawards.com/",
  l_36: "Visit site",
  doordash_3: { src: "../../framerusercontent.com/images/CzIt9BMelg2aZTj4oJO6F3lIMzU8f22.png?width=644&height=768", alt: "" },
  l_37: "https://auto.doordash.com/",
  l_38: "Visit site",
  dribbble_3: { src: "../../framerusercontent.com/images/CPFW3uiMfnXMVx2DxgHiZsnA459b3.png?width=868&height=932", alt: "" },
  l_39: "https://framer-ai.com/dribbble",
  l_40: "Read story",
  nba_3: { src: "../../framerusercontent.com/images/U5dfNq7wU60AQEebMnh2U09Ras86d6.png?width=1252&height=1534", alt: "" },
  l_41: "https://www.launchpad.nba.com/",
  l_42: "Visit site",
  zapier_5: { src: "../../framerusercontent.com/images/8pD68YvWk5laMvt1NjuOKaKKAMQb9c2.jpg?width=1872&height=1248", alt: "" },
  l_43: "https://groupme.com/",
  l_44: "Visit site",
  plaid_3: { src: "../../framerusercontent.com/images/vaTGvDavm2xy6HTQ0xZy1Ygaw77e5.jpg?width=789&height=994", alt: "" },
  l_45: "https://designedbyplaid.com/",
  l_46: "Visit site",
  huel_3: { src: "../../framerusercontent.com/images/BQFK0A786h9xx1ahqSkkAItcL01d14.png?width=523&height=717", alt: "" },
  l_47: "https://try.huel.com/uk/theoverlap",
  l_48: "Visit site",
  desktop3_3: { src: "../../framerusercontent.com/images/2wB5IrHzsTdbbt8ceqZSfaUz845f61.jpg?width=741&height=865", alt: "" },
  l_49: "https://play.runescape.com/",
  l_50: "Visit site",
  zapier_6: { src: "../../framerusercontent.com/images/RaJKHx0hAiYbu7i5mEAWz1GFnE6b44.png?width=734&height=798", alt: "" },
  l_51: "https://zapier.com/ai-transformation",
  l_52: "Visit site",
  elevenlabs_3: { src: "../../framerusercontent.com/images/eg6Yz93u9CA6WiUERkw07P9DEqI96c5.jpg?width=1900&height=1080", alt: "" },
  l_53: "https://chromaawards.com/",
  l_54: "Visit site",
  doordash_4: { src: "../../framerusercontent.com/images/CzIt9BMelg2aZTj4oJO6F3lIMzU8f22.png?width=644&height=768", alt: "" },
  l_55: "https://auto.doordash.com/",
  l_56: "Visit site",
  dribbble_4: { src: "../../framerusercontent.com/images/CPFW3uiMfnXMVx2DxgHiZsnA459b3.png?width=868&height=932", alt: "" },
  l_57: "https://framer-ai.com/dribbble",
  l_58: "Read story",
  nba_4: { src: "../../framerusercontent.com/images/U5dfNq7wU60AQEebMnh2U09Ras86d6.png?width=1252&height=1534", alt: "" },
  l_59: "https://www.launchpad.nba.com/",
  l_60: "Visit site",
  zapier_7: { src: "../../framerusercontent.com/images/8pD68YvWk5laMvt1NjuOKaKKAMQb9c2.jpg?width=1872&height=1248", alt: "" },
  l_61: "https://groupme.com/",
  l_62: "Visit site",
  plaid_4: { src: "../../framerusercontent.com/images/vaTGvDavm2xy6HTQ0xZy1Ygaw77e5.jpg?width=789&height=994", alt: "" },
  l_63: "https://designedbyplaid.com/",
  l_64: "Visit site",
  huel_4: { src: "../../framerusercontent.com/images/BQFK0A786h9xx1ahqSkkAItcL01d14.png?width=523&height=717", alt: "" },
  l_65: "https://try.huel.com/uk/theoverlap",
  l_66: "Visit site",
  desktop3_4: { src: "../../framerusercontent.com/images/2wB5IrHzsTdbbt8ceqZSfaUz845f61.jpg?width=741&height=865", alt: "" },
  l_67: "https://play.runescape.com/",
  l_68: "Visit site",
  zapier_8: { src: "../../framerusercontent.com/images/RaJKHx0hAiYbu7i5mEAWz1GFnE6b44.png?width=734&height=798", alt: "" },
  l_69: "https://zapier.com/ai-transformation",
  l_70: "Visit site",
  elevenlabs_4: { src: "../../framerusercontent.com/images/eg6Yz93u9CA6WiUERkw07P9DEqI96c5.jpg?width=1900&height=1080", alt: "" },
  l_71: "https://chromaawards.com/",
  l_72: "Visit site",
  desktopSlideshow: { src: "/images/05857cb2-SzKYlP68BhaloDCrMKantxTmoCA7ff5.png?width=120&height=120", alt: "Back Arrow" },
  desktopSlideshow_2: { src: "/images/83ee04b7-KSFWbTMQdDEmgaGOcFwdYRJ5SA7ff5.png?width=120&height=120", alt: "Next Arrow" },
  dribbble_5: "ships landing pages",
  dribbble_6: "10x faster",
  legora: "had over",
  legora_2: "5 million visitors",
  legora_3: "since site launch",
  flora: "increased homepage",
  flora_2: "conversions by 35%",
  perplexity: "built their site with",
  perplexity_2: "0 developers",
  caseStudies: "Leading brands, standout sites",
  caseStudies_2: "https://framer-ai.com/i-d",
  caseStudies_3: { src: "/images/5566dbe6-42FYqfHjxZDHK7dDaPZ5JxmrcA781f.png?width=408&height=44", alt: "" },
  cta2026: "Read story",
  asset: { src: "../../framerusercontent.com/images/aWkbRZFJ06yuK2JJxO0iSTCMjBQ57d4.png?width=2276&height=2260", alt: "" },
  caseStudies_4: "https://framer-ai.com/flora",
  caseStudies_5: { src: "/images/580ec15b-qrfv7aLHQpii5CkculSvZoDXtt4781f.png?width=408&height=44", alt: "" },
  cta2026_2: "Read story",
  asset_2: { src: "../../framerusercontent.com/images/vDELFTSKFSTn2jyUi4i8yf0ZL863b9.jpg?width=3600&height=3600", alt: "Website made in Framer" },
  caseStudies_6: "https://framer-ai.com/mixpanel",
  variant1: { src: "/images/af89d457-LQCHmSlimLKaUQlPLcpMygkTY781f.png?width=408&height=44", alt: "" },
  quote: "“We love working in Framer. It gives our design team the autonomy to manage the design system, handle complex UI updates, and ship changes without slowing down engineering.”",
  cta2026_3: "Read story",
  caseStudies_7: "https://framer-ai.com/calcom",
  variant1_2: { src: "/images/e387c55f-MB5O9MHUyihOaLjHJpKAAHbSE90781f.png?width=408&height=44", alt: "" },
  quote_2: "“We thought Framer with our Next.js app could be a problem. Turns out it works beautifully. Now the team can move fast, test fast, and publish without devs.”",
  cta2026_4: "Read story",
  caseStudies_8: "https://framer-ai.com/miro",
  variant1_3: { src: "/images/08134f62-CWHGCtptlQWhTHHA90R5ucCmBA781f.png?width=408&height=44", alt: "" },
  quote_3: "“Framer allowed us to ship high-performing, beautifully designed pages at record speed, all while keeping design control in-house.”",
  cta2026_5: "Read story",
  caseStudies_9: "How teams win with Framer",
  caseStudies_10: "https://framer-ai.com/analogue",
  quote_4: "Reached over one million visitors, shipped over 15 designer-built Framer sites, and cut delivery from three months to one.",
  variant1_4: { src: "/images/1bdf8e38-OIm2a5DHwHrlg6QawkUPz1pYvWw781f.png?width=408&height=44", alt: "" },
  caseStudies_11: "https://framer-ai.com/wild",
  quote_5: "Built over 10 Framer sites, including award-winning work, while halving launch time across start-up, e-commerce, and internal projects.",
  variant1_5: { src: "/images/b1c42b86-YPMBNZehN0bUIoOqdPn7dnIb2YM781f.png?width=408&height=44", alt: "" },
  caseStudies_12: "https://framer-ai.com/libra",
  quote_6: "Expanded from one to 13 locales in two months, reached 300K+ monthly website views, and built 7 CMS systems powering local experiences.",
  variant1_6: { src: "/images/7ad0d896-zShrOz7UvFXdtPELDaqxfEDqk781f.png?width=408&height=44", alt: "" },
  caseStudies_13: "https://framer-ai.com/zapier",
  quote_7: "ZapConnect welcomed 12k+ attendees and lifted registrations 7% year over year, while bringing an immersive new world to life with creative precision.",
  variant1_7: { src: "/images/f562d76a-PFosSszHaIl6tHdPEGhfrzUJYR8781f.png?width=408&height=44", alt: "" },
  caseStudies_14: "https://framer-ai.com/hellohello",
  quote_8: "Won two Site of the Year awards, reached 150k+ visitors with one launch, and shipped over 10 Framer sites.",
  variant1_8: { src: "/images/62277c5c-wCFU8DyLBlVdgtpwSTBHrrQ1Fc781f.png?width=408&height=44", alt: "" },
  caseStudies_15: "https://framer-ai.com/legora",
  quote_9: "Reached 5M+ visitors since launch, shipped 40+ website updates every week, and enabled 30 editors to manage the site in Framer.",
  variant1_9: { src: "/images/1a1b9c18-Z8WIHqCBfxpsVJOqtgAB1YhpU781f.png?width=408&height=44", alt: "" },
  caseStudies_16: "https://framer-ai.com/mutiny",
  quote_10: "Cut days of work with Framer’s agent, fully migrated from Contentful, and saved $6k a month on agency support.",
  variant1_10: { src: "/images/c7eed904-izNFnj8UxzZOiuG3GtUp9i4vHs781f.png?width=408&height=44", alt: "" },
  caseStudies_17: "https://framer-ai.com/stackai",
  quote_11: "Nearly 2,000 pages published without developers, daily site updates, and 90% faster page creation with Framer’s CMS.",
  variant1_11: { src: "/images/77767cf4-Egj9XEvRel38S2A5JXeGIs20G2U781f.png?width=408&height=44", alt: "" },
  caseStudies_18: "https://framer-ai.com/possible",
  quote_12: "Over 200 CMS-powered pages built, doubled session time, and 1.5M+ visitors welcomed over the past year.",
  variant1_12: { src: "/images/b38abc5f-io1hwfbYlblgPYjGSGVLSXvrz48781f.png?width=408&height=44", alt: "" },
  caseStudies_19: "https://framer-ai.com/designerfund",
  quote_13: "Enabled instant updates, seamless CMS elements migration, and total ownership over design and layout.",
  variant1_13: { src: "/images/e2c56c31-eQtqkrP0Ofc8szkl0V6ai9eKH0781f.png?width=408&height=44", alt: "" },
  caseStudies_20: "https://framer-ai.com/alterego",
  quote_14: "Rolled out fast with a flexible, developer-free website that continuously evolves in real time.",
  variant1_14: { src: "/images/3bb3820e-edWBtiERAF9dZNxOkEYWXxavGvE781f.png?width=408&height=44", alt: "" },
  caseStudies_21: "https://framer-ai.com/planhat",
  quote_15: "Linked content across topics and contributors, guided visitors toward conversion, and enabled the entire team to publish directly in Framer.",
  variant1_15: { src: "/images/bce26921-n5leb2ZTp3yda2dlqph36UF79A781f.png?width=408&height=44", alt: "" },
};
