// Usecases.tsx — section converted to a real JSX component by extract-site.
// Editable React: entrance animations are inline framer-motion props with the
// MEASURED timing from the original site; hover effects live in hover.css.
// Copy, photos, and links live in the sibling content module — edit there to
// re-skin this section without touching layout/motion.
import type { CSSProperties } from "react";
import { motion } from "framer-motion";
import content from "../content/05-Usecases";

export function Usecases() {
  return (
    <section className="framer-19vblyd" data-framer-name="Usecases" id="tools" style={{ width: "1440px", height: "604.797px", padding: "120px 20px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "40px" } as CSSProperties}>
      <div className="framer-oeuouq" data-framer-name="Header" style={{ width: "1200px", height: "96.7969px", maxWidth: "1200px", position: "relative", display: "flex", flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", alignItems: "flex-end", alignContent: "flex-end" } as CSSProperties}>
        <div className="framer-krg08c" data-framer-component-type="RichTextContainer" style={{ width: "671px", height: "96.7969px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", transform: "none" } as CSSProperties}>
          <h2 className="framer-text framer-styles-preset-fbtpvo" data-styles-preset="qRN7MgZKk" dir="auto" style={{ width: "671px", height: "96.7969px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"GT Walsheim Medium\", \"GT Walsheim Medium Placeholder\", sans-serif", fontSize: "44px", fontWeight: "500", lineHeight: "48.4px", letterSpacing: "-1.76px", textAlign: "left", color: "rgb(255, 255, 255)", "--framer-text-alignment": "left", "--framer-text-color": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))" } as CSSProperties}>
            {content.header}
          </h2>
        </div>
      </div>
      <div className="ssr-variant hidden-v0wwfd" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties}>
        <motion.div className="framer-1grxk2g-container" style={{ width: "1200px", height: "228px", maxWidth: "1200px", position: "relative", display: "block", flexDirection: "row" } as CSSProperties} initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
          <motion.div className="ssr-variant hidden-brtj6u" style={{ position: "static", display: "contents", flexDirection: "row" } as CSSProperties} initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
            <div className="framer-gR8rc framer-7t2te9 framer-v-7t2te9" data-border="true" data-framer-name="Desktop" style={{ width: "100%", height: "228px", maxWidth: "100%", position: "relative", display: "grid", flexDirection: "row", justifyContent: "center", gridTemplateColumns: "240px 240px 240px 240px 240px", gridTemplateRows: "114px 114px", borderRadius: "18px", overflow: "hidden", "--border-bottom-width": "1px", "--border-color": "var(--token-5e0b3b72-9a97-43f8-96f2-85d741f3d8ca, rgb(26, 26, 26))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
              <div className="framer-jikcjt-container" style={{ width: "240px", height: "114px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                <a className="framer-SpFex framer-1ylh6f framer-v-ottlqz framer-1141ein" data-border="true" data-framer-name="Simple" style={{ width: "100%", height: "114px", padding: "20px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-end", alignItems: "flex-start", alignContent: "flex-start", gap: "20px", color: "rgb(0, 0, 238)", overflow: "hidden", "--border-bottom-width": "1px", "--border-color": "var(--token-5e0b3b72-9a97-43f8-96f2-85d741f3d8ca, rgb(26, 26, 26))", "--border-left-width": "0px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "0px", "--owisgu": "20px", backgroundColor: "rgba(0, 0, 0, 0)", cornerShape: "superellipse(1)", borderRadius: "0px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.simple}>
                  <div className="framer-1cef1mv" style={{ width: "241px", height: "114px", position: "absolute", right: "-1px", inset: "0px -1px 0px 0px", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "20px", overflow: "clip", opacity: "1" } as CSSProperties} />
                  <motion.div className="framer-5pqpoi" style={{ width: "18px", height: "18px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties} initial={{ opacity: 0.5 }} whileInView={{ opacity: 1 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                    <svg data-framer-name="Icon L" className="framer-IbFO6 framer-g8wfnk" role="presentation" viewBox="0 0 20 20" style={{ width: "18px", height: "18px", position: "relative", display: "block", flexDirection: "row", opacity: "0.5", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "rgb(255, 255, 255)", "--17kkcf8": "rgba(255, 255, 255, 0.15)" } as CSSProperties}>
                      <use href="#2993768241" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                    </svg>
                  </motion.div>
                  <div className="framer-cdozc7" style={{ width: "200px", height: "36px", padding: "0px 5px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                    <div className="framer-1fh73r7-container" style={{ width: "116px", height: "36px", maxWidth: "100%", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                      <div className="framer-aE3iw framer-13ihfp7 framer-v-fni1y4" data-framer-name="M" style={{ width: "116px", height: "100%", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                        <div className="framer-1ptol71" data-framer-component-type="RichTextContainer" style={{ width: "116px", height: "36px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre-wrap", "--extracted-2gg91v": "\"opsz\" 32, \"wght\" 500", "--extracted-r6o4lv": "rgb(255, 255, 255)", "--variable-reference-hx_eyvbb1-cncr1d_lo": "15", transform: "none", opacity: "1" } as CSSProperties}>
                          <motion.p dir="auto" className="framer-text" style={{ width: "116px", height: "36px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "15px", lineHeight: "18px", letterSpacing: "-0.01px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss07' on, 'cv05' on, 'ss03' on, 'cv11' on", "--framer-font-size": "calc(var(--variable-reference-hx_eyvbB1-Cncr1d_lo) * 1px)", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 32, \"wght\" 500)", "--framer-letter-spacing": "-0.01px", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))" } as CSSProperties} initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                            {content.m}
                          </motion.p>
                        </div>
                      </div>
                    </div>
                    <div className="framer-1x6nu5f" data-framer-name="Arrow" style={{ width: "28px", height: "28px", minWidth: "28px", minHeight: "28px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "6px", borderRadius: "100px", opacity: "0", overflow: "clip", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px" } as CSSProperties} />
                  </div>
                  <div className="framer-1euzglo" data-framer-name="GenBorder" style={{ width: "240px", height: "114px", position: "absolute", display: "block", flexDirection: "row", opacity: "0" } as CSSProperties} />
                </a>
              </div>
              <div className="framer-1w5z7e2-container" style={{ width: "240px", height: "114px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                <a className="framer-SpFex framer-1ylh6f framer-v-ottlqz framer-1141ein" data-border="true" data-framer-name="Simple" style={{ width: "100%", height: "114px", padding: "20px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-end", alignItems: "flex-start", alignContent: "flex-start", gap: "20px", color: "rgb(0, 0, 238)", overflow: "hidden", "--border-bottom-width": "1px", "--border-color": "var(--token-5e0b3b72-9a97-43f8-96f2-85d741f3d8ca, rgb(26, 26, 26))", "--border-left-width": "0px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "0px", "--owisgu": "20px", backgroundColor: "rgba(0, 0, 0, 0)", cornerShape: "superellipse(1)", borderRadius: "0px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.simple_2}>
                  <div className="framer-1cef1mv" style={{ width: "241px", height: "114px", position: "absolute", right: "-1px", inset: "0px -1px 0px 0px", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "20px", overflow: "clip", opacity: "1" } as CSSProperties} />
                  <motion.div className="framer-5pqpoi" style={{ width: "18px", height: "18px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties} initial={{ opacity: 0.5 }} whileInView={{ opacity: 1 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                    <svg data-framer-name="Icon L" className="framer-4j1yF framer-g8wfnk" role="presentation" viewBox="0 0 20 20" style={{ width: "18px", height: "18px", position: "relative", display: "block", flexDirection: "row", opacity: "0.5", overflow: "hidden", aspectRatio: "1 / 1", "--17kkcf8": "rgba(255, 255, 255, 0.15)", "--1iwhep7": "2", "--1l3yetw": "rgb(255, 255, 255)" } as CSSProperties}>
                      <use href="#1232319397" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                    </svg>
                  </motion.div>
                  <div className="framer-cdozc7" style={{ width: "200px", height: "36px", padding: "0px 5px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                    <div className="framer-1fh73r7-container" style={{ width: "94px", height: "36px", maxWidth: "100%", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                      <div className="framer-aE3iw framer-13ihfp7 framer-v-fg4kt" data-framer-name="S" style={{ width: "94px", height: "100%", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                        <div className="framer-1ptol71" data-framer-component-type="RichTextContainer" style={{ width: "94px", height: "36px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre-wrap", "--extracted-2gg91v": "\"opsz\" 32, \"wght\" 500", "--extracted-r6o4lv": "rgb(255, 255, 255)", "--variable-reference-hx_eyvbb1-cncr1d_lo": "15", transform: "none", opacity: "1" } as CSSProperties}>
                          <motion.p dir="auto" className="framer-text" style={{ width: "94px", height: "36px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "15px", lineHeight: "18px", letterSpacing: "-0.01px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss07' on, 'cv05' on, 'ss03' on, 'cv11' on", "--framer-font-size": "calc(var(--variable-reference-hx_eyvbB1-Cncr1d_lo) * 1px)", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 32, \"wght\" 500)", "--framer-letter-spacing": "-0.01px", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))" } as CSSProperties} initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                            {content.s}
                          </motion.p>
                        </div>
                      </div>
                    </div>
                    <div className="framer-1x6nu5f" data-framer-name="Arrow" style={{ width: "28px", height: "28px", minWidth: "28px", minHeight: "28px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "6px", borderRadius: "100px", opacity: "0", overflow: "clip", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px" } as CSSProperties} />
                  </div>
                  <div className="framer-1euzglo" data-framer-name="GenBorder" style={{ width: "240px", height: "114px", position: "absolute", display: "block", flexDirection: "row", opacity: "0" } as CSSProperties} />
                </a>
              </div>
              <div className="framer-azew5u-container" style={{ width: "240px", height: "114px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                <a className="framer-SpFex framer-1ylh6f framer-v-ottlqz framer-1141ein" data-border="true" data-framer-name="Simple" style={{ width: "100%", height: "114px", padding: "20px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-end", alignItems: "flex-start", alignContent: "flex-start", gap: "20px", backdropFilter: "saturate(115%) brightness(115%) blur(5px)", color: "rgb(0, 0, 238)", overflow: "hidden", "--border-bottom-width": "1px", "--border-color": "var(--token-5e0b3b72-9a97-43f8-96f2-85d741f3d8ca, rgb(26, 26, 26))", "--border-left-width": "0px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "0px", "--owisgu": "20px", backgroundColor: "rgba(0, 0, 0, 0)", cornerShape: "superellipse(1)", borderRadius: "0px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.simple_3}>
                  <div className="framer-1cef1mv" style={{ width: "241px", height: "114px", position: "absolute", right: "-1px", inset: "0px -1px 0px 0px", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "20px", overflow: "clip", opacity: "1" } as CSSProperties} />
                  <motion.div className="framer-5pqpoi" style={{ width: "18px", height: "18px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties} initial={{ opacity: 0.5 }} whileInView={{ opacity: 1 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                    <svg data-framer-name="Icon L" className="framer-gChrr framer-g8wfnk" role="presentation" viewBox="0 0 20 20" style={{ width: "18px", height: "18px", position: "relative", display: "block", flexDirection: "row", opacity: "0.5", overflow: "hidden", aspectRatio: "1 / 1", "--17kkcf8": "rgba(255, 255, 255, 0.15)", "--1iwhep7": "2", "--1l3yetw": "rgb(255, 255, 255)" } as CSSProperties}>
                      <use href="#4290634540" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                    </svg>
                  </motion.div>
                  <div className="framer-cdozc7" style={{ width: "200px", height: "36px", padding: "0px 5px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                    <div className="framer-1fh73r7-container" style={{ width: "116px", height: "36px", maxWidth: "100%", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                      <div className="framer-aE3iw framer-13ihfp7 framer-v-fni1y4" data-framer-name="M" style={{ width: "116px", height: "100%", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                        <div className="framer-1ptol71" data-framer-component-type="RichTextContainer" style={{ width: "116px", height: "36px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre-wrap", "--extracted-2gg91v": "\"opsz\" 32, \"wght\" 500", "--extracted-r6o4lv": "rgb(255, 255, 255)", "--variable-reference-hx_eyvbb1-cncr1d_lo": "15", transform: "none", opacity: "1" } as CSSProperties}>
                          <motion.p dir="auto" className="framer-text" style={{ width: "116px", height: "36px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "15px", lineHeight: "18px", letterSpacing: "-0.01px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss07' on, 'cv05' on, 'ss03' on, 'cv11' on", "--framer-font-size": "calc(var(--variable-reference-hx_eyvbB1-Cncr1d_lo) * 1px)", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 32, \"wght\" 500)", "--framer-letter-spacing": "-0.01px", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))" } as CSSProperties} initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                            {content.m_2}
                          </motion.p>
                        </div>
                      </div>
                    </div>
                    <div className="framer-1x6nu5f" data-framer-name="Arrow" style={{ width: "28px", height: "28px", minWidth: "28px", minHeight: "28px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "6px", borderRadius: "100px", opacity: "0", overflow: "clip", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px" } as CSSProperties} />
                  </div>
                  <div className="framer-1euzglo" data-framer-name="GenBorder" style={{ width: "240px", height: "114px", position: "absolute", display: "block", flexDirection: "row", opacity: "0" } as CSSProperties} />
                </a>
              </div>
              <div className="framer-1mcfuad-container" style={{ width: "240px", height: "114px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                <a className="framer-SpFex framer-1ylh6f framer-v-ottlqz framer-1141ein" data-border="true" data-framer-name="Simple" style={{ width: "100%", height: "114px", padding: "20px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-end", alignItems: "flex-start", alignContent: "flex-start", gap: "20px", color: "rgb(0, 0, 238)", overflow: "hidden", "--border-bottom-width": "1px", "--border-color": "var(--token-5e0b3b72-9a97-43f8-96f2-85d741f3d8ca, rgb(26, 26, 26))", "--border-left-width": "0px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "0px", "--owisgu": "20px", backgroundColor: "rgba(0, 0, 0, 0)", cornerShape: "superellipse(1)", borderRadius: "0px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.simple_4}>
                  <div className="framer-1cef1mv" style={{ width: "241px", height: "114px", position: "absolute", right: "-1px", inset: "0px -1px 0px 0px", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "20px", overflow: "clip", opacity: "1" } as CSSProperties} />
                  <motion.div className="framer-5pqpoi" style={{ width: "18px", height: "18px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties} initial={{ opacity: 0.5 }} whileInView={{ opacity: 1 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                    <svg data-framer-name="Icon L" className="framer-ooj1j framer-g8wfnk" role="presentation" viewBox="0 0 20 20" style={{ width: "18px", height: "18px", position: "relative", display: "block", flexDirection: "row", opacity: "0.5", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "rgb(255, 255, 255)", "--17kkcf8": "rgba(255, 255, 255, 0.15)" } as CSSProperties}>
                      <use href="#1825208344" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                    </svg>
                  </motion.div>
                  <div className="framer-cdozc7" style={{ width: "200px", height: "36px", padding: "0px 5px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                    <div className="framer-1fh73r7-container" style={{ width: "116px", height: "36px", maxWidth: "100%", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                      <div className="framer-aE3iw framer-13ihfp7 framer-v-fni1y4" data-framer-name="M" style={{ width: "116px", height: "100%", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                        <div className="framer-1ptol71" data-framer-component-type="RichTextContainer" style={{ width: "116px", height: "36px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre-wrap", "--extracted-2gg91v": "\"opsz\" 32, \"wght\" 500", "--extracted-r6o4lv": "rgb(255, 255, 255)", "--variable-reference-hx_eyvbb1-cncr1d_lo": "15", transform: "none", opacity: "1" } as CSSProperties}>
                          <motion.p dir="auto" className="framer-text" style={{ width: "116px", height: "36px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "15px", lineHeight: "18px", letterSpacing: "-0.01px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss07' on, 'cv05' on, 'ss03' on, 'cv11' on", "--framer-font-size": "calc(var(--variable-reference-hx_eyvbB1-Cncr1d_lo) * 1px)", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 32, \"wght\" 500)", "--framer-letter-spacing": "-0.01px", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))" } as CSSProperties} initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                            {content.m_3}
                          </motion.p>
                        </div>
                      </div>
                    </div>
                    <div className="framer-1x6nu5f" data-framer-name="Arrow" style={{ width: "28px", height: "28px", minWidth: "28px", minHeight: "28px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "6px", borderRadius: "100px", opacity: "0", overflow: "clip", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px" } as CSSProperties} />
                  </div>
                  <div className="framer-1euzglo" data-framer-name="GenBorder" style={{ width: "240px", height: "114px", position: "absolute", display: "block", flexDirection: "row", opacity: "0" } as CSSProperties} />
                </a>
              </div>
              <div className="framer-mizl0c-container" style={{ width: "240px", height: "114px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                <a className="framer-SpFex framer-1ylh6f framer-v-ottlqz framer-1141ein" data-border="true" data-framer-name="Simple" style={{ width: "100%", height: "114px", padding: "20px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-end", alignItems: "flex-start", alignContent: "flex-start", gap: "20px", color: "rgb(0, 0, 238)", overflow: "hidden", "--border-bottom-width": "1px", "--border-color": "var(--token-5e0b3b72-9a97-43f8-96f2-85d741f3d8ca, rgb(26, 26, 26))", "--border-left-width": "0px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "0px", "--owisgu": "20px", backgroundColor: "rgba(0, 0, 0, 0)", cornerShape: "superellipse(1)", borderRadius: "0px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.simple_5}>
                  <div className="framer-1cef1mv" style={{ width: "241px", height: "114px", position: "absolute", right: "-1px", inset: "0px -1px 0px 0px", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "20px", overflow: "clip", opacity: "1" } as CSSProperties} />
                  <motion.div className="framer-5pqpoi" style={{ width: "18px", height: "18px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties} initial={{ opacity: 0.5 }} whileInView={{ opacity: 1 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                    <svg data-framer-name="Icon L" className="framer-TXDnm framer-g8wfnk" role="presentation" viewBox="0 0 20 20" style={{ width: "18px", height: "18px", position: "relative", display: "block", flexDirection: "row", opacity: "0.5", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "rgb(255, 255, 255)", "--17kkcf8": "rgba(255, 255, 255, 0.15)" } as CSSProperties}>
                      <use href="#2712300145" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                    </svg>
                  </motion.div>
                  <div className="framer-cdozc7" style={{ width: "200px", height: "36px", padding: "0px 5px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                    <div className="framer-1fh73r7-container" style={{ width: "116px", height: "36px", maxWidth: "100%", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                      <div className="framer-aE3iw framer-13ihfp7 framer-v-fni1y4" data-framer-name="M" style={{ width: "116px", height: "100%", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                        <div className="framer-1ptol71" data-framer-component-type="RichTextContainer" style={{ width: "116px", height: "36px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre-wrap", "--extracted-2gg91v": "\"opsz\" 32, \"wght\" 500", "--extracted-r6o4lv": "rgb(255, 255, 255)", "--variable-reference-hx_eyvbb1-cncr1d_lo": "15", transform: "none", opacity: "1" } as CSSProperties}>
                          <motion.p dir="auto" className="framer-text" style={{ width: "116px", height: "36px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "15px", lineHeight: "18px", letterSpacing: "-0.01px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss07' on, 'cv05' on, 'ss03' on, 'cv11' on", "--framer-font-size": "calc(var(--variable-reference-hx_eyvbB1-Cncr1d_lo) * 1px)", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 32, \"wght\" 500)", "--framer-letter-spacing": "-0.01px", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))" } as CSSProperties} initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                            {content.m_4}
                          </motion.p>
                        </div>
                      </div>
                    </div>
                    <div className="framer-1x6nu5f" data-framer-name="Arrow" style={{ width: "28px", height: "28px", minWidth: "28px", minHeight: "28px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "6px", borderRadius: "100px", opacity: "0", overflow: "clip", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px" } as CSSProperties} />
                  </div>
                  <div className="framer-1euzglo" data-framer-name="GenBorder" style={{ width: "240px", height: "114px", position: "absolute", display: "block", flexDirection: "row", opacity: "0" } as CSSProperties} />
                </a>
              </div>
              <div className="framer-1jz7b0k-container" style={{ width: "240px", height: "114px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                <a className="framer-SpFex framer-1ylh6f framer-v-ottlqz framer-1141ein" data-border="true" data-framer-name="Simple" style={{ width: "100%", height: "114px", padding: "20px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-end", alignItems: "flex-start", alignContent: "flex-start", gap: "20px", color: "rgb(0, 0, 238)", overflow: "hidden", "--border-bottom-width": "1px", "--border-color": "var(--token-5e0b3b72-9a97-43f8-96f2-85d741f3d8ca, rgb(26, 26, 26))", "--border-left-width": "0px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "0px", "--owisgu": "20px", backgroundColor: "rgba(0, 0, 0, 0)", cornerShape: "superellipse(1)", borderRadius: "0px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.simple_6}>
                  <div className="framer-1cef1mv" style={{ width: "241px", height: "114px", position: "absolute", right: "-1px", inset: "0px -1px 0px 0px", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "20px", overflow: "clip", opacity: "1" } as CSSProperties} />
                  <motion.div className="framer-5pqpoi" style={{ width: "18px", height: "18px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties} initial={{ opacity: 0.5 }} whileInView={{ opacity: 1 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                    <svg data-framer-name="Icon L" className="framer-93zNj framer-g8wfnk" role="presentation" viewBox="0 0 20 20" style={{ width: "18px", height: "18px", position: "relative", display: "block", flexDirection: "row", opacity: "0.5", overflow: "hidden", aspectRatio: "1 / 1", "--17kkcf8": "rgba(255, 255, 255, 0.15)", "--1iwhep7": "2", "--1l3yetw": "rgb(255, 255, 255)" } as CSSProperties}>
                      <use href="#3515536241" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                    </svg>
                  </motion.div>
                  <div className="framer-cdozc7" style={{ width: "200px", height: "36px", padding: "0px 5px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                    <div className="framer-1fh73r7-container" style={{ width: "116px", height: "36px", maxWidth: "100%", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                      <div className="framer-aE3iw framer-13ihfp7 framer-v-fni1y4" data-framer-name="M" style={{ width: "116px", height: "100%", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                        <div className="framer-1ptol71" data-framer-component-type="RichTextContainer" style={{ width: "116px", height: "36px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre-wrap", "--extracted-2gg91v": "\"opsz\" 32, \"wght\" 500", "--extracted-r6o4lv": "rgb(255, 255, 255)", "--variable-reference-hx_eyvbb1-cncr1d_lo": "15", transform: "none", opacity: "1" } as CSSProperties}>
                          <motion.p dir="auto" className="framer-text" style={{ width: "116px", height: "36px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "15px", lineHeight: "18px", letterSpacing: "-0.01px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss07' on, 'cv05' on, 'ss03' on, 'cv11' on", "--framer-font-size": "calc(var(--variable-reference-hx_eyvbB1-Cncr1d_lo) * 1px)", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 32, \"wght\" 500)", "--framer-letter-spacing": "-0.01px", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))" } as CSSProperties} initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                            {content.m_5}
                          </motion.p>
                        </div>
                      </div>
                    </div>
                    <div className="framer-1x6nu5f" data-framer-name="Arrow" style={{ width: "28px", height: "28px", minWidth: "28px", minHeight: "28px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "6px", borderRadius: "100px", opacity: "0", overflow: "clip", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px" } as CSSProperties} />
                  </div>
                  <div className="framer-1euzglo" data-framer-name="GenBorder" style={{ width: "240px", height: "114px", position: "absolute", display: "block", flexDirection: "row", opacity: "0" } as CSSProperties} />
                </a>
              </div>
              <div className="framer-1vd55x0-container" style={{ width: "240px", height: "114px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                <a className="framer-SpFex framer-1ylh6f framer-v-ottlqz framer-1141ein" data-border="true" data-framer-name="Simple" style={{ width: "100%", height: "114px", padding: "20px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-end", alignItems: "flex-start", alignContent: "flex-start", gap: "20px", color: "rgb(0, 0, 238)", overflow: "hidden", "--border-bottom-width": "1px", "--border-color": "var(--token-5e0b3b72-9a97-43f8-96f2-85d741f3d8ca, rgb(26, 26, 26))", "--border-left-width": "0px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "0px", "--owisgu": "20px", backgroundColor: "rgba(0, 0, 0, 0)", cornerShape: "superellipse(1)", borderRadius: "0px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.simple_7}>
                  <div className="framer-1cef1mv" style={{ width: "241px", height: "114px", position: "absolute", right: "-1px", inset: "0px -1px 0px 0px", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "20px", overflow: "clip", opacity: "1" } as CSSProperties} />
                  <motion.div className="framer-5pqpoi" style={{ width: "18px", height: "18px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties} initial={{ opacity: 0.5 }} whileInView={{ opacity: 1 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                    <svg data-framer-name="Icon L" className="framer-4E5dL framer-g8wfnk" role="presentation" viewBox="0 0 20 20" style={{ width: "18px", height: "18px", position: "relative", display: "block", flexDirection: "row", opacity: "0.5", overflow: "hidden", aspectRatio: "1 / 1", "--17kkcf8": "rgba(255, 255, 255, 0.15)", "--1iwhep7": "2", "--1l3yetw": "rgb(255, 255, 255)" } as CSSProperties}>
                      <use href="#3797874707" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                    </svg>
                  </motion.div>
                  <div className="framer-cdozc7" style={{ width: "200px", height: "36px", padding: "0px 5px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                    <div className="framer-1fh73r7-container" style={{ width: "130px", height: "36px", maxWidth: "100%", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                      <div className="framer-aE3iw framer-13ihfp7 framer-v-13ihfp7" data-framer-name="L" style={{ width: "130px", height: "100%", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                        <div className="framer-1ptol71" data-framer-component-type="RichTextContainer" style={{ width: "130px", height: "36px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre-wrap", "--extracted-2gg91v": "\"opsz\" 32, \"wght\" 500", "--extracted-r6o4lv": "rgb(255, 255, 255)", "--variable-reference-hx_eyvbb1-cncr1d_lo": "15", transform: "none", opacity: "1" } as CSSProperties}>
                          <motion.p dir="auto" className="framer-text" style={{ width: "130px", height: "36px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "15px", lineHeight: "18px", letterSpacing: "-0.01px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss07' on, 'cv05' on, 'ss03' on, 'cv11' on", "--framer-font-size": "calc(var(--variable-reference-hx_eyvbB1-Cncr1d_lo) * 1px)", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 32, \"wght\" 500)", "--framer-letter-spacing": "-0.01px", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))" } as CSSProperties} initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                            {content.l}
                          </motion.p>
                        </div>
                      </div>
                    </div>
                    <div className="framer-1x6nu5f" data-framer-name="Arrow" style={{ width: "28px", height: "28px", minWidth: "28px", minHeight: "28px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "6px", borderRadius: "100px", opacity: "0", overflow: "clip", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px" } as CSSProperties} />
                  </div>
                  <div className="framer-1euzglo" data-framer-name="GenBorder" style={{ width: "240px", height: "114px", position: "absolute", display: "block", flexDirection: "row", opacity: "0" } as CSSProperties} />
                </a>
              </div>
              <div className="framer-1ypb86x-container" style={{ width: "240px", height: "114px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                <a className="framer-SpFex framer-1ylh6f framer-v-ottlqz framer-1141ein" data-border="true" data-framer-name="Simple" style={{ width: "100%", height: "114px", padding: "20px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-end", alignItems: "flex-start", alignContent: "flex-start", gap: "20px", color: "rgb(0, 0, 238)", overflow: "hidden", "--border-bottom-width": "1px", "--border-color": "var(--token-5e0b3b72-9a97-43f8-96f2-85d741f3d8ca, rgb(26, 26, 26))", "--border-left-width": "0px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "0px", "--owisgu": "20px", backgroundColor: "rgba(0, 0, 0, 0)", cornerShape: "superellipse(1)", borderRadius: "0px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.simple_8}>
                  <div className="framer-1cef1mv" style={{ width: "241px", height: "114px", position: "absolute", right: "-1px", inset: "0px -1px 0px 0px", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "20px", overflow: "clip", opacity: "1" } as CSSProperties} />
                  <div className="framer-5pqpoi" style={{ width: "18px", height: "18px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                    <svg data-framer-name="Icon L" className="framer-uSyMf framer-g8wfnk" role="presentation" viewBox="0 0 20 20" style={{ width: "18px", height: "18px", position: "relative", display: "block", flexDirection: "row", opacity: "0.5", overflow: "hidden", aspectRatio: "1 / 1", "--17kkcf8": "rgba(255, 255, 255, 0.15)", "--1iwhep7": "2", "--1l3yetw": "rgb(255, 255, 255)" } as CSSProperties}>
                      <use href="#3578254236" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                    </svg>
                  </div>
                  <div className="framer-cdozc7" style={{ width: "200px", height: "36px", padding: "0px 5px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                    <motion.div className="framer-1fh73r7-container" style={{ width: "116px", height: "36px", maxWidth: "100%", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties} initial={{ y: "-50%" }} whileInView={{ y: "0%" }} viewport={{ once: true, margin: "0px 0px -10% 0px", amount: 0.05 }} transition={{ duration: 0.75, ease: "linear" }}>
                      <div className="framer-aE3iw framer-13ihfp7 framer-v-fni1y4" data-framer-name="M" style={{ width: "116px", height: "100%", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                        <div className="framer-1ptol71" data-framer-component-type="RichTextContainer" style={{ width: "116px", height: "36px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre-wrap", "--extracted-2gg91v": "\"opsz\" 32, \"wght\" 500", "--extracted-r6o4lv": "rgb(255, 255, 255)", "--variable-reference-hx_eyvbb1-cncr1d_lo": "15", transform: "none", opacity: "1" } as CSSProperties}>
                          <p dir="auto" className="framer-text" style={{ width: "116px", height: "36px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "15px", lineHeight: "18px", letterSpacing: "-0.01px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss07' on, 'cv05' on, 'ss03' on, 'cv11' on", "--framer-font-size": "calc(var(--variable-reference-hx_eyvbB1-Cncr1d_lo) * 1px)", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 32, \"wght\" 500)", "--framer-letter-spacing": "-0.01px", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))" } as CSSProperties}>
                            {content.m_6}
                          </p>
                        </div>
                      </div>
                    </motion.div>
                    <div className="framer-1x6nu5f" data-framer-name="Arrow" style={{ width: "28px", height: "28px", minWidth: "28px", minHeight: "28px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "6px", borderRadius: "100px", opacity: "0", overflow: "clip", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px" } as CSSProperties} />
                  </div>
                  <div className="framer-1euzglo" data-framer-name="GenBorder" style={{ width: "240px", height: "114px", position: "absolute", display: "block", flexDirection: "row", opacity: "0" } as CSSProperties} />
                </a>
              </div>
              <div className="framer-1g3kq3y-container" style={{ width: "240px", height: "114px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                <a className="framer-SpFex framer-1ylh6f framer-v-ottlqz framer-1141ein" data-border="true" data-framer-name="Simple" style={{ width: "100%", height: "114px", padding: "20px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-end", alignItems: "flex-start", alignContent: "flex-start", gap: "20px", color: "rgb(0, 0, 238)", overflow: "hidden", "--border-bottom-width": "1px", "--border-color": "var(--token-5e0b3b72-9a97-43f8-96f2-85d741f3d8ca, rgb(26, 26, 26))", "--border-left-width": "0px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "0px", "--owisgu": "20px", backgroundColor: "rgba(0, 0, 0, 0)", cornerShape: "superellipse(1)", borderRadius: "0px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.simple_9}>
                  <div className="framer-1cef1mv" style={{ width: "241px", height: "114px", position: "absolute", right: "-1px", inset: "0px -1px 0px 0px", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "20px", overflow: "clip", opacity: "1" } as CSSProperties} />
                  <div className="framer-5pqpoi" style={{ width: "18px", height: "18px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                    <svg data-framer-name="Icon L" className="framer-vqnL3 framer-g8wfnk" role="presentation" viewBox="0 0 20 20" style={{ width: "18px", height: "18px", position: "relative", display: "block", flexDirection: "row", opacity: "0.5", overflow: "hidden", aspectRatio: "1 / 1", "--17kkcf8": "rgba(255, 255, 255, 0.15)", "--1iwhep7": "2", "--1l3yetw": "rgb(255, 255, 255)" } as CSSProperties}>
                      <use href="#1770930775" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                    </svg>
                  </div>
                  <div className="framer-cdozc7" style={{ width: "200px", height: "36px", padding: "0px 5px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                    <div className="framer-1fh73r7-container" style={{ width: "94px", height: "36px", maxWidth: "100%", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                      <div className="framer-aE3iw framer-13ihfp7 framer-v-fg4kt" data-framer-name="S" style={{ width: "94px", height: "100%", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                        <div className="framer-1ptol71" data-framer-component-type="RichTextContainer" style={{ width: "94px", height: "36px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre-wrap", "--extracted-2gg91v": "\"opsz\" 32, \"wght\" 500", "--extracted-r6o4lv": "rgb(255, 255, 255)", "--variable-reference-hx_eyvbb1-cncr1d_lo": "15", transform: "none", opacity: "1" } as CSSProperties}>
                          <p dir="auto" className="framer-text" style={{ width: "94px", height: "36px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "15px", lineHeight: "18px", letterSpacing: "-0.01px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss07' on, 'cv05' on, 'ss03' on, 'cv11' on", "--framer-font-size": "calc(var(--variable-reference-hx_eyvbB1-Cncr1d_lo) * 1px)", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 32, \"wght\" 500)", "--framer-letter-spacing": "-0.01px", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))" } as CSSProperties}>
                            {content.s_2}
                          </p>
                        </div>
                      </div>
                    </div>
                    <div className="framer-1x6nu5f" data-framer-name="Arrow" style={{ width: "28px", height: "28px", minWidth: "28px", minHeight: "28px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "6px", borderRadius: "100px", opacity: "0", overflow: "clip", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px" } as CSSProperties} />
                  </div>
                  <div className="framer-1euzglo" data-framer-name="GenBorder" style={{ width: "240px", height: "114px", position: "absolute", display: "block", flexDirection: "row", opacity: "0" } as CSSProperties} />
                </a>
              </div>
              <div className="framer-1lq1qoo-container" style={{ width: "240px", height: "114px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                <a className="framer-SpFex framer-1ylh6f framer-v-ottlqz framer-1141ein" data-border="true" data-framer-name="Simple" style={{ width: "100%", height: "114px", padding: "20px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-end", alignItems: "flex-start", alignContent: "flex-start", gap: "20px", color: "rgb(0, 0, 238)", overflow: "hidden", "--border-bottom-width": "1px", "--border-color": "var(--token-5e0b3b72-9a97-43f8-96f2-85d741f3d8ca, rgb(26, 26, 26))", "--border-left-width": "0px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "0px", "--owisgu": "20px", backgroundColor: "rgba(0, 0, 0, 0)", cornerShape: "superellipse(1)", borderRadius: "0px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.simple_10}>
                  <div className="framer-1cef1mv" style={{ width: "241px", height: "114px", position: "absolute", right: "-1px", inset: "0px -1px 0px 0px", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", borderRadius: "20px", overflow: "clip", opacity: "1" } as CSSProperties} />
                  <div className="framer-5pqpoi" style={{ width: "18px", height: "18px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                    <svg data-framer-name="Icon L" className="framer-FWUEe framer-g8wfnk" role="presentation" viewBox="0 0 20 20" style={{ width: "18px", height: "18px", position: "relative", display: "block", flexDirection: "row", opacity: "0.5", overflow: "hidden", aspectRatio: "1 / 1", "--17kkcf8": "rgba(255, 255, 255, 0.15)", "--1l3yetw": "rgb(255, 255, 255)", "--1iwhep7": "2" } as CSSProperties}>
                      <use href="#4112815077" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                    </svg>
                  </div>
                  <div className="framer-cdozc7" style={{ width: "200px", height: "36px", padding: "0px 5px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                    <div className="framer-1fh73r7-container" style={{ width: "130px", height: "36px", maxWidth: "100%", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                      <div className="framer-aE3iw framer-13ihfp7 framer-v-13ihfp7" data-framer-name="L" style={{ width: "130px", height: "100%", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
                        <div className="framer-1ptol71" data-framer-component-type="RichTextContainer" style={{ width: "130px", height: "36px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre-wrap", "--extracted-2gg91v": "\"opsz\" 32, \"wght\" 500", "--extracted-r6o4lv": "rgb(255, 255, 255)", "--variable-reference-hx_eyvbb1-cncr1d_lo": "15", transform: "none", opacity: "1" } as CSSProperties}>
                          <p dir="auto" className="framer-text" style={{ width: "130px", height: "36px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "15px", lineHeight: "18px", letterSpacing: "-0.01px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss07' on, 'cv05' on, 'ss03' on, 'cv11' on", "--framer-font-size": "calc(var(--variable-reference-hx_eyvbB1-Cncr1d_lo) * 1px)", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 32, \"wght\" 500)", "--framer-letter-spacing": "-0.01px", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))" } as CSSProperties}>
                            {content.l_2}
                          </p>
                        </div>
                      </div>
                    </div>
                    <div className="framer-1x6nu5f" data-framer-name="Arrow" style={{ width: "28px", height: "28px", minWidth: "28px", minHeight: "28px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "6px", borderRadius: "100px", opacity: "0", overflow: "clip", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px" } as CSSProperties} />
                  </div>
                  <div className="framer-1euzglo" data-framer-name="GenBorder" style={{ width: "240px", height: "114px", position: "absolute", display: "block", flexDirection: "row", opacity: "0" } as CSSProperties} />
                </a>
              </div>
            </div>
          </motion.div>
        </motion.div>
      </div>
    </section>
  );
}
