// NewPivot.tsx — section converted to a real JSX component by extract-site.
// Editable React: entrance animations are inline framer-motion props with the
// MEASURED timing from the original site; hover effects live in hover.css.
// Copy, photos, and links live in the sibling content module — edit there to
// re-skin this section without touching layout/motion.
import type { CSSProperties } from "react";
import content from "../content/09-NewPivot";

export function NewPivot() {
  return (
    <div className="framer-1ic9yvz" data-framer-name="New Pivot" style={{ width: "1440px", height: "641.203px", padding: "120px 0px 150px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "40px", backgroundColor: "rgb(0, 0, 0)", overflow: "clip" } as CSSProperties}>
      <div className="framer-8i2eol hvt-2787" style={{ width: "1440px", height: "200px", position: "absolute", top: "441.203px", zIndex: "2", inset: "441.203px 0px 0px", display: "block", flexDirection: "row" } as CSSProperties} />
      <header className="framer-fd1hfd" data-framer-name="Header" style={{ width: "1200px", height: "54px", maxWidth: "1200px", padding: "0px 40px", position: "relative", zIndex: "2", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "15px" } as CSSProperties}>
        <div className="framer-1jstmf3 hv-2789" data-framer-component-type="RichTextContainer" style={{ width: "682px", height: "54px", maxWidth: "100%", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", transform: "none" } as CSSProperties}>
          <h2 className="framer-text framer-styles-preset-1gzpg4m" data-styles-preset="gM4yNG9Qq" dir="auto" style={{ width: "682px", height: "54px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"GT Walsheim Medium\", \"GT Walsheim Medium Placeholder\", sans-serif", fontSize: "54px", fontWeight: "500", lineHeight: "54px", letterSpacing: "-2.16px", textAlign: "center", color: "rgb(255, 255, 255)", "--framer-text-alignment": "center" } as CSSProperties}>
            {content.header}
          </h2>
        </div>
      </header>
      <div className="framer-u87vhl-container hidden-sv03hi hvt-2791" style={{ width: "582px", height: "221px", position: "relative", display: "block", flexDirection: "row" } as CSSProperties}>
        <div className="framer-WNEgj framer-Y1MUo framer-lxmkf4 framer-v-lxmkf4" data-framer-name="Empty" style={{ width: "100%", height: "221px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
          <form className="framer-7yc5tw hv-2793" data-border="true" data-framer-name="Input" style={{ width: "582px", height: "186px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "flex-end", alignContent: "flex-end", gap: "10px", backgroundColor: "rgb(26, 26, 26)", borderRadius: "15px", overflow: "hidden", "--border-bottom-width": "1px", "--border-color": "rgba(255, 255, 255, 0.07)", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
            <div className="framer-8pgnt" data-framer-name="Input" style={{ width: "582px", height: "186px", padding: "10px", position: "relative", zIndex: "1", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", alignContent: "flex-start", gap: "10px", opacity: "1" } as CSSProperties}>
              <div style={{ position: "relative", display: "contents", flexDirection: "row" } as CSSProperties} className="hvt-2795">
                <div className="framer-form-text-input framer-form-input-wrapper framer-pkok8v framer-form-textarea-input-type" style={{ width: "562px", height: "125px", minHeight: "50px", position: "relative", display: "flex", flexDirection: "row", alignItems: "center", overflow: "hidden", "--framer-input-font-color": "rgb(255, 255, 255)", "--framer-input-icon-mask-image": "none", "--framer-input-placeholder-color": "rgb(102, 102, 102)", opacity: "1" } as CSSProperties}>
                  <textarea required name="Prompt" placeholder="Redesign my existing website into something mo" className="framer-form-input hv-2797" style={{ width: "562px", height: "125px", minHeight: "50px", position: "static", display: "flex", flexDirection: "row", fontFamily: "Inter", fontWeight: "500", lineHeight: "16.8px", color: "rgb(255, 255, 255)", whiteSpace: "break-spaces", overflow: "hidden auto" } as CSSProperties} />
                </div>
              </div>
              <div className="framer-1rmx0ug" data-framer-name="Border" style={{ width: "562px", height: "1px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(255, 255, 255, 0.06)", overflow: "clip", opacity: "1" } as CSSProperties} />
              <div className="framer-j65a5z hvt-2799" data-framer-name="Actions" style={{ width: "562px", height: "20px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                <div className="framer-ag3rkn" data-highlight="true" id="undefined-ag3rkn" style={{ width: "93.8672px", height: "16.7969px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "6px", opacity: "1" } as CSSProperties}>
                  <div className="framer-121eqcm hv-2801" data-framer-component-type="RichTextContainer" style={{ width: "79.8672px", height: "16.7969px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "rgb(153, 153, 153)", transform: "none", opacity: "1" } as CSSProperties}>
                    <p dir="auto" className="framer-text" style={{ width: "79.8672px", height: "16.7969px", position: "static", display: "block", flexDirection: "row", fontFamily: "Inter, \"Inter Placeholder\", sans-serif", fontWeight: "500", lineHeight: "16.8px", textAlign: "left", color: "rgb(153, 153, 153)", "--font-selector": "SW50ZXItTWVkaXVt", "--framer-font-open-type-features": "'cv01' on, 'cv09' on, 'tnum' on", "--framer-font-size": "12px", "--framer-font-weight": "500", "--framer-line-height": "1.4em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, rgb(153, 153, 153))" } as CSSProperties}>
                      {content.actions}
                    </p>
                  </div>
                  <div data-framer-component-type="SVG" className="framer-g8p6za hvt-2803" aria-hidden="true" style={{ width: "8px", height: "8px", position: "relative", display: "block", flexDirection: "row", backgroundColor: "rgba(0, 0, 0, 0)", imageRendering: "pixelated", flexShrink: "0", backgroundSize: "100% 100%", backgroundImage: "url(\"data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 xmlns:xlink=%22http://www.w3.org/1999/xlink%22 viewBox=%220 0 8 8%22><path d=%22M 0 6 L 2.293 3.707 C 2.683 3.317 2.683 2.683 2.293 2.293 L 0 0%22 transform=%22translate(2.5 1) rotate(90 1.5 3)%22 fill=%22transparent%22 stroke-width=%221.5%22 stroke=%22rgb(153, 153, 153)%22 stroke-linecap=%22round%22 stroke-linejoin=%22round%22></path></svg>\")", opacity: "1" } as CSSProperties} />
                </div>
                <div className="framer-tobqst" style={{ width: "20px", height: "20px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "5px", opacity: "1" } as CSSProperties}>
                  <div className="framer-1r7c7vc-container hv-2805" style={{ width: "20px", height: "20px", position: "relative", zIndex: "1", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                    <button className="framer-rc2Tf framer-1pjvk2z framer-v-1pjvk2z" data-border="true" data-framer-name="Active" data-highlight="true" data-reset="button" style={{ width: "100%", height: "100%", padding: "0px 0.5px 0px 0px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "8px", backgroundColor: "rgba(255, 255, 255, 0.3)", border: "0px outset rgb(0, 0, 0)", borderRadius: "5px", textAlign: "center", "--border-bottom-width": "0px", "--border-color": "rgba(255, 255, 255, 0.1)", "--border-left-width": "0px", "--border-right-width": "0px", "--border-style": "solid", "--border-top-width": "0.5px", borderBottomLeftRadius: "5px", borderBottomRightRadius: "5px", borderTopLeftRadius: "5px", borderTopRightRadius: "5px", opacity: "1" } as CSSProperties}>
                      <div data-framer-component-type="SVG" className="framer-1i7m2jr hvt-2807" aria-hidden="true" style={{ width: "20px", height: "20px", position: "relative", display: "block", flexDirection: "row", imageRendering: "pixelated", flexShrink: "0", backgroundSize: "100% 100%", backgroundImage: "url(\"data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 xmlns:xlink=%22http://www.w3.org/1999/xlink%22 viewBox=%220 0 19.5 19.5%22><path d=%22M 4.75 9.5 L 9.043 5.207 C 9.433 4.817 10.067 4.817 10.457 5.207 L 14.75 9.5%22 fill=%22transparent%22 stroke-width=%221.5%22 stroke=%22rgb(255, 255, 255)%22 stroke-linecap=%22round%22 stroke-linejoin=%22round%22></path><path d=%22M 9.75 6.253 L 9.75 14.753%22 fill=%22transparent%22 stroke-width=%221.5%22 stroke=%22rgb(255, 255, 255)%22 stroke-linecap=%22round%22 stroke-linejoin=%22round%22></path></svg>\")", opacity: "1" } as CSSProperties} />
                    </button>
                  </div>
                </div>
              </div>
            </div>
            <input type="text" name="website" tabIndex={-1} autoComplete="one-time-code" aria-hidden="true" style={{ width: "133px", height: "20px", padding: "1px 2px", position: "absolute", bottom: "166px", left: "449px", inset: "0px 0px 166px 449px", display: "block", flexDirection: "row", backgroundColor: "rgb(255, 255, 255)", border: "2px inset rgb(118, 118, 118)", transform: "scale(0)", transformOrigin: "66.5px 10px", overflow: "clip" } as CSSProperties} data-1p-ignore="true" data-lpignore="true" data-form-type="other" data-bwignore="true" value="" />
            <input type="text" name="company" tabIndex={-1} autoComplete="one-time-code" aria-hidden="true" style={{ width: "133px", height: "20px", padding: "1px 2px", position: "absolute", bottom: "166px", left: "449px", inset: "0px 0px 166px 449px", display: "block", flexDirection: "row", backgroundColor: "rgb(255, 255, 255)", border: "2px inset rgb(118, 118, 118)", transform: "scale(0)", transformOrigin: "66.5px 10px", overflow: "clip" } as CSSProperties} data-1p-ignore="true" data-lpignore="true" data-form-type="other" data-bwignore="true" value="" />
            <input type="text" name="message" tabIndex={-1} autoComplete="one-time-code" aria-hidden="true" style={{ width: "133px", height: "20px", padding: "1px 2px", position: "absolute", bottom: "166px", left: "449px", inset: "0px 0px 166px 449px", display: "block", flexDirection: "row", backgroundColor: "rgb(255, 255, 255)", border: "2px inset rgb(118, 118, 118)", transform: "scale(0)", transformOrigin: "66.5px 10px", overflow: "clip" } as CSSProperties} data-1p-ignore="true" data-lpignore="true" data-form-type="other" data-bwignore="true" value="" />
            <input type="text" name="subject" tabIndex={-1} autoComplete="one-time-code" aria-hidden="true" style={{ width: "133px", height: "20px", padding: "1px 2px", position: "absolute", bottom: "166px", left: "449px", inset: "0px 0px 166px 449px", display: "block", flexDirection: "row", backgroundColor: "rgb(255, 255, 255)", border: "2px inset rgb(118, 118, 118)", transform: "scale(0)", transformOrigin: "66.5px 10px", overflow: "clip" } as CSSProperties} data-1p-ignore="true" data-lpignore="true" data-form-type="other" data-bwignore="true" value="" />
            <input type="text" name="title" tabIndex={-1} autoComplete="one-time-code" aria-hidden="true" style={{ width: "133px", height: "20px", padding: "1px 2px", position: "absolute", bottom: "166px", left: "449px", inset: "0px 0px 166px 449px", display: "block", flexDirection: "row", backgroundColor: "rgb(255, 255, 255)", border: "2px inset rgb(118, 118, 118)", transform: "scale(0)", transformOrigin: "66.5px 10px", overflow: "clip" } as CSSProperties} data-1p-ignore="true" data-lpignore="true" data-form-type="other" data-bwignore="true" value="" />
            <input type="text" name="description" tabIndex={-1} autoComplete="one-time-code" aria-hidden="true" style={{ width: "133px", height: "20px", padding: "1px 2px", position: "absolute", bottom: "166px", left: "449px", inset: "0px 0px 166px 449px", display: "block", flexDirection: "row", backgroundColor: "rgb(255, 255, 255)", border: "2px inset rgb(118, 118, 118)", transform: "scale(0)", transformOrigin: "66.5px 10px", overflow: "clip" } as CSSProperties} data-1p-ignore="true" data-lpignore="true" data-form-type="other" data-bwignore="true" value="" />
            <input type="text" name="feedback" tabIndex={-1} autoComplete="one-time-code" aria-hidden="true" style={{ width: "133px", height: "20px", padding: "1px 2px", position: "absolute", bottom: "166px", left: "449px", inset: "0px 0px 166px 449px", display: "block", flexDirection: "row", backgroundColor: "rgb(255, 255, 255)", border: "2px inset rgb(118, 118, 118)", transform: "scale(0)", transformOrigin: "66.5px 10px", overflow: "clip" } as CSSProperties} data-1p-ignore="true" data-lpignore="true" data-form-type="other" data-bwignore="true" value="" />
            <input type="text" name="notes" tabIndex={-1} autoComplete="one-time-code" aria-hidden="true" style={{ width: "133px", height: "20px", padding: "1px 2px", position: "absolute", bottom: "166px", left: "449px", inset: "0px 0px 166px 449px", display: "block", flexDirection: "row", backgroundColor: "rgb(255, 255, 255)", border: "2px inset rgb(118, 118, 118)", transform: "scale(0)", transformOrigin: "66.5px 10px", overflow: "clip" } as CSSProperties} data-1p-ignore="true" data-lpignore="true" data-form-type="other" data-bwignore="true" value="" className="hv-2815" />
            <input type="text" name="details" tabIndex={-1} autoComplete="one-time-code" aria-hidden="true" style={{ width: "133px", height: "20px", padding: "1px 2px", position: "absolute", bottom: "166px", left: "449px", inset: "0px 0px 166px 449px", display: "block", flexDirection: "row", backgroundColor: "rgb(255, 255, 255)", border: "2px inset rgb(118, 118, 118)", transform: "scale(0)", transformOrigin: "66.5px 10px", overflow: "clip" } as CSSProperties} data-1p-ignore="true" data-lpignore="true" data-form-type="other" data-bwignore="true" value="" />
            <input type="text" name="remarks" tabIndex={-1} autoComplete="one-time-code" aria-hidden="true" style={{ width: "133px", height: "20px", padding: "1px 2px", position: "absolute", bottom: "166px", left: "449px", inset: "0px 0px 166px 449px", display: "block", flexDirection: "row", backgroundColor: "rgb(255, 255, 255)", border: "2px inset rgb(118, 118, 118)", transform: "scale(0)", transformOrigin: "66.5px 10px", overflow: "clip" } as CSSProperties} data-1p-ignore="true" data-lpignore="true" data-form-type="other" data-bwignore="true" value="" className="hvt-2817" />
            <input type="text" name="comments" tabIndex={-1} autoComplete="one-time-code" aria-hidden="true" style={{ width: "133px", height: "20px", padding: "1px 2px", position: "absolute", bottom: "166px", left: "449px", inset: "0px 0px 166px 449px", display: "block", flexDirection: "row", backgroundColor: "rgb(255, 255, 255)", border: "2px inset rgb(118, 118, 118)", transform: "scale(0)", transformOrigin: "66.5px 10px", overflow: "clip" } as CSSProperties} data-1p-ignore="true" data-lpignore="true" data-form-type="other" data-bwignore="true" value="" />
          </form>
          <div className="framer-1tfeyil hv-2819" data-framer-name="Suggestions" style={{ width: "581.023px", height: "25px", position: "relative", zIndex: "2", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", opacity: "1" } as CSSProperties}>
            <div className="framer-mu90bt" data-border="true" data-highlight="true" tabIndex={0} style={{ width: "162.578px", height: "25px", padding: "0px 10px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", backgroundColor: "rgba(255, 255, 255, 0.08)", borderRadius: "8px", "--border-bottom-width": "1px", "--border-color": "rgba(255, 255, 255, 0.05)", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
              <div className="framer-2ayj93 hvt-2821" data-framer-component-type="RichTextContainer" style={{ width: "142.578px", height: "16.7969px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "rgb(153, 153, 153)", transform: "none", opacity: "1" } as CSSProperties}>
                <p dir="auto" className="framer-text" style={{ width: "142.578px", height: "16.7969px", position: "static", display: "block", flexDirection: "row", fontFamily: "Inter, \"Inter Placeholder\", sans-serif", fontWeight: "500", lineHeight: "16.8px", textAlign: "left", color: "rgb(153, 153, 153)", "--font-selector": "SW50ZXItTWVkaXVt", "--framer-font-open-type-features": "'cv01' on, 'cv09' on, 'tnum' on", "--framer-font-size": "12px", "--framer-font-weight": "500", "--framer-line-height": "1.4em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, rgb(153, 153, 153))" } as CSSProperties}>
                  {content.suggestions}
                </p>
              </div>
            </div>
            <div className="framer-16ktwpi hv-2823" data-border="true" data-highlight="true" tabIndex={0} style={{ width: "116.5px", height: "25px", padding: "0px 10px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", backgroundColor: "rgba(255, 255, 255, 0.08)", borderRadius: "8px", "--border-bottom-width": "1px", "--border-color": "rgba(255, 255, 255, 0.05)", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
              <div className="framer-x6npa9" data-framer-component-type="RichTextContainer" style={{ width: "96.5px", height: "16.7969px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "rgb(153, 153, 153)", transform: "none", opacity: "1" } as CSSProperties}>
                <p dir="auto" className="framer-text hvt-2825" style={{ width: "96.5px", height: "16.7969px", position: "static", display: "block", flexDirection: "row", fontFamily: "Inter, \"Inter Placeholder\", sans-serif", fontWeight: "500", lineHeight: "16.8px", textAlign: "left", color: "rgb(153, 153, 153)", "--font-selector": "SW50ZXItTWVkaXVt", "--framer-font-open-type-features": "'cv01' on, 'cv09' on, 'tnum' on", "--framer-font-size": "12px", "--framer-font-weight": "500", "--framer-line-height": "1.4em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, rgb(153, 153, 153))" } as CSSProperties}>
                  {content.suggestions_2}
                </p>
              </div>
            </div>
            <div className="framer-kdogyq" data-border="true" data-highlight="true" tabIndex={0} style={{ width: "139.617px", height: "25px", padding: "0px 10px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", backgroundColor: "rgba(255, 255, 255, 0.08)", borderRadius: "8px", "--border-bottom-width": "1px", "--border-color": "rgba(255, 255, 255, 0.05)", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
              <div className="framer-1qn7ayf hv-2827" data-framer-component-type="RichTextContainer" style={{ width: "119.617px", height: "16.7969px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "rgb(153, 153, 153)", transform: "none", opacity: "1" } as CSSProperties}>
                <p dir="auto" className="framer-text" style={{ width: "119.617px", height: "16.7969px", position: "static", display: "block", flexDirection: "row", fontFamily: "Inter, \"Inter Placeholder\", sans-serif", fontWeight: "500", lineHeight: "16.8px", textAlign: "left", color: "rgb(153, 153, 153)", "--font-selector": "SW50ZXItTWVkaXVt", "--framer-font-open-type-features": "'cv01' on, 'cv09' on, 'tnum' on", "--framer-font-size": "12px", "--framer-font-weight": "500", "--framer-line-height": "1.4em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, rgb(153, 153, 153))" } as CSSProperties}>
                  <code className="framer-text hvt-2829" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties}>
                    {content.suggestions_3}
                  </code>
                </p>
              </div>
            </div>
            <div className="framer-1rp9zpe" data-border="true" data-highlight="true" tabIndex={0} style={{ width: "132.328px", height: "25px", padding: "0px 10px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", backgroundColor: "rgba(255, 255, 255, 0.08)", borderRadius: "8px", "--border-bottom-width": "1px", "--border-color": "rgba(255, 255, 255, 0.05)", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", opacity: "1" } as CSSProperties}>
              <div className="framer-bhsh7p hv-2831" data-framer-component-type="RichTextContainer" style={{ width: "112.328px", height: "16.7969px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-r6o4lv": "rgb(153, 153, 153)", transform: "none", opacity: "1" } as CSSProperties}>
                <p dir="auto" className="framer-text" style={{ width: "112.328px", height: "16.7969px", position: "static", display: "block", flexDirection: "row", fontFamily: "Inter, \"Inter Placeholder\", sans-serif", fontWeight: "500", lineHeight: "16.8px", textAlign: "left", color: "rgb(153, 153, 153)", "--font-selector": "SW50ZXItTWVkaXVt", "--framer-font-open-type-features": "'cv01' on, 'cv09' on, 'tnum' on", "--framer-font-size": "12px", "--framer-font-weight": "500", "--framer-line-height": "1.4em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, rgb(153, 153, 153))" } as CSSProperties}>
                  {content.suggestions_4}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="framer-wc2dv3-container hidden-sv03hi hvt-2833" style={{ width: "98.875px", height: "16.2031px", position: "relative", zIndex: "2", display: "block", flexDirection: "row", opacity: "0.7" } as CSSProperties}>
        <a className="framer-y3Tcj framer-1yj9q62 framer-v-1yo7lad framer-fbfhdw" data-framer-name="S" data-highlight="true" tabIndex={0} style={{ width: "98.875px", height: "16.2031px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "3px", filter: "invert(0)", color: "rgb(0, 0, 238)", overflow: "hidden", WebkitFilter: "invert(0)", opacity: "1" } as CSSProperties} href={content.s}>
          <div className="framer-46btbc hv-2835" data-framer-component-type="RichTextContainer" style={{ width: "85.875px", height: "16.2031px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-a0htzi": "var(--variable-reference-u7EixmfP1-M8z52uvts)", "--extracted-zfisys": "\"opsz\" 18, \"wght\" 420", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", "--variable-reference-u7eixmfp1-m8z52uvts": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--extracted-2gg91v": "\"opsz\" 14, \"wght\" 500", "--extracted-r6o4lv": "var(--variable-reference-u7EixmfP1-M8z52uvts)", transform: "none", opacity: "1" } as CSSProperties}>
            <p dir="auto" className="framer-text" style={{ width: "85.875px", height: "16.2031px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", lineHeight: "16.2px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTBMQ0FpZDJkb2RDSWdOVEF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv11' on", "--framer-font-size": "12px", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 14, \"wght\" 500)", "--framer-letter-spacing": "-0.2px", "--framer-line-height": "1.35em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-u7EixmfP1-M8z52uvts))" } as CSSProperties}>
              {content.s_2}
            </p>
          </div>
          <div className="framer-17vqbi5 hvt-2837" style={{ width: "10px", height: "16.2031px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
            <svg className="framer-ooj1j framer-1pqbd5p" role="presentation" viewBox="0 0 20 20" style={{ width: "10px", height: "10px", position: "relative", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "2", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--17kkcf8": "rgba(136, 136, 136, 0.2)", opacity: "1" } as CSSProperties}>
              <use href="#1825208344" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} className="hv-2839" />
            </svg>
          </div>
        </a>
      </div>
    </div>
  );
}
