// App.tsx — generated by `extract-site rebuild-site`.
//
// A ~40-line history router rather than a react-router dependency: the rebuilt
// markup is plain <a href="/route"> (the generator rewrote the mirror's
// ../../ paths), so all this needs to do is intercept those clicks, push
// history, and swap the route module.
import { Suspense, useCallback, useEffect, useState } from "react";
import { routes } from "./routes";
import { NavDropdowns } from "./NavDropdowns";

function currentPath(): string {
  const p = window.location.pathname.replace(/\/+$/, "");
  return p || "/";
}

export function App() {
  const [path, setPath] = useState(currentPath);

  const navigate = useCallback((to: string) => {
    if (to === currentPath()) return;
    window.history.pushState({}, "", to);
    setPath(to);
  }, []);

  useEffect(() => {
    const onPop = () => setPath(currentPath());
    window.addEventListener("popstate", onPop);

    const onClick = (e: MouseEvent) => {
      // let the browser handle anything that isn't a plain left-click on an
      // internal link — new tabs, downloads and external routes must survive.
      if (e.defaultPrevented || e.button !== 0) return;
      if (e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;
      const a = (e.target as Element | null)?.closest?.("a");
      if (!a) return;
      if (a.hasAttribute("download") || a.hasAttribute("data-external-route")) return;
      if (a.target && a.target !== "" && a.target !== "_self") return;
      const href = a.getAttribute("href") ?? "";
      if (!href.startsWith("/")) return; // #anchor, mailto:, http(s):// … not ours
      const to = href.replace(/\/+$/, "") || "/";
      if (!(to in routes)) return; // not a route we serve — let it 404 honestly
      e.preventDefault();
      navigate(to);
    };
    document.addEventListener("click", onClick);

    return () => {
      window.removeEventListener("popstate", onPop);
      document.removeEventListener("click", onClick);
    };
  }, [navigate]);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [path]);

  const Route = routes[path];
  if (!Route) {
    return (
      <main style={{ padding: "6rem 2rem", fontFamily: "system-ui", color: "#fff", background: "#000", minHeight: "100vh" }}>
        <h1 style={{ fontSize: "2rem", marginBottom: "0.5rem" }}>Not rebuilt</h1>
        <p style={{ opacity: 0.7 }}>
          <code>{path}</code> isn't one of the rebuilt routes.
        </p>
        <ul style={{ marginTop: "1.5rem", lineHeight: 1.9 }}>
          {Object.keys(routes).map((r) => (
            <li key={r}><a href={r} style={{ color: "#8ab4ff" }}>{r}</a></li>
          ))}
        </ul>
      </main>
    );
  }

  return (
    <>
      <Suspense fallback={<div style={{ minHeight: "100vh", background: "#000" }} />}>
        <Route key={path} />
      </Suspense>
      <NavDropdowns />
    </>
  );
}
