// route table — generated by `extract-site rebuild-site`.
// Lazy imports so each page's markup AND its ~470 kB stylesheet load only when
// that route is visited.
import { lazy } from "react";
import type { ComponentType } from "react";

export const routes: Record<string, ReturnType<typeof lazy<ComponentType>>> = {
  "/academy": lazy(() => import("./pages/academy")),
  "/agents": lazy(() => import("./pages/agents")),
  "/cms": lazy(() => import("./pages/cms")),
  "/collaborate": lazy(() => import("./pages/collaborate")),
  "/design": lazy(() => import("./pages/design")),
  "/solutions/designers": lazy(() => import("./pages/solutions-designers")),
  "/enterprise": lazy(() => import("./pages/enterprise")),
  "/": lazy(() => import("./pages/home")),
  "/hosting": lazy(() => import("./pages/hosting")),
  "/performance": lazy(() => import("./pages/performance")),
  "/publish": lazy(() => import("./pages/publish")),
  "/seo": lazy(() => import("./pages/seo")),
  "/stories": lazy(() => import("./pages/stories")),
};

export const routePaths = Object.keys(routes);
