// content for the "Header" section — extracted by extract-site.
// Edit values here to re-skin the "Header" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  content: "Build sites in parallel. Publish with confidence.",
  regular: "https://framer-ai.com/r/signup",
  label: "Get started for free",
  label_2: "Used by teams at:",
  canvas: "Canvas",
  default: "Site",
  default_2: "·",
  off: "main",
  number: "12",
  team: { src: "/images/67795d4b-UnfUTFiycUvyLiWVaZSTQX3S7kA73f7.png?width=335&height=335", alt: "Interface preview in 2026 UI/Canvas UI/App UI Top Bar." },
  team_2: { src: "/images/02612926-23W7URwXzeyNBGr6KAR1Ovou6V44395.png?width=475&height=475", alt: "Interface preview in 2026 UI/Canvas UI/App UI Top Bar." },
  team_3: { src: "/images/9081ee25-HpuIynUBjhAJSaXjaIesR9XZ7fMdb13.png?scale-down-to=512&width=2160&height=2160", alt: "Interface preview in 2026 UI/Canvas UI/App UI Top Bar." },
  invite: "Invite",
  publish: "Publish",
  on: "Pages",
  off_2: "Layers",
  off_3: "Assets",
  input: "Search…",
  pageHeader: "Pages",
  page: "Home",
  branch: "3",
  page_2: "/about",
  activePage: "/notes",
  branch_2: "2",
  branch1: { src: "/images/89705f1b-ntiwDgzi5wOqmqjXDo9kHq9Ni3sf73b.png?width=192&height=192", alt: "Interface preview in 2026 UI/Canvas UI/App UI Page Item." },
  branch1_2: "typography",
  branch1_3: "3m",
  branch2: { src: "/images/8d225e32-PNKbO6dGnRRwEvctPlhddS3H2s20cf.png?width=512&height=512", alt: "Interface preview in 2026 UI/Canvas UI/App UI Page Item." },
  branch2_2: "newsletter",
  branch2_3: "2d",
  subPage: "Notes Pages",
  page_3: "/inspiration",
  page_4: "/authors",
  branch_3: "1",
  subPage_2: "Author Pages",
  page_5: "/legal",
  subPage_3: "/privacy",
  subPage_4: "/terms",
  zoom: "100%",
  off_4: "Desktop",
  off_5: "1200",
  blog: { src: "../../framerusercontent.com/images/Mua7e6puZY3RTamVkeCN2bb63982f0e.jpg?width=1800&height=2937", alt: "Collaborative design workspace preview" },
  off_6: "Tablet",
  off_7: "810",
  default_3: { src: "../../framerusercontent.com/images/ICi2m2zyPai1LKwz9XZEkgSzQbacd.jpg?width=1620&height=140", alt: "Default interface preview in 2026 Frontpage/Home Hero Site Tablet." },
  hero: "https://framerusercontent.com/assets/tIWm3IhzJNTfEtVL9lEqnFZAy58.mp4",
  about: { src: "../../framerusercontent.com/images/HMvEeofMOWYzHDwChgXFgpYcs9a75.jpg?width=1620&height=370", alt: "About interface preview in 2026 Frontpage/Home Hero Site Tablet." },
  heroVideo: { src: "../../framerusercontent.com/images/VDou7Mwa4dcffjzYvoa80Cmi7438ca.jpg?width=1620&height=960", alt: "Hero Video interface preview in 2026 Frontpage/Home Hero Site Tablet." },
  list: { src: "../../framerusercontent.com/images/MvPPd7I4xJxeNO5ievRfaoAEdd78.jpg?width=1620&height=1180", alt: "List interface preview in 2026 Frontpage/Home Hero Site Tablet." },
  footer: { src: "../../framerusercontent.com/images/I4HWeSzUbC3vy22QykEaieasPYbacd.jpg?width=1620&height=140", alt: "Interface preview in 2026 Frontpage/Home Hero Site Tablet." },
  header: "Comments",
  user: { src: "/images/96913bcf-OmKDjH7juzfJ8ETRwLy9hglwa0f73b.png?width=192&height=192", alt: "Collaborator avatar" },
  user_2: "Jorn van Dijk",
  user_3: "2m ago",
  comment1: "The card borders look great, really subtle. Can we apply the same style to the pricing table rows too?",
  user_4: { src: "/images/89705f1b-ntiwDgzi5wOqmqjXDo9kHq9Ni3sf73b.png?width=192&height=192", alt: "Collaborator avatar" },
  user_5: "Paul Lapkin",
  user_6: "2h ago",
  comment2: "The H2 at 56px feels much more balanced on the hero. Should we tighten the letter spacing just a touch more?",
  comment2_2: "2 replies",
  user_7: { src: "/images/e9f471f8-Qmgj3M1wKdUN21KeMuSnVcLlYcf73b.png?width=192&height=192", alt: "Collaborator avatar" },
  user_8: "Jurre Houtkamp",
  user_9: "45m ago",
  comment3: "The cards are wrapping weirdly at 810px and the gap feels too wide. Worth reducing it to 16px on tablet?",
  comment3_2: "2 replies",
};
