// content for the "Benefits" section — extracted by extract-site.
// Edit values here to re-skin the "Benefits" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "From design to deploy, together",
  dynamicIsland: { src: "/images/0a2a7cfb-sHQsKwHsePaBOMy5WRzZXEPX42abb.png?width=190&height=60", alt: "Dynamic island interface preview" },
  searchBar: "website.com/notes",
  logo: "Common Form",
  back: "Notes",
  top: "Inspiration",
  typewriter: "Before the image",
  typewriter_2: "|",
  image: { src: "../../framerusercontent.com/images/0HbgO4OOARF8eP65HCSKlTfksec97.jpg?width=1540&height=1021", alt: "Framer collaboration feature preview" },
  l: "https://framer-ai.com/help/articles/on-page-editing",
  l_2: "Edit content anywhere",
  text: "Update collections directly on your site, on any device. Teammates can edit content on mobile without ever opening the canvas.",
  avatar: { src: "/images/7895a687-d3fc20aSN9xHRKfHu8HAC30Is420cf.png?width=512&height=512", alt: "Collaborator avatar" },
  name: "Adam Seckel",
  permissions: "Design, Content",
  design: "Design",
  design_2: "Canvas",
  content: "Content",
  content_2: "CMS, On-Page",
  deploy: "Deploy",
  deploy_2: "Publish",
  l_3: "https://framer-ai.com/help/articles/member-roles-and-permissions",
  l_4: "Give everyone the right level of access",
  text_2: "Set roles for every team member. Full editors can design and publish. Viewers can comment and review without touching the project.",
  user: { src: "/images/89705f1b-ntiwDgzi5wOqmqjXDo9kHq9Ni3sf73b.png?width=192&height=192", alt: "Collaborator avatar" },
  off1: { src: "/images/89705f1b-ntiwDgzi5wOqmqjXDo9kHq9Ni3sf73b.png?width=192&height=192", alt: "Collaborator avatar" },
  off1_2: "Paul Lapkin",
  off1_3: "30m ago",
  off1_4: "The H2 at 56px feels much more balanced on the hero. Should we tighten the letter spacing just a touch more?",
  text_3: "Leave feedback directly on the canvas",
  text_4: "Press",
  text_5: "C",
  text_6: "and comment directly on the canvas. Pin feedback to any element, reply in threads, and resolve notes as changes are made.",
  branch: "launch",
  domain: "stale-gift…new-pricing.framer.app",
  time: "3m ago · by Benjamin den Boer",
  changes: "32 changes",
  button: "Update",
  l_5: "https://framer-ai.com/help/articles/staging-and-versions",
  l_6: "Test changes before they go live",
  text_7: "Every branch gets a staging URL. Share it with your team, run QA on a real domain, and only push to production when you’re ready.",
};
