// content for the "Bento" section — extracted by extract-site.
// Edit values here to re-skin the "Bento" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  url: "Home",
  url_2: "/features",
  url_3: "/blog",
  url_4: "/support",
  bentoCard: "https://framer-ai.com/blog/dynamic-optimization",
  bentoCard_2: "Pre-rendering for faster page loads",
  bentoCard_3: ".",
  bentoCard_4: "Framer websites combine Traffic-aware Pre-Rendering (TPR) and Static Site Generation (SSG) to intelligently pre-render your top pages to deliver the fastest page load speed.",
  pill: "Paul",
  desktop: { src: "../../framerusercontent.com/images/S43v7ZyH8pHp6AHP7VjTF1b2Rwcc2a.jpg?width=720&height=720", alt: "Rocket blasting off" },
  saved: "Saved",
  saved_2: "27%",
  image: "Format",
  image_2: "WebP",
  bentoCard_5: "Dynamic image optimization.",
  bentoCard_6: "Images resize for every device. Large assets are compressed at the edge to",
  bentoCard_7: "WebP",
  bentoCard_8: "and",
  bentoCard_9: "AVIF",
  bentoCard_10: "without quality loss.",
  visual: { src: "../../framerusercontent.com/images/LHwPBb8KjkVBo1GtFNHwLaTEc7a00.jpg?width=720&height=480", alt: "" },
  visual_2: { src: "../../framerusercontent.com/images/OVYESfwO9UCoNJ6kAhXpNRU6uIMd97e.png?width=1968&height=2464", alt: "" },
  visual_3: { src: "../../framerusercontent.com/images/pwI8IwnaePeesfbgyFPyq0j4rkd97e.png?width=1968&height=2464", alt: "" },
  visual_4: { src: "../../framerusercontent.com/images/fRuLfsZmHFongbDXONMpCPgNkk8120.png?width=2688&height=1792", alt: "" },
  bentoCard_11: "Server-side lazy loading.",
  bentoCard_12: "We render each page on the server, prioritize the initial viewport, and lazy load offscreen content for the fastest load times.",
  googleSheets2020LogoSvg: { src: "../../framerusercontent.com/images/0lnipoWDC3o7pWz2H93q7KiCHgc120.png?lossless=1&width=1024&height=1024", alt: "" },
  txt: "llms",
  txt_2: ".txt",
  bentoCardAeo: "/seo",
  bentoCardAeo_2: "SEO, AEO, and AI visibility",
  bentoCardAeo_3: ".",
  bentoCardAeo_4: "Sitemaps, caching, clean metadata, and",
  bentoCardAeo_5: "llms.txt",
  bentoCardAeo_6: "help search engines and AI discover and understand your site.",
  header: "Core Web Vitals",
  status: "GOOD",
  label: "LCP",
  top: "1.1s",
  label_2: "INP",
  top_2: "95ms",
  label_3: "CLS",
  top_3: "0.01",
  bentoCardVitals: "PageSpeed and Core Web Vitals.",
  bentoCardVitals_2: "Framer improves performance scores with fast LCP, low CLS, responsive INP, optimized assets, and edge delivery.",
  visual_5: { src: "../../framerusercontent.com/images/wgYWpiBI7OOAhkJiqszZfeOR2I7a00.jpg?width=720&height=480", alt: "Man on laptop" },
  texts: "How predictive preloading anticipates your next click",
  category: "Performance",
  category_2: "•",
  category_3: "3 min read",
  visual_6: { src: "../../framerusercontent.com/images/oB03uw8yV2HUpWZZz0bNOMOdOWg7a00.jpg?width=720&height=480", alt: "Jet flying in the sky" },
  texts_2: "Using predictive preloading for instant page transitions",
  category_4: "Engineering",
  category_5: "•",
  category_6: "4 min read",
  bentoCard_13: "Predictive preloading for instant navigation.",
  bentoCard_14: "As links enter the viewport, pages are quietly prepared via background fetch. The algorithm adapts to network speed and device type to avoid wasting resources.",
  bentoCard_15: "Concurrent React rendering.",
  bentoCard_16: "Framer keeps the main thread free for fast hydration, smooth re-renders, and responsive input.",
};
