// content for the "Benefits" section — extracted by extract-site.
// Edit values here to re-skin the "Benefits" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "Fast delivery across the full website stack",
  l: "/hosting",
  l_2: "Global edge network",
  text: "Published sites deploy across a worldwide edge network, reducing latency and keeping response times fast for visitors in every region.",
  text_2: "Before rolldown",
  text_3: "67 chunks",
  percentile: "P75",
  label: "LCP",
  top: "4.5s",
  text_4: "After rolldown",
  text_5: "22 chunks",
  percentile_2: "P75",
  label_2: "LCP",
  time: "1.1s",
  text_6: "JavaScript bundle optimization",
  text_7: "Powered by",
  text_8: "https://framer-ai.com/blog/framer-rolldown",
  text_9: "Rolldown",
  text_10: ", JavaScript is bundled into an optimal number of chunks. This reduces download sizes and ensures sites become interactive faster.",
  stop: "Hero",
  site: "Next-generation orbital computing",
  visual: "/videos/473d18b3-TsxA2L36uM1kKLrdZam71oCqiVA.mp4",
  text_11: "Virtualization and culling",
  text_12: "Heavy elements like videos activate only in view and stop when out of view, reducing battery drain and keeping CPU and GPU usage low.",
  planet1: "Venus",
  image1: { src: "../../framerusercontent.com/images/DT7E8EnDiySso7pGpVBbq96oXPQ849e.png?width=800&height=800", alt: "Planet Venus" },
  planet2: "Earth",
  planet3: "Mars",
  planet4: "Jupiter",
  text_13: "Smooth animation",
  text_14: "Animations are powered by",
  text_15: "https://motion.dev/",
  text_16: "Motion and WAAPI",
  text_17: "to run off the main thread and even before JavaScript finishes loading, resulting in faster perceived speed.",
};
