// DesktopNav.tsx — section converted to a real JSX component by extract-site.
// Editable React: entrance animations are inline framer-motion props with the
// MEASURED timing from the original site; hover effects live in hover.css.
// Copy, photos, and links live in the sibling content module — edit there to
// re-skin this section without touching layout/motion.
import type { CSSProperties } from "react";
import content from "../content/01-DesktopNav";

export function DesktopNav() {
  return (
    <nav className="framer-DaaDp framer-140pdlc framer-v-140pdlc" data-framer-name="Desktop Nav" data-hide-scrollbars="true" style={{ width: "100%", height: "100%", padding: "0px 20px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", backgroundColor: "rgba(0, 0, 0, 0)", opacity: "1" } as CSSProperties} data-cs-id="5">
      <div className="framer-mhxkvs" data-framer-name="Wrapper" style={{ width: "1200px", height: "34px", maxWidth: "1200px", position: "relative", zIndex: "10", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
        <div className="framer-z96yy7" data-framer-name="Logo + CTA" style={{ width: "1200px", height: "34px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "5px", backgroundColor: "rgba(0, 0, 0, 0)", opacity: "1" } as CSSProperties}>
          <div className="framer-fzxmln" style={{ width: "1200px", height: "34px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "15px", opacity: "1" } as CSSProperties}>
            <div className="framer-1e61pkd-container" style={{ width: "71.7969px", height: "26px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
              <a className="framer-T7ghy framer-qdeek2 framer-v-qdeek2 framer-4n26gx" data-framer-name="On" data-highlight="true" tabIndex={0} style={{ width: "71.7969px", height: "100%", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "10px", color: "rgb(0, 0, 238)", opacity: "1" } as CSSProperties} href={content.on}>
                <div data-framer-component-type="SVG" className="framer-ngytjn" aria-hidden="true" style={{ width: "16px", height: "24px", position: "relative", display: "block", flexDirection: "row", imageRendering: "pixelated", flexShrink: "0", backgroundSize: "100% 100%", backgroundImage: "url(\"data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 xmlns:xlink=%22http://www.w3.org/1999/xlink%22 viewBox=%220 0 16 24%22 overflow=%22visible%22><path d=%22M 16 0 L 16 8 L 8 8 L 0 0 Z M 0 8 L 8 8 L 16 16 L 8 16 L 8 24 L 0 16 Z%22 fill=%22rgb(255, 255, 255)%22></path></svg>\")", opacity: "1" } as CSSProperties} />
                <div className="framer-1gzwofs" data-framer-component-type="RichTextContainer" style={{ width: "45.7969px", height: "14px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 32, \"wght\" 600", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none", opacity: "1" } as CSSProperties}>
                  <p dir="auto" className="framer-text" style={{ width: "45.7969px", height: "14px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "14px", lineHeight: "14px", letterSpacing: "-0.01px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOakF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss07' on, 'cv05' on, 'ss03' on, 'cv11' on", "--framer-font-size": "14px", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 32, \"wght\" 600)", "--framer-letter-spacing": "-0.01px", "--framer-line-height": "1em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                    {content.on_2}
                  </p>
                </div>
              </a>
            </div>
            <div className="framer-1zvg2i" data-framer-name="Links Desktop" data-hide-scrollbars="true" style={{ width: "451.57px", height: "34px", position: "relative", zIndex: "1", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
              <div className="framer-2nzk8h-container" data-framer-name="Platform" style={{ width: "91.2734px", height: "34px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                <a className="framer-IMZjl framer-Bwt8q framer-ly7rus framer-v-1e0zr5a framer-1fczci3 hv-16" data-framer-name="Main Small" data-highlight="true" tabIndex={0} style={{ width: "91.2734px", height: "34px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "10px", opacity: "0.6", "--1h5usve": "default", backgroundColor: "rgba(0, 0, 0, 0)", borderBottomLeftRadius: "0px", borderBottomRightRadius: "0px", borderTopLeftRadius: "0px", borderTopRightRadius: "0px" } as CSSProperties}>
                  <div className="framer-1ach59f" data-framer-name="Topbar Links Text" style={{ width: "91.2734px", height: "34px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "5px", opacity: "1" } as CSSProperties}>
                    <div className="framer-1cso6lv" style={{ width: "91.2734px", height: "34px", padding: "10px 12px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "4px", opacity: "1" } as CSSProperties}>
                      <div className="framer-tcbjjn" data-framer-component-type="RichTextContainer" style={{ width: "55.2734px", height: "14px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 14, \"wght\" 460", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none", opacity: "1" } as CSSProperties}>
                        <p dir="auto" className="framer-text" style={{ width: "55.2734px", height: "14px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "14px", lineHeight: "14px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTBMQ0FpZDJkb2RDSWdORFl3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss07' on, 'cv05' on, 'ss03' on, 'cv11' on", "--framer-font-size": "14px", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 14, \"wght\" 460)", "--framer-letter-spacing": "-0.2px", "--framer-line-height": "1em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.topbarLinksText}
                        </p>
                      </div>
                      <svg data-framer-name="Dropdown" className="framer-iSnEi framer-v1fz1" role="presentation" viewBox="0 0 20 20" style={{ width: "8px", height: "8px", position: "relative", zIndex: "1", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "3", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--17kkcf8": "rgba(136, 136, 136, 0.2)", opacity: "1" } as CSSProperties}>
                        <use href="#367334708" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                      </svg>
                    </div>
                  </div>
                  <div className="framer-4mgnl8" data-framer-name="BG" style={{ width: "87.2734px", height: "30px", position: "absolute", top: "2px", right: "2px", bottom: "2px", left: "2px", zIndex: "1", inset: "2px", display: "block", flexDirection: "row", backgroundColor: "var(--token-70c17056-82cb-4934-97c9-7213cf77c853, rgba(255, 255, 255, 0.1))", borderRadius: "8px", opacity: "0", overflow: "clip", borderBottomLeftRadius: "8px", borderBottomRightRadius: "8px", borderTopLeftRadius: "8px", borderTopRightRadius: "8px" } as CSSProperties} />
                </a>
              </div>
              <div className="framer-npqg6x-container" data-framer-name="Solutions" style={{ width: "96.4062px", height: "34px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                <a className="framer-IMZjl framer-Bwt8q framer-ly7rus framer-v-1e0zr5a framer-1fczci3 hv-25" data-framer-name="Main Small" data-highlight="true" tabIndex={0} style={{ width: "96.4062px", height: "34px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "10px", opacity: "0.6", "--1h5usve": "default", backgroundColor: "rgba(0, 0, 0, 0)", borderBottomLeftRadius: "0px", borderBottomRightRadius: "0px", borderTopLeftRadius: "0px", borderTopRightRadius: "0px" } as CSSProperties}>
                  <div className="framer-1ach59f" data-framer-name="Topbar Links Text" style={{ width: "96.4062px", height: "34px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "5px", opacity: "1" } as CSSProperties}>
                    <div className="framer-1cso6lv" style={{ width: "96.4062px", height: "34px", padding: "10px 12px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "4px", opacity: "1" } as CSSProperties}>
                      <div className="framer-tcbjjn" data-framer-component-type="RichTextContainer" style={{ width: "60.4062px", height: "14px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 14, \"wght\" 460", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none", opacity: "1" } as CSSProperties}>
                        <p dir="auto" className="framer-text" style={{ width: "60.4062px", height: "14px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "14px", lineHeight: "14px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTBMQ0FpZDJkb2RDSWdORFl3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss07' on, 'cv05' on, 'ss03' on, 'cv11' on", "--framer-font-size": "14px", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 14, \"wght\" 460)", "--framer-letter-spacing": "-0.2px", "--framer-line-height": "1em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.topbarLinksText_2}
                        </p>
                      </div>
                      <svg data-framer-name="Dropdown" className="framer-iSnEi framer-v1fz1" role="presentation" viewBox="0 0 20 20" style={{ width: "8px", height: "8px", position: "relative", zIndex: "1", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "3", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--17kkcf8": "rgba(136, 136, 136, 0.2)", opacity: "1" } as CSSProperties}>
                        <use href="#367334708" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                      </svg>
                    </div>
                  </div>
                  <div className="framer-4mgnl8" data-framer-name="BG" style={{ width: "92.4062px", height: "30px", position: "absolute", top: "2px", right: "2px", bottom: "2px", left: "2px", zIndex: "1", inset: "2px", display: "block", flexDirection: "row", backgroundColor: "var(--token-70c17056-82cb-4934-97c9-7213cf77c853, rgba(255, 255, 255, 0.1))", borderRadius: "8px", opacity: "0", overflow: "clip", borderBottomLeftRadius: "8px", borderBottomRightRadius: "8px", borderTopLeftRadius: "8px", borderTopRightRadius: "8px" } as CSSProperties} />
                </a>
              </div>
              <div className="framer-10ktg55-container" data-framer-name="Resources" style={{ width: "104.359px", height: "34px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                <a className="framer-IMZjl framer-Bwt8q framer-ly7rus framer-v-14hpa61 framer-1fczci3" data-framer-name="Main Small Active" data-highlight="true" tabIndex={0} style={{ width: "104.359px", height: "34px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "10px", "--1h5usve": "default", backgroundColor: "rgba(0, 0, 0, 0)", borderBottomLeftRadius: "0px", borderBottomRightRadius: "0px", borderTopLeftRadius: "0px", borderTopRightRadius: "0px", opacity: "1" } as CSSProperties}>
                  <div className="framer-1ach59f" data-framer-name="Topbar Links Text" style={{ width: "104.359px", height: "34px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "5px", opacity: "1" } as CSSProperties}>
                    <div className="framer-1cso6lv" style={{ width: "104.359px", height: "34px", padding: "10px 12px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "4px", opacity: "1" } as CSSProperties}>
                      <div className="framer-tcbjjn" data-framer-component-type="RichTextContainer" style={{ width: "68.3594px", height: "14px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 14, \"wght\" 460", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none", opacity: "1" } as CSSProperties}>
                        <p dir="auto" className="framer-text" style={{ width: "68.3594px", height: "14px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "14px", lineHeight: "14px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTBMQ0FpZDJkb2RDSWdORFl3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss07' on, 'cv05' on, 'ss03' on, 'cv11' on", "--framer-font-size": "14px", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 14, \"wght\" 460)", "--framer-letter-spacing": "-0.2px", "--framer-line-height": "1em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.topbarLinksText_3}
                        </p>
                      </div>
                      <svg data-framer-name="Dropdown" className="framer-iSnEi framer-v1fz1" role="presentation" viewBox="0 0 20 20" style={{ width: "8px", height: "8px", position: "relative", zIndex: "1", display: "block", flexDirection: "row", overflow: "hidden", aspectRatio: "1 / 1", "--1iwhep7": "3", "--1l3yetw": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--17kkcf8": "rgba(136, 136, 136, 0.2)", opacity: "1" } as CSSProperties}>
                        <use href="#367334708" style={{ position: "static", display: "inline", flexDirection: "row" } as CSSProperties} />
                      </svg>
                    </div>
                  </div>
                  <div className="framer-4mgnl8" data-framer-name="BG" style={{ width: "100.359px", height: "30px", position: "absolute", top: "2px", right: "2px", bottom: "2px", left: "2px", zIndex: "1", inset: "2px", display: "block", flexDirection: "row", backgroundColor: "var(--token-70c17056-82cb-4934-97c9-7213cf77c853, rgba(255, 255, 255, 0.1))", borderRadius: "8px", opacity: "0", overflow: "clip", borderBottomLeftRadius: "8px", borderBottomRightRadius: "8px", borderTopLeftRadius: "8px", borderTopRightRadius: "8px" } as CSSProperties} />
                </a>
              </div>
              <div className="framer-r3cx1d-container" data-framer-name="Enterprise" style={{ width: "90.4219px", height: "34px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                <a className="framer-IMZjl framer-Bwt8q framer-ly7rus framer-v-1e0zr5a framer-1fczci3 hv-43" data-framer-name="Main Small" data-highlight="true" tabIndex={0} style={{ width: "90.4219px", height: "34px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "10px", opacity: "0.6", color: "rgb(0, 0, 238)", "--1h5usve": "pointer", backgroundColor: "rgba(0, 0, 0, 0)", borderBottomLeftRadius: "0px", borderBottomRightRadius: "0px", borderTopLeftRadius: "0px", borderTopRightRadius: "0px" } as CSSProperties} href={content.mainSmall}>
                  <div className="framer-1ach59f" data-framer-name="Topbar Links Text" style={{ width: "90.4219px", height: "34px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "5px", opacity: "1" } as CSSProperties}>
                    <div className="framer-1cso6lv" style={{ width: "90.4219px", height: "34px", padding: "10px 12px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "4px", opacity: "1" } as CSSProperties}>
                      <div className="framer-tcbjjn" data-framer-component-type="RichTextContainer" style={{ width: "66.4219px", height: "14px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 14, \"wght\" 460", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none", opacity: "1" } as CSSProperties}>
                        <p dir="auto" className="framer-text" style={{ width: "66.4219px", height: "14px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "14px", lineHeight: "14px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTBMQ0FpZDJkb2RDSWdORFl3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss07' on, 'cv05' on, 'ss03' on, 'cv11' on", "--framer-font-size": "14px", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 14, \"wght\" 460)", "--framer-letter-spacing": "-0.2px", "--framer-line-height": "1em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.topbarLinksText_4}
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className="framer-4mgnl8" data-framer-name="BG" style={{ width: "86.4219px", height: "30px", position: "absolute", top: "2px", right: "2px", bottom: "2px", left: "2px", zIndex: "1", inset: "2px", display: "block", flexDirection: "row", backgroundColor: "var(--token-70c17056-82cb-4934-97c9-7213cf77c853, rgba(255, 255, 255, 0.1))", borderRadius: "8px", opacity: "0", overflow: "clip", borderBottomLeftRadius: "8px", borderBottomRightRadius: "8px", borderTopLeftRadius: "8px", borderTopRightRadius: "8px" } as CSSProperties} />
                </a>
              </div>
              <div className="framer-1n9o8d5-container" data-framer-name="Pricing" style={{ width: "69.1094px", height: "34px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                <a className="framer-IMZjl framer-Bwt8q framer-ly7rus framer-v-1e0zr5a framer-1fczci3 hv-50" data-framer-name="Main Small" data-highlight="true" tabIndex={0} style={{ width: "69.1094px", height: "34px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "10px", opacity: "0.6", color: "rgb(0, 0, 238)", "--1h5usve": "pointer", backgroundColor: "rgba(0, 0, 0, 0)", borderBottomLeftRadius: "0px", borderBottomRightRadius: "0px", borderTopLeftRadius: "0px", borderTopRightRadius: "0px" } as CSSProperties} data-external-route="1" href={content.mainSmall_2}>
                  <div className="framer-1ach59f" data-framer-name="Topbar Links Text" style={{ width: "69.1094px", height: "34px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "5px", opacity: "1" } as CSSProperties}>
                    <div className="framer-1cso6lv" style={{ width: "69.1094px", height: "34px", padding: "10px 12px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "4px", opacity: "1" } as CSSProperties}>
                      <div className="framer-tcbjjn" data-framer-component-type="RichTextContainer" style={{ width: "45.1094px", height: "14px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 14, \"wght\" 460", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none", opacity: "1" } as CSSProperties}>
                        <p dir="auto" className="framer-text" style={{ width: "45.1094px", height: "14px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "14px", lineHeight: "14px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTBMQ0FpZDJkb2RDSWdORFl3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss07' on, 'cv05' on, 'ss03' on, 'cv11' on", "--framer-font-size": "14px", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 14, \"wght\" 460)", "--framer-letter-spacing": "-0.2px", "--framer-line-height": "1em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.topbarLinksText_5}
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className="framer-4mgnl8" data-framer-name="BG" style={{ width: "65.1094px", height: "30px", position: "absolute", top: "2px", right: "2px", bottom: "2px", left: "2px", zIndex: "1", inset: "2px", display: "block", flexDirection: "row", backgroundColor: "var(--token-70c17056-82cb-4934-97c9-7213cf77c853, rgba(255, 255, 255, 0.1))", borderRadius: "8px", opacity: "0", overflow: "clip", borderBottomLeftRadius: "8px", borderBottomRightRadius: "8px", borderTopLeftRadius: "8px", borderTopRightRadius: "8px" } as CSSProperties} />
                </a>
              </div>
            </div>
            <div className="framer-r8u5fh-container" data-framer-name="Login" style={{ width: "646.633px", height: "30px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
              <div className="framer-oZJjC framer-1crjff3 framer-v-1crjff3 error" data-framer-name="Primary" style={{ width: "100%", height: "30px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-end", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                <div className="framer-1vfh97j-container" style={{ width: "120.648px", height: "30px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                  <div className="framer-5o3IX framer-s7ootn framer-v-s7ootn" data-framer-name="LoggedOut" style={{ width: "120.648px", height: "100%", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-end", alignItems: "flex-start", alignContent: "flex-start", gap: "10px 15px", rowGap: "10px", columnGap: "15px", opacity: "1" } as CSSProperties}>
                    <div className="framer-tgz4ad-container" data-framer-appear-id="tgz4ad" data-framer-name="Login" style={{ width: "39.6562px", height: "30px", position: "relative", display: "block", flexDirection: "row", willChange: "transform", opacity: "1", transform: "none" } as CSSProperties}>
                      <div className="framer-73Ucq framer-fVH2p framer-1j0fhlb framer-v-wb24o hv-61" data-framer-name="Login" data-highlight="true" tabIndex={0} style={{ width: "39.6562px", height: "100%", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "8px", opacity: "1" } as CSSProperties}>
                        <div className="framer-rc1brt hv-62" data-framer-component-type="RichTextContainer" style={{ width: "39.6562px", height: "14px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 14, \"wght\" 400", "--extracted-r6o4lv": "rgb(255, 255, 255)", transform: "none", opacity: "1" } as CSSProperties}>
                          <p dir="auto" className="framer-text hv-63" style={{ width: "39.6562px", height: "14px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "14px", lineHeight: "14px", letterSpacing: "-0.14px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTBMQ0FpZDJkb2RDSWdOREF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv11' on, 'cv05' on, 'cv01' on, 'cv09' on, 'dlig' on", "--framer-font-size": "14px", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 14, \"wght\" 400)", "--framer-letter-spacing": "-0.01em", "--framer-line-height": "1em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))" } as CSSProperties}>
                            <a className="framer-text framer-styles-preset-1si2ozi hv-64 hvt-64" data-styles-preset="FYtNM2koB" target="_blank" rel="" style={{ position: "static", display: "inline", flexDirection: "row", color: "rgba(255, 255, 255, 0.6)" } as CSSProperties} href={content.login}>
                              {content.login_2}
                            </a>
                          </p>
                        </div>
                      </div>
                    </div>
                    <div className="framer-2ycu6x-container" data-framer-appear-id="2ycu6x" data-framer-name="Signup" style={{ width: "65.9922px", height: "30px", position: "relative", display: "block", flexDirection: "row", willChange: "transform", opacity: "1", transform: "none" } as CSSProperties}>
                      <div className="framer-73Ucq framer-fVH2p framer-1j0fhlb framer-v-1j0fhlb hv-66" data-framer-name="Signup" data-highlight="true" tabIndex={0} style={{ width: "65.9922px", height: "100%", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "8px", opacity: "1" } as CSSProperties}>
                        <a className="framer-16mrjhl framer-enysp5" style={{ width: "65.9922px", height: "30px", padding: "8px 10px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", alignContent: "center", gap: "10px", backgroundColor: "rgb(255, 255, 255)", borderRadius: "8px", color: "rgb(0, 0, 238)", overflow: "clip", opacity: "1" } as CSSProperties} data-external-route="1" href={content.signup}>
                          <div className="framer-cp2n07" data-framer-component-type="RichTextContainer" style={{ width: "45.9922px", height: "14px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 18, \"wght\" 540", transform: "none", opacity: "1" } as CSSProperties}>
                            <p dir="auto" className="framer-text" style={{ width: "45.9922px", height: "14px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "14px", lineHeight: "14px", letterSpacing: "-0.56px", textAlign: "left", color: "rgb(0, 0, 0)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTRMQ0FpZDJkb2RDSWdOVFF3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'cv11' on, 'cv06' on, 'ss03' on, 'dlig' on", "--framer-font-size": "14px", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 18, \"wght\" 540)", "--framer-letter-spacing": "-0.04em", "--framer-line-height": "1em", "--framer-text-alignment": "left" } as CSSProperties}>
                              {content.signup_2}
                            </p>
                          </div>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="framer-160r4by-container" style={{ position: "absolute", top: "30px", left: "646.633px", zIndex: "1", inset: "30px 0px 0px 646.633px", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                  <div className="framer-YAWEf framer-ikp74b framer-v-ikp74b" data-framer-name="CTA" style={{ position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-end", alignItems: "center", alignContent: "center", opacity: "1" } as CSSProperties}>
                    <div className="framer-thmmli-container" style={{ position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties} />
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div style={{ width: "174px", height: "108px", position: "absolute", top: "40px", right: "1026px", bottom: "-114px", zIndex: "0", inset: "40px 1026px -114px 0px", display: "block", flexDirection: "row", left: "0", pointerEvents: "none" } as CSSProperties}>
            <div className="framer-1s5lrpg" data-framer-name="Links: Brand" data-nosnippet="true" style={{ width: "174px", height: "108px", padding: "10px", position: "relative", zIndex: "10", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", backgroundColor: "rgb(0, 0, 0)", borderRadius: "12px", boxShadow: "0px 0px 0px 1px rgba(255, 255, 255, 0.1)", opacity: "0", overflow: "hidden", transform: "scale(1)", transition: "ease 0s", borderBottomLeftRadius: "12px", borderBottomRightRadius: "12px", borderTopLeftRadius: "12px", borderTopRightRadius: "12px" } as CSSProperties}>
              <div className="framer-10zn3yo-container" style={{ width: "154px", height: "44px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                <a className="framer-IMZjl framer-Bwt8q framer-ly7rus framer-v-ly7rus framer-1fczci3" data-framer-name="Large" data-highlight="true" tabIndex={0} style={{ width: "100%", height: "44px", padding: "15px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "10px", backgroundColor: "rgba(255, 255, 255, 0)", borderRadius: "8px", "--1h5usve": "pointer", borderBottomLeftRadius: "8px", borderBottomRightRadius: "8px", borderTopLeftRadius: "8px", borderTopRightRadius: "8px", opacity: "1" } as CSSProperties}>
                  <div className="framer-1ach59f" data-framer-name="Topbar Links Text" style={{ width: "124px", height: "14px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "5px", opacity: "1" } as CSSProperties}>
                    <div className="framer-1cso6lv" style={{ width: "98.0859px", height: "14px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "4px", opacity: "1" } as CSSProperties}>
                      <div className="framer-tcbjjn" data-framer-component-type="RichTextContainer" style={{ width: "98.0859px", height: "14px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 14, \"wght\" 460", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none", opacity: "1" } as CSSProperties}>
                        <p dir="auto" className="framer-text" style={{ width: "98.0859px", height: "14px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "14px", lineHeight: "14px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTBMQ0FpZDJkb2RDSWdORFl3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss07' on, 'cv05' on, 'ss03' on, 'cv11' on", "--framer-font-size": "14px", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 14, \"wght\" 460)", "--framer-letter-spacing": "-0.2px", "--framer-line-height": "1em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.topbarLinksText_6}
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className="framer-4mgnl8" data-framer-name="BG" style={{ width: "150px", height: "40px", position: "absolute", top: "2px", right: "2px", bottom: "2px", left: "2px", zIndex: "1", inset: "2px", display: "block", flexDirection: "row", backgroundColor: "var(--token-70c17056-82cb-4934-97c9-7213cf77c853, rgba(255, 255, 255, 0.1))", borderRadius: "8px", opacity: "0", overflow: "clip", borderBottomLeftRadius: "8px", borderBottomRightRadius: "8px", borderTopLeftRadius: "8px", borderTopRightRadius: "8px" } as CSSProperties} />
                </a>
              </div>
              <div className="framer-oks5m1-container" style={{ width: "154px", height: "44px", position: "relative", display: "block", flexDirection: "row", opacity: "1" } as CSSProperties}>
                <a className="framer-IMZjl framer-Bwt8q framer-ly7rus framer-v-ly7rus framer-1fczci3" data-framer-name="Large" data-highlight="true" tabIndex={0} style={{ width: "100%", height: "44px", padding: "15px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "10px", backgroundColor: "rgba(255, 255, 255, 0)", borderRadius: "8px", color: "rgb(0, 0, 238)", "--1h5usve": "pointer", borderBottomLeftRadius: "8px", borderBottomRightRadius: "8px", borderTopLeftRadius: "8px", borderTopRightRadius: "8px", opacity: "1" } as CSSProperties} data-external-route="1" href={content.large}>
                  <div className="framer-1ach59f" data-framer-name="Topbar Links Text" style={{ width: "124px", height: "14px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", alignItems: "flex-start", alignContent: "flex-start", gap: "5px", opacity: "1" } as CSSProperties}>
                    <div className="framer-1cso6lv" style={{ width: "109.258px", height: "14px", position: "relative", display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", alignContent: "center", gap: "4px", opacity: "1" } as CSSProperties}>
                      <div className="framer-tcbjjn" data-framer-component-type="RichTextContainer" style={{ width: "109.258px", height: "14px", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-start", whiteSpace: "pre", "--extracted-2gg91v": "\"opsz\" 14, \"wght\" 460", "--extracted-r6o4lv": "var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none", opacity: "1" } as CSSProperties}>
                        <p dir="auto" className="framer-text" style={{ width: "109.258px", height: "14px", position: "static", display: "block", flexDirection: "row", fontFamily: "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", fontSize: "14px", lineHeight: "14px", letterSpacing: "-0.2px", textAlign: "left", color: "rgb(255, 255, 255)", "--font-selector": "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTBMQ0FpZDJkb2RDSWdORFl3", "--framer-font-family": "\"Inter Variable\", \"Inter Variable Placeholder\", sans-serif", "--framer-font-open-type-features": "'ss07' on, 'cv05' on, 'ss03' on, 'cv11' on", "--framer-font-size": "14px", "--framer-font-variation-axes": "var(--extracted-2gg91v, \"opsz\" 14, \"wght\" 460)", "--framer-letter-spacing": "-0.2px", "--framer-line-height": "1em", "--framer-text-alignment": "left", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-26e3cb56-8447-4a64-9b7d-37f16a9909d4, rgb(255, 255, 255)))" } as CSSProperties}>
                          {content.topbarLinksText_7}
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className="framer-4mgnl8" data-framer-name="BG" style={{ width: "150px", height: "40px", position: "absolute", top: "2px", right: "2px", bottom: "2px", left: "2px", zIndex: "1", inset: "2px", display: "block", flexDirection: "row", backgroundColor: "var(--token-70c17056-82cb-4934-97c9-7213cf77c853, rgba(255, 255, 255, 0.1))", borderRadius: "8px", opacity: "0", overflow: "clip", borderBottomLeftRadius: "8px", borderBottomRightRadius: "8px", borderTopLeftRadius: "8px", borderTopRightRadius: "8px" } as CSSProperties} />
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="framer-1gyv5v7" data-framer-name="DynamicBg" style={{ width: "1440px", height: "64px", position: "absolute", zIndex: "0", display: "block", flexDirection: "row", backgroundColor: "rgb(0, 0, 0)", overflow: "clip", opacity: "1" } as CSSProperties} data-cs-id="89" />
    </nav>
  );
}
