// content for the "Header" section — extracted by extract-site.
// Edit values here to re-skin the "Header" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  text: "Built-in SEO tools with AI assistance",
  regular: "https://framer-ai.com/r/signup",
  label: "Get started for free",
  regular_2: "https://updates.framer.com/electron/darwin/arm64/Framer.zip?_ga=2.113395847.1447313862.1646043056-273660571.1642151053",
  label_2: "Download app",
  metadata: "Page Settings",
  shareLabel: "Save",
  metadata_2: "Title",
  metadata_3: "Otto - {{Title}}",
  deviceTitle: "URL",
  enumValue: "/resources/:slug/",
  enumValue_2: "en",
  deviceTitle_2: "Description",
  enumValue_3: "{{Seo Description}}",
  helpText: "Plain text values from the CMS can be used for the title & description. For example, a field named “Title” can be referenced as",
  helpText_2: "{{Title}}",
  helpText_3: "to display unique content per page.",
  cmsVariables: "CMS Variables:",
  cmsVariables_2: "Title, SEO Description, Intro, Slug, Quote",
  settings: "Page Images",
  deviceTitle_3: "Social Preview",
  deviceTitle_4: "1200 × 630 pixels",
  settings_2: "Upload",
  settings_3: { src: "../../framerusercontent.com/images/6k9NbTAb2eenLvE24Ri22E2LA6875.jpg?width=1200&height=630", alt: "Social preview card mockup for an SEO page." },
  deviceRow: "Automatic Locale",
  deviceRow_2: "Auto-redirect site visitors to their preferred locale based on their browser language settings if a matching locale exists. Only active on optimized sites and the custom domain if it is set.",
  visual: "Preview",
  visual_2: "www.ottoinvest.com",
  visual_3: "Otto - Investing on Agent Autopilot",
  visual_4: "Put your investing on autopilot. Otto’s AI agents research, monitor, and act on your portfolio, while you stay in control of the rules.",
  webVitals: "Core Web Vitals",
  webVitals_2: "GOOD",
  webVitals_3: "LCP",
  webVitals_4: "1.1s",
  webVitals_5: "INP",
  webVitals_6: "95ms",
  webVitals_7: "CLS",
  webVitals_8: "0.01",
  title: "Files",
  description: "Upload well-known files like robots.txt, security.txt, or llms.txt, or serve any static file on a fixed URL.",
  description_2: "Learn more",
  name: "File",
  name_2: "Path",
  name_3: "llms.txt",
  name_4: "/llms.txt",
  name_5: "robots.txt",
  name_6: "/robots.txt",
  name_7: "security.txt",
  name_8: "/.well-known/security.txt",
  title_2: "Accessibility",
  tag: "Tag",
  value: "nav",
  text_2: "Fill",
  star13: { src: "../../framerusercontent.com/images/RSYnHEEEkCnOAsDpBlIxTbOKIQsd7a6.jpg?width=550&height=402", alt: "Decorative star graphic" },
  label_3: "Resolution",
  value_2: "Auto",
  label_4: "Type",
  value_3: "Fill",
  label_5: "Position",
  value_4: "Center",
  label_6: "Alt Text",
  value_5: "Illustration of a stack",
  title_3: "Crop",
  title_4: "Plugins",
  m: "/stories",
  m_2: "Meet our customers",
};
