// content for the "Agent" section — extracted by extract-site.
// Edit values here to re-skin the "Agent" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "Optimize every page with agents",
  agent: "@keyframes ghostFlow { 0%, 18% { opacity: 1; } 35% { opacity: 0.6; } 50%, 100% { opacity: 0.3; } } @keyframes doubleSlow { 0%, 100% { opacity: 0.3; } 8% { opacity: 0.72; } 16%, 24% { opacity: 1; } 34%, 50% { opacity: 0.3; } 58% { opacity: 0.58; } 66%, 74% { opacity: 0.96; } 84% { opacity: 0.48; } } @keyframes danceSpark { 0%, 6% { opacity: 1; } 18% { opacity: 0.45; } 24%, 100% { opacity: 0.3; } }",
  agent_2: "Desktop",
  agent_3: "1200",
  logo: "Otto",
  dropdown: "Invest",
  links: "How it works",
  links_2: "Learn",
  links_3: "Support",
  cta: "Contact sales",
  text: "Investing on Agent Autopilot",
  text_2: "Meet Otto. A team of AI agents that research, monitor, and act on your portfolio. You set the rules.",
  cta_2: "Get started",
  text_3: "Audit SEO with agents",
  text_4: "Ask an agent to scan your page, prioritize SEO fixes, and apply approved updates to metadata, headings, alt text, and internal links.",
  header_2: "Page Settings",
  shareLabel: "Save",
  title: "Title",
  input: "Otto - Investing on Agent Autopilot",
  url: "URL",
  description: "Description",
  textArea: "Put your investing on autopilot. Otto’s AI agents research, monitor, and act on your portfolio, while you stay in control of the rules.",
  helpText: "Plain text values from the CMS can be used for the title & description. For example, a field named “Title” can be referenced as",
  helpText_2: "{{Title}}",
  helpText_3: "to display unique content per page.",
  cmsVariables: "CMS Variables:",
  cmsVariables_2: "Title, SEO Description, Intro, Slug, Quote",
  text_5: "Generate metadata and copy with AI",
  text_6: "Ask the agent to improve your title, description, headings, and key copy so the page is clearer, more specific, and easier to discover.",
  on: "Desktop",
  on_2: "1200",
  logo_2: "Otto",
  dropdown_2: "Invest",
  links_4: "How it works",
  links_5: "Learn",
  links_6: "Support",
  cta_3: "Contact sales",
  content: "How Agent Autopilot Is Reshaping Investing",
  content_2: { src: "/images/1e463046-TA0VNbnHSdlhm4tnGDb9AJaXUWsb0e6.png?width=109&height=109", alt: "portrait of a man in a black shirt" },
  content_3: "Evan Brooks",
  content_4: "•",
  content_5: "Research Lead",
  content_6: "Otto starts with research. Each morning it scans earnings, filings, and market sentiment across thousands of tickers, surfacing only the signals that matter to your holdings, so the day’s key opportunities and risks are ready before markets open.",
  text_7: "Find internal link opportunities",
  text_8: "Ask the agent to suggest links, anchor text, and missing supporting content so visitors and search engines understand what matters.",
  top: "Home",
  top_2: "Scan this page for",
  fpAgentsChatBox: "SEO issues and turn them into a prioritized list I can act on.",
  thinking: "Thinking...",
  thinking_2: "Thinking...",
  fpAgentsChatResponse: "I’ll inspect the current page’s structure, metadata, text hierarchy, links, and media so the list is grounded in what’s actually on the page.",
  fpAgentsChatResponse_2: "Explored 25 layers",
  fpAgentsChatResponse_3: "13s",
  fpAgentsChatResponse_4: "Here’s the prioritized SEO checklist for the current",
  fpAgentsChatResponse_5: "/home/",
  fpAgentsChatResponse_6: "page.",
  fpAgentsChatResponse_7: "1.",
  fpAgentsChatResponse_8: "Improve heading structure.",
  fpAgentsChatResponse_9: "Keep the H1, but make key section titles real H2/H3 headings.",
  fpAgentsChatResponse_10: "2.",
  fpAgentsChatResponse_11: "Tighten metadata and page copy.",
  fpAgentsChatResponse_12: "Align the title, description, H1, and intro around one SEO message.",
  fpAgentsChatResponse_13: "3.",
  fpAgentsChatResponse_14: "Align metadata, H1, and on-page copy more tightly.",
  fpAgentsChatResponse_15: "4.",
  fpAgentsChatResponse_16: "Add a clearer crawlable intro paragraph near the top of the page.",
  promptInput: "._R5jbclraal5dp_::placeholder { color: var(--token-f5637926-8ee6-41cb-a320-ec3462d62cd5, rgba(255, 255, 255, 0.4)); opacity: 1; }",
  aiModel: "GPT 5.6",
  aiModel_2: "Terra",
};
