// content for the "Bento" section — extracted by extract-site.
// Edit values here to re-skin the "Bento" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "Built-in SEO essentials",
  settings: "Page Images",
  deviceTitle: "Social Preview",
  deviceTitle_2: "1200 × 630 pixels",
  settings_2: "Upload",
  settings_3: { src: "../../framerusercontent.com/images/6k9NbTAb2eenLvE24Ri22E2LA6875.jpg?width=1200&height=630", alt: "Social preview card mockup for Open Graph image settings." },
  bentoCard: "Open Graph images.",
  bentoCard_2: "Set the share image for perfect previews.",
  visual1: { src: "../../framerusercontent.com/images/Z8UXD0eXmUGjsukYt8M4ME1mE40a7.png?width=1672&height=941", alt: "WebP image optimization comparison showing smaller file size for faster SEO performance." },
  webp: "WebP: 94kb",
  webp_2: "PNG: 492KB",
  webp_3: "saved",
  webp_4: "81%",
  bentoCard_3: "Image optimization & CDN.",
  bentoCard_4: "Serve WebP images through a global CDN for fast, SEO-friendly performance.",
  page: "Home",
  page_2: "Features",
  sitemap: "AI",
  sitemap_2: "Design",
  sitemap_3: "SEO",
  page_3: "Blog",
  sitemap_4: "Blog Article",
  bentoCard_5: "Sitemaps &",
  bentoCard_6: "robots.txt",
  bentoCard_7: ".",
  bentoCard_8: "Auto-generated for easier crawling.",
  deviceTitle_3: "Search",
  enumValue: "Search Engines",
  enumValue_2: "Tell search engines to index and show this page in their search results.",
  enumValue_3: "Site Search",
  enumValue_4: "Show this page in your site search results.",
  bentoCard_9: "Indexing controls.",
  bentoCard_10: "Choose which pages appear in search.",
  on: "Pages",
  off: "Layers",
  off_2: "Assets",
  input: "Search…",
  pageHeader: "Pages",
  page_4: "Home",
  page_5: "/about",
  appUiPageItem: "/",
  appUiPageItem_2: "guides",
  appUiPageItem_3: "|",
  subPage: "Videos",
  subPage_2: "Categories",
  page_6: "/how-it-works",
  page_7: "/invest",
  branch: "1",
  page_8: "/learn",
  page_9: "/legal",
  subPage_3: "Terms and Conditions",
  subPage_4: "Privacy",
  page_10: "/performance",
  branch_2: "2",
  page_11: "/portfolio",
  branch_3: "1",
  page_12: "/pricing",
  page_13: "/research",
  page_14: "/resources",
  branch_4: "4",
  page_15: "/security",
  page_16: "/support",
  bentoCard_11: "Custom URLs and slugs.",
  bentoCard_12: "Create clear, SEO-friendly paths.",
  metadata: "Page Settings",
  shareLabel: "Save",
  metadata_2: "Title",
  metadata_3: "Otto - {{Title}}",
  deviceTitle_4: "URL",
  enumValue_5: "/resources/:slug/",
  deviceTitle_5: "Description",
  enumValue_6: "{{Seo Description}}",
  helpText: "Plain text values from the CMS can be used for the title & description. For example, a field named “Title” can be referenced as",
  helpText_2: "{{Title}}",
  helpText_3: "to display unique content per page.",
  cmsVariables: "CMS Variables:",
  cmsVariables_2: "Title, SEO Description, Intro, Slug, Quote",
  bentoCard_13: "Dynamic metadata.",
  bentoCard_14: "Use variables like",
  bentoCard_15: "{{Title}}",
  bentoCard_16: "and",
  bentoCard_17: "{{Description}}",
  bentoCard_18: "to render unique SEO strings per CMS entry.",
  canonicalUrl: "Default",
  canonicalUrl_2: "https://www.ottoinvest.com",
  canonicalUrl_3: "Multi Site",
  canonicalUrl_4: "Set the canonical URL for this site when used as a rewrite target",
  bentoCard_19: "https://framer-ai.com/help/articles/setting-up-a-custom-canonical-url-in-framer",
  bentoCard_20: "Canonical URLs",
  bentoCard_21: ".",
  bentoCard_22: "Set the preferred version search engines should index.",
};
