// content for the "Technical SEO" section — extracted by extract-site.
// Edit values here to re-skin the "Technical SEO" section (copy, photos, links) without touching
// its layout, styles, or motion.

export default {
  header: "Technical SEO, built into your site",
  logo: "Otto",
  dropdown: "Invest",
  links: "How it works",
  cta: "Get started",
  rowTitle: "Accessibility",
  widthTitle: "Tag",
  controlValue: "nav",
  l: "https://framer-ai.com/academy/lessons/framer-seo-semantic-tags",
  l_2: "Use semantic markup",
  text: "Structure your site with semantic HTML tags like",
  text_2: "<header>",
  text_3: ",",
  text_4: "<nav>",
  text_5: ", and",
  text_6: "<article>",
  text_7: "to enhance accessibility and search engine comprehension.",
  ui: "Redirects",
  ui_2: "Redirect existing URLs to new ones to maintain search engine ranking. The order of the items defines the priority.",
  ui_3: "Learn more",
  ui_4: "Search…",
  enumValue: "From",
  enumValue_2: "To",
  enumValue_3: "/about",
  enumValue_4: "www.framer.com",
  enumValue_5: "/articles/",
  enumValue_6: "/article/:1",
  enumValue_7: "/product",
  enumValue_8: "/what-is-framer",
  enumValue_9: "/404",
  enumValue_10: "/page-not-found",
  enumValue_11: "/tutorials",
  enumValue_12: "/academy",
  enumValue_13: "/company",
  enumValue_14: "www.framer.com/jobs",
  l_3: "https://framer-ai.com/help/articles/how-to-setup-redirects-to-maintain-seo-ranking",
  l_4: "Set up redirects",
  text_8: "Maintain page ranking and traffic when moving or renaming pages. Framer automatically handles 301 redirects between old and new URLs.",
  deviceRow: "Custom Code",
  deviceRow_2: "Name",
  deviceRow_3: "Performance",
  deviceTitle: "Placement",
  enumValue_15: "Start of <head>",
  deviceRow_4: "Page",
  deviceRow_5: "All",
  deviceTitle_2: "Run",
  enumValue_16: "Once",
  deviceTitle_3: "Code",
  deviceRow_6: "1",
  deviceRow_7: "<!-- Schema Markup -->",
  deviceRow_8: "2",
  deviceRow_9: "<",
  deviceRow_10: "script",
  deviceRow_11: "type",
  deviceRow_12: "=”application/ld+json”>",
  deviceRow_13: "3",
  deviceRow_14: "{",
  deviceRow_15: "4",
  deviceRow_16: "“@context”: “https://schema.org”,",
  deviceRow_17: "5",
  deviceRow_18: "“@type”: “Organization”,",
  deviceRow_19: "6",
  deviceRow_20: "“name”: “Framer”,",
  deviceRow_21: "7",
  deviceRow_22: "“url”: “https://framer.com”,",
  deviceRow_23: "8",
  deviceRow_24: "“image”: “https://framerusercontent.com/images/b2hliN8q6RI1alDDMojdsEiXDU.png”,",
  deviceRow_25: "9",
  deviceRow_26: "“description”: “The web builder for stunning sites. Design and publish modern sites at any scale.”,",
  deviceRow_27: "10",
  deviceRow_28: "“description”: “The web builder for stunning sites. Design and publish modern sites at any scale.”,",
  l_5: "https://framer-ai.com/help/articles/structured-data-through-json-ld",
  l_6: "Add structured data",
  text_9: "Implement structured data using",
  text_10: "JSON-LD",
  text_11: "for articles, products, and events to enable rich results and improved crawl understanding.",
  image1: { src: "../../framerusercontent.com/images/RSYnHEEEkCnOAsDpBlIxTbOKIQsd7a6.jpg?width=550&height=402", alt: "Lazy loading image preview." },
  image2: { src: "../../framerusercontent.com/images/084wb8yPTGlrVbcPd5FyJFme4d7a6.jpg?width=550&height=402", alt: "Lazy loading image preview." },
  image3: { src: "../../framerusercontent.com/images/V5YasviIEPfWVNscNWWzFMOFMd7a6.jpg?width=550&height=402", alt: "Lazy loading image preview." },
  image4: { src: "../../framerusercontent.com/images/Nsgr7sBP4ybZqLBvviQZ8Ov5Qd7a6.jpg?width=550&height=402", alt: "Lazy loading image preview." },
  paragraph1: "Lazy Load Images",
  l_7: "/performance",
  l_8: "Optimized performance",
  text_12: "Improve Core Web Vitals with CDN caching, lazy loading, asset compression, and responsive rendering for faster LCP, CLS, and INP performance.",
  card: "Google Analytics",
  shareLabel: "Save",
  card_2: "Directly integrate Google Analytics into your Framer site. Please note that as a site owner, you are responsible for making sure that your site is handling data in a way that is in line with privacy laws, such as the GDPR.",
  card_3: "Learn more",
  card_4: "G-XXXXXXXXXXXX",
  l_9: "https://framer-ai.com/help/integrations",
  l_10: "Use integrations",
  text_13: "Integrate Google Analytics or Tag Manager and track performance in Semrush or Ahrefs. No plugins needed, just paste your measurement ID or script and go.",
  wellKnownFiles2x: { src: "../../framerusercontent.com/images/LFyagGXTf0UlVIYDKHItJizlI751f.png?width=960&height=552", alt: "Well known files modal" },
  l_11: "https://framer-ai.com/help/articles/static-files",
  l_12: "Add well-known files",
  text_14: "Add root-level and",
  text_15: "/.well-known/",
  text_16: "files for search, security, and AI discovery. Support standards like",
  text_17: "robots.txt",
  text_18: ",",
  text_19: "security.txt",
  text_20: ", and",
  text_21: "llms.txt",
  text_22: "directly in Framer.",
};
